// jqwidgets-vue3/vue_jqxtree.vue
<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
	import { onUpdated, onMounted } from 'vue';
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxdata.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxscrollbar.js';
    import '../jqwidgets/jqxpanel.js';
    import '../jqwidgets/jqxdragdrop.js';
    import '../jqwidgets/jqxtree.js';
    import '../jqwidgets/jqxcheckbox.js';

    export default {
        props: {
            animationShowDuration: Number,
            animationHideDuration: Number,
            allowDrag: {
                default: false,
                type: Boolean
            },
            allowDrop: {
                default: false,
                type: Boolean
            },
            checkboxes: {
                default: false,
                type: Boolean
            },
            dragStart: Function,
            dragEnd: Function,
            disabled: {
                default: false,
                type: Boolean
            },
            easing: String,
            enableHover: {
                default: true,
                type: Boolean
            },
            height: [Number, String],
            hasThreeStates: {
                default: false,
                type: Boolean
            },
            incrementalSearch: {
                default: true,
                type: Boolean
            },
            keyboardNavigation: {
                default: true,
                type: Boolean
            },
            rtl: {
                default: false,
                type: Boolean
            },
            source: [Array, Object],
            toggleIndicatorSize: Number,
            toggleMode: String,
            theme: String,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        emits: ["added","checkChange","collapse","dragStart","dragEnd","expand","itemClick","removed","select"],
        setup(props, context) {
			const id = "jqxTree" + JQXLite.generateID();
			const componentSelector = '#' + id;
            function createComponent(options) {
                if (!props.autoCreate) __createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            }
            function setOptions (options) {
                JQXLite(componentSelector).jqxTree(options);
            }
            function getOptions() {
                const usedProps = Object.keys(__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(componentSelector).jqxTree(usedProps[i]);
                }
                return resultToReturn;
            }
            function addBefore(item, id) {
                JQXLite(componentSelector).jqxTree('addBefore', item, id);  
            }
            function addAfter(item, id) {
                JQXLite(componentSelector).jqxTree('addAfter', item, id);  
            }
            function addTo(item, id) {
                JQXLite(componentSelector).jqxTree('addTo', item, id);  
            }
            function clear() {
                JQXLite(componentSelector).jqxTree('clear');  
            }
            function checkAll() {
                JQXLite(componentSelector).jqxTree('checkAll');  
            }
            function checkItem(item, checked) {
                JQXLite(componentSelector).jqxTree('checkItem', item, checked);  
            }
            function collapseAll() {
                JQXLite(componentSelector).jqxTree('collapseAll');  
            }
            function collapseItem(item) {
                JQXLite(componentSelector).jqxTree('collapseItem', item);  
            }
            function destroy() {
                JQXLite(componentSelector).jqxTree('destroy');  
            }
            function disableItem(item) {
                JQXLite(componentSelector).jqxTree('disableItem', item);  
            }
            function ensureVisible(item) {
                JQXLite(componentSelector).jqxTree('ensureVisible', item);  
            }
            function enableItem(item) {
                JQXLite(componentSelector).jqxTree('enableItem', item);  
            }
            function enableAll() {
                JQXLite(componentSelector).jqxTree('enableAll');  
            }
            function expandAll() {
                JQXLite(componentSelector).jqxTree('expandAll');  
            }
            function expandItem(item) {
                JQXLite(componentSelector).jqxTree('expandItem', item);  
            }
            function focus() {
                JQXLite(componentSelector).jqxTree('focus');  
            }
            function getCheckedItems() {
                return JQXLite(componentSelector).jqxTree('getCheckedItems');  
            }
            function getUncheckedItems() {
                return JQXLite(componentSelector).jqxTree('getUncheckedItems');  
            }
            function getItems() {
                return JQXLite(componentSelector).jqxTree('getItems');  
            }
            function getItem(element) {
                return JQXLite(componentSelector).jqxTree('getItem', element);  
            }
            function getSelectedItem() {
                return JQXLite(componentSelector).jqxTree('getSelectedItem');  
            }
            function getPrevItem(item) {
                return JQXLite(componentSelector).jqxTree('getPrevItem', item);  
            }
            function getNextItem(item) {
                return JQXLite(componentSelector).jqxTree('getNextItem', item);  
            }
            function hitTest(left, top) {
                return JQXLite(componentSelector).jqxTree('hitTest', left, top);  
            }
            function removeItem(item) {
                JQXLite(componentSelector).jqxTree('removeItem', item);  
            }
            function render() {
                JQXLite(componentSelector).jqxTree('render');  
            }
            function refresh() {
                JQXLite(componentSelector).jqxTree('refresh');  
            }
            function selectItem(item) {
                JQXLite(componentSelector).jqxTree('selectItem', item);  
            }
            function uncheckAll() {
                JQXLite(componentSelector).jqxTree('uncheckAll');  
            }
            function uncheckItem(item) {
                JQXLite(componentSelector).jqxTree('uncheckItem', item);  
            }
            function updateItem(item, newItem) {
                JQXLite(componentSelector).jqxTree('updateItem', item, newItem);  
            }
            function val(value) {
                if (value !== undefined) {
                    JQXLite(componentSelector).jqxTree('val',  value)
                } else {
                    return JQXLite(componentSelector).jqxTree('val');
                }
            }
            function _animationShowDuration (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('animationShowDuration', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('animationShowDuration');
                }
            }
            function _animationHideDuration (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('animationHideDuration', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('animationHideDuration');
                }
            }
            function _allowDrag (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('allowDrag', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('allowDrag');
                }
            }
            function _allowDrop (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('allowDrop', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('allowDrop');
                }
            }
            function _checkboxes (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('checkboxes', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('checkboxes');
                }
            }
            function _dragStart (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('dragStart', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('dragStart');
                }
            }
            function _dragEnd (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('dragEnd', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('dragEnd');
                }
            }
            function _disabled (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('disabled', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('disabled');
                }
            }
            function _easing (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('easing', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('easing');
                }
            }
            function _enableHover (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('enableHover', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('enableHover');
                }
            }
            function _height (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('height', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('height');
                }
            }
            function _hasThreeStates (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('hasThreeStates', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('hasThreeStates');
                }
            }
            function _incrementalSearch (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('incrementalSearch', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('incrementalSearch');
                }
            }
            function _keyboardNavigation (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('keyboardNavigation', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('keyboardNavigation');
                }
            }
            function _rtl (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('rtl', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('rtl');
                }
            }
            function _source (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('source', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('source');
                }
            }
            function _toggleIndicatorSize (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('toggleIndicatorSize', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('toggleIndicatorSize');
                }
            }
            function _toggleMode (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('toggleMode', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('toggleMode');
                }
            }
            function _theme (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('theme', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('theme');
                }
            }
            function _width (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxTree('width', arg)
                } else {
                    return JQXLite(componentSelector).jqxTree('width');
                }
            }
            function __createComponent__ (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = __manageProps__();
                JQXLite(componentSelector).jqxTree(widgetOptions);
                __wireEvents__();
            }
            function __manageProps__() {
                const widgetProps = ['animationShowDuration','animationHideDuration','allowDrag','allowDrop','checkboxes','dragStart','dragEnd','disabled','easing','enableHover','height','hasThreeStates','incrementalSearch','keyboardNavigation','rtl','source','toggleIndicatorSize','toggleMode','theme','width'];
                const componentProps = props;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1 && componentProps[prop] !== undefined) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            }
            const options = {
                 get animationShowDuration() {
                     return _animationShowDuration();
                 },
                 set animationShowDuration(newValue) {
                     _animationShowDuration(newValue);
                 },
                 get animationHideDuration() {
                     return _animationHideDuration();
                 },
                 set animationHideDuration(newValue) {
                     _animationHideDuration(newValue);
                 },
                 get allowDrag() {
                     return _allowDrag();
                 },
                 set allowDrag(newValue) {
                     _allowDrag(newValue);
                 },
                 get allowDrop() {
                     return _allowDrop();
                 },
                 set allowDrop(newValue) {
                     _allowDrop(newValue);
                 },
                 get checkboxes() {
                     return _checkboxes();
                 },
                 set checkboxes(newValue) {
                     _checkboxes(newValue);
                 },
                 get dragStart() {
                     return _dragStart();
                 },
                 set dragStart(newValue) {
                     _dragStart(newValue);
                 },
                 get dragEnd() {
                     return _dragEnd();
                 },
                 set dragEnd(newValue) {
                     _dragEnd(newValue);
                 },
                 get disabled() {
                     return _disabled();
                 },
                 set disabled(newValue) {
                     _disabled(newValue);
                 },
                 get easing() {
                     return _easing();
                 },
                 set easing(newValue) {
                     _easing(newValue);
                 },
                 get enableHover() {
                     return _enableHover();
                 },
                 set enableHover(newValue) {
                     _enableHover(newValue);
                 },
                 get height() {
                     return _height();
                 },
                 set height(newValue) {
                     _height(newValue);
                 },
                 get hasThreeStates() {
                     return _hasThreeStates();
                 },
                 set hasThreeStates(newValue) {
                     _hasThreeStates(newValue);
                 },
                 get incrementalSearch() {
                     return _incrementalSearch();
                 },
                 set incrementalSearch(newValue) {
                     _incrementalSearch(newValue);
                 },
                 get keyboardNavigation() {
                     return _keyboardNavigation();
                 },
                 set keyboardNavigation(newValue) {
                     _keyboardNavigation(newValue);
                 },
                 get rtl() {
                     return _rtl();
                 },
                 set rtl(newValue) {
                     _rtl(newValue);
                 },
                 get source() {
                     return _source();
                 },
                 set source(newValue) {
                     _source(newValue);
                 },
                 get toggleIndicatorSize() {
                     return _toggleIndicatorSize();
                 },
                 set toggleIndicatorSize(newValue) {
                     _toggleIndicatorSize(newValue);
                 },
                 get toggleMode() {
                     return _toggleMode();
                 },
                 set toggleMode(newValue) {
                     _toggleMode(newValue);
                 },
                 get theme() {
                     return _theme();
                 },
                 set theme(newValue) {
                     _theme(newValue);
                 },
                 get width() {
                     return _width();
                 },
                 set width(newValue) {
                     _width(newValue);
                 },
            }
            function __wireEvents__() {
                const that = context;

                JQXLite(componentSelector).on('added', function (event) { that.emit('added', event); });
                JQXLite(componentSelector).on('checkChange', function (event) { that.emit('checkChange', event); });
                JQXLite(componentSelector).on('collapse', function (event) { that.emit('collapse', event); });
                JQXLite(componentSelector).on('dragStart', function (event) { that.emit('dragStart', event); });
                JQXLite(componentSelector).on('dragEnd', function (event) { that.emit('dragEnd', event); });
                JQXLite(componentSelector).on('expand', function (event) { that.emit('expand', event); });
                JQXLite(componentSelector).on('itemClick', function (event) { that.emit('itemClick', event); });
                JQXLite(componentSelector).on('removed', function (event) { that.emit('removed', event); });
                JQXLite(componentSelector).on('select', function (event) { that.emit('select', event); });
            }

			onMounted(() => {
				if (props.autoCreate) __createComponent__();
			})
			onUpdated(() => {
				const widgetOptions = __manageProps__();
				JQXLite(componentSelector).jqxTree(widgetOptions);
			})
			return {id, componentSelector, addBefore,addAfter,addTo,clear,checkAll,checkItem,collapseAll,collapseItem,destroy,disableItem,ensureVisible,enableItem,enableAll,expandAll,expandItem,focus,getCheckedItems,getUncheckedItems,getItems,getItem,getSelectedItem,getPrevItem,getNextItem,hitTest,removeItem,render,refresh,selectItem,uncheckAll,uncheckItem,updateItem,val, setOptions, options, getOptions, createComponent};
        },
    }
</script>

// jqwidgets-ng/esm5/jqxtree/angular_jqxtree.js
import '../jqwidgets/jqxcore';
import '../jqwidgets/jqxdata';
import '../jqwidgets/jqxbuttons';
import '../jqwidgets/jqxscrollbar';
import '../jqwidgets/jqxpanel';
import '../jqwidgets/jqxdragdrop';
import '../jqwidgets/jqxtree';
import '../jqwidgets/jqxcheckbox';
/// <reference path="../../jqwidgets.d.ts" />
import * as tslib_1 from "tslib";
import { Component, Input, Output, EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
var jqxTreeComponent = /** @class */ (function () {
    function jqxTreeComponent(containerElement) {
        this.autoCreate = true;
        this.properties = ['animationShowDuration', 'animationHideDuration', 'allowDrag', 'allowDrop', 'checkboxes', 'dragStart', 'dragEnd', 'disabled', 'easing', 'enableHover', 'height', 'hasThreeStates', 'incrementalSearch', 'keyboardNavigation', 'rtl', 'source', 'toggleIndicatorSize', 'toggleMode', 'theme', 'width'];
        // jqxTreeComponent events
        this.onAdded = new EventEmitter();
        this.onCheckChange = new EventEmitter();
        this.onCollapse = new EventEmitter();
        this.onDragStart = new EventEmitter();
        this.onDragEnd = new EventEmitter();
        this.onExpand = new EventEmitter();
        this.onItemClick = new EventEmitter();
        this.onRemoved = new EventEmitter();
        this.onSelect = new EventEmitter();
        this.elementRef = containerElement;
    }
    jqxTreeComponent.prototype.ngOnInit = function () {
        if (this.autoCreate) {
            this.createComponent();
        }
    };
    ;
    jqxTreeComponent.prototype.ngOnChanges = function (changes) {
        if (this.host) {
            for (var i = 0; i < this.properties.length; i++) {
                var attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
                var areEqual = false;
                if (this[attrName] !== undefined) {
                    if (typeof this[attrName] === 'object') {
                        if (this[attrName] instanceof Array) {
                            areEqual = this.arraysEqual(this[attrName], this.host.jqxTree(this.properties[i]));
                        }
                        if (areEqual) {
                            return false;
                        }
                        this.host.jqxTree(this.properties[i], this[attrName]);
                        continue;
                    }
                    if (this[attrName] !== this.host.jqxTree(this.properties[i])) {
                        this.host.jqxTree(this.properties[i], this[attrName]);
                    }
                }
            }
        }
    };
    jqxTreeComponent.prototype.arraysEqual = function (attrValue, hostValue) {
        if ((attrValue && !hostValue) || (!attrValue && hostValue)) {
            return false;
        }
        if (attrValue.length != hostValue.length) {
            return false;
        }
        for (var i = 0; i < attrValue.length; i++) {
            if (attrValue[i] !== hostValue[i]) {
                return false;
            }
        }
        return true;
    };
    jqxTreeComponent.prototype.manageAttributes = function () {
        var options = {};
        for (var i = 0; i < this.properties.length; i++) {
            var attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            if (this[attrName] !== undefined) {
                options[this.properties[i]] = this[attrName];
            }
        }
        return options;
    };
    jqxTreeComponent.prototype.moveClasses = function (parentEl, childEl) {
        var _a;
        var classes = parentEl.classList;
        if (classes.length > 0) {
            (_a = childEl.classList).add.apply(_a, tslib_1.__spread(classes));
        }
        parentEl.className = '';
    };
    jqxTreeComponent.prototype.moveStyles = function (parentEl, childEl) {
        var style = parentEl.style.cssText;
        childEl.style.cssText = style;
        parentEl.style.cssText = '';
    };
    jqxTreeComponent.prototype.createComponent = function (options) {
        if (this.host) {
            return;
        }
        if (options) {
            JQXLite.extend(options, this.manageAttributes());
        }
        else {
            options = this.manageAttributes();
        }
        this.host = JQXLite(this.elementRef.nativeElement.firstChild);
        this.moveClasses(this.elementRef.nativeElement, this.host[0]);
        this.moveStyles(this.elementRef.nativeElement, this.host[0]);
        this.__wireEvents__();
        this.widgetObject = jqwidgets.createInstance(this.host, 'jqxTree', options);
    };
    jqxTreeComponent.prototype.createWidget = function (options) {
        this.createComponent(options);
    };
    jqxTreeComponent.prototype.__updateRect__ = function () {
        if (this.host)
            this.host.css({ width: this.attrWidth, height: this.attrHeight });
    };
    jqxTreeComponent.prototype.setOptions = function (options) {
        this.host.jqxTree('setOptions', options);
    };
    // jqxTreeComponent properties
    jqxTreeComponent.prototype.animationShowDuration = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('animationShowDuration', arg);
        }
        else {
            return this.host.jqxTree('animationShowDuration');
        }
    };
    jqxTreeComponent.prototype.animationHideDuration = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('animationHideDuration', arg);
        }
        else {
            return this.host.jqxTree('animationHideDuration');
        }
    };
    jqxTreeComponent.prototype.allowDrag = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('allowDrag', arg);
        }
        else {
            return this.host.jqxTree('allowDrag');
        }
    };
    jqxTreeComponent.prototype.allowDrop = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('allowDrop', arg);
        }
        else {
            return this.host.jqxTree('allowDrop');
        }
    };
    jqxTreeComponent.prototype.checkboxes = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('checkboxes', arg);
        }
        else {
            return this.host.jqxTree('checkboxes');
        }
    };
    jqxTreeComponent.prototype.dragStart = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('dragStart', arg);
        }
        else {
            return this.host.jqxTree('dragStart');
        }
    };
    jqxTreeComponent.prototype.dragEnd = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('dragEnd', arg);
        }
        else {
            return this.host.jqxTree('dragEnd');
        }
    };
    jqxTreeComponent.prototype.disabled = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('disabled', arg);
        }
        else {
            return this.host.jqxTree('disabled');
        }
    };
    jqxTreeComponent.prototype.easing = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('easing', arg);
        }
        else {
            return this.host.jqxTree('easing');
        }
    };
    jqxTreeComponent.prototype.enableHover = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('enableHover', arg);
        }
        else {
            return this.host.jqxTree('enableHover');
        }
    };
    jqxTreeComponent.prototype.height = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('height', arg);
        }
        else {
            return this.host.jqxTree('height');
        }
    };
    jqxTreeComponent.prototype.hasThreeStates = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('hasThreeStates', arg);
        }
        else {
            return this.host.jqxTree('hasThreeStates');
        }
    };
    jqxTreeComponent.prototype.incrementalSearch = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('incrementalSearch', arg);
        }
        else {
            return this.host.jqxTree('incrementalSearch');
        }
    };
    jqxTreeComponent.prototype.keyboardNavigation = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('keyboardNavigation', arg);
        }
        else {
            return this.host.jqxTree('keyboardNavigation');
        }
    };
    jqxTreeComponent.prototype.rtl = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('rtl', arg);
        }
        else {
            return this.host.jqxTree('rtl');
        }
    };
    jqxTreeComponent.prototype.source = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('source', arg);
        }
        else {
            return this.host.jqxTree('source');
        }
    };
    jqxTreeComponent.prototype.toggleIndicatorSize = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('toggleIndicatorSize', arg);
        }
        else {
            return this.host.jqxTree('toggleIndicatorSize');
        }
    };
    jqxTreeComponent.prototype.toggleMode = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('toggleMode', arg);
        }
        else {
            return this.host.jqxTree('toggleMode');
        }
    };
    jqxTreeComponent.prototype.theme = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('theme', arg);
        }
        else {
            return this.host.jqxTree('theme');
        }
    };
    jqxTreeComponent.prototype.width = function (arg) {
        if (arg !== undefined) {
            this.host.jqxTree('width', arg);
        }
        else {
            return this.host.jqxTree('width');
        }
    };
    // jqxTreeComponent functions
    jqxTreeComponent.prototype.addBefore = function (item, id) {
        this.host.jqxTree('addBefore', item, id);
    };
    jqxTreeComponent.prototype.addAfter = function (item, id) {
        this.host.jqxTree('addAfter', item, id);
    };
    jqxTreeComponent.prototype.addTo = function (item, id) {
        this.host.jqxTree('addTo', item, id);
    };
    jqxTreeComponent.prototype.clear = function () {
        this.host.jqxTree('clear');
    };
    jqxTreeComponent.prototype.checkAll = function () {
        this.host.jqxTree('checkAll');
    };
    jqxTreeComponent.prototype.checkItem = function (item, checked) {
        this.host.jqxTree('checkItem', item, checked);
    };
    jqxTreeComponent.prototype.collapseAll = function () {
        this.host.jqxTree('collapseAll');
    };
    jqxTreeComponent.prototype.collapseItem = function (item) {
        this.host.jqxTree('collapseItem', item);
    };
    jqxTreeComponent.prototype.destroy = function () {
        this.host.jqxTree('destroy');
    };
    jqxTreeComponent.prototype.disableItem = function (item) {
        this.host.jqxTree('disableItem', item);
    };
    jqxTreeComponent.prototype.ensureVisible = function (item) {
        this.host.jqxTree('ensureVisible', item);
    };
    jqxTreeComponent.prototype.enableItem = function (item) {
        this.host.jqxTree('enableItem', item);
    };
    jqxTreeComponent.prototype.enableAll = function () {
        this.host.jqxTree('enableAll');
    };
    jqxTreeComponent.prototype.expandAll = function () {
        this.host.jqxTree('expandAll');
    };
    jqxTreeComponent.prototype.expandItem = function (item) {
        this.host.jqxTree('expandItem', item);
    };
    jqxTreeComponent.prototype.focus = function () {
        this.host.jqxTree('focus');
    };
    jqxTreeComponent.prototype.getCheckedItems = function () {
        return this.host.jqxTree('getCheckedItems');
    };
    jqxTreeComponent.prototype.getUncheckedItems = function () {
        return this.host.jqxTree('getUncheckedItems');
    };
    jqxTreeComponent.prototype.getItems = function () {
        return this.host.jqxTree('getItems');
    };
    jqxTreeComponent.prototype.getItem = function (element) {
        return this.host.jqxTree('getItem', element);
    };
    jqxTreeComponent.prototype.getSelectedItem = function () {
        return this.host.jqxTree('getSelectedItem');
    };
    jqxTreeComponent.prototype.getPrevItem = function (item) {
        return this.host.jqxTree('getPrevItem', item);
    };
    jqxTreeComponent.prototype.getNextItem = function (item) {
        return this.host.jqxTree('getNextItem', item);
    };
    jqxTreeComponent.prototype.hitTest = function (left, top) {
        return this.host.jqxTree('hitTest', left, top);
    };
    jqxTreeComponent.prototype.removeItem = function (item) {
        this.host.jqxTree('removeItem', item);
    };
    jqxTreeComponent.prototype.render = function () {
        this.host.jqxTree('render');
    };
    jqxTreeComponent.prototype.refresh = function () {
        this.host.jqxTree('refresh');
    };
    jqxTreeComponent.prototype.selectItem = function (item) {
        this.host.jqxTree('selectItem', item);
    };
    jqxTreeComponent.prototype.uncheckAll = function () {
        this.host.jqxTree('uncheckAll');
    };
    jqxTreeComponent.prototype.uncheckItem = function (item) {
        this.host.jqxTree('uncheckItem', item);
    };
    jqxTreeComponent.prototype.updateItem = function (item, newItem) {
        this.host.jqxTree('updateItem', item, newItem);
    };
    jqxTreeComponent.prototype.val = function (value) {
        if (value !== undefined) {
            return this.host.jqxTree('val', value);
        }
        else {
            return this.host.jqxTree('val');
        }
    };
    ;
    jqxTreeComponent.prototype.__wireEvents__ = function () {
        var _this = this;
        this.host.on('added', function (eventData) { _this.onAdded.emit(eventData); });
        this.host.on('checkChange', function (eventData) { _this.onCheckChange.emit(eventData); });
        this.host.on('collapse', function (eventData) { _this.onCollapse.emit(eventData); });
        this.host.on('dragStart', function (eventData) { _this.onDragStart.emit(eventData); });
        this.host.on('dragEnd', function (eventData) { _this.onDragEnd.emit(eventData); });
        this.host.on('expand', function (eventData) { _this.onExpand.emit(eventData); });
        this.host.on('itemClick', function (eventData) { _this.onItemClick.emit(eventData); });
        this.host.on('removed', function (eventData) { _this.onRemoved.emit(eventData); });
        this.host.on('select', function (eventData) { _this.onSelect.emit(eventData); });
    };
    jqxTreeComponent.ctorParameters = function () { return [
        { type: ElementRef }
    ]; };
    tslib_1.__decorate([
        Input('animationShowDuration'),
        tslib_1.__metadata("design:type", Number)
    ], jqxTreeComponent.prototype, "attrAnimationShowDuration", void 0);
    tslib_1.__decorate([
        Input('animationHideDuration'),
        tslib_1.__metadata("design:type", Number)
    ], jqxTreeComponent.prototype, "attrAnimationHideDuration", void 0);
    tslib_1.__decorate([
        Input('allowDrag'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxTreeComponent.prototype, "attrAllowDrag", void 0);
    tslib_1.__decorate([
        Input('allowDrop'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxTreeComponent.prototype, "attrAllowDrop", void 0);
    tslib_1.__decorate([
        Input('checkboxes'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxTreeComponent.prototype, "attrCheckboxes", void 0);
    tslib_1.__decorate([
        Input('dragStart'),
        tslib_1.__metadata("design:type", Function)
    ], jqxTreeComponent.prototype, "attrDragStart", void 0);
    tslib_1.__decorate([
        Input('dragEnd'),
        tslib_1.__metadata("design:type", Function)
    ], jqxTreeComponent.prototype, "attrDragEnd", void 0);
    tslib_1.__decorate([
        Input('disabled'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxTreeComponent.prototype, "attrDisabled", void 0);
    tslib_1.__decorate([
        Input('easing'),
        tslib_1.__metadata("design:type", String)
    ], jqxTreeComponent.prototype, "attrEasing", void 0);
    tslib_1.__decorate([
        Input('enableHover'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxTreeComponent.prototype, "attrEnableHover", void 0);
    tslib_1.__decorate([
        Input('hasThreeStates'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxTreeComponent.prototype, "attrHasThreeStates", void 0);
    tslib_1.__decorate([
        Input('incrementalSearch'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxTreeComponent.prototype, "attrIncrementalSearch", void 0);
    tslib_1.__decorate([
        Input('keyboardNavigation'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxTreeComponent.prototype, "attrKeyboardNavigation", void 0);
    tslib_1.__decorate([
        Input('rtl'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxTreeComponent.prototype, "attrRtl", void 0);
    tslib_1.__decorate([
        Input('source'),
        tslib_1.__metadata("design:type", Object)
    ], jqxTreeComponent.prototype, "attrSource", void 0);
    tslib_1.__decorate([
        Input('toggleIndicatorSize'),
        tslib_1.__metadata("design:type", Number)
    ], jqxTreeComponent.prototype, "attrToggleIndicatorSize", void 0);
    tslib_1.__decorate([
        Input('toggleMode'),
        tslib_1.__metadata("design:type", String)
    ], jqxTreeComponent.prototype, "attrToggleMode", void 0);
    tslib_1.__decorate([
        Input('theme'),
        tslib_1.__metadata("design:type", String)
    ], jqxTreeComponent.prototype, "attrTheme", void 0);
    tslib_1.__decorate([
        Input('width'),
        tslib_1.__metadata("design:type", Object)
    ], jqxTreeComponent.prototype, "attrWidth", void 0);
    tslib_1.__decorate([
        Input('height'),
        tslib_1.__metadata("design:type", Object)
    ], jqxTreeComponent.prototype, "attrHeight", void 0);
    tslib_1.__decorate([
        Input('auto-create'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxTreeComponent.prototype, "autoCreate", void 0);
    tslib_1.__decorate([
        Output(),
        tslib_1.__metadata("design:type", Object)
    ], jqxTreeComponent.prototype, "onAdded", void 0);
    tslib_1.__decorate([
        Output(),
        tslib_1.__metadata("design:type", Object)
    ], jqxTreeComponent.prototype, "onCheckChange", void 0);
    tslib_1.__decorate([
        Output(),
        tslib_1.__metadata("design:type", Object)
    ], jqxTreeComponent.prototype, "onCollapse", void 0);
    tslib_1.__decorate([
        Output(),
        tslib_1.__metadata("design:type", Object)
    ], jqxTreeComponent.prototype, "onDragStart", void 0);
    tslib_1.__decorate([
        Output(),
        tslib_1.__metadata("design:type", Object)
    ], jqxTreeComponent.prototype, "onDragEnd", void 0);
    tslib_1.__decorate([
        Output(),
        tslib_1.__metadata("design:type", Object)
    ], jqxTreeComponent.prototype, "onExpand", void 0);
    tslib_1.__decorate([
        Output(),
        tslib_1.__metadata("design:type", Object)
    ], jqxTreeComponent.prototype, "onItemClick", void 0);
    tslib_1.__decorate([
        Output(),
        tslib_1.__metadata("design:type", Object)
    ], jqxTreeComponent.prototype, "onRemoved", void 0);
    tslib_1.__decorate([
        Output(),
        tslib_1.__metadata("design:type", Object)
    ], jqxTreeComponent.prototype, "onSelect", void 0);
    jqxTreeComponent = tslib_1.__decorate([
        Component({
            selector: 'jqxTree',
            template: '<div><ng-content></ng-content></div>'
        }),
        tslib_1.__metadata("design:paramtypes", [ElementRef])
    ], jqxTreeComponent);
    return jqxTreeComponent;
}()); //jqxTreeComponent
export { jqxTreeComponent };
