// jqwidgets-ts/angular_jqxsortable.ts
/// <reference path="jqwidgets.d.ts" />
import {Component, Input, Output, EventEmitter, ElementRef, forwardRef} from '@angular/core';
declare let $: any;

@Component({
    selector: 'angularSortable',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxSortableComponent {
   @Input('width') containerWidth: any;
   @Input('height') containerHeight: any;

   elementRef: ElementRef;
   host;
   widgetObject:  jqwidgets.jqxSortable;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   isHostReady(): boolean {
       return (this.host !== undefined && this.host.length == 1);
   }

   createWidget(options: any): void {
      if (!this.isHostReady()) {

         this.host = $(this.elementRef.nativeElement.firstChild);
         this.__wireEvents__();
         this.widgetObject = jqwidgets.createInstance(this.host, 'jqxSortable', options);
         this.__updateRect__();

      }
   }

   __updateRect__() : void {
      this.host.css({width: this.containerWidth, height: this.containerHeight});
   }

   setOptions(options: any) : void {
      this.host.jqxSortable('setOptions', options);
   }

   // jqxSortableComponent properties
   appendTo(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('appendTo', arg);
      } else {
          return this.host.jqxSortable('appendTo');
      }
   }

   axis(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('axis', arg);
      } else {
          return this.host.jqxSortable('axis');
      }
   }

   cancelProperty(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('cancelProperty', arg);
      } else {
          return this.host.jqxSortable('cancelProperty');
      }
   }

   connectWith(arg?: String | Boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('connectWith', arg);
      } else {
          return this.host.jqxSortable('connectWith');
      }
   }

   containment(arg?: String | Boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('containment', arg);
      } else {
          return this.host.jqxSortable('containment');
      }
   }

   cursor(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('cursor', arg);
      } else {
          return this.host.jqxSortable('cursor');
      }
   }

   cursorAt(arg?: jqwidgets.SortableCursorAt) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('cursorAt', arg);
      } else {
          return this.host.jqxSortable('cursorAt');
      }
   }

   delay(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('delay', arg);
      } else {
          return this.host.jqxSortable('delay');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('disabled', arg);
      } else {
          return this.host.jqxSortable('disabled');
      }
   }

   distance(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('distance', arg);
      } else {
          return this.host.jqxSortable('distance');
      }
   }

   dropOnEmpty(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('dropOnEmpty', arg);
      } else {
          return this.host.jqxSortable('dropOnEmpty');
      }
   }

   forceHelperSize(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('forceHelperSize', arg);
      } else {
          return this.host.jqxSortable('forceHelperSize');
      }
   }

   forcePlaceholderSize(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('forcePlaceholderSize', arg);
      } else {
          return this.host.jqxSortable('forcePlaceholderSize');
      }
   }

   grid(arg?: Array<Number>) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('grid', arg);
      } else {
          return this.host.jqxSortable('grid');
      }
   }

   handle(arg?: String | Boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('handle', arg);
      } else {
          return this.host.jqxSortable('handle');
      }
   }

   helper(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('helper', arg);
      } else {
          return this.host.jqxSortable('helper');
      }
   }

   items(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('items', arg);
      } else {
          return this.host.jqxSortable('items');
      }
   }

   opacity(arg?: Number | Boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('opacity', arg);
      } else {
          return this.host.jqxSortable('opacity');
      }
   }

   placeholderShow(arg?: String | Boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('placeholderShow', arg);
      } else {
          return this.host.jqxSortable('placeholderShow');
      }
   }

   revert(arg?: Number | Boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('revert', arg);
      } else {
          return this.host.jqxSortable('revert');
      }
   }

   scroll(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('scroll', arg);
      } else {
          return this.host.jqxSortable('scroll');
      }
   }

   scrollSensitivity(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('scrollSensitivity', arg);
      } else {
          return this.host.jqxSortable('scrollSensitivity');
      }
   }

   scrollSpeed(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('scrollSpeed', arg);
      } else {
          return this.host.jqxSortable('scrollSpeed');
      }
   }

   tolerance(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('tolerance', arg);
      } else {
          return this.host.jqxSortable('tolerance');
      }
   }

   zIndex(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxSortable('zIndex', arg);
      } else {
          return this.host.jqxSortable('zIndex');
      }
   }


   // jqxSortableComponent functions
   cancelMethod(): void {
      this.host.jqxSortable('cancelMethod');

   }
   destroy(): void {
      this.host.jqxSortable('destroy');

   }
   disable(): void {
      this.host.jqxSortable('disable');

   }
   enable(): void {
      this.host.jqxSortable('enable');

   }
   refresh(): void {
      this.host.jqxSortable('refresh');

   }
   refreshPositions(): void {
      this.host.jqxSortable('refreshPositions');

   }
   serialize(): void {
      this.host.jqxSortable('serialize');

   }
   toArray(): Array<any> {
      return this.host.jqxSortable('toArray');

   }

   // jqxSortableComponent events
   @Output() OnActivate = new EventEmitter();
   @Output() OnBeforeStop = new EventEmitter();
   @Output() OnChange = new EventEmitter();
   @Output() OnCreate = new EventEmitter();
   @Output() OnDeactivate = new EventEmitter();
   @Output() OnOut = new EventEmitter();
   @Output() OnOver = new EventEmitter();
   @Output() OnReceive = new EventEmitter();
   @Output() OnRemove = new EventEmitter();
   @Output() OnSort = new EventEmitter();
   @Output() OnStart = new EventEmitter();
   @Output() OnStop = new EventEmitter();
   @Output() OnUpdate = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('activate', (eventData) => { this.OnActivate.emit(eventData); });
      this.host.on('beforeStop', (eventData) => { this.OnBeforeStop.emit(eventData); });
      this.host.on('change', (eventData) => { this.OnChange.emit(eventData); });
      this.host.on('create', (eventData) => { this.OnCreate.emit(eventData); });
      this.host.on('deactivate', (eventData) => { this.OnDeactivate.emit(eventData); });
      this.host.on('out', (eventData) => { this.OnOut.emit(eventData); });
      this.host.on('over', (eventData) => { this.OnOver.emit(eventData); });
      this.host.on('receive', (eventData) => { this.OnReceive.emit(eventData); });
      this.host.on('remove', (eventData) => { this.OnRemove.emit(eventData); });
      this.host.on('sort', (eventData) => { this.OnSort.emit(eventData); });
      this.host.on('start', (eventData) => { this.OnStart.emit(eventData); });
      this.host.on('stop', (eventData) => { this.OnStop.emit(eventData); });
      this.host.on('update', (eventData) => { this.OnUpdate.emit(eventData); });
   }

} //jqxSortableComponent

// jqwidgets-react-tsx/src/react_jqxsortable.tsx

/* tslint:disable:ordered-imports */
import * as React from 'react';

class JqxSortable extends React.PureComponent<ISortableProps, IState> {
    protected static getDerivedStateFromProps(props: ISortableProps, state: IState): null | IState {
        if (!Object.is) {
            Object.is = function (x, y) {
                if (x === y) {
                    return x !== 0 || 1 / x === 1 / y;
                } else {
                    return x !== x && y !== y;
                }
            };
        }

        const areEqual = Object.is(props, state.lastProps) as boolean;

        if (!areEqual) {
            const newState = { lastProps: props } as IState;
            return newState;
        }

        return null;
    }

    /* tslint:disable:variable-name */
    private _jqx = JQXLite as any;
    /* tslint:disable:variable-name */
    private _id: string;
    /* tslint:disable:variable-name */
    private _componentSelector: string;

    constructor(props: ISortableProps) {
        super(props);

        this._id = 'JqxSortable' + this._jqx.generateID();
        this._componentSelector = '#' + this._id;

        this.state = { lastProps: props };
    }

    public componentDidMount(): void {
        const widgetOptions = this._manageProps() as ISortableProps;
        this._jqx(this._componentSelector).jqxSortable(widgetOptions);
        this._wireEvents();
    }

    public componentDidUpdate(): void {
        const widgetOptions = this._manageProps() as ISortableProps;
        this.setOptions(widgetOptions);
    }

    public render(): React.ReactNode {
        return (
            <div id={this._id} className={this.props.className} style={this.props.style}>
                {this.props.children}
            </div>
        );
    }

    public setOptions(options: ISortableProps): void {
        this._jqx(this._componentSelector).jqxSortable(options);
    }

    public getOptions(option: string): any {
        return this._jqx(this._componentSelector).jqxSortable(option);
    }

    public cancelMethod(): void {
        this._jqx(this._componentSelector).jqxSortable('cancelMethod' );
    };

    public destroy(): void {
        this._jqx(this._componentSelector).jqxSortable('destroy' );
    };

    public disable(): void {
        this._jqx(this._componentSelector).jqxSortable('disable' );
    };

    public enable(): void {
        this._jqx(this._componentSelector).jqxSortable('enable' );
    };

    public refresh(): void {
        this._jqx(this._componentSelector).jqxSortable('refresh' );
    };

    public refreshPositions(): void {
        this._jqx(this._componentSelector).jqxSortable('refreshPositions' );
    };

    public serialize(object: any): string {
        return this._jqx(this._componentSelector).jqxSortable('serialize' , object);
    };

    public toArray(): any[] {
        return this._jqx(this._componentSelector).jqxSortable('toArray' );
    };

    private _manageProps(): ISortableProps {
        const widgetProps: string[] = ['appendTo','axis','cancel','connectWith','containment','cursor','cursorAt','delay','disabled','distance','dropOnEmpty','forceHelperSize','forcePlaceholderSize','grid','handle','helper','items','opacity','placeholderShow','revert','scroll','scrollSensitivity','scrollSpeed','tolerance','zIndex'];

        const options = {} as ISortableProps;

        for (const prop in this.props) {
            if (widgetProps.indexOf(prop) !== -1) {
                options[prop] = this.props[prop];
            }
        }

        return options;
    }

    private _wireEvents(): void {
        for (const prop in this.props) {
            if (prop.indexOf('on') === 0) {
                let originalEventName = prop.slice(2) as string;
                originalEventName = originalEventName.charAt(0).toLowerCase() + originalEventName.slice(1);
                this._jqx(this._componentSelector).on(originalEventName, this.props[prop]);
            }
        }
    }
}

export default JqxSortable;

interface IWindow { jqx: any;  JQXLite: any; }
declare const window: IWindow;
export const jqx = window.jqx;
export const JQXLite = window.JQXLite;

interface IState {
    lastProps: object;
}

export interface ISortableCursorAt {
    left?: number;
    top?: number;
    right?: number;
    bottom?: number;
}

interface ISortableOptions {
    appendTo?: string;
    axis?: number | string;
    cancel?: string;
    connectWith?: string | boolean;
    containment?: string | boolean;
    cursor?: string;
    cursorAt?: ISortableCursorAt;
    delay?: number;
    disabled?: boolean;
    distance?: number;
    dropOnEmpty?: boolean;
    forceHelperSize?: boolean;
    forcePlaceholderSize?: boolean;
    grid?: number[];
    handle?: string | boolean;
    helper?: (originalEvent?: any, content?: any) => void | 'original' | 'clone';
    items?: string;
    opacity?: number | boolean;
    placeholderShow?: string | boolean;
    revert?: number | boolean;
    scroll?: boolean;
    scrollSensitivity?: number;
    scrollSpeed?: number;
    tolerance?: 'intersect' | 'pointer';
    zIndex?: number;
}

export interface ISortableProps extends ISortableOptions {
    className?: string; 
    style?: React.CSSProperties; 
    onActivate?: (e?: Event) => void;
    onBeforeStop?: (e?: Event) => void;
    onChange?: (e?: Event) => void;
    onDeactivate?: (e?: Event) => void;
    onOut?: (e?: Event) => void;
    onOver?: (e?: Event) => void;
    onReceive?: (e?: Event) => void;
    onRemove?: (e?: Event) => void;
    onSort?: (e?: Event) => void;
    onStart?: (e?: Event) => void;
    onStop?: (e?: Event) => void;
    onUpdate?: (e?: Event) => void;
}
