// jqwidgets-ts/angular_jqxcombobox.ts
/*
jQWidgets v5.3.2 (2017-Sep)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges, ChangeDetectionStrategy } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

const noop = () => { };
declare let JQXLite: any;

export const CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR: any = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => jqxComboBoxComponent),
    multi: true
}

@Component({
    selector: 'jqxComboBox',
    template: '<div><ng-content></ng-content></div>',
    providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR],
    changeDetection: ChangeDetectionStrategy.OnPush
})

export class jqxComboBoxComponent implements ControlValueAccessor, OnChanges 
{
   @Input('animationType') attrAnimationType: any;
   @Input('autoComplete') attrAutoComplete: any;
   @Input('autoOpen') attrAutoOpen: any;
   @Input('autoItemsHeight') attrAutoItemsHeight: any;
   @Input('autoDropDownHeight') attrAutoDropDownHeight: any;
   @Input('closeDelay') attrCloseDelay: any;
   @Input('checkboxes') attrCheckboxes: any;
   @Input('disabled') attrDisabled: any;
   @Input('displayMember') attrDisplayMember: any;
   @Input('dropDownHorizontalAlignment') attrDropDownHorizontalAlignment: any;
   @Input('dropDownVerticalAlignment') attrDropDownVerticalAlignment: any;
   @Input('dropDownHeight') attrDropDownHeight: any;
   @Input('dropDownWidth') attrDropDownWidth: any;
   @Input('enableHover') attrEnableHover: any;
   @Input('enableSelection') attrEnableSelection: any;
   @Input('enableBrowserBoundsDetection') attrEnableBrowserBoundsDetection: any;
   @Input('itemHeight') attrItemHeight: any;
   @Input('multiSelect') attrMultiSelect: any;
   @Input('minLength') attrMinLength: any;
   @Input('openDelay') attrOpenDelay: any;
   @Input('popupZIndex') attrPopupZIndex: any;
   @Input('placeHolder') attrPlaceHolder: any;
   @Input('remoteAutoComplete') attrRemoteAutoComplete: any;
   @Input('remoteAutoCompleteDelay') attrRemoteAutoCompleteDelay: any;
   @Input('renderer') attrRenderer: any;
   @Input('renderSelectedItem') attrRenderSelectedItem: any;
   @Input('rtl') attrRtl: any;
   @Input('selectedIndex') attrSelectedIndex: any;
   @Input('showArrow') attrShowArrow: any;
   @Input('showCloseButtons') attrShowCloseButtons: any;
   @Input('searchMode') attrSearchMode: any;
   @Input('search') attrSearch: any;
   @Input('source') attrSource: any;
   @Input('scrollBarSize') attrScrollBarSize: any;
   @Input('template') attrTemplate: any;
   @Input('theme') attrTheme: any;
   @Input('validateSelection') attrValidateSelection: any;
   @Input('valueMember') attrValueMember: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['animationType','autoComplete','autoOpen','autoItemsHeight','autoDropDownHeight','closeDelay','checkboxes','disabled','displayMember','dropDownHorizontalAlignment','dropDownVerticalAlignment','dropDownHeight','dropDownWidth','enableHover','enableSelection','enableBrowserBoundsDetection','height','itemHeight','multiSelect','minLength','openDelay','popupZIndex','placeHolder','remoteAutoComplete','remoteAutoCompleteDelay','renderer','renderSelectedItem','rtl','selectedIndex','showArrow','showCloseButtons','searchMode','search','source','scrollBarSize','template','theme','validateSelection','valueMember','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxComboBox;

   private onTouchedCallback: () => void = noop;
   private onChangeCallback: (_: any) => void = noop;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxComboBox(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxComboBox(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxComboBox(this.properties[i])) {
                  this.host.jqxComboBox(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void {
      let classes: any = parentEl.classList;
      childEl.classList.add(...classes);
      parentEl.className = '';
   }

   moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void {
      let style = parentEl.style.cssText;
      childEl.style.cssText = style
      parentEl.style.cssText = '';
   }

   createComponent(options?: any): void {
      if (options) {
         JQXLite.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = JQXLite(this.elementRef.nativeElement.firstChild);

      this.moveClasses(this.elementRef.nativeElement, this.host[0]);
      this.moveStyles(this.elementRef.nativeElement, this.host[0]);

      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxComboBox', options);

      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   writeValue(value: any): void {
       if(this.widgetObject) {
           this.onChangeCallback(this.host.val());
       }
   }

   registerOnChange(fn: any): void {
       this.onChangeCallback = fn;
   }

   registerOnTouched(fn: any): void {
       this.onTouchedCallback = fn;
   }

   setOptions(options: any) : void {
      this.host.jqxComboBox('setOptions', options);
   }

   // jqxComboBoxComponent properties
   animationType(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('animationType', arg);
      } else {
          return this.host.jqxComboBox('animationType');
      }
   }

   autoComplete(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('autoComplete', arg);
      } else {
          return this.host.jqxComboBox('autoComplete');
      }
   }

   autoOpen(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('autoOpen', arg);
      } else {
          return this.host.jqxComboBox('autoOpen');
      }
   }

   autoItemsHeight(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('autoItemsHeight', arg);
      } else {
          return this.host.jqxComboBox('autoItemsHeight');
      }
   }

   autoDropDownHeight(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('autoDropDownHeight', arg);
      } else {
          return this.host.jqxComboBox('autoDropDownHeight');
      }
   }

   closeDelay(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('closeDelay', arg);
      } else {
          return this.host.jqxComboBox('closeDelay');
      }
   }

   checkboxes(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('checkboxes', arg);
      } else {
          return this.host.jqxComboBox('checkboxes');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('disabled', arg);
      } else {
          return this.host.jqxComboBox('disabled');
      }
   }

   displayMember(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('displayMember', arg);
      } else {
          return this.host.jqxComboBox('displayMember');
      }
   }

   dropDownHorizontalAlignment(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('dropDownHorizontalAlignment', arg);
      } else {
          return this.host.jqxComboBox('dropDownHorizontalAlignment');
      }
   }

   dropDownVerticalAlignment(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('dropDownVerticalAlignment', arg);
      } else {
          return this.host.jqxComboBox('dropDownVerticalAlignment');
      }
   }

   dropDownHeight(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('dropDownHeight', arg);
      } else {
          return this.host.jqxComboBox('dropDownHeight');
      }
   }

   dropDownWidth(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('dropDownWidth', arg);
      } else {
          return this.host.jqxComboBox('dropDownWidth');
      }
   }

   enableHover(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('enableHover', arg);
      } else {
          return this.host.jqxComboBox('enableHover');
      }
   }

   enableSelection(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('enableSelection', arg);
      } else {
          return this.host.jqxComboBox('enableSelection');
      }
   }

   enableBrowserBoundsDetection(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('enableBrowserBoundsDetection', arg);
      } else {
          return this.host.jqxComboBox('enableBrowserBoundsDetection');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('height', arg);
      } else {
          return this.host.jqxComboBox('height');
      }
   }

   itemHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('itemHeight', arg);
      } else {
          return this.host.jqxComboBox('itemHeight');
      }
   }

   multiSelect(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('multiSelect', arg);
      } else {
          return this.host.jqxComboBox('multiSelect');
      }
   }

   minLength(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('minLength', arg);
      } else {
          return this.host.jqxComboBox('minLength');
      }
   }

   openDelay(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('openDelay', arg);
      } else {
          return this.host.jqxComboBox('openDelay');
      }
   }

   popupZIndex(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('popupZIndex', arg);
      } else {
          return this.host.jqxComboBox('popupZIndex');
      }
   }

   placeHolder(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('placeHolder', arg);
      } else {
          return this.host.jqxComboBox('placeHolder');
      }
   }

   remoteAutoComplete(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('remoteAutoComplete', arg);
      } else {
          return this.host.jqxComboBox('remoteAutoComplete');
      }
   }

   remoteAutoCompleteDelay(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('remoteAutoCompleteDelay', arg);
      } else {
          return this.host.jqxComboBox('remoteAutoCompleteDelay');
      }
   }

   renderer(arg?: (index:number, label?:string, value?:any) => string) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('renderer', arg);
      } else {
          return this.host.jqxComboBox('renderer');
      }
   }

   renderSelectedItem(arg?: (index:number, item?:any) => string) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('renderSelectedItem', arg);
      } else {
          return this.host.jqxComboBox('renderSelectedItem');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('rtl', arg);
      } else {
          return this.host.jqxComboBox('rtl');
      }
   }

   selectedIndex(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('selectedIndex', arg);
      } else {
          return this.host.jqxComboBox('selectedIndex');
      }
   }

   showArrow(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('showArrow', arg);
      } else {
          return this.host.jqxComboBox('showArrow');
      }
   }

   showCloseButtons(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('showCloseButtons', arg);
      } else {
          return this.host.jqxComboBox('showCloseButtons');
      }
   }

   searchMode(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('searchMode', arg);
      } else {
          return this.host.jqxComboBox('searchMode');
      }
   }

   search(arg?: (searchString:string) => void) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('search', arg);
      } else {
          return this.host.jqxComboBox('search');
      }
   }

   source(arg?: Array<any>) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('source', arg);
      } else {
          return this.host.jqxComboBox('source');
      }
   }

   scrollBarSize(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('scrollBarSize', arg);
      } else {
          return this.host.jqxComboBox('scrollBarSize');
      }
   }

   template(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('template', arg);
      } else {
          return this.host.jqxComboBox('template');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('theme', arg);
      } else {
          return this.host.jqxComboBox('theme');
      }
   }

   validateSelection(arg?: (itemValue:string) => boolean) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('validateSelection', arg);
      } else {
          return this.host.jqxComboBox('validateSelection');
      }
   }

   valueMember(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('valueMember', arg);
      } else {
          return this.host.jqxComboBox('valueMember');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxComboBox('width', arg);
      } else {
          return this.host.jqxComboBox('width');
      }
   }


   // jqxComboBoxComponent functions
   addItem(item: any): boolean {
      return this.host.jqxComboBox('addItem', item);
   }

   clearSelection(): void {
      this.host.jqxComboBox('clearSelection');
   }

   clear(): void {
      this.host.jqxComboBox('clear');
   }

   close(): void {
      this.host.jqxComboBox('close');
   }

   checkIndex(index: number): void {
      this.host.jqxComboBox('checkIndex', index);
   }

   checkItem(item: any): void {
      this.host.jqxComboBox('checkItem', item);
   }

   checkAll(): void {
      this.host.jqxComboBox('checkAll');
   }

   destroy(): void {
      this.host.jqxComboBox('destroy');
   }

   disableItem(item: any): void {
      this.host.jqxComboBox('disableItem', item);
   }

   disableAt(index: number): void {
      this.host.jqxComboBox('disableAt', index);
   }

   enableItem(item: any): void {
      this.host.jqxComboBox('enableItem', item);
   }

   enableAt(index: number): void {
      this.host.jqxComboBox('enableAt', index);
   }

   ensureVisible(index: number): void {
      this.host.jqxComboBox('ensureVisible', index);
   }

   focus(): void {
      this.host.jqxComboBox('focus');
   }

   getItem(index: number): any {
      return this.host.jqxComboBox('getItem', index);
   }

   getItemByValue(value: string): any {
      return this.host.jqxComboBox('getItemByValue', value);
   }

   getVisibleItems(): Array<any> {
      return this.host.jqxComboBox('getVisibleItems');
   }

   getItems(): Array<any> {
      return this.host.jqxComboBox('getItems');
   }

   getCheckedItems(): Array<any> {
      return this.host.jqxComboBox('getCheckedItems');
   }

   getSelectedItem(): any {
      return this.host.jqxComboBox('getSelectedItem');
   }

   getSelectedItems(): Array<any> {
      return this.host.jqxComboBox('getSelectedItems');
   }

   getSelectedIndex(): number {
      return this.host.jqxComboBox('getSelectedIndex');
   }

   insertAt(item: any, index: number): boolean {
      return this.host.jqxComboBox('insertAt', item, index);
   }

   isOpened(): boolean {
      return this.host.jqxComboBox('isOpened');
   }

   indeterminateIndex(index: number): void {
      this.host.jqxComboBox('indeterminateIndex', index);
   }

   indeterminateItem(item: any): void {
      this.host.jqxComboBox('indeterminateItem', item);
   }

   loadFromSelect(selectTagId: string): void {
      this.host.jqxComboBox('loadFromSelect', selectTagId);
   }

   open(): void {
      this.host.jqxComboBox('open');
   }

   removeItem(item: any): boolean {
      return this.host.jqxComboBox('removeItem', item);
   }

   removeAt(index: number): boolean {
      return this.host.jqxComboBox('removeAt', index);
   }

   selectIndex(index: number): void {
      this.host.jqxComboBox('selectIndex', index);
   }

   selectItem(item: any): void {
      this.host.jqxComboBox('selectItem', item);
   }

   searchString(): undefined {
      return this.host.jqxComboBox('searchString');
   }

   updateItem(item: any, itemValue: string): void {
      this.host.jqxComboBox('updateItem', item, itemValue);
   }

   updateAt(item: any, index: any): void {
      this.host.jqxComboBox('updateAt', item, index);
   }

   unselectIndex(index: number): void {
      this.host.jqxComboBox('unselectIndex', index);
   }

   unselectItem(item: any): void {
      this.host.jqxComboBox('unselectItem', item);
   }

   uncheckIndex(index: number): void {
      this.host.jqxComboBox('uncheckIndex', index);
   }

   uncheckItem(item: any): void {
      this.host.jqxComboBox('uncheckItem', item);
   }

   uncheckAll(): void {
      this.host.jqxComboBox('uncheckAll');
   }

   val(value?: string): any {
      if (value !== undefined) {
         return this.host.jqxComboBox("val", value);
      } else {
         return this.host.jqxComboBox("val");
      }
   };


   // jqxComboBoxComponent events
   @Output() onBindingComplete = new EventEmitter();
   @Output() onCheckChange = new EventEmitter();
   @Output() onClose = new EventEmitter();
   @Output() onChange = new EventEmitter();
   @Output() onOpen = new EventEmitter();
   @Output() onSelect = new EventEmitter();
   @Output() onUnselect = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('bindingComplete', (eventData: any) => { this.onBindingComplete.emit(eventData); });
      this.host.on('checkChange', (eventData: any) => { this.onCheckChange.emit(eventData); });
      this.host.on('close', (eventData: any) => { this.onClose.emit(eventData); });
      this.host.on('change', (eventData: any) => { this.onChange.emit(eventData); if(eventData.args) if(eventData.args.item !== null) this.onChangeCallback(eventData.args.item.label); });
      this.host.on('open', (eventData: any) => { this.onOpen.emit(eventData); });
      this.host.on('select', (eventData: any) => { this.onSelect.emit(eventData); });
      this.host.on('unselect', (eventData: any) => { this.onUnselect.emit(eventData); });
   }

} //jqxComboBoxComponent

// jqwidgets-react-tsx/src/react_jqxcombobox.tsx

/* tslint:disable:ordered-imports */
import * as React from 'react';

class JqxComboBox extends React.PureComponent<IComboBoxProps, IState> {
    protected static getDerivedStateFromProps(props: IComboBoxProps, state: IState): null | IState {
        if (!Object.is) {
            Object.is = function (x, y) {
                if (x === y) {
                    return x !== 0 || 1 / x === 1 / y;
                } else {
                    return x !== x && y !== y;
                }
            };
        }

        const areEqual = Object.is(props, state.lastProps) as boolean;

        if (!areEqual) {
            const newState = { lastProps: props } as IState;
            return newState;
        }

        return null;
    }

    /* tslint:disable:variable-name */
    private _jqx = JQXLite as any;
    /* tslint:disable:variable-name */
    private _id: string;
    /* tslint:disable:variable-name */
    private _componentSelector: string;

    constructor(props: IComboBoxProps) {
        super(props);

        this._id = 'JqxComboBox' + this._jqx.generateID();
        this._componentSelector = '#' + this._id;

        this.state = { lastProps: props };
    }

    public componentDidMount(): void {
        const widgetOptions = this._manageProps() as IComboBoxProps;
        this._jqx(this._componentSelector).jqxComboBox(widgetOptions);
        this._wireEvents();
    }

    public componentDidUpdate(): void {
        const widgetOptions = this._manageProps() as IComboBoxProps;
        this.setOptions(widgetOptions);
    }

    public render(): React.ReactNode {
        return (
            <div id={this._id} className={this.props.className} style={this.props.style}>
                {this.props.children}
            </div>
        );
    }

    public setOptions(options: IComboBoxProps): void {
        this._jqx(this._componentSelector).jqxComboBox(options);
    }

    public getOptions(option: string): any {
        return this._jqx(this._componentSelector).jqxComboBox(option);
    }

    public addItem(item: any): boolean {
        return this._jqx(this._componentSelector).jqxComboBox('addItem' , item);
    };

    public clearSelection(): void {
        this._jqx(this._componentSelector).jqxComboBox('clearSelection' );
    };

    public clear(): void {
        this._jqx(this._componentSelector).jqxComboBox('clear' );
    };

    public close(): void {
        this._jqx(this._componentSelector).jqxComboBox('close' );
    };

    public checkIndex(index: number): void {
        this._jqx(this._componentSelector).jqxComboBox('checkIndex' , index);
    };

    public checkItem(item: any): void {
        this._jqx(this._componentSelector).jqxComboBox('checkItem' , item);
    };

    public checkAll(): void {
        this._jqx(this._componentSelector).jqxComboBox('checkAll' );
    };

    public destroy(): void {
        this._jqx(this._componentSelector).jqxComboBox('destroy' );
    };

    public disableItem(item: any): void {
        this._jqx(this._componentSelector).jqxComboBox('disableItem' , item);
    };

    public disableAt(index: number): void {
        this._jqx(this._componentSelector).jqxComboBox('disableAt' , index);
    };

    public enableItem(item: any): void {
        this._jqx(this._componentSelector).jqxComboBox('enableItem' , item);
    };

    public enableAt(index: number): void {
        this._jqx(this._componentSelector).jqxComboBox('enableAt' , index);
    };

    public ensureVisible(index: number): void {
        this._jqx(this._componentSelector).jqxComboBox('ensureVisible' , index);
    };

    public focus(): void {
        this._jqx(this._componentSelector).jqxComboBox('focus' );
    };

    public getItem(index: number): any {
        return this._jqx(this._componentSelector).jqxComboBox('getItem' , index);
    };

    public getItemByValue(value: string): any {
        return this._jqx(this._componentSelector).jqxComboBox('getItemByValue' , value);
    };

    public getVisibleItems(): any[] {
        return this._jqx(this._componentSelector).jqxComboBox('getVisibleItems' );
    };

    public getItems(): any[] {
        return this._jqx(this._componentSelector).jqxComboBox('getItems' );
    };

    public getCheckedItems(): any[] {
        return this._jqx(this._componentSelector).jqxComboBox('getCheckedItems' );
    };

    public getSelectedItem(): any {
        return this._jqx(this._componentSelector).jqxComboBox('getSelectedItem' );
    };

    public getSelectedItems(): any[] {
        return this._jqx(this._componentSelector).jqxComboBox('getSelectedItems' );
    };

    public getSelectedIndex(): number {
        return this._jqx(this._componentSelector).jqxComboBox('getSelectedIndex' );
    };

    public insertAt(item: any, index: number): boolean {
        return this._jqx(this._componentSelector).jqxComboBox('insertAt' , item, index);
    };

    public isOpened(): boolean {
        return this._jqx(this._componentSelector).jqxComboBox('isOpened' );
    };

    public indeterminateIndex(index: number): void {
        this._jqx(this._componentSelector).jqxComboBox('indeterminateIndex' , index);
    };

    public indeterminateItem(item: any): void {
        this._jqx(this._componentSelector).jqxComboBox('indeterminateItem' , item);
    };

    public loadFromSelect(selectTagId: string): void {
        this._jqx(this._componentSelector).jqxComboBox('loadFromSelect' , selectTagId);
    };

    public open(): void {
        this._jqx(this._componentSelector).jqxComboBox('open' );
    };

    public removeItem(item: any): boolean {
        return this._jqx(this._componentSelector).jqxComboBox('removeItem' , item);
    };

    public removeAt(index: number): boolean {
        return this._jqx(this._componentSelector).jqxComboBox('removeAt' , index);
    };

    public selectIndex(index: number): void {
        this._jqx(this._componentSelector).jqxComboBox('selectIndex' , index);
    };

    public selectItem(item: any): void {
        this._jqx(this._componentSelector).jqxComboBox('selectItem' , item);
    };

    public searchString(): string {
        return this._jqx(this._componentSelector).jqxComboBox('searchString' );
    };

    public updateItem(item: any, itemValue: string): void {
        this._jqx(this._componentSelector).jqxComboBox('updateItem' , item, itemValue);
    };

    public updateAt(item: any, index: any): void {
        this._jqx(this._componentSelector).jqxComboBox('updateAt' , item, index);
    };

    public unselectIndex(index: number): void {
        this._jqx(this._componentSelector).jqxComboBox('unselectIndex' , index);
    };

    public unselectItem(item: any): void {
        this._jqx(this._componentSelector).jqxComboBox('unselectItem' , item);
    };

    public uncheckIndex(index: number): void {
        this._jqx(this._componentSelector).jqxComboBox('uncheckIndex' , index);
    };

    public uncheckItem(item: any): void {
        this._jqx(this._componentSelector).jqxComboBox('uncheckItem' , item);
    };

    public uncheckAll(): void {
        this._jqx(this._componentSelector).jqxComboBox('uncheckAll' );
    };

    public val(value?: string): string {
        return this._jqx(this._componentSelector).jqxComboBox('val' , value);
    };

    private _manageProps(): IComboBoxProps {
        const widgetProps: string[] = ['animationType','autoComplete','autoOpen','autoItemsHeight','autoDropDownHeight','closeDelay','checkboxes','disabled','displayMember','dropDownHorizontalAlignment','dropDownVerticalAlignment','dropDownHeight','dropDownWidth','enableHover','enableSelection','enableBrowserBoundsDetection','height','itemHeight','multiSelect','minLength','openDelay','popupZIndex','placeHolder','remoteAutoComplete','remoteAutoCompleteDelay','renderer','renderSelectedItem','rtl','selectedIndex','showArrow','showCloseButtons','searchMode','search','source','scrollBarSize','template','theme','validateSelection','valueMember','width'];

        const options = {} as IComboBoxProps;

        for (const prop in this.props) {
            if (widgetProps.indexOf(prop) !== -1) {
                 options[prop] = this.props[prop];
            }
        }

        return options;
    }

    private _wireEvents(): void {
        for (const prop in this.props) {
            if (prop.indexOf('on') === 0) {
                let originalEventName = prop.slice(2) as string;
                originalEventName = originalEventName.charAt(0).toLowerCase() + originalEventName.slice(1);
                this._jqx(this._componentSelector).on(originalEventName, this.props[prop]);
            }
        }
    }
}

export default JqxComboBox;

interface IWindow { jqx: any;  JQXLite: any; }
declare const window: IWindow;
export const jqx = window.jqx;
export const JQXLite = window.JQXLite;

interface IState {
    lastProps: object;
}

export interface IComboBoxRenderer {
    index?: number;
    label?: number | string;
    value?: number | string;
}

export interface IComboBoxRenderSelectedItem {
    index?: number;
    item?: any;
}

export interface IComboBoxSearch {
    searchString?: string;
}

export interface IComboBoxValidateSelection {
    itemValue?: string;
}

interface IComboBoxOptions {
    animationType?: 'fade' | 'slide' | 'none';
    autoComplete?: boolean;
    autoOpen?: boolean;
    autoItemsHeight?: boolean;
    autoDropDownHeight?: boolean;
    closeDelay?: number;
    checkboxes?: boolean;
    disabled?: boolean;
    displayMember?: string;
    dropDownHorizontalAlignment?: 'left' | 'right';
    dropDownVerticalAlignment?: 'top' | 'bottom';
    dropDownHeight?: number | string;
    dropDownWidth?: number | string;
    enableHover?: boolean;
    enableSelection?: boolean;
    enableBrowserBoundsDetection?: boolean;
    height?: string | number;
    itemHeight?: number;
    multiSelect?: boolean;
    minLength?: number;
    openDelay?: number;
    popupZIndex?: number;
    placeHolder?: string;
    remoteAutoComplete?: boolean;
    remoteAutoCompleteDelay?: number;
    renderer?: (index?: IComboBoxRenderer['index'], label?: IComboBoxRenderer['label'], value?: IComboBoxRenderer['value']) => string;
    renderSelectedItem?: (index?: IComboBoxRenderSelectedItem['index'], item?: IComboBoxRenderSelectedItem['item']) => string;
    rtl?: boolean;
    selectedIndex?: number;
    showArrow?: boolean;
    showCloseButtons?: boolean;
    searchMode?: 'none' | 'contains' | 'containsignorecase' | 'equals' | 'equalsignorecase' | 'startswithignorecase' | 'startswith' | 'endswithignorecase' | 'endswith';
    search?: (searchString?: IComboBoxSearch['searchString']) => void;
    source?: any;
    scrollBarSize?: number | string;
    template?: 'default' | 'primary' | 'success' | 'warning' | 'danger' | 'info';
    theme?: string;
    validateSelection?: (itemValue?: IComboBoxValidateSelection['itemValue']) => boolean;
    valueMember?: string;
    width?: string | number;
}

export interface IComboBoxProps extends IComboBoxOptions {
    className?: string; 
    style?: React.CSSProperties; 
    onBindingComplete?: (e?: Event) => void;
    onCheckChange?: (e?: Event) => void;
    onClose?: (e?: Event) => void;
    onChange?: (e?: Event) => void;
    onOpen?: (e?: Event) => void;
    onSelect?: (e?: Event) => void;
    onUnselect?: (e?: Event) => void;
}
