// jqwidgets-vue3/vue_jqxeditor.vue
<template>
        <textarea :value="modelValue" v-bind:id="id"></textarea>
</template>

<script>
	import { onUpdated, onMounted } from 'vue';
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxdata.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxscrollbar.js';
    import '../jqwidgets/jqxlistbox.js';
    import '../jqwidgets/jqxdropdownlist.js';
    import '../jqwidgets/jqxdropdownbutton.js';
    import '../jqwidgets/jqxwindow.js';
    import '../jqwidgets/jqxeditor.js';
    import '../jqwidgets/jqxcheckbox.js';
    import '../jqwidgets/jqxtooltip.js';
    import '../jqwidgets/jqxcolorpicker.js';

    export default {
        props: {
            createCommand: Function,
            disabled: {
                default: false,
                type: Boolean
            },
            editable: {
                default: true,
                type: Boolean
            },
            height: [String, Number],
            lineBreak: String,
            localization: Object,
            pasteMode: String,
            rtl: {
                default: false,
                type: Boolean
            },
            stylesheets: Array,
            theme: String,
            toolbarPosition: String,
            tools: String,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        emits: ["change"],
        setup(props, context) {
			const id = "jqxEditor" + JQXLite.generateID();
			const componentSelector = '#' + id;
            function createComponent(options) {
                if (!props.autoCreate) __createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            }
            function setOptions (options) {
                JQXLite(componentSelector).jqxEditor(options);
            }
            function getOptions() {
                const usedProps = Object.keys(__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(componentSelector).jqxEditor(usedProps[i]);
                }
                return resultToReturn;
            }
            function destroy() {
                JQXLite(componentSelector).jqxEditor('destroy');  
            }
            function focus() {
                JQXLite(componentSelector).jqxEditor('focus');  
            }
            function print() {
                JQXLite(componentSelector).jqxEditor('print');  
            }
            function setMode(mode) {
                JQXLite(componentSelector).jqxEditor('setMode', mode);  
            }
            function val(value) {
                if (value !== undefined) {
                    JQXLite(componentSelector).jqxEditor('val',  value)
                } else {
                    return JQXLite(componentSelector).jqxEditor('val');
                }
            }
            function _createCommand (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxEditor('createCommand', arg)
                } else {
                    return JQXLite(componentSelector).jqxEditor('createCommand');
                }
            }
            function _disabled (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxEditor('disabled', arg)
                } else {
                    return JQXLite(componentSelector).jqxEditor('disabled');
                }
            }
            function _editable (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxEditor('editable', arg)
                } else {
                    return JQXLite(componentSelector).jqxEditor('editable');
                }
            }
            function _height (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxEditor('height', arg)
                } else {
                    return JQXLite(componentSelector).jqxEditor('height');
                }
            }
            function _lineBreak (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxEditor('lineBreak', arg)
                } else {
                    return JQXLite(componentSelector).jqxEditor('lineBreak');
                }
            }
            function _localization (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxEditor('localization', arg)
                } else {
                    return JQXLite(componentSelector).jqxEditor('localization');
                }
            }
            function _pasteMode (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxEditor('pasteMode', arg)
                } else {
                    return JQXLite(componentSelector).jqxEditor('pasteMode');
                }
            }
            function _rtl (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxEditor('rtl', arg)
                } else {
                    return JQXLite(componentSelector).jqxEditor('rtl');
                }
            }
            function _stylesheets (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxEditor('stylesheets', arg)
                } else {
                    return JQXLite(componentSelector).jqxEditor('stylesheets');
                }
            }
            function _theme (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxEditor('theme', arg)
                } else {
                    return JQXLite(componentSelector).jqxEditor('theme');
                }
            }
            function _toolbarPosition (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxEditor('toolbarPosition', arg)
                } else {
                    return JQXLite(componentSelector).jqxEditor('toolbarPosition');
                }
            }
            function _tools (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxEditor('tools', arg)
                } else {
                    return JQXLite(componentSelector).jqxEditor('tools');
                }
            }
            function _width (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxEditor('width', arg)
                } else {
                    return JQXLite(componentSelector).jqxEditor('width');
                }
            }
            function __createComponent__ (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = __manageProps__();
                JQXLite(componentSelector).jqxEditor(widgetOptions);
                if ($slots.default) {
                    JQXLite(componentSelector).jqxEditor('val', $slots.default[0].text);
                }
                __wireEvents__();
            }
            function __manageProps__() {
                const widgetProps = ['createCommand','disabled','editable','height','lineBreak','localization','pasteMode','rtl','stylesheets','theme','toolbarPosition','tools','width'];
                const componentProps = props;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1 && componentProps[prop] !== undefined) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            }
            const options = {
                 get createCommand() {
                     return _createCommand();
                 },
                 set createCommand(newValue) {
                     _createCommand(newValue);
                 },
                 get disabled() {
                     return _disabled();
                 },
                 set disabled(newValue) {
                     _disabled(newValue);
                 },
                 get editable() {
                     return _editable();
                 },
                 set editable(newValue) {
                     _editable(newValue);
                 },
                 get height() {
                     return _height();
                 },
                 set height(newValue) {
                     _height(newValue);
                 },
                 get lineBreak() {
                     return _lineBreak();
                 },
                 set lineBreak(newValue) {
                     _lineBreak(newValue);
                 },
                 get localization() {
                     return _localization();
                 },
                 set localization(newValue) {
                     _localization(newValue);
                 },
                 get pasteMode() {
                     return _pasteMode();
                 },
                 set pasteMode(newValue) {
                     _pasteMode(newValue);
                 },
                 get rtl() {
                     return _rtl();
                 },
                 set rtl(newValue) {
                     _rtl(newValue);
                 },
                 get stylesheets() {
                     return _stylesheets();
                 },
                 set stylesheets(newValue) {
                     _stylesheets(newValue);
                 },
                 get theme() {
                     return _theme();
                 },
                 set theme(newValue) {
                     _theme(newValue);
                 },
                 get toolbarPosition() {
                     return _toolbarPosition();
                 },
                 set toolbarPosition(newValue) {
                     _toolbarPosition(newValue);
                 },
                 get tools() {
                     return _tools();
                 },
                 set tools(newValue) {
                     _tools(newValue);
                 },
                 get width() {
                     return _width();
                 },
                 set width(newValue) {
                     _width(newValue);
                 },
            }
            function __wireEvents__() {
                const that = context;

                JQXLite(componentSelector).on('change', function (event) { that.emit('change', event); });
            }

			onMounted(() => {
				if (props.autoCreate) __createComponent__();
			})
			onUpdated(() => {
				const widgetOptions = __manageProps__();
				JQXLite(componentSelector).jqxEditor(widgetOptions);
			})
			return {id, componentSelector, destroy,focus,print,setMode,val, setOptions, options, getOptions, createComponent};
        },
    }
</script>

// jqwidgets-ng/esm5/jqxeditor/angular_jqxeditor.js
import '../jqwidgets/jqxcore';
import '../jqwidgets/jqxdata';
import '../jqwidgets/jqxbuttons';
import '../jqwidgets/jqxscrollbar';
import '../jqwidgets/jqxlistbox';
import '../jqwidgets/jqxdropdownlist';
import '../jqwidgets/jqxdropdownbutton';
import '../jqwidgets/jqxwindow';
import '../jqwidgets/jqxeditor';
import '../jqwidgets/jqxcheckbox';
import '../jqwidgets/jqxtooltip';
import '../jqwidgets/jqxcolorpicker';
/// <reference path="../../jqwidgets.d.ts" />
import * as tslib_1 from "tslib";
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges, ChangeDetectionStrategy } from '@angular/core';
import { NG_VALUE_ACCESSOR } from '@angular/forms';
var noop = function () { };
var ɵ0 = noop;
var CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(function () { return jqxEditorComponent; }),
    multi: true
};
var jqxEditorComponent = /** @class */ (function () {
    function jqxEditorComponent(containerElement) {
        this.autoCreate = true;
        this.properties = ['createCommand', 'disabled', 'editable', 'height', 'lineBreak', 'localization', 'pasteMode', 'rtl', 'stylesheets', 'theme', 'toolbarPosition', 'tools', 'width'];
        this.onTouchedCallback = noop;
        this.onChangeCallback = noop;
        // jqxEditorComponent events
        this.onChange = new EventEmitter();
        this.elementRef = containerElement;
    }
    jqxEditorComponent.prototype.ngOnInit = function () {
        if (this.autoCreate) {
            this.createComponent();
        }
    };
    ;
    jqxEditorComponent.prototype.ngOnChanges = function (changes) {
        if (this.host) {
            for (var i = 0; i < this.properties.length; i++) {
                var attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
                var areEqual = false;
                if (this[attrName] !== undefined) {
                    if (typeof this[attrName] === 'object') {
                        if (this[attrName] instanceof Array) {
                            areEqual = this.arraysEqual(this[attrName], this.host.jqxEditor(this.properties[i]));
                        }
                        if (areEqual) {
                            return false;
                        }
                        this.host.jqxEditor(this.properties[i], this[attrName]);
                        continue;
                    }
                    if (this[attrName] !== this.host.jqxEditor(this.properties[i])) {
                        this.host.jqxEditor(this.properties[i], this[attrName]);
                    }
                }
            }
        }
    };
    jqxEditorComponent.prototype.arraysEqual = function (attrValue, hostValue) {
        if ((attrValue && !hostValue) || (!attrValue && hostValue)) {
            return false;
        }
        if (attrValue.length != hostValue.length) {
            return false;
        }
        for (var i = 0; i < attrValue.length; i++) {
            if (attrValue[i] !== hostValue[i]) {
                return false;
            }
        }
        return true;
    };
    jqxEditorComponent.prototype.manageAttributes = function () {
        var options = {};
        for (var i = 0; i < this.properties.length; i++) {
            var attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            if (this[attrName] !== undefined) {
                options[this.properties[i]] = this[attrName];
            }
        }
        return options;
    };
    jqxEditorComponent.prototype.moveClasses = function (parentEl, childEl) {
        var _a;
        var classes = parentEl.classList;
        if (classes.length > 0) {
            (_a = childEl.classList).add.apply(_a, tslib_1.__spread(classes));
        }
        parentEl.className = '';
    };
    jqxEditorComponent.prototype.moveStyles = function (parentEl, childEl) {
        var style = parentEl.style.cssText;
        childEl.style.cssText = style;
        parentEl.style.cssText = '';
    };
    jqxEditorComponent.prototype.createComponent = function (options) {
        if (this.host) {
            return;
        }
        if (options) {
            JQXLite.extend(options, this.manageAttributes());
        }
        else {
            options = this.manageAttributes();
        }
        this.host = JQXLite(this.elementRef.nativeElement.firstChild);
        this.moveClasses(this.elementRef.nativeElement, this.host[0]);
        this.moveStyles(this.elementRef.nativeElement, this.host[0]);
        this.widgetObject = jqwidgets.createInstance(this.host, 'jqxEditor', options);
        this.host = this.widgetObject['host'];
        this.__wireEvents__();
    };
    jqxEditorComponent.prototype.createWidget = function (options) {
        this.createComponent(options);
    };
    jqxEditorComponent.prototype.__updateRect__ = function () {
        if (this.host)
            this.host.css({ width: this.attrWidth, height: this.attrHeight });
    };
    jqxEditorComponent.prototype.writeValue = function (value) {
        if (this.widgetObject) {
            this.onChangeCallback(this.host.val());
        }
    };
    jqxEditorComponent.prototype.registerOnChange = function (fn) {
        this.onChangeCallback = fn;
    };
    jqxEditorComponent.prototype.registerOnTouched = function (fn) {
        this.onTouchedCallback = fn;
    };
    jqxEditorComponent.prototype.setOptions = function (options) {
        this.host.jqxEditor('setOptions', options);
    };
    // jqxEditorComponent properties
    jqxEditorComponent.prototype.createCommand = function (arg) {
        if (arg !== undefined) {
            this.host.jqxEditor('createCommand', arg);
        }
        else {
            return this.host.jqxEditor('createCommand');
        }
    };
    jqxEditorComponent.prototype.disabled = function (arg) {
        if (arg !== undefined) {
            this.host.jqxEditor('disabled', arg);
        }
        else {
            return this.host.jqxEditor('disabled');
        }
    };
    jqxEditorComponent.prototype.editable = function (arg) {
        if (arg !== undefined) {
            this.host.jqxEditor('editable', arg);
        }
        else {
            return this.host.jqxEditor('editable');
        }
    };
    jqxEditorComponent.prototype.height = function (arg) {
        if (arg !== undefined) {
            this.host.jqxEditor('height', arg);
        }
        else {
            return this.host.jqxEditor('height');
        }
    };
    jqxEditorComponent.prototype.lineBreak = function (arg) {
        if (arg !== undefined) {
            this.host.jqxEditor('lineBreak', arg);
        }
        else {
            return this.host.jqxEditor('lineBreak');
        }
    };
    jqxEditorComponent.prototype.localization = function (arg) {
        if (arg !== undefined) {
            this.host.jqxEditor('localization', arg);
        }
        else {
            return this.host.jqxEditor('localization');
        }
    };
    jqxEditorComponent.prototype.pasteMode = function (arg) {
        if (arg !== undefined) {
            this.host.jqxEditor('pasteMode', arg);
        }
        else {
            return this.host.jqxEditor('pasteMode');
        }
    };
    jqxEditorComponent.prototype.rtl = function (arg) {
        if (arg !== undefined) {
            this.host.jqxEditor('rtl', arg);
        }
        else {
            return this.host.jqxEditor('rtl');
        }
    };
    jqxEditorComponent.prototype.stylesheets = function (arg) {
        if (arg !== undefined) {
            this.host.jqxEditor('stylesheets', arg);
        }
        else {
            return this.host.jqxEditor('stylesheets');
        }
    };
    jqxEditorComponent.prototype.theme = function (arg) {
        if (arg !== undefined) {
            this.host.jqxEditor('theme', arg);
        }
        else {
            return this.host.jqxEditor('theme');
        }
    };
    jqxEditorComponent.prototype.toolbarPosition = function (arg) {
        if (arg !== undefined) {
            this.host.jqxEditor('toolbarPosition', arg);
        }
        else {
            return this.host.jqxEditor('toolbarPosition');
        }
    };
    jqxEditorComponent.prototype.tools = function (arg) {
        if (arg !== undefined) {
            this.host.jqxEditor('tools', arg);
        }
        else {
            return this.host.jqxEditor('tools');
        }
    };
    jqxEditorComponent.prototype.width = function (arg) {
        if (arg !== undefined) {
            this.host.jqxEditor('width', arg);
        }
        else {
            return this.host.jqxEditor('width');
        }
    };
    // jqxEditorComponent functions
    jqxEditorComponent.prototype.destroy = function () {
        this.host.jqxEditor('destroy');
    };
    jqxEditorComponent.prototype.focus = function () {
        this.host.jqxEditor('focus');
    };
    jqxEditorComponent.prototype.print = function () {
        this.host.jqxEditor('print');
    };
    jqxEditorComponent.prototype.setMode = function (mode) {
        this.host.jqxEditor('setMode', mode);
    };
    jqxEditorComponent.prototype.val = function (value) {
        if (value !== undefined) {
            return this.host.jqxEditor('val', value);
        }
        else {
            return this.host.jqxEditor('val');
        }
    };
    ;
    jqxEditorComponent.prototype.__wireEvents__ = function () {
        var _this = this;
        this.host.on('change', function (eventData) { _this.onChange.emit(eventData); _this.onChangeCallback(_this.host.val()); });
    };
    jqxEditorComponent.ctorParameters = function () { return [
        { type: ElementRef }
    ]; };
    tslib_1.__decorate([
        Input('createCommand'),
        tslib_1.__metadata("design:type", Function)
    ], jqxEditorComponent.prototype, "attrCreateCommand", void 0);
    tslib_1.__decorate([
        Input('disabled'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxEditorComponent.prototype, "attrDisabled", void 0);
    tslib_1.__decorate([
        Input('editable'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxEditorComponent.prototype, "attrEditable", void 0);
    tslib_1.__decorate([
        Input('lineBreak'),
        tslib_1.__metadata("design:type", String)
    ], jqxEditorComponent.prototype, "attrLineBreak", void 0);
    tslib_1.__decorate([
        Input('localization'),
        tslib_1.__metadata("design:type", Object)
    ], jqxEditorComponent.prototype, "attrLocalization", void 0);
    tslib_1.__decorate([
        Input('pasteMode'),
        tslib_1.__metadata("design:type", String)
    ], jqxEditorComponent.prototype, "attrPasteMode", void 0);
    tslib_1.__decorate([
        Input('rtl'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxEditorComponent.prototype, "attrRtl", void 0);
    tslib_1.__decorate([
        Input('stylesheets'),
        tslib_1.__metadata("design:type", Array)
    ], jqxEditorComponent.prototype, "attrStylesheets", void 0);
    tslib_1.__decorate([
        Input('theme'),
        tslib_1.__metadata("design:type", String)
    ], jqxEditorComponent.prototype, "attrTheme", void 0);
    tslib_1.__decorate([
        Input('toolbarPosition'),
        tslib_1.__metadata("design:type", String)
    ], jqxEditorComponent.prototype, "attrToolbarPosition", void 0);
    tslib_1.__decorate([
        Input('tools'),
        tslib_1.__metadata("design:type", String)
    ], jqxEditorComponent.prototype, "attrTools", void 0);
    tslib_1.__decorate([
        Input('width'),
        tslib_1.__metadata("design:type", Object)
    ], jqxEditorComponent.prototype, "attrWidth", void 0);
    tslib_1.__decorate([
        Input('height'),
        tslib_1.__metadata("design:type", Object)
    ], jqxEditorComponent.prototype, "attrHeight", void 0);
    tslib_1.__decorate([
        Input('auto-create'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxEditorComponent.prototype, "autoCreate", void 0);
    tslib_1.__decorate([
        Output(),
        tslib_1.__metadata("design:type", Object)
    ], jqxEditorComponent.prototype, "onChange", void 0);
    jqxEditorComponent = tslib_1.__decorate([
        Component({
            selector: 'jqxEditor',
            template: '<div><ng-content></ng-content></div>',
            providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR],
            changeDetection: ChangeDetectionStrategy.OnPush
        }),
        tslib_1.__metadata("design:paramtypes", [ElementRef])
    ], jqxEditorComponent);
    return jqxEditorComponent;
}()); //jqxEditorComponent
export { jqxEditorComponent };
export { ɵ0 };
