// jqwidgets-react/react_jqxnotification.js
/*
jQWidgets v5.7.0 (2018-Apr)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxNotification extends React.Component {
    componentDidMount() {
        let options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        let properties = ['appendContainer','autoOpen','animationOpenDelay','animationCloseDelay','autoClose','autoCloseDelay','blink','browserBoundsOffset','closeOnClick','disabled','height','hoverOpacity','icon','notificationOffset','opacity','position','rtl','showCloseButton','template','theme','width'];
        let options = {};
        for(let item in this.props) {
              if(item === 'settings') {
                  for(let itemTwo in this.props[item]) {
                      options[itemTwo] = this.props[item][itemTwo];
                      }
                } else {
                      if(properties.indexOf(item) !== -1) {
                        options[item] = this.props[item];
                      }
                }
          }
          return options;
      };
    createComponent(options) {
        if(!this.style) {
              for (let style in this.props.style) {
                  JQXLite(this.componentSelector).css(style, this.props.style[style]);
              }
        }
        if(this.props.className !== undefined) {
            let classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
              JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxNotification(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxNotification('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxNotification(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    appendContainer(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('appendContainer', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('appendContainer');
        }
    };
    autoOpen(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('autoOpen', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('autoOpen');
        }
    };
    animationOpenDelay(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('animationOpenDelay', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('animationOpenDelay');
        }
    };
    animationCloseDelay(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('animationCloseDelay', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('animationCloseDelay');
        }
    };
    autoClose(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('autoClose', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('autoClose');
        }
    };
    autoCloseDelay(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('autoCloseDelay', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('autoCloseDelay');
        }
    };
    blink(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('blink', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('blink');
        }
    };
    browserBoundsOffset(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('browserBoundsOffset', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('browserBoundsOffset');
        }
    };
    closeOnClick(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('closeOnClick', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('closeOnClick');
        }
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('disabled');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('height');
        }
    };
    hoverOpacity(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('hoverOpacity', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('hoverOpacity');
        }
    };
    icon(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('icon', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('icon');
        }
    };
    notificationOffset(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('notificationOffset', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('notificationOffset');
        }
    };
    opacity(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('opacity', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('opacity');
        }
    };
    position(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('position', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('position');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('rtl');
        }
    };
    showCloseButton(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('showCloseButton', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('showCloseButton');
        }
    };
    template(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('template', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('template');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('theme');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxNotification('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxNotification('width');
        }
    };
    closeAll() {
        JQXLite(this.componentSelector).jqxNotification('closeAll');  
    };
    closeLast() {
        JQXLite(this.componentSelector).jqxNotification('closeLast');  
    };
    destroy() {
        JQXLite(this.componentSelector).jqxNotification('destroy');  
    };
    open() {
        JQXLite(this.componentSelector).jqxNotification('open');  
    };
    refresh() {
        JQXLite(this.componentSelector).jqxNotification('refresh');  
    };
    performRender() {
        JQXLite(this.componentSelector).jqxNotification('render');
    };
    render() {
        let id = 'jqxNotification' + JQXLite.generateID();
        this.componentSelector = '#' + id;
        return (
            <div id={id}>{this.props.value}{this.props.children}</div>
        )
    };
};

// jqwidgets-ts/angular_jqxnotification.ts
/// <reference path="jqwidgets.d.ts" />
import {Component, Input, Output, EventEmitter, ElementRef, forwardRef} from '@angular/core';
declare let $: any;

@Component({
    selector: 'angularNotification',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxNotificationComponent {
   @Input('width') containerWidth: any;
   @Input('height') containerHeight: any;

   elementRef: ElementRef;
   host;
   widgetObject:  jqwidgets.jqxNotification;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   isHostReady(): boolean {
       return (this.host !== undefined && this.host.length == 1);
   }

   createWidget(options: any): void {
      if (!this.isHostReady()) {

         this.host = $(this.elementRef.nativeElement.firstChild);
         this.__wireEvents__();
         this.widgetObject = jqwidgets.createInstance(this.host, 'jqxNotification', options);
         this.__updateRect__();

      }
   }

   __updateRect__() : void {
      this.host.css({width: this.containerWidth, height: this.containerHeight});
   }

   setOptions(options: any) : void {
      this.host.jqxNotification('setOptions', options);
   }

   // jqxNotificationComponent properties
   appendContainer(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('appendContainer', arg);
      } else {
          return this.host.jqxNotification('appendContainer');
      }
   }

   autoOpen(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('autoOpen', arg);
      } else {
          return this.host.jqxNotification('autoOpen');
      }
   }

   animationOpenDelay(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('animationOpenDelay', arg);
      } else {
          return this.host.jqxNotification('animationOpenDelay');
      }
   }

   animationCloseDelay(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('animationCloseDelay', arg);
      } else {
          return this.host.jqxNotification('animationCloseDelay');
      }
   }

   autoClose(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('autoClose', arg);
      } else {
          return this.host.jqxNotification('autoClose');
      }
   }

   autoCloseDelay(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('autoCloseDelay', arg);
      } else {
          return this.host.jqxNotification('autoCloseDelay');
      }
   }

   blink(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('blink', arg);
      } else {
          return this.host.jqxNotification('blink');
      }
   }

   browserBoundsOffset(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('browserBoundsOffset', arg);
      } else {
          return this.host.jqxNotification('browserBoundsOffset');
      }
   }

   closeOnClick(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('closeOnClick', arg);
      } else {
          return this.host.jqxNotification('closeOnClick');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('disabled', arg);
      } else {
          return this.host.jqxNotification('disabled');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('height', arg);
      } else {
          return this.host.jqxNotification('height');
      }
   }

   hoverOpacity(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('hoverOpacity', arg);
      } else {
          return this.host.jqxNotification('hoverOpacity');
      }
   }

   icon(arg?: jqwidgets.NotificationIcon) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('icon', arg);
      } else {
          return this.host.jqxNotification('icon');
      }
   }

   notificationOffset(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('notificationOffset', arg);
      } else {
          return this.host.jqxNotification('notificationOffset');
      }
   }

   opacity(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('opacity', arg);
      } else {
          return this.host.jqxNotification('opacity');
      }
   }

   position(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('position', arg);
      } else {
          return this.host.jqxNotification('position');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('rtl', arg);
      } else {
          return this.host.jqxNotification('rtl');
      }
   }

   showCloseButton(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('showCloseButton', arg);
      } else {
          return this.host.jqxNotification('showCloseButton');
      }
   }

   template(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('template', arg);
      } else {
          return this.host.jqxNotification('template');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('theme', arg);
      } else {
          return this.host.jqxNotification('theme');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNotification('width', arg);
      } else {
          return this.host.jqxNotification('width');
      }
   }


   // jqxNotificationComponent functions
   closeAll(): void {
      this.host.jqxNotification('closeAll');

   }
   closeLast(): void {
      this.host.jqxNotification('closeLast');

   }
   destroy(): void {
      this.host.jqxNotification('destroy');

   }
   open(): void {
      this.host.jqxNotification('open');

   }
   refresh(): void {
      this.host.jqxNotification('refresh');

   }
   render(): void {
      this.host.jqxNotification('render');

   }

   // jqxNotificationComponent events
   @Output() OnClose = new EventEmitter();
   @Output() OnClick = new EventEmitter();
   @Output() OnOpen = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('close', (eventData) => { this.OnClose.emit(eventData); });
      this.host.on('click', (eventData) => { this.OnClick.emit(eventData); });
      this.host.on('open', (eventData) => { this.OnOpen.emit(eventData); });
   }

} //jqxNotificationComponent
