// jqwidgets-react/react_jqxscheduler.js
/*
jQWidgets v5.0.0 (2017-Aug)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxScheduler extends React.Component {
    componentDidMount() {
        let options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        let properties = ['appointmentOpacity','appointmentsMinHeight','appointmentDataFields','appointmentTooltips','columnsHeight','contextMenu','contextMenuOpen','contextMenuClose','contextMenuItemClick','contextMenuCreate','changedAppointments','disabled','date','dayNameFormat','enableHover','editDialog','editDialogDateTimeFormatString','editDialogDateFormatString','editDialogOpen','editDialogCreate','editDialogKeyDown','editDialogClose','exportSettings','height','legendPosition','legendHeight','localization','min','max','ready','renderAppointment','rendering','rendered','rtl','resources','rowsHeight','showToolbar','showLegend','scrollBarSize','source','statuses','touchRowsHeight','theme','touchAppointmentsMinHeight','touchScrollBarSize','timeZone','touchDayNameFormat','toolBarRangeFormat','toolBarRangeFormatAbbr','toolbarHeight','views','view','width'];
        let options = {};
        for(let item in this.props) {
              if(item === 'settings') {
                  for(let itemTwo in this.props[item]) {
                      options[itemTwo] = this.props[item][itemTwo];
                      }
                } else {
                      if(properties.indexOf(item) !== -1) {
                        options[item] = this.props[item];
                      }
                }
          }
          return options;
      };
    createComponent(options) {
        if(!this.style) {
              for (let style in this.props.style) {
                  JQXLite(this.componentSelector).css(style, this.props.style[style]);
              }
        }
        if(this.props.className !== undefined) {
            let classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
              JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxScheduler(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxScheduler('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxScheduler(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    appointmentOpacity(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('appointmentOpacity', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('appointmentOpacity');
        }
    };
    appointmentsMinHeight(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('appointmentsMinHeight', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('appointmentsMinHeight');
        }
    };
    appointmentDataFields(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('appointmentDataFields', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('appointmentDataFields');
        }
    };
    appointmentTooltips(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('appointmentTooltips', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('appointmentTooltips');
        }
    };
    columnsHeight(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('columnsHeight', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('columnsHeight');
        }
    };
    contextMenu(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('contextMenu', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('contextMenu');
        }
    };
    contextMenuOpen(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('contextMenuOpen', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('contextMenuOpen');
        }
    };
    contextMenuClose(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('contextMenuClose', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('contextMenuClose');
        }
    };
    contextMenuItemClick(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('contextMenuItemClick', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('contextMenuItemClick');
        }
    };
    contextMenuCreate(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('contextMenuCreate', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('contextMenuCreate');
        }
    };
    changedAppointments(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('changedAppointments', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('changedAppointments');
        }
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('disabled');
        }
    };
    date(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('date', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('date');
        }
    };
    dayNameFormat(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('dayNameFormat', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('dayNameFormat');
        }
    };
    enableHover(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('enableHover', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('enableHover');
        }
    };
    editDialog(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('editDialog', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('editDialog');
        }
    };
    editDialogDateTimeFormatString(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('editDialogDateTimeFormatString', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('editDialogDateTimeFormatString');
        }
    };
    editDialogDateFormatString(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('editDialogDateFormatString', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('editDialogDateFormatString');
        }
    };
    editDialogOpen(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('editDialogOpen', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('editDialogOpen');
        }
    };
    editDialogCreate(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('editDialogCreate', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('editDialogCreate');
        }
    };
    editDialogKeyDown(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('editDialogKeyDown', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('editDialogKeyDown');
        }
    };
    editDialogClose(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('editDialogClose', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('editDialogClose');
        }
    };
    exportSettings(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('exportSettings', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('exportSettings');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('height');
        }
    };
    legendPosition(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('legendPosition', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('legendPosition');
        }
    };
    legendHeight(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('legendHeight', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('legendHeight');
        }
    };
    localization(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('localization', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('localization');
        }
    };
    min(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('min', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('min');
        }
    };
    max(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('max', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('max');
        }
    };
    ready(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('ready', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('ready');
        }
    };
    renderAppointment(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('renderAppointment', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('renderAppointment');
        }
    };
    rendering(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('rendering', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('rendering');
        }
    };
    rendered(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('rendered', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('rendered');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('rtl');
        }
    };
    resources(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('resources', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('resources');
        }
    };
    rowsHeight(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('rowsHeight', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('rowsHeight');
        }
    };
    showToolbar(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('showToolbar', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('showToolbar');
        }
    };
    showLegend(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('showLegend', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('showLegend');
        }
    };
    scrollBarSize(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('scrollBarSize', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('scrollBarSize');
        }
    };
    source(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('source', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('source');
        }
    };
    statuses(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('statuses', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('statuses');
        }
    };
    touchRowsHeight(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('touchRowsHeight', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('touchRowsHeight');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('theme');
        }
    };
    touchAppointmentsMinHeight(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('touchAppointmentsMinHeight', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('touchAppointmentsMinHeight');
        }
    };
    touchScrollBarSize(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('touchScrollBarSize', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('touchScrollBarSize');
        }
    };
    timeZone(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('timeZone', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('timeZone');
        }
    };
    touchDayNameFormat(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('touchDayNameFormat', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('touchDayNameFormat');
        }
    };
    toolBarRangeFormat(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('toolBarRangeFormat', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('toolBarRangeFormat');
        }
    };
    toolBarRangeFormatAbbr(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('toolBarRangeFormatAbbr', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('toolBarRangeFormatAbbr');
        }
    };
    toolbarHeight(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('toolbarHeight', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('toolbarHeight');
        }
    };
    views(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('views', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('views');
        }
    };
    view(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('view', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('view');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxScheduler('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxScheduler('width');
        }
    };
    addAppointment(item) {
        JQXLite(this.componentSelector).jqxScheduler('addAppointment', item);  
    };
    beginAppointmentsUpdate() {
        JQXLite(this.componentSelector).jqxScheduler('beginAppointmentsUpdate');  
    };
    clearAppointmentsSelection() {
        JQXLite(this.componentSelector).jqxScheduler('clearAppointmentsSelection');  
    };
    clearSelection() {
        JQXLite(this.componentSelector).jqxScheduler('clearSelection');  
    };
    closeMenu() {
        JQXLite(this.componentSelector).jqxScheduler('closeMenu');  
    };
    closeDialog() {
        JQXLite(this.componentSelector).jqxScheduler('closeDialog');  
    };
    deleteAppointment(appointmenId) {
        JQXLite(this.componentSelector).jqxScheduler('deleteAppointment', appointmenId);  
    };
    destroy() {
        JQXLite(this.componentSelector).jqxScheduler('destroy');  
    };
    endAppointmentsUpdate() {
        JQXLite(this.componentSelector).jqxScheduler('endAppointmentsUpdate');  
    };
    ensureAppointmentVisible(id) {
        JQXLite(this.componentSelector).jqxScheduler('ensureAppointmentVisible', id);  
    };
    ensureVisible(item, resourceId) {
        JQXLite(this.componentSelector).jqxScheduler('ensureVisible', item, resourceId);  
    };
    exportData(format) {
        return JQXLite(this.componentSelector).jqxScheduler('exportData', format);  
    };
    focus() {
        JQXLite(this.componentSelector).jqxScheduler('focus');  
    };
    getAppointmentProperty(appointmentId, name) {
        return JQXLite(this.componentSelector).jqxScheduler('getAppointmentProperty', appointmentId, name);  
    };
    getSelection() {
        return JQXLite(this.componentSelector).jqxScheduler('getSelection');  
    };
    getAppointments() {
        return JQXLite(this.componentSelector).jqxScheduler('getAppointments');  
    };
    getDataAppointments() {
        return JQXLite(this.componentSelector).jqxScheduler('getDataAppointments');  
    };
    hideAppointmentsByResource(resourcesId) {
        JQXLite(this.componentSelector).jqxScheduler('hideAppointmentsByResource', resourcesId);  
    };
    openMenu(left, top) {
        JQXLite(this.componentSelector).jqxScheduler('openMenu', left, top);  
    };
    openDialog(left, top) {
        JQXLite(this.componentSelector).jqxScheduler('openDialog', left, top);  
    };
    selectAppointment(appointmentId) {
        JQXLite(this.componentSelector).jqxScheduler('selectAppointment', appointmentId);  
    };
    setAppointmentProperty(appointmentId, name, value) {
        JQXLite(this.componentSelector).jqxScheduler('setAppointmentProperty', appointmentId, name, value);  
    };
    selectCell(date, allday, resourceId) {
        JQXLite(this.componentSelector).jqxScheduler('selectCell', date, allday, resourceId);  
    };
    showAppointmentsByResource(resourceId) {
        JQXLite(this.componentSelector).jqxScheduler('showAppointmentsByResource', resourceId);  
    };
    scrollWidth() {
        return JQXLite(this.componentSelector).jqxScheduler('scrollWidth');  
    };
    scrollHeight() {
        return JQXLite(this.componentSelector).jqxScheduler('scrollHeight');  
    };
    scrollLeft(left) {
        JQXLite(this.componentSelector).jqxScheduler('scrollLeft', left);  
    };
    scrollTop(top) {
        JQXLite(this.componentSelector).jqxScheduler('scrollTop', top);  
    };
    render() {
        let id = 'jqxScheduler' + JQXLite.generateID();
        this.componentSelector = '#' + id;
        return (
            <div id={id}>{this.props.value}{this.props.children}</div>
        )
    };
};

// jqwidgets-ts/angular_jqxscheduler.ts
/*
jQWidgets v4.5.0 (2017-Jan)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
declare let $: any;

@Component({
    selector: 'jqxScheduler',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxSchedulerComponent implements OnChanges
{
   @Input('appointmentOpacity') attrAppointmentOpacity: any;
   @Input('appointmentsMinHeight') attrAppointmentsMinHeight: any;
   @Input('appointmentDataFields') attrAppointmentDataFields: any;
   @Input('appointmentTooltips') attrAppointmentTooltips: any;
   @Input('columnsHeight') attrColumnsHeight: any;
   @Input('contextMenu') attrContextMenu: any;
   @Input('contextMenuOpen') attrContextMenuOpen: any;
   @Input('contextMenuClose') attrContextMenuClose: any;
   @Input('contextMenuItemClick') attrContextMenuItemClick: any;
   @Input('contextMenuCreate') attrContextMenuCreate: any;
   @Input('changedAppointments') attrChangedAppointments: any;
   @Input('disabled') attrDisabled: any;
   @Input('date') attrDate: any;
   @Input('dayNameFormat') attrDayNameFormat: any;
   @Input('enableHover') attrEnableHover: any;
   @Input('editDialog') attrEditDialog: any;
   @Input('editDialogDateTimeFormatString') attrEditDialogDateTimeFormatString: any;
   @Input('editDialogDateFormatString') attrEditDialogDateFormatString: any;
   @Input('editDialogOpen') attrEditDialogOpen: any;
   @Input('editDialogCreate') attrEditDialogCreate: any;
   @Input('editDialogKeyDown') attrEditDialogKeyDown: any;
   @Input('editDialogClose') attrEditDialogClose: any;
   @Input('exportSettings') attrExportSettings: any;
   @Input('legendPosition') attrLegendPosition: any;
   @Input('legendHeight') attrLegendHeight: any;
   @Input('localization') attrLocalization: any;
   @Input('min') attrMin: any;
   @Input('max') attrMax: any;
   @Input('ready') attrReady: any;
   @Input('renderAppointment') attrRenderAppointment: any;
   @Input('rendering') attrRendering: any;
   @Input('rendered') attrRendered: any;
   @Input('rtl') attrRtl: any;
   @Input('resources') attrResources: any;
   @Input('rowsHeight') attrRowsHeight: any;
   @Input('showToolbar') attrShowToolbar: any;
   @Input('showLegend') attrShowLegend: any;
   @Input('scrollBarSize') attrScrollBarSize: any;
   @Input('source') attrSource: any;
   @Input('statuses') attrStatuses: any;
   @Input('touchRowsHeight') attrTouchRowsHeight: any;
   @Input('theme') attrTheme: any;
   @Input('touchAppointmentsMinHeight') attrTouchAppointmentsMinHeight: any;
   @Input('touchScrollBarSize') attrTouchScrollBarSize: any;
   @Input('timeZone') attrTimeZone: any;
   @Input('touchDayNameFormat') attrTouchDayNameFormat: any;
   @Input('toolBarRangeFormat') attrToolBarRangeFormat: any;
   @Input('toolBarRangeFormatAbbr') attrToolBarRangeFormatAbbr: any;
   @Input('toolbarHeight') attrToolbarHeight: any;
   @Input('views') attrViews: any;
   @Input('view') attrView: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['appointmentOpacity','appointmentsMinHeight','appointmentDataFields','appointmentTooltips','columnsHeight','contextMenu','contextMenuOpen','contextMenuClose','contextMenuItemClick','contextMenuCreate','changedAppointments','disabled','date','dayNameFormat','enableHover','editDialog','editDialogDateTimeFormatString','editDialogDateFormatString','editDialogOpen','editDialogCreate','editDialogKeyDown','editDialogClose','exportSettings','height','legendPosition','legendHeight','localization','min','max','ready','renderAppointment','rendering','rendered','rtl','resources','rowsHeight','showToolbar','showLegend','scrollBarSize','source','statuses','touchRowsHeight','theme','touchAppointmentsMinHeight','touchScrollBarSize','timeZone','touchDayNameFormat','toolBarRangeFormat','toolBarRangeFormatAbbr','toolbarHeight','views','view','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxScheduler;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
      setTimeout(() => {
         if (this.autoCreate) {
            this.createComponent(); 
         }
      }); 
   }

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName]) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxScheduler(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxScheduler(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxScheduler(this.properties[i])) {
                  this.host.jqxScheduler(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }
   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxScheduler', options);
      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({width: this.attrWidth, height: this.attrHeight});
   }

   setOptions(options: any) : void {
      this.host.jqxScheduler('setOptions', options);
   }

   // jqxSchedulerComponent properties
   appointmentOpacity(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('appointmentOpacity', arg);
      } else {
          return this.host.jqxScheduler('appointmentOpacity');
      }
   }

   appointmentsMinHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('appointmentsMinHeight', arg);
      } else {
          return this.host.jqxScheduler('appointmentsMinHeight');
      }
   }

   appointmentDataFields(arg?: jqwidgets.SchedulerAppointmentDataFields) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('appointmentDataFields', arg);
      } else {
          return this.host.jqxScheduler('appointmentDataFields');
      }
   }

   appointmentTooltips(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('appointmentTooltips', arg);
      } else {
          return this.host.jqxScheduler('appointmentTooltips');
      }
   }

   columnsHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('columnsHeight', arg);
      } else {
          return this.host.jqxScheduler('columnsHeight');
      }
   }

   contextMenu(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('contextMenu', arg);
      } else {
          return this.host.jqxScheduler('contextMenu');
      }
   }

   contextMenuOpen(arg?: (menu: any, appointment: any, event: any) => void) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('contextMenuOpen', arg);
      } else {
          return this.host.jqxScheduler('contextMenuOpen');
      }
   }

   contextMenuClose(arg?: (menu: any, appointment: any, event: any) => void) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('contextMenuClose', arg);
      } else {
          return this.host.jqxScheduler('contextMenuClose');
      }
   }

   contextMenuItemClick(arg?: (menu: any, appointment: any, event: any) => Boolean) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('contextMenuItemClick', arg);
      } else {
          return this.host.jqxScheduler('contextMenuItemClick');
      }
   }

   contextMenuCreate(arg?: (menu: any, appointment: any, event: any) => void) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('contextMenuCreate', arg);
      } else {
          return this.host.jqxScheduler('contextMenuCreate');
      }
   }

   changedAppointments(arg?: Array<jqwidgets.SchedulerChangedAppointments>) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('changedAppointments', arg);
      } else {
          return this.host.jqxScheduler('changedAppointments');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('disabled', arg);
      } else {
          return this.host.jqxScheduler('disabled');
      }
   }

   date(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('date', arg);
      } else {
          return this.host.jqxScheduler('date');
      }
   }

   dayNameFormat(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('dayNameFormat', arg);
      } else {
          return this.host.jqxScheduler('dayNameFormat');
      }
   }

   enableHover(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('enableHover', arg);
      } else {
          return this.host.jqxScheduler('enableHover');
      }
   }

   editDialog(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('editDialog', arg);
      } else {
          return this.host.jqxScheduler('editDialog');
      }
   }

   editDialogDateTimeFormatString(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('editDialogDateTimeFormatString', arg);
      } else {
          return this.host.jqxScheduler('editDialogDateTimeFormatString');
      }
   }

   editDialogDateFormatString(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('editDialogDateFormatString', arg);
      } else {
          return this.host.jqxScheduler('editDialogDateFormatString');
      }
   }

   editDialogOpen(arg?: (dialog?: any, fields?: any, editAppointment?: any) => void) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('editDialogOpen', arg);
      } else {
          return this.host.jqxScheduler('editDialogOpen');
      }
   }

   editDialogCreate(arg?: (dialog?: any, fields?: any, editAppointment?: any) => void) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('editDialogCreate', arg);
      } else {
          return this.host.jqxScheduler('editDialogCreate');
      }
   }

   editDialogKeyDown(arg?: (dialog?: any, fields?: any, editAppointment?: any, event?: any) => Boolean) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('editDialogKeyDown', arg);
      } else {
          return this.host.jqxScheduler('editDialogKeyDown');
      }
   }

   editDialogClose(arg?: (dialog?: any, fields?: any, editAppointment?: any) => void) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('editDialogClose', arg);
      } else {
          return this.host.jqxScheduler('editDialogClose');
      }
   }

   exportSettings(arg?: jqwidgets.SchedulerExportSettings) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('exportSettings', arg);
      } else {
          return this.host.jqxScheduler('exportSettings');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('height', arg);
      } else {
          return this.host.jqxScheduler('height');
      }
   }

   legendPosition(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('legendPosition', arg);
      } else {
          return this.host.jqxScheduler('legendPosition');
      }
   }

   legendHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('legendHeight', arg);
      } else {
          return this.host.jqxScheduler('legendHeight');
      }
   }

   localization(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('localization', arg);
      } else {
          return this.host.jqxScheduler('localization');
      }
   }

   min(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('min', arg);
      } else {
          return this.host.jqxScheduler('min');
      }
   }

   max(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('max', arg);
      } else {
          return this.host.jqxScheduler('max');
      }
   }

   ready(arg?: () => void) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('ready', arg);
      } else {
          return this.host.jqxScheduler('ready');
      }
   }

   renderAppointment(arg?: (data: any) => any) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('renderAppointment', arg);
      } else {
          return this.host.jqxScheduler('renderAppointment');
      }
   }

   rendering(arg?: () => void) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('rendering', arg);
      } else {
          return this.host.jqxScheduler('rendering');
      }
   }

   rendered(arg?: () => void) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('rendered', arg);
      } else {
          return this.host.jqxScheduler('rendered');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('rtl', arg);
      } else {
          return this.host.jqxScheduler('rtl');
      }
   }

   resources(arg?: jqwidgets.SchedulerResources) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('resources', arg);
      } else {
          return this.host.jqxScheduler('resources');
      }
   }

   rowsHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('rowsHeight', arg);
      } else {
          return this.host.jqxScheduler('rowsHeight');
      }
   }

   showToolbar(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('showToolbar', arg);
      } else {
          return this.host.jqxScheduler('showToolbar');
      }
   }

   showLegend(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('showLegend', arg);
      } else {
          return this.host.jqxScheduler('showLegend');
      }
   }

   scrollBarSize(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('scrollBarSize', arg);
      } else {
          return this.host.jqxScheduler('scrollBarSize');
      }
   }

   source(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('source', arg);
      } else {
          return this.host.jqxScheduler('source');
      }
   }

   statuses(arg?: jqwidgets.SchedulerStatuses) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('statuses', arg);
      } else {
          return this.host.jqxScheduler('statuses');
      }
   }

   touchRowsHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('touchRowsHeight', arg);
      } else {
          return this.host.jqxScheduler('touchRowsHeight');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('theme', arg);
      } else {
          return this.host.jqxScheduler('theme');
      }
   }

   touchAppointmentsMinHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('touchAppointmentsMinHeight', arg);
      } else {
          return this.host.jqxScheduler('touchAppointmentsMinHeight');
      }
   }

   touchScrollBarSize(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('touchScrollBarSize', arg);
      } else {
          return this.host.jqxScheduler('touchScrollBarSize');
      }
   }

   timeZone(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('timeZone', arg);
      } else {
          return this.host.jqxScheduler('timeZone');
      }
   }

   touchDayNameFormat(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('touchDayNameFormat', arg);
      } else {
          return this.host.jqxScheduler('touchDayNameFormat');
      }
   }

   toolBarRangeFormat(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('toolBarRangeFormat', arg);
      } else {
          return this.host.jqxScheduler('toolBarRangeFormat');
      }
   }

   toolBarRangeFormatAbbr(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('toolBarRangeFormatAbbr', arg);
      } else {
          return this.host.jqxScheduler('toolBarRangeFormatAbbr');
      }
   }

   toolbarHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('toolbarHeight', arg);
      } else {
          return this.host.jqxScheduler('toolbarHeight');
      }
   }

   views(arg?: Array<any>) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('views', arg);
      } else {
          return this.host.jqxScheduler('views');
      }
   }

   view(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('view', arg);
      } else {
          return this.host.jqxScheduler('view');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxScheduler('width', arg);
      } else {
          return this.host.jqxScheduler('width');
      }
   }


   // jqxSchedulerComponent functions
   addAppointment(item: jqwidgets.SchedulerAppointmentDataFields): void {
      this.host.jqxScheduler('addAppointment', item);
   }

   beginAppointmentsUpdate(): void {
      this.host.jqxScheduler('beginAppointmentsUpdate');
   }

   clearAppointmentsSelection(): void {
      this.host.jqxScheduler('clearAppointmentsSelection');
   }

   clearSelection(): void {
      this.host.jqxScheduler('clearSelection');
   }

   closeMenu(): void {
      this.host.jqxScheduler('closeMenu');
   }

   closeDialog(): void {
      this.host.jqxScheduler('closeDialog');
   }

   deleteAppointment(appointmenId: string): void {
      this.host.jqxScheduler('deleteAppointment', appointmenId);
   }

   destroy(): void {
      this.host.jqxScheduler('destroy');
   }

   endAppointmentsUpdate(): void {
      this.host.jqxScheduler('endAppointmentsUpdate');
   }

   ensureAppointmentVisible(id: string): void {
      this.host.jqxScheduler('ensureAppointmentVisible', id);
   }

   ensureVisible(item: any, resourceId: string): void {
      this.host.jqxScheduler('ensureVisible', item, resourceId);
   }

   exportData(format: string): any {
      return this.host.jqxScheduler('exportData', format);
   }

   focus(): void {
      this.host.jqxScheduler('focus');
   }

   getAppointmentProperty(appointmentId: string, name: string): any {
      return this.host.jqxScheduler('getAppointmentProperty', appointmentId, name);
   }

   getSelection(): jqwidgets.SchedulerGetSelection {
      return this.host.jqxScheduler('getSelection');
   }

   getAppointments(): Array<jqwidgets.SchedulerAppointmentDataFields> {
      return this.host.jqxScheduler('getAppointments');
   }

   getDataAppointments(): Array<any> {
      return this.host.jqxScheduler('getDataAppointments');
   }

   hideAppointmentsByResource(resourcesId: string): void {
      this.host.jqxScheduler('hideAppointmentsByResource', resourcesId);
   }

   openMenu(left: number, top: number): void {
      this.host.jqxScheduler('openMenu', left, top);
   }

   openDialog(left: number, top: number): void {
      this.host.jqxScheduler('openDialog', left, top);
   }

   selectAppointment(appointmentId: string): void {
      this.host.jqxScheduler('selectAppointment', appointmentId);
   }

   setAppointmentProperty(appointmentId: string, name: string, value: any): void {
      this.host.jqxScheduler('setAppointmentProperty', appointmentId, name, value);
   }

   selectCell(date: any, allday: boolean, resourceId: string): void {
      this.host.jqxScheduler('selectCell', date, allday, resourceId);
   }

   showAppointmentsByResource(resourceId: string): void {
      this.host.jqxScheduler('showAppointmentsByResource', resourceId);
   }

   scrollWidth(): number {
      return this.host.jqxScheduler('scrollWidth');
   }

   scrollHeight(): number {
      return this.host.jqxScheduler('scrollHeight');
   }

   scrollLeft(left: number): void {
      this.host.jqxScheduler('scrollLeft', left);
   }

   scrollTop(top: number): void {
      this.host.jqxScheduler('scrollTop', top);
   }


   // jqxSchedulerComponent events
   @Output() onAppointmentChange = new EventEmitter();
   @Output() onAppointmentClick = new EventEmitter();
   @Output() onAppointmentDoubleClick = new EventEmitter();
   @Output() onAppointmentDelete = new EventEmitter();
   @Output() onAppointmentAdd = new EventEmitter();
   @Output() onBindingComplete = new EventEmitter();
   @Output() onCellClick = new EventEmitter();
   @Output() onCellDoubleClick = new EventEmitter();
   @Output() onContextMenuOpen = new EventEmitter();
   @Output() onContextMenuClose = new EventEmitter();
   @Output() onContextMenuItemClick = new EventEmitter();
   @Output() onContextMenuCreate = new EventEmitter();
   @Output() onDateChange = new EventEmitter();
   @Output() onEditRecurrenceDialogOpen = new EventEmitter();
   @Output() onEditRecurrenceDialogClose = new EventEmitter();
   @Output() onEditDialogCreate = new EventEmitter();
   @Output() onEditDialogOpen = new EventEmitter();
   @Output() onEditDialogClose = new EventEmitter();
   @Output() onViewChange = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('appointmentChange', (eventData: any) => { this.onAppointmentChange.emit(eventData); });
      this.host.on('appointmentClick', (eventData: any) => { this.onAppointmentClick.emit(eventData); });
      this.host.on('appointmentDoubleClick', (eventData: any) => { this.onAppointmentDoubleClick.emit(eventData); });
      this.host.on('appointmentDelete', (eventData: any) => { this.onAppointmentDelete.emit(eventData); });
      this.host.on('appointmentAdd', (eventData: any) => { this.onAppointmentAdd.emit(eventData); });
      this.host.on('bindingComplete', (eventData: any) => { this.onBindingComplete.emit(eventData); });
      this.host.on('cellClick', (eventData: any) => { this.onCellClick.emit(eventData); });
      this.host.on('cellDoubleClick', (eventData: any) => { this.onCellDoubleClick.emit(eventData); });
      this.host.on('contextMenuOpen', (eventData: any) => { this.onContextMenuOpen.emit(eventData); });
      this.host.on('contextMenuClose', (eventData: any) => { this.onContextMenuClose.emit(eventData); });
      this.host.on('contextMenuItemClick', (eventData: any) => { this.onContextMenuItemClick.emit(eventData); });
      this.host.on('contextMenuCreate', (eventData: any) => { this.onContextMenuCreate.emit(eventData); });
      this.host.on('dateChange', (eventData: any) => { this.onDateChange.emit(eventData); });
      this.host.on('editRecurrenceDialogOpen', (eventData: any) => { this.onEditRecurrenceDialogOpen.emit(eventData); });
      this.host.on('editRecurrenceDialogClose', (eventData: any) => { this.onEditRecurrenceDialogClose.emit(eventData); });
      this.host.on('editDialogCreate', (eventData: any) => { this.onEditDialogCreate.emit(eventData); });
      this.host.on('editDialogOpen', (eventData: any) => { this.onEditDialogOpen.emit(eventData); });
      this.host.on('editDialogClose', (eventData: any) => { this.onEditDialogClose.emit(eventData); });
      this.host.on('viewChange', (eventData: any) => { this.onViewChange.emit(eventData); });
   }

} //jqxSchedulerComponent
