// jqwidgets-react/react_jqxresponse.js
/*
jQWidgets v4.5.0 (2017-Jan)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxResponse = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['browser','device','document','destroyProperty','resize','os'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxResponse(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxResponse('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxResponse(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  browser: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxResponse("browser", arg)
    } else {
      return $("#" +this.componentSelector).jqxResponse("browser");
    }
  },
  device: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxResponse("device", arg)
    } else {
      return $("#" +this.componentSelector).jqxResponse("device");
    }
  },
  document: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxResponse("document", arg)
    } else {
      return $("#" +this.componentSelector).jqxResponse("document");
    }
  },
  destroyProperty: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxResponse("destroyProperty", arg)
    } else {
      return $("#" +this.componentSelector).jqxResponse("destroyProperty");
    }
  },
  resize: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxResponse("resize", arg)
    } else {
      return $("#" +this.componentSelector).jqxResponse("resize");
    }
  },
  os: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxResponse("os", arg)
    } else {
      return $("#" +this.componentSelector).jqxResponse("os");
    }
  },
  refresh: function () {
    $("#" +this.componentSelector).jqxResponse("refresh");  
  },
  responsive: function (container, colWidths, colOffsets, colClass, deviceTypes, margin, padding, breakpoints) {
    $("#" +this.componentSelector).jqxResponse("responsive", container, colWidths, colOffsets, colClass, deviceTypes, margin, padding, breakpoints);  
  },
  isHidden: function (element) {
    return $("#" +this.componentSelector).jqxResponse("isHidden", element);  
  },
  inViewPort: function (element) {
    return $("#" +this.componentSelector).jqxResponse("inViewPort", element);  
  },
  pointerDown: function (element, callback) {
    $("#" +this.componentSelector).jqxResponse("pointerDown", element, callback);  
  },
  pointerMove: function (element, callback) {
    $("#" +this.componentSelector).jqxResponse("pointerMove", element, callback);  
  },
  pointerUp: function (element, callback) {
    $("#" +this.componentSelector).jqxResponse("pointerUp", element, callback);  
  },
  scroll: function () {
    return $("#" +this.componentSelector).jqxResponse("scroll");  
  },
  viewPort: function () {
    return $("#" +this.componentSelector).jqxResponse("viewPort");  
  },
  render: function () {
    let id = 'jqxResponse' + this.generateID() + this.generateID();
    this.componentSelector = id;    return (
      <div id={id}>{this.value ? null : this.props.value}{this.props.children}</div>
    )
  }
});

module.exports = jqxResponse;

// jqwidgets-ts/angular_jqxresponse.ts
/*
jQWidgets v4.5.0 (2017-Jan)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
declare let $: any;

@Component({
    selector: 'jqxResponse',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxResponseComponent implements OnChanges
{
   @Input('browser') attrBrowser: any;
   @Input('device') attrDevice: any;
   @Input('document') attrDocument: any;
   @Input('destroyProperty') attrDestroyProperty: any;
   @Input('resize') attrResize: any;
   @Input('os') attrOs: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['browser','device','document','destroyProperty','resize','os'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxResponse;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
      setTimeout(() => {
         if (this.autoCreate) {
            this.createComponent(); 
         }
      }); 
   }

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName]) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxResponse(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxResponse(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxResponse(this.properties[i])) {
                  this.host.jqxResponse(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }
   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxResponse', options);
      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({width: this.attrWidth, height: this.attrHeight});
   }

   setOptions(options: any) : void {
      this.host.jqxResponse('setOptions', options);
   }

   // jqxResponseComponent properties
   browser(arg?: jqwidgets.ResponseBrowser) : any {
      if (arg !== undefined) {
          this.host.jqxResponse('browser', arg);
      } else {
          return this.host.jqxResponse('browser');
      }
   }

   device(arg?: jqwidgets.ResponseDevice) : any {
      if (arg !== undefined) {
          this.host.jqxResponse('device', arg);
      } else {
          return this.host.jqxResponse('device');
      }
   }

   document(arg?: jqwidgets.ResponseDocument) : any {
      if (arg !== undefined) {
          this.host.jqxResponse('document', arg);
      } else {
          return this.host.jqxResponse('document');
      }
   }

   destroyProperty(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxResponse('destroyProperty', arg);
      } else {
          return this.host.jqxResponse('destroyProperty');
      }
   }

   resize(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxResponse('resize', arg);
      } else {
          return this.host.jqxResponse('resize');
      }
   }

   os(arg?: jqwidgets.ResponseOs) : any {
      if (arg !== undefined) {
          this.host.jqxResponse('os', arg);
      } else {
          return this.host.jqxResponse('os');
      }
   }


   // jqxResponseComponent functions
   refresh(): void {
      this.host.jqxResponse('refresh');
   }

   responsive(container: string, colWidths: Array<Number>, colOffsets: Array<Number>, colClass: string, deviceTypes: string, margin: jqwidgets.ResponseOffset, padding: jqwidgets.ResponseOffset, breakpoints: Array<jqwidgets.ResponseBreakpoint>): void {
      this.host.jqxResponse('responsive', container, colWidths, colOffsets, colClass, deviceTypes, margin, padding, breakpoints);
   }

   isHidden(element: any): boolean {
      return this.host.jqxResponse('isHidden', element);
   }

   inViewPort(element: any): boolean {
      return this.host.jqxResponse('inViewPort', element);
   }

   pointerDown(element: any, callback: any): void {
      this.host.jqxResponse('pointerDown', element, callback);
   }

   pointerMove(element: any, callback: any): void {
      this.host.jqxResponse('pointerMove', element, callback);
   }

   pointerUp(element: any, callback: any): void {
      this.host.jqxResponse('pointerUp', element, callback);
   }

   scroll(): Object {
      return this.host.jqxResponse('scroll');
   }

   viewPort(): Object {
      return this.host.jqxResponse('viewPort');
   }


   // jqxResponseComponent events


   __wireEvents__(): void {

   }

} //jqxResponseComponent
