// jqwidgets-react/react_jqxbargauge.js
/*
jQWidgets v6.1.0 (2018-October)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxdraw.js';
import '../jqwidgets/jqxbargauge.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxBarGauge extends React.Component {
    constructor(props) {
        super(props);
        const widgetId = 'jqxBarGauge' + JQXLite.generateID();
        this.componentSelector = '#' + widgetId;
        this.state = { id: widgetId };
    };
    componentDidMount() {
        const options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        const properties = ['animationDuration','backgroundColor','barSpacing','baseValue','colorScheme','customColorScheme','disabled','endAngle','formatFunction','height','labels','max','min','relativeInnerRadius','rendered','startAngle','title','tooltip','useGradient','values','width'];
        let options = {};
        for(let item in this.props) {
            if(item === 'settings') {
                for(let itemTwo in this.props[item]) {
                    options[itemTwo] = this.props[item][itemTwo];
                }
            } else {
                if(properties.indexOf(item) !== -1) {
                      options[item] = this.props[item];
                }
            }
        }
        return options;
    };
    createComponent(options) {
        if(!this.style) {
            for (let style in this.props.style) {
                JQXLite(this.componentSelector).css(style, this.props.style[style]);
            }
        }
        if(this.props.className !== undefined) {
            const classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
            JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxBarGauge(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxBarGauge('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxBarGauge(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    animationDuration(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('animationDuration', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('animationDuration');
        }
    };
    backgroundColor(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('backgroundColor', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('backgroundColor');
        }
    };
    barSpacing(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('barSpacing', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('barSpacing');
        }
    };
    baseValue(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('baseValue', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('baseValue');
        }
    };
    colorScheme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('colorScheme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('colorScheme');
        }
    };
    customColorScheme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('customColorScheme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('customColorScheme');
        }
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('disabled');
        }
    };
    endAngle(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('endAngle', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('endAngle');
        }
    };
    formatFunction(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('formatFunction', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('formatFunction');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('height');
        }
    };
    labels(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('labels', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('labels');
        }
    };
    max(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('max', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('max');
        }
    };
    min(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('min', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('min');
        }
    };
    relativeInnerRadius(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('relativeInnerRadius', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('relativeInnerRadius');
        }
    };
    rendered(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('rendered', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('rendered');
        }
    };
    startAngle(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('startAngle', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('startAngle');
        }
    };
    title(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('title', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('title');
        }
    };
    tooltip(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('tooltip', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('tooltip');
        }
    };
    useGradient(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('useGradient', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('useGradient');
        }
    };
    values(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('values', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('values');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('width');
        }
    };
    refresh() {
        JQXLite(this.componentSelector).jqxBarGauge('refresh');  
    };
    performRender() {
        JQXLite(this.componentSelector).jqxBarGauge('render');
    };
    val(value) {
        if (value !== undefined) {
            JQXLite(this.componentSelector).jqxBarGauge('val',  value)
        } else {
            return JQXLite(this.componentSelector).jqxBarGauge('val');
        }
    };

    render() {
        return (
            <div id={this.state.id}>{this.props.value}{this.props.children}</div>
        )
    };
};

// jqwidgets-vue/vue_jqxbargauge.vue
/*
jQWidgets v6.1.0 (2018-October)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxdraw.js';
    import '../jqwidgets/jqxbargauge.js';

    export default {
        props: {
            animationDuration: Number,
            backgroundColor: String,
            barSpacing: Number,
            baseValue: Number,
            colorScheme: String,
            customColorScheme: [String, Object],
            disabled: Boolean,
            endAngle: Number,
            formatFunction: [Object, Function],
            height: [Number, String],
            labels: Object,
            max: Number,
            min: Number,
            relativeInnerRadius: Number,
            rendered: Function,
            startAngle: Number,
            title: [Object, String],
            tooltip: Object,
            useGradient: Boolean,
            values: Array,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxBarGauge' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxBarGauge(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxBarGauge(usedProps[i]);
                }
                return resultToReturn;
            },
            refresh: function() {
                JQXLite(this.componentSelector).jqxBarGauge('refresh');  
            },
            render: function() {
                JQXLite(this.componentSelector).jqxBarGauge('render');  
            },
            val: function(value) {
                if (value !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('val',  value)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('val');
                }
            },
            _animationDuration: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('animationDuration', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('animationDuration');
                }
            },
            _backgroundColor: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('backgroundColor', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('backgroundColor');
                }
            },
            _barSpacing: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('barSpacing', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('barSpacing');
                }
            },
            _baseValue: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('baseValue', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('baseValue');
                }
            },
            _colorScheme: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('colorScheme', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('colorScheme');
                }
            },
            _customColorScheme: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('customColorScheme', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('customColorScheme');
                }
            },
            _disabled: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('disabled', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('disabled');
                }
            },
            _endAngle: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('endAngle', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('endAngle');
                }
            },
            _formatFunction: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('formatFunction', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('formatFunction');
                }
            },
            _height: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('height', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('height');
                }
            },
            _labels: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('labels', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('labels');
                }
            },
            _max: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('max', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('max');
                }
            },
            _min: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('min', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('min');
                }
            },
            _relativeInnerRadius: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('relativeInnerRadius', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('relativeInnerRadius');
                }
            },
            _rendered: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('rendered', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('rendered');
                }
            },
            _startAngle: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('startAngle', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('startAngle');
                }
            },
            _title: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('title', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('title');
                }
            },
            _tooltip: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('tooltip', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('tooltip');
                }
            },
            _useGradient: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('useGradient', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('useGradient');
                }
            },
            _values: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('values', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('values');
                }
            },
            _width: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBarGauge('width', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBarGauge('width');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxBarGauge(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['animationDuration','backgroundColor','barSpacing','baseValue','colorScheme','customColorScheme','disabled','endAngle','formatFunction','height','labels','max','min','relativeInnerRadius','rendered','startAngle','title','tooltip','useGradient','values','width'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'animationDuration', {
                    get() {
                        return that._animationDuration();
                    },
                    set(newValue) {
                        that._animationDuration(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'backgroundColor', {
                    get() {
                        return that._backgroundColor();
                    },
                    set(newValue) {
                        that._backgroundColor(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'barSpacing', {
                    get() {
                        return that._barSpacing();
                    },
                    set(newValue) {
                        that._barSpacing(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'baseValue', {
                    get() {
                        return that._baseValue();
                    },
                    set(newValue) {
                        that._baseValue(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'colorScheme', {
                    get() {
                        return that._colorScheme();
                    },
                    set(newValue) {
                        that._colorScheme(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'customColorScheme', {
                    get() {
                        return that._customColorScheme();
                    },
                    set(newValue) {
                        that._customColorScheme(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'disabled', {
                    get() {
                        return that._disabled();
                    },
                    set(newValue) {
                        that._disabled(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'endAngle', {
                    get() {
                        return that._endAngle();
                    },
                    set(newValue) {
                        that._endAngle(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'formatFunction', {
                    get() {
                        return that._formatFunction();
                    },
                    set(newValue) {
                        that._formatFunction(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'height', {
                    get() {
                        return that._height();
                    },
                    set(newValue) {
                        that._height(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'labels', {
                    get() {
                        return that._labels();
                    },
                    set(newValue) {
                        that._labels(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'max', {
                    get() {
                        return that._max();
                    },
                    set(newValue) {
                        that._max(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'min', {
                    get() {
                        return that._min();
                    },
                    set(newValue) {
                        that._min(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'relativeInnerRadius', {
                    get() {
                        return that._relativeInnerRadius();
                    },
                    set(newValue) {
                        that._relativeInnerRadius(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'rendered', {
                    get() {
                        return that._rendered();
                    },
                    set(newValue) {
                        that._rendered(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'startAngle', {
                    get() {
                        return that._startAngle();
                    },
                    set(newValue) {
                        that._startAngle(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'title', {
                    get() {
                        return that._title();
                    },
                    set(newValue) {
                        that._title(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'tooltip', {
                    get() {
                        return that._tooltip();
                    },
                    set(newValue) {
                        that._tooltip(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'useGradient', {
                    get() {
                        return that._useGradient();
                    },
                    set(newValue) {
                        that._useGradient(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'values', {
                    get() {
                        return that._values();
                    },
                    set(newValue) {
                        that._values(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'width', {
                    get() {
                        return that._width();
                    },
                    set(newValue) {
                        that._width(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __wireEvents__: function () {
                const that = this;

                JQXLite(this.componentSelector).on('drawEnd', function (event) { that.$emit('drawEnd', event); });
                JQXLite(this.componentSelector).on('drawStart', function (event) { that.$emit('drawStart', event); });
                JQXLite(this.componentSelector).on('initialized', function (event) { that.$emit('initialized', event); });
                JQXLite(this.componentSelector).on('tooltipClose', function (event) { that.$emit('tooltipClose', event); });
                JQXLite(this.componentSelector).on('tooltipOpen', function (event) { that.$emit('tooltipOpen', event); });
                JQXLite(this.componentSelector).on('valueChanged', function (event) { that.$emit('valueChanged', event); });
            }
        }
    }
</script>
