// jqwidgets-react/react_jqxsortable.js
/*
jQWidgets v6.1.0 (2018-October)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxbuttons.js';
import '../jqwidgets/jqxsortable.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxSortable extends React.Component {
    constructor(props) {
        super(props);
        const widgetId = 'jqxSortable' + JQXLite.generateID();
        this.componentSelector = '#' + widgetId;
        this.state = { id: widgetId };
    };
    componentDidMount() {
        const options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        const properties = ['appendTo','axis','cancelProperty','connectWith','containment','cursor','cursorAt','delay','disabled','distance','dropOnEmpty','forceHelperSize','forcePlaceholderSize','grid','handle','helper','items','opacity','placeholderShow','revert','scroll','scrollSensitivity','scrollSpeed','tolerance','zIndex'];
        let options = {};
        for(let item in this.props) {
            if(item === 'settings') {
                for(let itemTwo in this.props[item]) {
                    options[itemTwo] = this.props[item][itemTwo];
                }
            } else {
                if(properties.indexOf(item) !== -1) {
                      options[item] = this.props[item];
                }
            }
        }
        return options;
    };
    createComponent(options) {
        if(!this.style) {
            for (let style in this.props.style) {
                JQXLite(this.componentSelector).css(style, this.props.style[style]);
            }
        }
        if(this.props.className !== undefined) {
            const classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
            JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxSortable(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxSortable('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxSortable(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    appendTo(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('appendTo', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('appendTo');
        }
    };
    axis(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('axis', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('axis');
        }
    };
    cancelProperty(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('cancelProperty', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('cancelProperty');
        }
    };
    connectWith(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('connectWith', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('connectWith');
        }
    };
    containment(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('containment', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('containment');
        }
    };
    cursor(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('cursor', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('cursor');
        }
    };
    cursorAt(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('cursorAt', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('cursorAt');
        }
    };
    delay(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('delay', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('delay');
        }
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('disabled');
        }
    };
    distance(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('distance', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('distance');
        }
    };
    dropOnEmpty(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('dropOnEmpty', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('dropOnEmpty');
        }
    };
    forceHelperSize(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('forceHelperSize', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('forceHelperSize');
        }
    };
    forcePlaceholderSize(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('forcePlaceholderSize', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('forcePlaceholderSize');
        }
    };
    grid(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('grid', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('grid');
        }
    };
    handle(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('handle', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('handle');
        }
    };
    helper(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('helper', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('helper');
        }
    };
    items(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('items', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('items');
        }
    };
    opacity(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('opacity', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('opacity');
        }
    };
    placeholderShow(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('placeholderShow', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('placeholderShow');
        }
    };
    revert(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('revert', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('revert');
        }
    };
    scroll(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('scroll', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('scroll');
        }
    };
    scrollSensitivity(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('scrollSensitivity', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('scrollSensitivity');
        }
    };
    scrollSpeed(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('scrollSpeed', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('scrollSpeed');
        }
    };
    tolerance(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('tolerance', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('tolerance');
        }
    };
    zIndex(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSortable('zIndex', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSortable('zIndex');
        }
    };
    cancelMethod() {
        JQXLite(this.componentSelector).jqxSortable('cancelMethod');  
    };
    destroy() {
        JQXLite(this.componentSelector).jqxSortable('destroy');  
    };
    disable() {
        JQXLite(this.componentSelector).jqxSortable('disable');  
    };
    enable() {
        JQXLite(this.componentSelector).jqxSortable('enable');  
    };
    refresh() {
        JQXLite(this.componentSelector).jqxSortable('refresh');  
    };
    refreshPositions() {
        JQXLite(this.componentSelector).jqxSortable('refreshPositions');  
    };
    serialize() {
        JQXLite(this.componentSelector).jqxSortable('serialize');  
    };
    toArray() {
        return JQXLite(this.componentSelector).jqxSortable('toArray');  
    };
    render() {
        return (
            <div id={this.state.id}>{this.props.value}{this.props.children}</div>
        )
    };
};

// jqwidgets-vue/vue_jqxsortable.vue
/*
jQWidgets v6.1.0 (2018-October)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxsortable.js';

    export default {
        props: {
            appendTo: String,
            axis: String,
            cancelProperty: String,
            connectWith: String,
            containment: String,
            cursor: String,
            cursorAt: Object,
            delay: Number,
            disabled: Boolean,
            distance: Number,
            dropOnEmpty: Boolean,
            forceHelperSize: Boolean,
            forcePlaceholderSize: Boolean,
            grid: Array,
            handle: String,
            helper: String,
            items: String,
            opacity: Number,
            placeholderShow: String,
            revert: Boolean,
            scroll: Boolean,
            scrollSensitivity: Number,
            scrollSpeed: Number,
            tolerance: String,
            zIndex: Number,
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxSortable' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxSortable(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxSortable(usedProps[i]);
                }
                return resultToReturn;
            },
            cancelMethod: function() {
                JQXLite(this.componentSelector).jqxSortable('cancelMethod');  
            },
            destroy: function() {
                JQXLite(this.componentSelector).jqxSortable('destroy');  
            },
            disable: function() {
                JQXLite(this.componentSelector).jqxSortable('disable');  
            },
            enable: function() {
                JQXLite(this.componentSelector).jqxSortable('enable');  
            },
            refresh: function() {
                JQXLite(this.componentSelector).jqxSortable('refresh');  
            },
            refreshPositions: function() {
                JQXLite(this.componentSelector).jqxSortable('refreshPositions');  
            },
            serialize: function() {
                JQXLite(this.componentSelector).jqxSortable('serialize');  
            },
            toArray: function() {
                return JQXLite(this.componentSelector).jqxSortable('toArray');  
            },
            _appendTo: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('appendTo', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('appendTo');
                }
            },
            _axis: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('axis', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('axis');
                }
            },
            _cancelProperty: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('cancelProperty', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('cancelProperty');
                }
            },
            _connectWith: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('connectWith', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('connectWith');
                }
            },
            _containment: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('containment', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('containment');
                }
            },
            _cursor: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('cursor', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('cursor');
                }
            },
            _cursorAt: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('cursorAt', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('cursorAt');
                }
            },
            _delay: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('delay', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('delay');
                }
            },
            _disabled: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('disabled', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('disabled');
                }
            },
            _distance: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('distance', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('distance');
                }
            },
            _dropOnEmpty: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('dropOnEmpty', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('dropOnEmpty');
                }
            },
            _forceHelperSize: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('forceHelperSize', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('forceHelperSize');
                }
            },
            _forcePlaceholderSize: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('forcePlaceholderSize', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('forcePlaceholderSize');
                }
            },
            _grid: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('grid', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('grid');
                }
            },
            _handle: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('handle', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('handle');
                }
            },
            _helper: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('helper', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('helper');
                }
            },
            _items: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('items', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('items');
                }
            },
            _opacity: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('opacity', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('opacity');
                }
            },
            _placeholderShow: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('placeholderShow', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('placeholderShow');
                }
            },
            _revert: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('revert', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('revert');
                }
            },
            _scroll: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('scroll', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('scroll');
                }
            },
            _scrollSensitivity: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('scrollSensitivity', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('scrollSensitivity');
                }
            },
            _scrollSpeed: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('scrollSpeed', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('scrollSpeed');
                }
            },
            _tolerance: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('tolerance', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('tolerance');
                }
            },
            _zIndex: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('zIndex', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('zIndex');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxSortable(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['appendTo','axis','cancelProperty','connectWith','containment','cursor','cursorAt','delay','disabled','distance','dropOnEmpty','forceHelperSize','forcePlaceholderSize','grid','handle','helper','items','opacity','placeholderShow','revert','scroll','scrollSensitivity','scrollSpeed','tolerance','zIndex'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'appendTo', {
                    get() {
                        return that._appendTo();
                    },
                    set(newValue) {
                        that._appendTo(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'axis', {
                    get() {
                        return that._axis();
                    },
                    set(newValue) {
                        that._axis(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'cancelProperty', {
                    get() {
                        return that._cancelProperty();
                    },
                    set(newValue) {
                        that._cancelProperty(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'connectWith', {
                    get() {
                        return that._connectWith();
                    },
                    set(newValue) {
                        that._connectWith(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'containment', {
                    get() {
                        return that._containment();
                    },
                    set(newValue) {
                        that._containment(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'cursor', {
                    get() {
                        return that._cursor();
                    },
                    set(newValue) {
                        that._cursor(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'cursorAt', {
                    get() {
                        return that._cursorAt();
                    },
                    set(newValue) {
                        that._cursorAt(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'delay', {
                    get() {
                        return that._delay();
                    },
                    set(newValue) {
                        that._delay(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'disabled', {
                    get() {
                        return that._disabled();
                    },
                    set(newValue) {
                        that._disabled(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'distance', {
                    get() {
                        return that._distance();
                    },
                    set(newValue) {
                        that._distance(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'dropOnEmpty', {
                    get() {
                        return that._dropOnEmpty();
                    },
                    set(newValue) {
                        that._dropOnEmpty(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'forceHelperSize', {
                    get() {
                        return that._forceHelperSize();
                    },
                    set(newValue) {
                        that._forceHelperSize(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'forcePlaceholderSize', {
                    get() {
                        return that._forcePlaceholderSize();
                    },
                    set(newValue) {
                        that._forcePlaceholderSize(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'grid', {
                    get() {
                        return that._grid();
                    },
                    set(newValue) {
                        that._grid(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'handle', {
                    get() {
                        return that._handle();
                    },
                    set(newValue) {
                        that._handle(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'helper', {
                    get() {
                        return that._helper();
                    },
                    set(newValue) {
                        that._helper(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'items', {
                    get() {
                        return that._items();
                    },
                    set(newValue) {
                        that._items(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'opacity', {
                    get() {
                        return that._opacity();
                    },
                    set(newValue) {
                        that._opacity(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'placeholderShow', {
                    get() {
                        return that._placeholderShow();
                    },
                    set(newValue) {
                        that._placeholderShow(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'revert', {
                    get() {
                        return that._revert();
                    },
                    set(newValue) {
                        that._revert(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'scroll', {
                    get() {
                        return that._scroll();
                    },
                    set(newValue) {
                        that._scroll(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'scrollSensitivity', {
                    get() {
                        return that._scrollSensitivity();
                    },
                    set(newValue) {
                        that._scrollSensitivity(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'scrollSpeed', {
                    get() {
                        return that._scrollSpeed();
                    },
                    set(newValue) {
                        that._scrollSpeed(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'tolerance', {
                    get() {
                        return that._tolerance();
                    },
                    set(newValue) {
                        that._tolerance(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'zIndex', {
                    get() {
                        return that._zIndex();
                    },
                    set(newValue) {
                        that._zIndex(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __wireEvents__: function () {
                const that = this;

                JQXLite(this.componentSelector).on('activate', function (event) { that.$emit('activate', event); });
                JQXLite(this.componentSelector).on('beforeStop', function (event) { that.$emit('beforeStop', event); });
                JQXLite(this.componentSelector).on('change', function (event) { that.$emit('change', event); });
                JQXLite(this.componentSelector).on('create', function (event) { that.$emit('create', event); });
                JQXLite(this.componentSelector).on('deactivate', function (event) { that.$emit('deactivate', event); });
                JQXLite(this.componentSelector).on('out', function (event) { that.$emit('out', event); });
                JQXLite(this.componentSelector).on('over', function (event) { that.$emit('over', event); });
                JQXLite(this.componentSelector).on('receive', function (event) { that.$emit('receive', event); });
                JQXLite(this.componentSelector).on('remove', function (event) { that.$emit('remove', event); });
                JQXLite(this.componentSelector).on('sort', function (event) { that.$emit('sort', event); });
                JQXLite(this.componentSelector).on('start', function (event) { that.$emit('start', event); });
                JQXLite(this.componentSelector).on('stop', function (event) { that.$emit('stop', event); });
                JQXLite(this.componentSelector).on('update', function (event) { that.$emit('update', event); });
            }
        }
    }
</script>
