// jqwidgets-react/react_jqxtreemap.js
/*
jQWidgets v6.0.4 (2018-July)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxdata.js';
import '../jqwidgets/jqxtreemap.js';
import '../jqwidgets/jqxtooltip.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxTreeMap extends React.Component {
    componentDidMount() {
        let options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        let properties = ['baseColor','colorRanges','colorRange','colorMode','displayMember','height','hoverEnabled','headerHeight','legendLabel','legendPosition','legendScaleCallback','renderCallbacks','selectionEnabled','showLegend','source','theme','valueMember','width'];
        let options = {};
        for(let item in this.props) {
              if(item === 'settings') {
                  for(let itemTwo in this.props[item]) {
                      options[itemTwo] = this.props[item][itemTwo];
                      }
                } else {
                      if(properties.indexOf(item) !== -1) {
                        options[item] = this.props[item];
                      }
                }
          }
          return options;
      };
    createComponent(options) {
        if(!this.style) {
              for (let style in this.props.style) {
                  JQXLite(this.componentSelector).css(style, this.props.style[style]);
              }
        }
        if(this.props.className !== undefined) {
            let classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
    JQXLite(this.componentSelector).css('margin-left', '1px');        if(!this.template) {
              JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxTreeMap(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxTreeMap('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxTreeMap(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    baseColor(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('baseColor', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('baseColor');
        }
    };
    colorRanges(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('colorRanges', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('colorRanges');
        }
    };
    colorRange(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('colorRange', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('colorRange');
        }
    };
    colorMode(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('colorMode', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('colorMode');
        }
    };
    displayMember(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('displayMember', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('displayMember');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('height');
        }
    };
    hoverEnabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('hoverEnabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('hoverEnabled');
        }
    };
    headerHeight(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('headerHeight', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('headerHeight');
        }
    };
    legendLabel(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('legendLabel', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('legendLabel');
        }
    };
    legendPosition(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('legendPosition', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('legendPosition');
        }
    };
    legendScaleCallback(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('legendScaleCallback', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('legendScaleCallback');
        }
    };
    renderCallbacks(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('renderCallbacks', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('renderCallbacks');
        }
    };
    selectionEnabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('selectionEnabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('selectionEnabled');
        }
    };
    showLegend(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('showLegend', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('showLegend');
        }
    };
    source(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('source', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('source');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('theme');
        }
    };
    valueMember(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('valueMember', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('valueMember');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxTreeMap('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxTreeMap('width');
        }
    };
    destroy() {
        JQXLite(this.componentSelector).jqxTreeMap('destroy');  
    };
    performRender() {
        JQXLite(this.componentSelector).jqxTreeMap('render');
    };
    render() {
        let id = 'jqxTreeMap' + JQXLite.generateID();
        this.componentSelector = '#' + id;
        return (
            <div id={id}>{this.props.value}{this.props.children}</div>
        )
    };
};

// jqwidgets-vue/vue_jqxtreemap.vue
/*
jQWidgets v8.1.4 (2019-July)
Copyright (c) 2011-2019 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxdata.js';
    import '../jqwidgets/jqxtreemap.js';
    import '../jqwidgets/jqxtooltip.js';

    export default {
        props: {
            baseColor: String,
            colorRanges: [Array, Object],
            colorRange: Number,
            colorMode: String,
            displayMember: String,
            height: [Number, String],
            hoverEnabled: Boolean,
            headerHeight: Number,
            legendLabel: String,
            legendPosition: Object,
            legendScaleCallback: Function,
            renderCallbacks: Object,
            selectionEnabled: Boolean,
            showLegend: Boolean,
            source: [Object, Array],
            theme: String,
            valueMember: String,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxTreeMap' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxTreeMap(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxTreeMap(usedProps[i]);
                }
                return resultToReturn;
            },
            destroy: function() {
                JQXLite(this.componentSelector).jqxTreeMap('destroy');  
            },
            render: function() {
                JQXLite(this.componentSelector).jqxTreeMap('render');  
            },
            _baseColor: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('baseColor', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('baseColor');
                }
            },
            _colorRanges: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('colorRanges', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('colorRanges');
                }
            },
            _colorRange: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('colorRange', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('colorRange');
                }
            },
            _colorMode: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('colorMode', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('colorMode');
                }
            },
            _displayMember: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('displayMember', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('displayMember');
                }
            },
            _height: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('height', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('height');
                }
            },
            _hoverEnabled: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('hoverEnabled', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('hoverEnabled');
                }
            },
            _headerHeight: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('headerHeight', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('headerHeight');
                }
            },
            _legendLabel: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('legendLabel', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('legendLabel');
                }
            },
            _legendPosition: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('legendPosition', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('legendPosition');
                }
            },
            _legendScaleCallback: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('legendScaleCallback', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('legendScaleCallback');
                }
            },
            _renderCallbacks: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('renderCallbacks', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('renderCallbacks');
                }
            },
            _selectionEnabled: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('selectionEnabled', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('selectionEnabled');
                }
            },
            _showLegend: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('showLegend', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('showLegend');
                }
            },
            _source: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('source', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('source');
                }
            },
            _theme: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('theme', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('theme');
                }
            },
            _valueMember: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('valueMember', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('valueMember');
                }
            },
            _width: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTreeMap('width', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTreeMap('width');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxTreeMap(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['baseColor','colorRanges','colorRange','colorMode','displayMember','height','hoverEnabled','headerHeight','legendLabel','legendPosition','legendScaleCallback','renderCallbacks','selectionEnabled','showLegend','source','theme','valueMember','width'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'baseColor', {
                    get: function() {
                        return that._baseColor();
                    },
                    set: function(newValue) {
                        that._baseColor(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'colorRanges', {
                    get: function() {
                        return that._colorRanges();
                    },
                    set: function(newValue) {
                        that._colorRanges(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'colorRange', {
                    get: function() {
                        return that._colorRange();
                    },
                    set: function(newValue) {
                        that._colorRange(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'colorMode', {
                    get: function() {
                        return that._colorMode();
                    },
                    set: function(newValue) {
                        that._colorMode(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'displayMember', {
                    get: function() {
                        return that._displayMember();
                    },
                    set: function(newValue) {
                        that._displayMember(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'height', {
                    get: function() {
                        return that._height();
                    },
                    set: function(newValue) {
                        that._height(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'hoverEnabled', {
                    get: function() {
                        return that._hoverEnabled();
                    },
                    set: function(newValue) {
                        that._hoverEnabled(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'headerHeight', {
                    get: function() {
                        return that._headerHeight();
                    },
                    set: function(newValue) {
                        that._headerHeight(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'legendLabel', {
                    get: function() {
                        return that._legendLabel();
                    },
                    set: function(newValue) {
                        that._legendLabel(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'legendPosition', {
                    get: function() {
                        return that._legendPosition();
                    },
                    set: function(newValue) {
                        that._legendPosition(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'legendScaleCallback', {
                    get: function() {
                        return that._legendScaleCallback();
                    },
                    set: function(newValue) {
                        that._legendScaleCallback(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'renderCallbacks', {
                    get: function() {
                        return that._renderCallbacks();
                    },
                    set: function(newValue) {
                        that._renderCallbacks(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'selectionEnabled', {
                    get: function() {
                        return that._selectionEnabled();
                    },
                    set: function(newValue) {
                        that._selectionEnabled(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'showLegend', {
                    get: function() {
                        return that._showLegend();
                    },
                    set: function(newValue) {
                        that._showLegend(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'source', {
                    get: function() {
                        return that._source();
                    },
                    set: function(newValue) {
                        that._source(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'theme', {
                    get: function() {
                        return that._theme();
                    },
                    set: function(newValue) {
                        that._theme(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'valueMember', {
                    get: function() {
                        return that._valueMember();
                    },
                    set: function(newValue) {
                        that._valueMember(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'width', {
                    get: function() {
                        return that._width();
                    },
                    set: function(newValue) {
                        that._width(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __wireEvents__: function () {
                const that = this;

                JQXLite(this.componentSelector).on('bindingComplete', function (event) { that.$emit('bindingComplete', event); });
            }
        }
    }
</script>
