// jqwidgets-react/react_jqxradiobutton.js
/*
jQWidgets v6.2.0 (2018-Dec)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxradiobutton.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxRadioButton extends React.Component {
    constructor(props) {
        super(props);
        const widgetId = 'jqxRadioButton' + JQXLite.generateID();
        this.componentSelector = '#' + widgetId;
        this.state = { id: widgetId };
    };
    componentDidMount() {
        const options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        const properties = ['animationShowDelay','animationHideDelay','boxSize','checked','disabled','enableContainerClick','groupName','hasThreeStates','height','rtl','theme','width'];
        let options = {};
        for(let item in this.props) {
            if(item === 'settings') {
                for(let itemTwo in this.props[item]) {
                    options[itemTwo] = this.props[item][itemTwo];
                }
            } else {
                if(properties.indexOf(item) !== -1) {
                      options[item] = this.props[item];
                }
            }
        }
        return options;
    };
    createComponent(options) {
        if(!this.style) {
            for (let style in this.props.style) {
                JQXLite(this.componentSelector).css(style, this.props.style[style]);
            }
        }
        if(this.props.className !== undefined) {
            const classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
            JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxRadioButton(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxRadioButton('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxRadioButton(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    animationShowDelay(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRadioButton('animationShowDelay', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRadioButton('animationShowDelay');
        }
    };
    animationHideDelay(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRadioButton('animationHideDelay', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRadioButton('animationHideDelay');
        }
    };
    boxSize(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRadioButton('boxSize', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRadioButton('boxSize');
        }
    };
    checked(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRadioButton('checked', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRadioButton('checked');
        }
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRadioButton('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRadioButton('disabled');
        }
    };
    enableContainerClick(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRadioButton('enableContainerClick', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRadioButton('enableContainerClick');
        }
    };
    groupName(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRadioButton('groupName', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRadioButton('groupName');
        }
    };
    hasThreeStates(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRadioButton('hasThreeStates', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRadioButton('hasThreeStates');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRadioButton('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRadioButton('height');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRadioButton('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRadioButton('rtl');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRadioButton('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRadioButton('theme');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRadioButton('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRadioButton('width');
        }
    };
    check() {
        JQXLite(this.componentSelector).jqxRadioButton('check');  
    };
    disable() {
        JQXLite(this.componentSelector).jqxRadioButton('disable');  
    };
    destroy() {
        JQXLite(this.componentSelector).jqxRadioButton('destroy');  
    };
    enable() {
        JQXLite(this.componentSelector).jqxRadioButton('enable');  
    };
    focus() {
        JQXLite(this.componentSelector).jqxRadioButton('focus');  
    };
    performRender() {
        JQXLite(this.componentSelector).jqxRadioButton('render');
    };
    uncheck() {
        JQXLite(this.componentSelector).jqxRadioButton('uncheck');  
    };
    val(value) {
        if (value !== undefined) {
            JQXLite(this.componentSelector).jqxRadioButton('val',  value)
        } else {
            return JQXLite(this.componentSelector).jqxRadioButton('val');
        }
    };

    render() {
        return (
            <div id={this.state.id}>{this.props.value}{this.props.children}</div>
        )
    };
};

// jqwidgets-vue/vue_jqxradiobutton.vue
/*
jQWidgets v6.2.0 (2018-Dec)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxradiobutton.js';

    export default {
        props: {
            animationShowDelay: Number,
            animationHideDelay: Number,
            boxSize: String,
            checked: Boolean,
            disabled: Boolean,
            enableContainerClick: Boolean,
            groupName: String,
            hasThreeStates: Boolean,
            height: [Number, String],
            rtl: Boolean,
            theme: String,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxRadioButton' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxRadioButton(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxRadioButton(usedProps[i]);
                }
                return resultToReturn;
            },
            check: function() {
                JQXLite(this.componentSelector).jqxRadioButton('check');  
            },
            disable: function() {
                JQXLite(this.componentSelector).jqxRadioButton('disable');  
            },
            destroy: function() {
                JQXLite(this.componentSelector).jqxRadioButton('destroy');  
            },
            enable: function() {
                JQXLite(this.componentSelector).jqxRadioButton('enable');  
            },
            focus: function() {
                JQXLite(this.componentSelector).jqxRadioButton('focus');  
            },
            render: function() {
                JQXLite(this.componentSelector).jqxRadioButton('render');  
            },
            uncheck: function() {
                JQXLite(this.componentSelector).jqxRadioButton('uncheck');  
            },
            val: function(value) {
                if (value !== undefined) {
                    JQXLite(this.componentSelector).jqxRadioButton('val',  value)
                } else {
                    return JQXLite(this.componentSelector).jqxRadioButton('val');
                }
            },
            _animationShowDelay: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxRadioButton('animationShowDelay', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxRadioButton('animationShowDelay');
                }
            },
            _animationHideDelay: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxRadioButton('animationHideDelay', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxRadioButton('animationHideDelay');
                }
            },
            _boxSize: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxRadioButton('boxSize', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxRadioButton('boxSize');
                }
            },
            _checked: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxRadioButton('checked', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxRadioButton('checked');
                }
            },
            _disabled: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxRadioButton('disabled', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxRadioButton('disabled');
                }
            },
            _enableContainerClick: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxRadioButton('enableContainerClick', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxRadioButton('enableContainerClick');
                }
            },
            _groupName: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxRadioButton('groupName', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxRadioButton('groupName');
                }
            },
            _hasThreeStates: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxRadioButton('hasThreeStates', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxRadioButton('hasThreeStates');
                }
            },
            _height: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxRadioButton('height', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxRadioButton('height');
                }
            },
            _rtl: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxRadioButton('rtl', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxRadioButton('rtl');
                }
            },
            _theme: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxRadioButton('theme', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxRadioButton('theme');
                }
            },
            _width: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxRadioButton('width', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxRadioButton('width');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxRadioButton(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['animationShowDelay','animationHideDelay','boxSize','checked','disabled','enableContainerClick','groupName','hasThreeStates','height','rtl','theme','width'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'animationShowDelay', {
                    get() {
                        return that._animationShowDelay();
                    },
                    set(newValue) {
                        that._animationShowDelay(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'animationHideDelay', {
                    get() {
                        return that._animationHideDelay();
                    },
                    set(newValue) {
                        that._animationHideDelay(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'boxSize', {
                    get() {
                        return that._boxSize();
                    },
                    set(newValue) {
                        that._boxSize(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'checked', {
                    get() {
                        return that._checked();
                    },
                    set(newValue) {
                        that._checked(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'disabled', {
                    get() {
                        return that._disabled();
                    },
                    set(newValue) {
                        that._disabled(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'enableContainerClick', {
                    get() {
                        return that._enableContainerClick();
                    },
                    set(newValue) {
                        that._enableContainerClick(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'groupName', {
                    get() {
                        return that._groupName();
                    },
                    set(newValue) {
                        that._groupName(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'hasThreeStates', {
                    get() {
                        return that._hasThreeStates();
                    },
                    set(newValue) {
                        that._hasThreeStates(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'height', {
                    get() {
                        return that._height();
                    },
                    set(newValue) {
                        that._height(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'rtl', {
                    get() {
                        return that._rtl();
                    },
                    set(newValue) {
                        that._rtl(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'theme', {
                    get() {
                        return that._theme();
                    },
                    set(newValue) {
                        that._theme(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'width', {
                    get() {
                        return that._width();
                    },
                    set(newValue) {
                        that._width(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __twoWayDataBinding__: function () {
                this.$emit('input', this.$el.innerText);
            },
            __wireEvents__: function () {
                const that = this;

                JQXLite(this.componentSelector).on('checked', function (event) { that.$emit('checked', event); that.__twoWayDataBinding__(); });
                JQXLite(this.componentSelector).on('change', function (event) { that.$emit('change', event); });
                JQXLite(this.componentSelector).on('unchecked', function (event) { that.$emit('unchecked', event); });
            }
        }
    }
</script>
