// jqwidgets-react/react_jqxpanel.js
/*
jQWidgets v7.1.0 (2019-Feb)
Copyright (c) 2011-2019 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxbuttons.js';
import '../jqwidgets/jqxscrollbar.js';
import '../jqwidgets/jqxpanel.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxPanel extends React.Component {
    constructor(props) {
        super(props);
        const widgetId = 'jqxPanel' + JQXLite.generateID();
        this.componentSelector = '#' + widgetId;
        this.state = { id: widgetId };
    };
    componentDidMount() {
        const options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        const properties = ['autoUpdate','disabled','height','rtl','sizeMode','scrollBarSize','theme','width'];
        let options = {};
        for(let item in this.props) {
            if(item === 'settings') {
                for(let itemTwo in this.props[item]) {
                    options[itemTwo] = this.props[item][itemTwo];
                }
            } else {
                if(properties.indexOf(item) !== -1) {
                      options[item] = this.props[item];
                }
            }
        }
        return options;
    };
    createComponent(options) {
        if(!this.style) {
            for (let style in this.props.style) {
                JQXLite(this.componentSelector).css(style, this.props.style[style]);
            }
        }
        if(this.props.className !== undefined) {
            const classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
            JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxPanel(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxPanel('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxPanel(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    autoUpdate(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxPanel('autoUpdate', arg)
        } else {
            return JQXLite(this.componentSelector).jqxPanel('autoUpdate');
        }
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxPanel('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxPanel('disabled');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxPanel('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxPanel('height');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxPanel('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxPanel('rtl');
        }
    };
    sizeMode(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxPanel('sizeMode', arg)
        } else {
            return JQXLite(this.componentSelector).jqxPanel('sizeMode');
        }
    };
    scrollBarSize(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxPanel('scrollBarSize', arg)
        } else {
            return JQXLite(this.componentSelector).jqxPanel('scrollBarSize');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxPanel('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxPanel('theme');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxPanel('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxPanel('width');
        }
    };
    append(HTMLElement) {
        JQXLite(this.componentSelector).jqxPanel('append', HTMLElement);  
    };
    clearcontent() {
        JQXLite(this.componentSelector).jqxPanel('clearcontent');  
    };
    destroy() {
        JQXLite(this.componentSelector).jqxPanel('destroy');  
    };
    focus() {
        JQXLite(this.componentSelector).jqxPanel('focus');  
    };
    getScrollHeight() {
        return JQXLite(this.componentSelector).jqxPanel('getScrollHeight');  
    };
    getVScrollPosition() {
        return JQXLite(this.componentSelector).jqxPanel('getVScrollPosition');  
    };
    getScrollWidth() {
        return JQXLite(this.componentSelector).jqxPanel('getScrollWidth');  
    };
    getHScrollPosition() {
        return JQXLite(this.componentSelector).jqxPanel('getHScrollPosition');  
    };
    prepend(HTMLElement) {
        JQXLite(this.componentSelector).jqxPanel('prepend', HTMLElement);  
    };
    remove(HTMLElement) {
        JQXLite(this.componentSelector).jqxPanel('remove', HTMLElement);  
    };
    scrollTo(top, left) {
        JQXLite(this.componentSelector).jqxPanel('scrollTo', top, left);  
    };
    render() {
        return (
            <div id={this.state.id}>{this.props.value}{this.props.children}</div>
        )
    };
};

// jqwidgets-vue/vue_jqxpanel.vue
/*
jQWidgets v7.2.0 (2019-Apr)
Copyright (c) 2011-2019 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxscrollbar.js';
    import '../jqwidgets/jqxpanel.js';

    export default {
        props: {
            autoUpdate: Boolean,
            disabled: Boolean,
            height: [Number, String],
            rtl: Boolean,
            sizeMode: String,
            scrollBarSize: Number,
            theme: String,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxPanel' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxPanel(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxPanel(usedProps[i]);
                }
                return resultToReturn;
            },
            append: function(HTMLElement) {
                JQXLite(this.componentSelector).jqxPanel('append', HTMLElement);  
            },
            clearcontent: function() {
                JQXLite(this.componentSelector).jqxPanel('clearcontent');  
            },
            destroy: function() {
                JQXLite(this.componentSelector).jqxPanel('destroy');  
            },
            focus: function() {
                JQXLite(this.componentSelector).jqxPanel('focus');  
            },
            getScrollHeight: function() {
                return JQXLite(this.componentSelector).jqxPanel('getScrollHeight');  
            },
            getVScrollPosition: function() {
                return JQXLite(this.componentSelector).jqxPanel('getVScrollPosition');  
            },
            getScrollWidth: function() {
                return JQXLite(this.componentSelector).jqxPanel('getScrollWidth');  
            },
            getHScrollPosition: function() {
                return JQXLite(this.componentSelector).jqxPanel('getHScrollPosition');  
            },
            prepend: function(HTMLElement) {
                JQXLite(this.componentSelector).jqxPanel('prepend', HTMLElement);  
            },
            remove: function(HTMLElement) {
                JQXLite(this.componentSelector).jqxPanel('remove', HTMLElement);  
            },
            scrollTo: function(left, top) {
                JQXLite(this.componentSelector).jqxPanel('scrollTo', left, top);  
            },
            _autoUpdate: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxPanel('autoUpdate', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxPanel('autoUpdate');
                }
            },
            _disabled: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxPanel('disabled', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxPanel('disabled');
                }
            },
            _height: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxPanel('height', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxPanel('height');
                }
            },
            _rtl: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxPanel('rtl', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxPanel('rtl');
                }
            },
            _sizeMode: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxPanel('sizeMode', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxPanel('sizeMode');
                }
            },
            _scrollBarSize: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxPanel('scrollBarSize', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxPanel('scrollBarSize');
                }
            },
            _theme: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxPanel('theme', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxPanel('theme');
                }
            },
            _width: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxPanel('width', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxPanel('width');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxPanel(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['autoUpdate','disabled','height','rtl','sizeMode','scrollBarSize','theme','width'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'autoUpdate', {
                    get() {
                        return that._autoUpdate();
                    },
                    set(newValue) {
                        that._autoUpdate(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'disabled', {
                    get() {
                        return that._disabled();
                    },
                    set(newValue) {
                        that._disabled(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'height', {
                    get() {
                        return that._height();
                    },
                    set(newValue) {
                        that._height(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'rtl', {
                    get() {
                        return that._rtl();
                    },
                    set(newValue) {
                        that._rtl(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'sizeMode', {
                    get() {
                        return that._sizeMode();
                    },
                    set(newValue) {
                        that._sizeMode(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'scrollBarSize', {
                    get() {
                        return that._scrollBarSize();
                    },
                    set(newValue) {
                        that._scrollBarSize(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'theme', {
                    get() {
                        return that._theme();
                    },
                    set(newValue) {
                        that._theme(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'width', {
                    get() {
                        return that._width();
                    },
                    set(newValue) {
                        that._width(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __wireEvents__: function () {
                const that = this;

            }
        }
    }
</script>
