// jqwidgets-react/react_jqxbulletchart.js
/*
jQWidgets v7.0.0 (2019-Jan)
Copyright (c) 2011-2019 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxdata.js';
import '../jqwidgets/jqxtooltip.js';
import '../jqwidgets/jqxbulletchart.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxBulletChart extends React.Component {
    constructor(props) {
        super(props);
        const widgetId = 'jqxBulletChart' + JQXLite.generateID();
        this.componentSelector = '#' + widgetId;
        this.state = { id: widgetId };
    };
    componentDidMount() {
        const options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        const properties = ['animationDuration','barSize','description','disabled','height','labelsFormat','labelsFormatFunction','orientation','pointer','rtl','ranges','showTooltip','target','ticks','title','tooltipFormatFunction','width'];
        let options = {};
        for(let item in this.props) {
            if(item === 'settings') {
                for(let itemTwo in this.props[item]) {
                    options[itemTwo] = this.props[item][itemTwo];
                }
            } else {
                if(properties.indexOf(item) !== -1) {
                      options[item] = this.props[item];
                }
            }
        }
        return options;
    };
    createComponent(options) {
        if(!this.style) {
            for (let style in this.props.style) {
                JQXLite(this.componentSelector).css(style, this.props.style[style]);
            }
        }
        if(this.props.className !== undefined) {
            const classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
            JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxBulletChart(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxBulletChart('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxBulletChart(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    animationDuration(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('animationDuration', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('animationDuration');
        }
    };
    barSize(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('barSize', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('barSize');
        }
    };
    description(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('description', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('description');
        }
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('disabled');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('height');
        }
    };
    labelsFormat(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('labelsFormat', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('labelsFormat');
        }
    };
    labelsFormatFunction(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('labelsFormatFunction', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('labelsFormatFunction');
        }
    };
    orientation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('orientation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('orientation');
        }
    };
    pointer(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('pointer', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('pointer');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('rtl');
        }
    };
    ranges(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('ranges', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('ranges');
        }
    };
    showTooltip(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('showTooltip', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('showTooltip');
        }
    };
    target(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('target', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('target');
        }
    };
    ticks(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('ticks', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('ticks');
        }
    };
    title(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('title', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('title');
        }
    };
    tooltipFormatFunction(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('tooltipFormatFunction', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('tooltipFormatFunction');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('width');
        }
    };
    destroy() {
        JQXLite(this.componentSelector).jqxBulletChart('destroy');  
    };
    performRender() {
        JQXLite(this.componentSelector).jqxBulletChart('render');
    };
    refresh() {
        JQXLite(this.componentSelector).jqxBulletChart('refresh');  
    };
    val(value) {
        if (value !== undefined) {
            JQXLite(this.componentSelector).jqxBulletChart('val',  value)
        } else {
            return JQXLite(this.componentSelector).jqxBulletChart('val');
        }
    };

    render() {
        return (
            <div id={this.state.id}>{this.props.value}{this.props.children}</div>
        )
    };
};

// jqwidgets-vue/vue_jqxbulletchart.vue
/*
jQWidgets v7.0.0 (2019-Jan)
Copyright (c) 2011-2019 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxdata.js';
    import '../jqwidgets/jqxtooltip.js';
    import '../jqwidgets/jqxbulletchart.js';

    export default {
        props: {
            animationDuration: Number,
            barSize: [String, Number],
            description: String,
            disabled: Boolean,
            height: [Number, String],
            labelsFormat: String,
            labelsFormatFunction: Function,
            orientation: String,
            pointer: Object,
            rtl: Boolean,
            ranges: Array,
            showTooltip: Boolean,
            target: Object,
            ticks: Object,
            title: String,
            tooltipFormatFunction: Function,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxBulletChart' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxBulletChart(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxBulletChart(usedProps[i]);
                }
                return resultToReturn;
            },
            destroy: function() {
                JQXLite(this.componentSelector).jqxBulletChart('destroy');  
            },
            render: function() {
                JQXLite(this.componentSelector).jqxBulletChart('render');  
            },
            refresh: function() {
                JQXLite(this.componentSelector).jqxBulletChart('refresh');  
            },
            val: function(value) {
                if (value !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('val',  value)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('val');
                }
            },
            _animationDuration: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('animationDuration', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('animationDuration');
                }
            },
            _barSize: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('barSize', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('barSize');
                }
            },
            _description: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('description', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('description');
                }
            },
            _disabled: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('disabled', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('disabled');
                }
            },
            _height: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('height', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('height');
                }
            },
            _labelsFormat: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('labelsFormat', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('labelsFormat');
                }
            },
            _labelsFormatFunction: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('labelsFormatFunction', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('labelsFormatFunction');
                }
            },
            _orientation: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('orientation', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('orientation');
                }
            },
            _pointer: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('pointer', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('pointer');
                }
            },
            _rtl: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('rtl', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('rtl');
                }
            },
            _ranges: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('ranges', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('ranges');
                }
            },
            _showTooltip: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('showTooltip', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('showTooltip');
                }
            },
            _target: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('target', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('target');
                }
            },
            _ticks: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('ticks', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('ticks');
                }
            },
            _title: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('title', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('title');
                }
            },
            _tooltipFormatFunction: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('tooltipFormatFunction', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('tooltipFormatFunction');
                }
            },
            _width: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxBulletChart('width', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxBulletChart('width');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxBulletChart(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['animationDuration','barSize','description','disabled','height','labelsFormat','labelsFormatFunction','orientation','pointer','rtl','ranges','showTooltip','target','ticks','title','tooltipFormatFunction','width'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'animationDuration', {
                    get() {
                        return that._animationDuration();
                    },
                    set(newValue) {
                        that._animationDuration(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'barSize', {
                    get() {
                        return that._barSize();
                    },
                    set(newValue) {
                        that._barSize(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'description', {
                    get() {
                        return that._description();
                    },
                    set(newValue) {
                        that._description(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'disabled', {
                    get() {
                        return that._disabled();
                    },
                    set(newValue) {
                        that._disabled(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'height', {
                    get() {
                        return that._height();
                    },
                    set(newValue) {
                        that._height(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'labelsFormat', {
                    get() {
                        return that._labelsFormat();
                    },
                    set(newValue) {
                        that._labelsFormat(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'labelsFormatFunction', {
                    get() {
                        return that._labelsFormatFunction();
                    },
                    set(newValue) {
                        that._labelsFormatFunction(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'orientation', {
                    get() {
                        return that._orientation();
                    },
                    set(newValue) {
                        that._orientation(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'pointer', {
                    get() {
                        return that._pointer();
                    },
                    set(newValue) {
                        that._pointer(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'rtl', {
                    get() {
                        return that._rtl();
                    },
                    set(newValue) {
                        that._rtl(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'ranges', {
                    get() {
                        return that._ranges();
                    },
                    set(newValue) {
                        that._ranges(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'showTooltip', {
                    get() {
                        return that._showTooltip();
                    },
                    set(newValue) {
                        that._showTooltip(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'target', {
                    get() {
                        return that._target();
                    },
                    set(newValue) {
                        that._target(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'ticks', {
                    get() {
                        return that._ticks();
                    },
                    set(newValue) {
                        that._ticks(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'title', {
                    get() {
                        return that._title();
                    },
                    set(newValue) {
                        that._title(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'tooltipFormatFunction', {
                    get() {
                        return that._tooltipFormatFunction();
                    },
                    set(newValue) {
                        that._tooltipFormatFunction(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'width', {
                    get() {
                        return that._width();
                    },
                    set(newValue) {
                        that._width(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __wireEvents__: function () {
                const that = this;

                JQXLite(this.componentSelector).on('change', function (event) { that.$emit('change', event); });
            }
        }
    }
</script>
