// jqwidgets-react/react_jqxresponsivepanel.js
/*
jQWidgets v6.0.5 (2018-July)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxresponsivepanel.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxResponsivePanel extends React.Component {
    componentDidMount() {
        let options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        let properties = ['animationDirection','animationHideDelay','animationShowDelay','animationType','autoClose','collapseBreakpoint','collapseWidth','height','initContent','theme','toggleButton','toggleButtonSize','width'];
        let options = {};
        for(let item in this.props) {
              if(item === 'settings') {
                  for(let itemTwo in this.props[item]) {
                      options[itemTwo] = this.props[item][itemTwo];
                      }
                } else {
                      if(properties.indexOf(item) !== -1) {
                        options[item] = this.props[item];
                      }
                }
          }
          return options;
      };
    createComponent(options) {
        if(!this.style) {
              for (let style in this.props.style) {
                  JQXLite(this.componentSelector).css(style, this.props.style[style]);
              }
        }
        if(this.props.className !== undefined) {
            let classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
              JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxResponsivePanel(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxResponsivePanel('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxResponsivePanel(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    animationDirection(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('animationDirection', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('animationDirection');
        }
    };
    animationHideDelay(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('animationHideDelay', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('animationHideDelay');
        }
    };
    animationShowDelay(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('animationShowDelay', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('animationShowDelay');
        }
    };
    animationType(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('animationType', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('animationType');
        }
    };
    autoClose(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('autoClose', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('autoClose');
        }
    };
    collapseBreakpoint(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('collapseBreakpoint', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('collapseBreakpoint');
        }
    };
    collapseWidth(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('collapseWidth', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('collapseWidth');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('height');
        }
    };
    initContent(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('initContent', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('initContent');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('theme');
        }
    };
    toggleButton(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('toggleButton', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('toggleButton');
        }
    };
    toggleButtonSize(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('toggleButtonSize', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('toggleButtonSize');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('width');
        }
    };
    close() {
        JQXLite(this.componentSelector).jqxResponsivePanel('close');  
    };
    destroy() {
        JQXLite(this.componentSelector).jqxResponsivePanel('destroy');  
    };
    isCollapsed() {
        return JQXLite(this.componentSelector).jqxResponsivePanel('isCollapsed');  
    };
    isOpened() {
        return JQXLite(this.componentSelector).jqxResponsivePanel('isOpened');  
    };
    open() {
        JQXLite(this.componentSelector).jqxResponsivePanel('open');  
    };
    refresh() {
        JQXLite(this.componentSelector).jqxResponsivePanel('refresh');  
    };
    performRender() {
        JQXLite(this.componentSelector).jqxResponsivePanel('render');
    };
    render() {
        let id = 'jqxResponsivePanel' + JQXLite.generateID();
        this.componentSelector = '#' + id;
        return (
            <div id={id}>{this.props.value}{this.props.children}</div>
        )
    };
};

// jqwidgets-vue/vue_jqxresponsivepanel.vue
/*
jQWidgets v8.1.4 (2019-July)
Copyright (c) 2011-2019 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxresponsivepanel.js';

    export default {
        props: {
            animationDirection: String,
            animationHideDelay: [String, Number],
            animationShowDelay: Number,
            animationType: String,
            autoClose: Boolean,
            collapseBreakpoint: Number,
            collapseWidth: Number,
            height: [Number, String],
            initContent: Function,
            theme: String,
            toggleButton: String,
            toggleButtonSize: Number,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxResponsivePanel' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxResponsivePanel(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxResponsivePanel(usedProps[i]);
                }
                return resultToReturn;
            },
            close: function() {
                JQXLite(this.componentSelector).jqxResponsivePanel('close');  
            },
            destroy: function() {
                JQXLite(this.componentSelector).jqxResponsivePanel('destroy');  
            },
            isCollapsed: function() {
                return JQXLite(this.componentSelector).jqxResponsivePanel('isCollapsed');  
            },
            isOpened: function() {
                return JQXLite(this.componentSelector).jqxResponsivePanel('isOpened');  
            },
            open: function() {
                JQXLite(this.componentSelector).jqxResponsivePanel('open');  
            },
            refresh: function() {
                JQXLite(this.componentSelector).jqxResponsivePanel('refresh');  
            },
            render: function() {
                JQXLite(this.componentSelector).jqxResponsivePanel('render');  
            },
            _animationDirection: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxResponsivePanel('animationDirection', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxResponsivePanel('animationDirection');
                }
            },
            _animationHideDelay: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxResponsivePanel('animationHideDelay', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxResponsivePanel('animationHideDelay');
                }
            },
            _animationShowDelay: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxResponsivePanel('animationShowDelay', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxResponsivePanel('animationShowDelay');
                }
            },
            _animationType: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxResponsivePanel('animationType', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxResponsivePanel('animationType');
                }
            },
            _autoClose: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxResponsivePanel('autoClose', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxResponsivePanel('autoClose');
                }
            },
            _collapseBreakpoint: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxResponsivePanel('collapseBreakpoint', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxResponsivePanel('collapseBreakpoint');
                }
            },
            _collapseWidth: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxResponsivePanel('collapseWidth', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxResponsivePanel('collapseWidth');
                }
            },
            _height: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxResponsivePanel('height', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxResponsivePanel('height');
                }
            },
            _initContent: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxResponsivePanel('initContent', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxResponsivePanel('initContent');
                }
            },
            _theme: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxResponsivePanel('theme', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxResponsivePanel('theme');
                }
            },
            _toggleButton: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxResponsivePanel('toggleButton', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxResponsivePanel('toggleButton');
                }
            },
            _toggleButtonSize: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxResponsivePanel('toggleButtonSize', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxResponsivePanel('toggleButtonSize');
                }
            },
            _width: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxResponsivePanel('width', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxResponsivePanel('width');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxResponsivePanel(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['animationDirection','animationHideDelay','animationShowDelay','animationType','autoClose','collapseBreakpoint','collapseWidth','height','initContent','theme','toggleButton','toggleButtonSize','width'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'animationDirection', {
                    get: function() {
                        return that._animationDirection();
                    },
                    set: function(newValue) {
                        that._animationDirection(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'animationHideDelay', {
                    get: function() {
                        return that._animationHideDelay();
                    },
                    set: function(newValue) {
                        that._animationHideDelay(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'animationShowDelay', {
                    get: function() {
                        return that._animationShowDelay();
                    },
                    set: function(newValue) {
                        that._animationShowDelay(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'animationType', {
                    get: function() {
                        return that._animationType();
                    },
                    set: function(newValue) {
                        that._animationType(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'autoClose', {
                    get: function() {
                        return that._autoClose();
                    },
                    set: function(newValue) {
                        that._autoClose(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'collapseBreakpoint', {
                    get: function() {
                        return that._collapseBreakpoint();
                    },
                    set: function(newValue) {
                        that._collapseBreakpoint(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'collapseWidth', {
                    get: function() {
                        return that._collapseWidth();
                    },
                    set: function(newValue) {
                        that._collapseWidth(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'height', {
                    get: function() {
                        return that._height();
                    },
                    set: function(newValue) {
                        that._height(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'initContent', {
                    get: function() {
                        return that._initContent();
                    },
                    set: function(newValue) {
                        that._initContent(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'theme', {
                    get: function() {
                        return that._theme();
                    },
                    set: function(newValue) {
                        that._theme(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'toggleButton', {
                    get: function() {
                        return that._toggleButton();
                    },
                    set: function(newValue) {
                        that._toggleButton(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'toggleButtonSize', {
                    get: function() {
                        return that._toggleButtonSize();
                    },
                    set: function(newValue) {
                        that._toggleButtonSize(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'width', {
                    get: function() {
                        return that._width();
                    },
                    set: function(newValue) {
                        that._width(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __wireEvents__: function () {
                const that = this;

                JQXLite(this.componentSelector).on('close', function (event) { that.$emit('close', event); });
                JQXLite(this.componentSelector).on('collapse', function (event) { that.$emit('collapse', event); });
                JQXLite(this.componentSelector).on('expand', function (event) { that.$emit('expand', event); });
                JQXLite(this.componentSelector).on('open', function (event) { that.$emit('open', event); });
            }
        }
    }
</script>
