// jqwidgets-react/react_jqxcomplexinput.js
/*
jQWidgets v6.0.5 (2018-July)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxbuttons.js';
import '../jqwidgets/jqxcomplexinput.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxComplexInput extends React.Component {
    componentDidMount() {
        let options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        let properties = ['decimalNotation','disabled','height','placeHolder','roundedCorners','rtl','spinButtons','spinButtonsStep','template','theme','value','width'];
        let options = {};
        for(let item in this.props) {
              if(item === 'settings') {
                  for(let itemTwo in this.props[item]) {
                      options[itemTwo] = this.props[item][itemTwo];
                      }
                } else {
                      if(properties.indexOf(item) !== -1) {
                        options[item] = this.props[item];
                      }
                }
          }
          return options;
      };
    createComponent(options) {
        if(!this.style) {
              for (let style in this.props.style) {
                  JQXLite(this.componentSelector).css(style, this.props.style[style]);
              }
        }
        if(this.props.className !== undefined) {
            let classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
              JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxComplexInput(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxComplexInput('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxComplexInput(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    decimalNotation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxComplexInput('decimalNotation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxComplexInput('decimalNotation');
        }
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxComplexInput('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxComplexInput('disabled');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxComplexInput('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxComplexInput('height');
        }
    };
    placeHolder(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxComplexInput('placeHolder', arg)
        } else {
            return JQXLite(this.componentSelector).jqxComplexInput('placeHolder');
        }
    };
    roundedCorners(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxComplexInput('roundedCorners', arg)
        } else {
            return JQXLite(this.componentSelector).jqxComplexInput('roundedCorners');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxComplexInput('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxComplexInput('rtl');
        }
    };
    spinButtons(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxComplexInput('spinButtons', arg)
        } else {
            return JQXLite(this.componentSelector).jqxComplexInput('spinButtons');
        }
    };
    spinButtonsStep(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxComplexInput('spinButtonsStep', arg)
        } else {
            return JQXLite(this.componentSelector).jqxComplexInput('spinButtonsStep');
        }
    };
    template(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxComplexInput('template', arg)
        } else {
            return JQXLite(this.componentSelector).jqxComplexInput('template');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxComplexInput('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxComplexInput('theme');
        }
    };
    value(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxComplexInput('value', arg)
        } else {
            return JQXLite(this.componentSelector).jqxComplexInput('value');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxComplexInput('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxComplexInput('width');
        }
    };
    destroy() {
        JQXLite(this.componentSelector).jqxComplexInput('destroy');  
    };
    getReal(complexnumber) {
        return JQXLite(this.componentSelector).jqxComplexInput('getReal', complexnumber);  
    };
    getImaginary(complexnumber) {
        return JQXLite(this.componentSelector).jqxComplexInput('getImaginary', complexnumber);  
    };
    getDecimalNotation(part, type) {
        return JQXLite(this.componentSelector).jqxComplexInput('getDecimalNotation', part, type);  
    };
    performRender() {
        JQXLite(this.componentSelector).jqxComplexInput('render');
    };
    refresh() {
        JQXLite(this.componentSelector).jqxComplexInput('refresh');  
    };
    val(value) {
        if (value !== undefined) {
            JQXLite(this.componentSelector).jqxComplexInput('val',  value)
        } else {
            return JQXLite(this.componentSelector).jqxComplexInput('val');
        }
    };

    render() {
        let id = 'jqxComplexInput' + JQXLite.generateID();
        this.componentSelector = '#' + id;
        return (
            <div id={id}>
                  <input type='text'></input>
                  <div></div>
            </div>
        )
    };
};

// jqwidgets-vue/vue_jqxcomplexinput.vue
/*
jQWidgets v8.0.0 (2019-May)
Copyright (c) 2011-2019 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

<template>
    <div v-bind:id="id">
        <input type="text" />
        <div></div>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxcomplexinput.js';

    export default {
        props: {
            decimalNotation: String,
            disabled: Boolean,
            height: [Number, String],
            placeHolder: String,
            roundedCorners: Boolean,
            rtl: Boolean,
            spinButtons: Boolean,
            spinButtonsStep: Number,
            template: String,
            theme: String,
            value: String,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxComplexInput' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxComplexInput(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxComplexInput(usedProps[i]);
                }
                return resultToReturn;
            },
            destroy: function() {
                JQXLite(this.componentSelector).jqxComplexInput('destroy');  
            },
            getDecimalNotation: function(part, decimalNotation) {
                return JQXLite(this.componentSelector).jqxComplexInput('getDecimalNotation', part, decimalNotation);  
            },
            getReal: function(complexnumber) {
                return JQXLite(this.componentSelector).jqxComplexInput('getReal', complexnumber);  
            },
            getImaginary: function(complexnumber) {
                return JQXLite(this.componentSelector).jqxComplexInput('getImaginary', complexnumber);  
            },
            render: function() {
                JQXLite(this.componentSelector).jqxComplexInput('render');  
            },
            refresh: function() {
                JQXLite(this.componentSelector).jqxComplexInput('refresh');  
            },
            val: function(value) {
                if (value !== undefined) {
                    JQXLite(this.componentSelector).jqxComplexInput('val',  value)
                } else {
                    return JQXLite(this.componentSelector).jqxComplexInput('val');
                }
            },
            _decimalNotation: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxComplexInput('decimalNotation', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxComplexInput('decimalNotation');
                }
            },
            _disabled: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxComplexInput('disabled', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxComplexInput('disabled');
                }
            },
            _height: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxComplexInput('height', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxComplexInput('height');
                }
            },
            _placeHolder: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxComplexInput('placeHolder', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxComplexInput('placeHolder');
                }
            },
            _roundedCorners: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxComplexInput('roundedCorners', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxComplexInput('roundedCorners');
                }
            },
            _rtl: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxComplexInput('rtl', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxComplexInput('rtl');
                }
            },
            _spinButtons: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxComplexInput('spinButtons', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxComplexInput('spinButtons');
                }
            },
            _spinButtonsStep: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxComplexInput('spinButtonsStep', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxComplexInput('spinButtonsStep');
                }
            },
            _template: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxComplexInput('template', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxComplexInput('template');
                }
            },
            _theme: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxComplexInput('theme', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxComplexInput('theme');
                }
            },
            _value: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxComplexInput('value', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxComplexInput('value');
                }
            },
            _width: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxComplexInput('width', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxComplexInput('width');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxComplexInput(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['decimalNotation','disabled','height','placeHolder','roundedCorners','rtl','spinButtons','spinButtonsStep','template','theme','value','width'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'decimalNotation', {
                    get: function() {
                        return that._decimalNotation();
                    },
                    set: function(newValue) {
                        that._decimalNotation(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'disabled', {
                    get: function() {
                        return that._disabled();
                    },
                    set: function(newValue) {
                        that._disabled(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'height', {
                    get: function() {
                        return that._height();
                    },
                    set: function(newValue) {
                        that._height(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'placeHolder', {
                    get: function() {
                        return that._placeHolder();
                    },
                    set: function(newValue) {
                        that._placeHolder(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'roundedCorners', {
                    get: function() {
                        return that._roundedCorners();
                    },
                    set: function(newValue) {
                        that._roundedCorners(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'rtl', {
                    get: function() {
                        return that._rtl();
                    },
                    set: function(newValue) {
                        that._rtl(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'spinButtons', {
                    get: function() {
                        return that._spinButtons();
                    },
                    set: function(newValue) {
                        that._spinButtons(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'spinButtonsStep', {
                    get: function() {
                        return that._spinButtonsStep();
                    },
                    set: function(newValue) {
                        that._spinButtonsStep(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'template', {
                    get: function() {
                        return that._template();
                    },
                    set: function(newValue) {
                        that._template(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'theme', {
                    get: function() {
                        return that._theme();
                    },
                    set: function(newValue) {
                        that._theme(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'value', {
                    get: function() {
                        return that._value();
                    },
                    set: function(newValue) {
                        that._value(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'width', {
                    get: function() {
                        return that._width();
                    },
                    set: function(newValue) {
                        that._width(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __twoWayDataBinding__: function () {
                const value = JQXLite(this.componentSelector).jqxComplexInput('val');
                this.$emit('input', value);
            },
            __wireEvents__: function () {
                const that = this;

                JQXLite(this.componentSelector).on('change', function (event) { that.$emit('change', event); that.__twoWayDataBinding__(); });
            }
        }
    }
</script>
