// jqwidgets-react/react_jqxlayout.js
/*
jQWidgets v6.2.0 (2018-Dec)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxbuttons.js';
import '../jqwidgets/jqxribbon.js';
import '../jqwidgets/jqxlayout.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxLayout extends React.Component {
    constructor(props) {
        super(props);
        const widgetId = 'jqxLayout' + JQXLite.generateID();
        this.componentSelector = '#' + widgetId;
        this.state = { id: widgetId };
    };
    componentDidMount() {
        const options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        const properties = ['contextMenu','height','layout','minGroupHeight','minGroupWidth','resizable','rtl','theme','width'];
        let options = {};
        for(let item in this.props) {
            if(item === 'settings') {
                for(let itemTwo in this.props[item]) {
                    options[itemTwo] = this.props[item][itemTwo];
                }
            } else {
                if(properties.indexOf(item) !== -1) {
                      options[item] = this.props[item];
                }
            }
        }
        return options;
    };
    createComponent(options) {
        if(!this.style) {
            for (let style in this.props.style) {
                JQXLite(this.componentSelector).css(style, this.props.style[style]);
            }
        }
        if(this.props.className !== undefined) {
            const classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
            JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxLayout(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxLayout('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxLayout(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    contextMenu(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxLayout('contextMenu', arg)
        } else {
            return JQXLite(this.componentSelector).jqxLayout('contextMenu');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxLayout('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxLayout('height');
        }
    };
    layout(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxLayout('layout', arg)
        } else {
            return JQXLite(this.componentSelector).jqxLayout('layout');
        }
    };
    minGroupHeight(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxLayout('minGroupHeight', arg)
        } else {
            return JQXLite(this.componentSelector).jqxLayout('minGroupHeight');
        }
    };
    minGroupWidth(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxLayout('minGroupWidth', arg)
        } else {
            return JQXLite(this.componentSelector).jqxLayout('minGroupWidth');
        }
    };
    resizable(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxLayout('resizable', arg)
        } else {
            return JQXLite(this.componentSelector).jqxLayout('resizable');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxLayout('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxLayout('rtl');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxLayout('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxLayout('theme');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxLayout('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxLayout('width');
        }
    };
    destroy() {
        JQXLite(this.componentSelector).jqxLayout('destroy');  
    };
    loadLayout(Layout) {
        JQXLite(this.componentSelector).jqxLayout('loadLayout', Layout);  
    };
    refresh() {
        JQXLite(this.componentSelector).jqxLayout('refresh');  
    };
    performRender() {
        JQXLite(this.componentSelector).jqxLayout('render');
    };
    saveLayout() {
        return JQXLite(this.componentSelector).jqxLayout('saveLayout');  
    };
    render() {
        return (
            <div id={this.state.id}>{this.props.value}{this.props.children}</div>
        )
    };
};

// jqwidgets-vue/vue_jqxlayout.vue
/*
jQWidgets v6.2.0 (2018-Dec)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxribbon.js';
    import '../jqwidgets/jqxmenu.js';
    import '../jqwidgets/jqxlayout.js';

    export default {
        props: {
            contextMenu: Boolean,
            height: [String, Number],
            layout: Array,
            minGroupHeight: Number,
            minGroupWidth: Number,
            resizable: Boolean,
            rtl: Boolean,
            theme: String,
            width: [String, Number],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxLayout' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxLayout(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxLayout(usedProps[i]);
                }
                return resultToReturn;
            },
            destroy: function() {
                JQXLite(this.componentSelector).jqxLayout('destroy');  
            },
            loadLayout: function(Layout) {
                JQXLite(this.componentSelector).jqxLayout('loadLayout', Layout);  
            },
            refresh: function() {
                JQXLite(this.componentSelector).jqxLayout('refresh');  
            },
            render: function() {
                JQXLite(this.componentSelector).jqxLayout('render');  
            },
            saveLayout: function() {
                return JQXLite(this.componentSelector).jqxLayout('saveLayout');  
            },
            _contextMenu: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxLayout('contextMenu', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxLayout('contextMenu');
                }
            },
            _height: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxLayout('height', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxLayout('height');
                }
            },
            _layout: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxLayout('layout', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxLayout('layout');
                }
            },
            _minGroupHeight: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxLayout('minGroupHeight', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxLayout('minGroupHeight');
                }
            },
            _minGroupWidth: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxLayout('minGroupWidth', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxLayout('minGroupWidth');
                }
            },
            _resizable: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxLayout('resizable', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxLayout('resizable');
                }
            },
            _rtl: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxLayout('rtl', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxLayout('rtl');
                }
            },
            _theme: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxLayout('theme', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxLayout('theme');
                }
            },
            _width: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxLayout('width', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxLayout('width');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxLayout(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['contextMenu','height','layout','minGroupHeight','minGroupWidth','resizable','rtl','theme','width'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'contextMenu', {
                    get() {
                        return that._contextMenu();
                    },
                    set(newValue) {
                        that._contextMenu(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'height', {
                    get() {
                        return that._height();
                    },
                    set(newValue) {
                        that._height(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'layout', {
                    get() {
                        return that._layout();
                    },
                    set(newValue) {
                        that._layout(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'minGroupHeight', {
                    get() {
                        return that._minGroupHeight();
                    },
                    set(newValue) {
                        that._minGroupHeight(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'minGroupWidth', {
                    get() {
                        return that._minGroupWidth();
                    },
                    set(newValue) {
                        that._minGroupWidth(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'resizable', {
                    get() {
                        return that._resizable();
                    },
                    set(newValue) {
                        that._resizable(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'rtl', {
                    get() {
                        return that._rtl();
                    },
                    set(newValue) {
                        that._rtl(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'theme', {
                    get() {
                        return that._theme();
                    },
                    set(newValue) {
                        that._theme(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'width', {
                    get() {
                        return that._width();
                    },
                    set(newValue) {
                        that._width(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __wireEvents__: function () {
                const that = this;

                JQXLite(this.componentSelector).on('pin', function (event) { that.$emit('pin', event); });
                JQXLite(this.componentSelector).on('resize', function (event) { that.$emit('resize', event); });
                JQXLite(this.componentSelector).on('unpin', function (event) { that.$emit('unpin', event); });
            }
        }
    }
</script>
