// jqwidgets-react/react_jqxformattedinput.js
/*
jQWidgets v7.0.0 (2019-Jan)
Copyright (c) 2011-2019 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxformattedinput.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxFormattedInput extends React.Component {
    constructor(props) {
        super(props);
        const widgetId = 'jqxFormattedInput' + JQXLite.generateID();
        this.componentSelector = '#' + widgetId;
        this.state = { id: widgetId };
    };
    componentDidMount() {
        const options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        const properties = ['disabled','decimalNotation','dropDown','dropDownWidth','height','min','max','placeHolder','popupZIndex','roundedCorners','rtl','radix','spinButtons','spinButtonsStep','template','theme','upperCase','value','width'];
        let options = {};
        for(let item in this.props) {
            if(item === 'settings') {
                for(let itemTwo in this.props[item]) {
                    options[itemTwo] = this.props[item][itemTwo];
                }
            } else {
                if(properties.indexOf(item) !== -1) {
                      options[item] = this.props[item];
                }
            }
        }
        return options;
    };
    createComponent(options) {
        if(!this.style) {
            for (let style in this.props.style) {
                JQXLite(this.componentSelector).css(style, this.props.style[style]);
            }
        }
        if(this.props.className !== undefined) {
            const classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
            JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxFormattedInput(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxFormattedInput('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxFormattedInput(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('disabled');
        }
    };
    decimalNotation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('decimalNotation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('decimalNotation');
        }
    };
    dropDown(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('dropDown', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('dropDown');
        }
    };
    dropDownWidth(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('dropDownWidth', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('dropDownWidth');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('height');
        }
    };
    min(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('min', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('min');
        }
    };
    max(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('max', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('max');
        }
    };
    placeHolder(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('placeHolder', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('placeHolder');
        }
    };
    popupZIndex(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('popupZIndex', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('popupZIndex');
        }
    };
    roundedCorners(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('roundedCorners', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('roundedCorners');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('rtl');
        }
    };
    radix(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('radix', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('radix');
        }
    };
    spinButtons(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('spinButtons', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('spinButtons');
        }
    };
    spinButtonsStep(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('spinButtonsStep', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('spinButtonsStep');
        }
    };
    template(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('template', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('template');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('theme');
        }
    };
    upperCase(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('upperCase', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('upperCase');
        }
    };
    value(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('value', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('value');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxFormattedInput('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('width');
        }
    };
    close() {
        JQXLite(this.componentSelector).jqxFormattedInput('close');  
    };
    destroy() {
        JQXLite(this.componentSelector).jqxFormattedInput('destroy');  
    };
    focus() {
        JQXLite(this.componentSelector).jqxFormattedInput('focus');  
    };
    open() {
        JQXLite(this.componentSelector).jqxFormattedInput('open');  
    };
    performRender() {
        JQXLite(this.componentSelector).jqxFormattedInput('render');
    };
    refresh() {
        JQXLite(this.componentSelector).jqxFormattedInput('refresh');  
    };
    selectAll() {
        JQXLite(this.componentSelector).jqxFormattedInput('selectAll');  
    };
    selectFirst() {
        JQXLite(this.componentSelector).jqxFormattedInput('selectFirst');  
    };
    selectLast() {
        JQXLite(this.componentSelector).jqxFormattedInput('selectLast');  
    };
    val(value) {
        if (value !== undefined) {
            if(typeof value === 'string') {                return JQXLite(this.componentSelector).jqxFormattedInput('val',  value)
            } else {
                JQXLite(this.componentSelector).jqxFormattedInput('val',  value)
        }
            JQXLite(this.componentSelector).jqxFormattedInput('val',  value)
        } else {
            return JQXLite(this.componentSelector).jqxFormattedInput('val');
        }
    };

    render() {
        let spinButtons = this.props.spinButtons;
        if ((!spinButtons) && (spinButtons !== false)) spinButtons = true;
        return (
            <div>
                {
                    this.props.rtl ?
                        (
                            <div id={this.state.id}>
                                  {spinButtons ? <div></div> : null}
                                  {this.props.dropDown ? <div></div> : null}
                                  <input type='text'></input>
                            </div>
                        ) : (
                            <div id={this.state.id}>
                                  <input type='text'></input>
                                      {spinButtons ? <div></div> : null}
                                      {this.props.dropDown ? <div></div> : null}
                            </div>
                        )
                }
            </div>
        )
    };
};

// jqwidgets-vue/vue_jqxformattedinput.vue
/*
jQWidgets v7.0.0 (2019-Jan)
Copyright (c) 2011-2019 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

<template>
    <div v-bind:id="id" v-if="rtl">
        <div v-if="spinButtons"></div>
        <div v-if="dropDown"></div>
        <input type='text' />
    </div>
     <div v-bind:id="id" v-else>
        <input type='text' />
        <div v-if="spinButtons"></div>
        <div v-if="dropDown"></div>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxformattedinput.js';

    export default {
        props: {
            disabled: Boolean,
            decimalNotation: String,
            dropDown: Boolean,
            dropDownWidth: Number,
            height: [Number, String],
            min: [Number, String],
            max: [Number, String],
            placeHolder: String,
            popupZIndex: Number,
            roundedCorners: Boolean,
            rtl: Boolean,
            radix: [Number, String],
            spinButtons: Boolean,
            spinButtonsStep: Number,
            template: String,
            theme: String,
            upperCase: Boolean,
            value: [Number, String],
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxFormattedInput' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxFormattedInput(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxFormattedInput(usedProps[i]);
                }
                return resultToReturn;
            },
            close: function() {
                JQXLite(this.componentSelector).jqxFormattedInput('close');  
            },
            destroy: function() {
                JQXLite(this.componentSelector).jqxFormattedInput('destroy');  
            },
            focus: function() {
                JQXLite(this.componentSelector).jqxFormattedInput('focus');  
            },
            open: function() {
                JQXLite(this.componentSelector).jqxFormattedInput('open');  
            },
            render: function() {
                JQXLite(this.componentSelector).jqxFormattedInput('render');  
            },
            refresh: function() {
                JQXLite(this.componentSelector).jqxFormattedInput('refresh');  
            },
            selectAll: function() {
                JQXLite(this.componentSelector).jqxFormattedInput('selectAll');  
            },
            selectFirst: function() {
                JQXLite(this.componentSelector).jqxFormattedInput('selectFirst');  
            },
            selectLast: function() {
                JQXLite(this.componentSelector).jqxFormattedInput('selectLast');  
            },
            val: function(value) {
                if (value !== undefined) {
                    if(typeof value === 'string') {                        return JQXLite(this.componentSelector).jqxFormattedInput('val',  value)
                    } else {
                        JQXLite(this.componentSelector).jqxFormattedInput('val',  value)
                }
                    JQXLite(this.componentSelector).jqxFormattedInput('val',  value)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('val');
                }
            },
            _disabled: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('disabled', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('disabled');
                }
            },
            _decimalNotation: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('decimalNotation', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('decimalNotation');
                }
            },
            _dropDown: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('dropDown', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('dropDown');
                }
            },
            _dropDownWidth: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('dropDownWidth', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('dropDownWidth');
                }
            },
            _height: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('height', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('height');
                }
            },
            _min: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('min', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('min');
                }
            },
            _max: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('max', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('max');
                }
            },
            _placeHolder: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('placeHolder', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('placeHolder');
                }
            },
            _popupZIndex: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('popupZIndex', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('popupZIndex');
                }
            },
            _roundedCorners: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('roundedCorners', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('roundedCorners');
                }
            },
            _rtl: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('rtl', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('rtl');
                }
            },
            _radix: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('radix', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('radix');
                }
            },
            _spinButtons: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('spinButtons', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('spinButtons');
                }
            },
            _spinButtonsStep: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('spinButtonsStep', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('spinButtonsStep');
                }
            },
            _template: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('template', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('template');
                }
            },
            _theme: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('theme', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('theme');
                }
            },
            _upperCase: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('upperCase', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('upperCase');
                }
            },
            _value: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('value', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('value');
                }
            },
            _width: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxFormattedInput('width', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxFormattedInput('width');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxFormattedInput(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['disabled','decimalNotation','dropDown','dropDownWidth','height','min','max','placeHolder','popupZIndex','roundedCorners','rtl','radix','spinButtons','spinButtonsStep','template','theme','upperCase','value','width'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'disabled', {
                    get() {
                        return that._disabled();
                    },
                    set(newValue) {
                        that._disabled(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'decimalNotation', {
                    get() {
                        return that._decimalNotation();
                    },
                    set(newValue) {
                        that._decimalNotation(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'dropDown', {
                    get() {
                        return that._dropDown();
                    },
                    set(newValue) {
                        that._dropDown(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'dropDownWidth', {
                    get() {
                        return that._dropDownWidth();
                    },
                    set(newValue) {
                        that._dropDownWidth(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'height', {
                    get() {
                        return that._height();
                    },
                    set(newValue) {
                        that._height(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'min', {
                    get() {
                        return that._min();
                    },
                    set(newValue) {
                        that._min(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'max', {
                    get() {
                        return that._max();
                    },
                    set(newValue) {
                        that._max(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'placeHolder', {
                    get() {
                        return that._placeHolder();
                    },
                    set(newValue) {
                        that._placeHolder(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'popupZIndex', {
                    get() {
                        return that._popupZIndex();
                    },
                    set(newValue) {
                        that._popupZIndex(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'roundedCorners', {
                    get() {
                        return that._roundedCorners();
                    },
                    set(newValue) {
                        that._roundedCorners(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'rtl', {
                    get() {
                        return that._rtl();
                    },
                    set(newValue) {
                        that._rtl(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'radix', {
                    get() {
                        return that._radix();
                    },
                    set(newValue) {
                        that._radix(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'spinButtons', {
                    get() {
                        return that._spinButtons();
                    },
                    set(newValue) {
                        that._spinButtons(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'spinButtonsStep', {
                    get() {
                        return that._spinButtonsStep();
                    },
                    set(newValue) {
                        that._spinButtonsStep(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'template', {
                    get() {
                        return that._template();
                    },
                    set(newValue) {
                        that._template(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'theme', {
                    get() {
                        return that._theme();
                    },
                    set(newValue) {
                        that._theme(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'upperCase', {
                    get() {
                        return that._upperCase();
                    },
                    set(newValue) {
                        that._upperCase(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'value', {
                    get() {
                        return that._value();
                    },
                    set(newValue) {
                        that._value(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'width', {
                    get() {
                        return that._width();
                    },
                    set(newValue) {
                        that._width(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __twoWayDataBinding__: function () {
                const value = JQXLite(this.componentSelector).jqxFormattedInput('val');
                this.$emit('input', value);
            },
            __wireEvents__: function () {
                const that = this;

                JQXLite(this.componentSelector).on('change', function (event) { that.$emit('change', event); that.__twoWayDataBinding__(); });
                JQXLite(this.componentSelector).on('close', function (event) { that.$emit('close', event); });
                JQXLite(this.componentSelector).on('open', function (event) { that.$emit('open', event); });
                JQXLite(this.componentSelector).on('radixChange', function (event) { that.$emit('radixChange', event); that.__twoWayDataBinding__(); });
            }
        }
    }
</script>
