// jqwidgets-vue3/vue_jqxribbon.vue
<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
	import { onUpdated, onMounted } from 'vue';
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxdata.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxribbon.js';

    export default {
        props: {
            animationType: String,
            animationDelay: Number,
            disabled: {
                default: false,
                type: Boolean
            },
            height: [Number, String],
            initContent: Function,
            mode: String,
            popupCloseMode: String,
            position: String,
            reorder: {
                default: false,
                type: Boolean
            },
            rtl: {
                default: false,
                type: Boolean
            },
            selectedIndex: Number,
            selectionMode: String,
            scrollPosition: String,
            scrollStep: Number,
            scrollDelay: Number,
            theme: String,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        emits: ["change","reorder","select","unselect"],
        setup(props, context) {
			const id = "jqxRibbon" + JQXLite.generateID();
			const componentSelector = '#' + id;
            function createComponent(options) {
                if (!props.autoCreate) __createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            }
            function setOptions (options) {
                JQXLite(componentSelector).jqxRibbon(options);
            }
            function getOptions() {
                const usedProps = Object.keys(__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(componentSelector).jqxRibbon(usedProps[i]);
                }
                return resultToReturn;
            }
            function addAt(index, item) {
                JQXLite(componentSelector).jqxRibbon('addAt', index, item);  
            }
            function clearSelection() {
                JQXLite(componentSelector).jqxRibbon('clearSelection');  
            }
            function disableAt(index) {
                JQXLite(componentSelector).jqxRibbon('disableAt', index);  
            }
            function destroy() {
                JQXLite(componentSelector).jqxRibbon('destroy');  
            }
            function enableAt(index) {
                JQXLite(componentSelector).jqxRibbon('enableAt', index);  
            }
            function hideAt(index) {
                JQXLite(componentSelector).jqxRibbon('hideAt', index);  
            }
            function removeAt(index) {
                JQXLite(componentSelector).jqxRibbon('removeAt', index);  
            }
            function render() {
                JQXLite(componentSelector).jqxRibbon('render');  
            }
            function refresh() {
                JQXLite(componentSelector).jqxRibbon('refresh');  
            }
            function selectAt(index) {
                JQXLite(componentSelector).jqxRibbon('selectAt', index);  
            }
            function showAt(index) {
                JQXLite(componentSelector).jqxRibbon('showAt', index);  
            }
            function setPopupLayout(index, layout, width, height) {
                JQXLite(componentSelector).jqxRibbon('setPopupLayout', index, layout, width, height);  
            }
            function updateAt(index, item) {
                JQXLite(componentSelector).jqxRibbon('updateAt', index, item);  
            }
            function val(value) {
                if (value !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('val',  value)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('val');
                }
            }
            function _animationType (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('animationType', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('animationType');
                }
            }
            function _animationDelay (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('animationDelay', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('animationDelay');
                }
            }
            function _disabled (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('disabled', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('disabled');
                }
            }
            function _height (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('height', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('height');
                }
            }
            function _initContent (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('initContent', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('initContent');
                }
            }
            function _mode (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('mode', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('mode');
                }
            }
            function _popupCloseMode (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('popupCloseMode', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('popupCloseMode');
                }
            }
            function _position (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('position', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('position');
                }
            }
            function _reorder (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('reorder', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('reorder');
                }
            }
            function _rtl (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('rtl', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('rtl');
                }
            }
            function _selectedIndex (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('selectedIndex', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('selectedIndex');
                }
            }
            function _selectionMode (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('selectionMode', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('selectionMode');
                }
            }
            function _scrollPosition (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('scrollPosition', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('scrollPosition');
                }
            }
            function _scrollStep (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('scrollStep', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('scrollStep');
                }
            }
            function _scrollDelay (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('scrollDelay', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('scrollDelay');
                }
            }
            function _theme (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('theme', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('theme');
                }
            }
            function _width (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxRibbon('width', arg)
                } else {
                    return JQXLite(componentSelector).jqxRibbon('width');
                }
            }
            function __createComponent__ (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = __manageProps__();
                JQXLite(componentSelector).jqxRibbon(widgetOptions);
                __wireEvents__();
            }
            function __manageProps__() {
                const widgetProps = ['animationType','animationDelay','disabled','height','initContent','mode','popupCloseMode','position','reorder','rtl','selectedIndex','selectionMode','scrollPosition','scrollStep','scrollDelay','theme','width'];
                const componentProps = props;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1 && componentProps[prop] !== undefined) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            }
            const options = {
                 get animationType() {
                     return _animationType();
                 },
                 set animationType(newValue) {
                     _animationType(newValue);
                 },
                 get animationDelay() {
                     return _animationDelay();
                 },
                 set animationDelay(newValue) {
                     _animationDelay(newValue);
                 },
                 get disabled() {
                     return _disabled();
                 },
                 set disabled(newValue) {
                     _disabled(newValue);
                 },
                 get height() {
                     return _height();
                 },
                 set height(newValue) {
                     _height(newValue);
                 },
                 get initContent() {
                     return _initContent();
                 },
                 set initContent(newValue) {
                     _initContent(newValue);
                 },
                 get mode() {
                     return _mode();
                 },
                 set mode(newValue) {
                     _mode(newValue);
                 },
                 get popupCloseMode() {
                     return _popupCloseMode();
                 },
                 set popupCloseMode(newValue) {
                     _popupCloseMode(newValue);
                 },
                 get position() {
                     return _position();
                 },
                 set position(newValue) {
                     _position(newValue);
                 },
                 get reorder() {
                     return _reorder();
                 },
                 set reorder(newValue) {
                     _reorder(newValue);
                 },
                 get rtl() {
                     return _rtl();
                 },
                 set rtl(newValue) {
                     _rtl(newValue);
                 },
                 get selectedIndex() {
                     return _selectedIndex();
                 },
                 set selectedIndex(newValue) {
                     _selectedIndex(newValue);
                 },
                 get selectionMode() {
                     return _selectionMode();
                 },
                 set selectionMode(newValue) {
                     _selectionMode(newValue);
                 },
                 get scrollPosition() {
                     return _scrollPosition();
                 },
                 set scrollPosition(newValue) {
                     _scrollPosition(newValue);
                 },
                 get scrollStep() {
                     return _scrollStep();
                 },
                 set scrollStep(newValue) {
                     _scrollStep(newValue);
                 },
                 get scrollDelay() {
                     return _scrollDelay();
                 },
                 set scrollDelay(newValue) {
                     _scrollDelay(newValue);
                 },
                 get theme() {
                     return _theme();
                 },
                 set theme(newValue) {
                     _theme(newValue);
                 },
                 get width() {
                     return _width();
                 },
                 set width(newValue) {
                     _width(newValue);
                 },
            }
            function __wireEvents__() {
                const that = context;

                JQXLite(componentSelector).on('change', function (event) { that.emit('change', event); });
                JQXLite(componentSelector).on('reorder', function (event) { that.emit('reorder', event); });
                JQXLite(componentSelector).on('select', function (event) { that.emit('select', event); });
                JQXLite(componentSelector).on('unselect', function (event) { that.emit('unselect', event); });
            }

			onMounted(() => {
				if (props.autoCreate) __createComponent__();
			})
			onUpdated(() => {
				const widgetOptions = __manageProps__();
				JQXLite(componentSelector).jqxRibbon(widgetOptions);
			})
			return {id, componentSelector, addAt,clearSelection,disableAt,destroy,enableAt,hideAt,removeAt,render,refresh,selectAt,showAt,setPopupLayout,updateAt,val, setOptions, options, getOptions, createComponent};
        },
    }
</script>

// jqwidgets-ng/esm2015/jqxribbon/angular_jqxribbon.js
import '../jqwidgets/jqxcore';
import '../jqwidgets/jqxdata';
import '../jqwidgets/jqxbuttons';
import '../jqwidgets/jqxribbon';
/// <reference path="../../jqwidgets.d.ts" />
import * as tslib_1 from "tslib";
import { Component, Input, Output, EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
let jqxRibbonComponent = class jqxRibbonComponent {
    constructor(containerElement) {
        this.autoCreate = true;
        this.properties = ['animationType', 'animationDelay', 'disabled', 'height', 'initContent', 'mode', 'popupCloseMode', 'position', 'reorder', 'rtl', 'selectedIndex', 'selectionMode', 'scrollPosition', 'scrollStep', 'scrollDelay', 'theme', 'width'];
        // jqxRibbonComponent events
        this.onChange = new EventEmitter();
        this.onReorder = new EventEmitter();
        this.onSelect = new EventEmitter();
        this.onUnselect = new EventEmitter();
        this.elementRef = containerElement;
    }
    ngOnInit() {
        if (this.autoCreate) {
            this.createComponent();
        }
    }
    ;
    ngOnChanges(changes) {
        if (this.host) {
            for (let i = 0; i < this.properties.length; i++) {
                let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
                let areEqual = false;
                if (this[attrName] !== undefined) {
                    if (typeof this[attrName] === 'object') {
                        if (this[attrName] instanceof Array) {
                            areEqual = this.arraysEqual(this[attrName], this.host.jqxRibbon(this.properties[i]));
                        }
                        if (areEqual) {
                            return false;
                        }
                        this.host.jqxRibbon(this.properties[i], this[attrName]);
                        continue;
                    }
                    if (this[attrName] !== this.host.jqxRibbon(this.properties[i])) {
                        this.host.jqxRibbon(this.properties[i], this[attrName]);
                    }
                }
            }
        }
    }
    arraysEqual(attrValue, hostValue) {
        if ((attrValue && !hostValue) || (!attrValue && hostValue)) {
            return false;
        }
        if (attrValue.length != hostValue.length) {
            return false;
        }
        for (let i = 0; i < attrValue.length; i++) {
            if (attrValue[i] !== hostValue[i]) {
                return false;
            }
        }
        return true;
    }
    manageAttributes() {
        let options = {};
        for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            if (this[attrName] !== undefined) {
                options[this.properties[i]] = this[attrName];
            }
        }
        return options;
    }
    moveClasses(parentEl, childEl) {
        let classes = parentEl.classList;
        if (classes.length > 0) {
            childEl.classList.add(...classes);
        }
        parentEl.className = '';
    }
    moveStyles(parentEl, childEl) {
        let style = parentEl.style.cssText;
        childEl.style.cssText = style;
        parentEl.style.cssText = '';
    }
    createComponent(options) {
        if (this.host) {
            return;
        }
        if (options) {
            JQXLite.extend(options, this.manageAttributes());
        }
        else {
            options = this.manageAttributes();
        }
        this.host = JQXLite(this.elementRef.nativeElement.firstChild);
        this.moveClasses(this.elementRef.nativeElement, this.host[0]);
        this.moveStyles(this.elementRef.nativeElement, this.host[0]);
        this.__wireEvents__();
        this.widgetObject = jqwidgets.createInstance(this.host, 'jqxRibbon', options);
    }
    createWidget(options) {
        this.createComponent(options);
    }
    __updateRect__() {
        if (this.host)
            this.host.css({ width: this.attrWidth, height: this.attrHeight });
    }
    setOptions(options) {
        this.host.jqxRibbon('setOptions', options);
    }
    // jqxRibbonComponent properties
    animationType(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('animationType', arg);
        }
        else {
            return this.host.jqxRibbon('animationType');
        }
    }
    animationDelay(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('animationDelay', arg);
        }
        else {
            return this.host.jqxRibbon('animationDelay');
        }
    }
    disabled(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('disabled', arg);
        }
        else {
            return this.host.jqxRibbon('disabled');
        }
    }
    height(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('height', arg);
        }
        else {
            return this.host.jqxRibbon('height');
        }
    }
    initContent(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('initContent', arg);
        }
        else {
            return this.host.jqxRibbon('initContent');
        }
    }
    mode(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('mode', arg);
        }
        else {
            return this.host.jqxRibbon('mode');
        }
    }
    popupCloseMode(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('popupCloseMode', arg);
        }
        else {
            return this.host.jqxRibbon('popupCloseMode');
        }
    }
    position(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('position', arg);
        }
        else {
            return this.host.jqxRibbon('position');
        }
    }
    reorder(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('reorder', arg);
        }
        else {
            return this.host.jqxRibbon('reorder');
        }
    }
    rtl(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('rtl', arg);
        }
        else {
            return this.host.jqxRibbon('rtl');
        }
    }
    selectedIndex(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('selectedIndex', arg);
        }
        else {
            return this.host.jqxRibbon('selectedIndex');
        }
    }
    selectionMode(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('selectionMode', arg);
        }
        else {
            return this.host.jqxRibbon('selectionMode');
        }
    }
    scrollPosition(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('scrollPosition', arg);
        }
        else {
            return this.host.jqxRibbon('scrollPosition');
        }
    }
    scrollStep(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('scrollStep', arg);
        }
        else {
            return this.host.jqxRibbon('scrollStep');
        }
    }
    scrollDelay(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('scrollDelay', arg);
        }
        else {
            return this.host.jqxRibbon('scrollDelay');
        }
    }
    theme(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('theme', arg);
        }
        else {
            return this.host.jqxRibbon('theme');
        }
    }
    width(arg) {
        if (arg !== undefined) {
            this.host.jqxRibbon('width', arg);
        }
        else {
            return this.host.jqxRibbon('width');
        }
    }
    // jqxRibbonComponent functions
    addAt(index, item) {
        this.host.jqxRibbon('addAt', index, item);
    }
    clearSelection() {
        this.host.jqxRibbon('clearSelection');
    }
    disableAt(index) {
        this.host.jqxRibbon('disableAt', index);
    }
    destroy() {
        this.host.jqxRibbon('destroy');
    }
    enableAt(index) {
        this.host.jqxRibbon('enableAt', index);
    }
    hideAt(index) {
        this.host.jqxRibbon('hideAt', index);
    }
    removeAt(index) {
        this.host.jqxRibbon('removeAt', index);
    }
    render() {
        this.host.jqxRibbon('render');
    }
    refresh() {
        this.host.jqxRibbon('refresh');
    }
    selectAt(index) {
        this.host.jqxRibbon('selectAt', index);
    }
    showAt(index) {
        this.host.jqxRibbon('showAt', index);
    }
    setPopupLayout(index, layout, width, height) {
        this.host.jqxRibbon('setPopupLayout', index, layout, width, height);
    }
    updateAt(index, item) {
        this.host.jqxRibbon('updateAt', index, item);
    }
    val(value) {
        if (value !== undefined) {
            return this.host.jqxRibbon('val', value);
        }
        else {
            return this.host.jqxRibbon('val');
        }
    }
    ;
    __wireEvents__() {
        this.host.on('change', (eventData) => { this.onChange.emit(eventData); });
        this.host.on('reorder', (eventData) => { this.onReorder.emit(eventData); });
        this.host.on('select', (eventData) => { this.onSelect.emit(eventData); });
        this.host.on('unselect', (eventData) => { this.onUnselect.emit(eventData); });
    }
}; //jqxRibbonComponent
jqxRibbonComponent.ctorParameters = () => [
    { type: ElementRef }
];
tslib_1.__decorate([
    Input('animationType'),
    tslib_1.__metadata("design:type", String)
], jqxRibbonComponent.prototype, "attrAnimationType", void 0);
tslib_1.__decorate([
    Input('animationDelay'),
    tslib_1.__metadata("design:type", Object)
], jqxRibbonComponent.prototype, "attrAnimationDelay", void 0);
tslib_1.__decorate([
    Input('disabled'),
    tslib_1.__metadata("design:type", Boolean)
], jqxRibbonComponent.prototype, "attrDisabled", void 0);
tslib_1.__decorate([
    Input('initContent'),
    tslib_1.__metadata("design:type", Function)
], jqxRibbonComponent.prototype, "attrInitContent", void 0);
tslib_1.__decorate([
    Input('mode'),
    tslib_1.__metadata("design:type", String)
], jqxRibbonComponent.prototype, "attrMode", void 0);
tslib_1.__decorate([
    Input('popupCloseMode'),
    tslib_1.__metadata("design:type", String)
], jqxRibbonComponent.prototype, "attrPopupCloseMode", void 0);
tslib_1.__decorate([
    Input('position'),
    tslib_1.__metadata("design:type", String)
], jqxRibbonComponent.prototype, "attrPosition", void 0);
tslib_1.__decorate([
    Input('reorder'),
    tslib_1.__metadata("design:type", Boolean)
], jqxRibbonComponent.prototype, "attrReorder", void 0);
tslib_1.__decorate([
    Input('rtl'),
    tslib_1.__metadata("design:type", Boolean)
], jqxRibbonComponent.prototype, "attrRtl", void 0);
tslib_1.__decorate([
    Input('selectedIndex'),
    tslib_1.__metadata("design:type", Number)
], jqxRibbonComponent.prototype, "attrSelectedIndex", void 0);
tslib_1.__decorate([
    Input('selectionMode'),
    tslib_1.__metadata("design:type", String)
], jqxRibbonComponent.prototype, "attrSelectionMode", void 0);
tslib_1.__decorate([
    Input('scrollPosition'),
    tslib_1.__metadata("design:type", String)
], jqxRibbonComponent.prototype, "attrScrollPosition", void 0);
tslib_1.__decorate([
    Input('scrollStep'),
    tslib_1.__metadata("design:type", Number)
], jqxRibbonComponent.prototype, "attrScrollStep", void 0);
tslib_1.__decorate([
    Input('scrollDelay'),
    tslib_1.__metadata("design:type", Number)
], jqxRibbonComponent.prototype, "attrScrollDelay", void 0);
tslib_1.__decorate([
    Input('theme'),
    tslib_1.__metadata("design:type", String)
], jqxRibbonComponent.prototype, "attrTheme", void 0);
tslib_1.__decorate([
    Input('width'),
    tslib_1.__metadata("design:type", Object)
], jqxRibbonComponent.prototype, "attrWidth", void 0);
tslib_1.__decorate([
    Input('height'),
    tslib_1.__metadata("design:type", Object)
], jqxRibbonComponent.prototype, "attrHeight", void 0);
tslib_1.__decorate([
    Input('auto-create'),
    tslib_1.__metadata("design:type", Boolean)
], jqxRibbonComponent.prototype, "autoCreate", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxRibbonComponent.prototype, "onChange", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxRibbonComponent.prototype, "onReorder", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxRibbonComponent.prototype, "onSelect", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxRibbonComponent.prototype, "onUnselect", void 0);
jqxRibbonComponent = tslib_1.__decorate([
    Component({
        selector: 'jqxRibbon',
        template: '<div><ng-content></ng-content></div>'
    }),
    tslib_1.__metadata("design:paramtypes", [ElementRef])
], jqxRibbonComponent);
export { jqxRibbonComponent };
