// jqwidgets-ts/angular_jqxdocking.ts
/*
jQWidgets v8.1.3 (2019-July)
Copyright (c) 2011-2019 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

/// <reference path="jqwidgets.d.ts" />

import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxbuttons.js';
import '../jqwidgets/jqxwindow.js';
import '../jqwidgets/jqxdocking.js';

import { Component, Input, Output, EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
declare let JQXLite: any;

@Component({
    selector: 'jqxDocking',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxDockingComponent implements OnChanges
{
   @Input('cookies') attrCookies: boolean;
   @Input('cookieOptions') attrCookieOptions: jqwidgets.DockingCookieOptions;
   @Input('disabled') attrDisabled: boolean;
   @Input('floatingWindowOpacity') attrFloatingWindowOpacity: number;
   @Input('keyboardNavigation') attrKeyboardNavigation: boolean;
   @Input('mode') attrMode: string;
   @Input('orientation') attrOrientation: string;
   @Input('rtl') attrRtl: boolean;
   @Input('theme') attrTheme: string;
   @Input('windowsMode') attrWindowsMode: object;
   @Input('windowsOffset') attrWindowsOffset: number;
   @Input('width') attrWidth: string | number;
   @Input('height') attrHeight: string | number;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['cookies','cookieOptions','disabled','floatingWindowOpacity','height','keyboardNavigation','mode','orientation','rtl','theme','width','windowsMode','windowsOffset'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxDocking;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean = false;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxDocking(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxDocking(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxDocking(this.properties[i])) {
                  this.host.jqxDocking(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if ((attrValue && !hostValue) || (!attrValue && hostValue)) {
         return false;
      }
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void {
      let classes: any = parentEl.classList;
      if (classes.length > 0) {
        childEl.classList.add(...classes);
      }
      parentEl.className = '';
   }

   moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void {
      let style = parentEl.style.cssText;
      childEl.style.cssText = style
      parentEl.style.cssText = '';
   }

   createComponent(options?: any): void {
      if (this.host) {
         return;
      }
      if (options) {
         JQXLite.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = JQXLite(this.elementRef.nativeElement.firstChild);

      this.moveClasses(this.elementRef.nativeElement, this.host[0]);
      this.moveStyles(this.elementRef.nativeElement, this.host[0]);

      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxDocking', options);

   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      if(this.host) this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   setOptions(options: any) : void {
      this.host.jqxDocking('setOptions', options);
   }

   // jqxDockingComponent properties
   cookies(arg?: boolean): boolean {
      if (arg !== undefined) {
          this.host.jqxDocking('cookies', arg);
      } else {
          return this.host.jqxDocking('cookies');
      }
   }

   cookieOptions(arg?: jqwidgets.DockingCookieOptions): jqwidgets.DockingCookieOptions {
      if (arg !== undefined) {
          this.host.jqxDocking('cookieOptions', arg);
      } else {
          return this.host.jqxDocking('cookieOptions');
      }
   }

   disabled(arg?: boolean): boolean {
      if (arg !== undefined) {
          this.host.jqxDocking('disabled', arg);
      } else {
          return this.host.jqxDocking('disabled');
      }
   }

   floatingWindowOpacity(arg?: number): number {
      if (arg !== undefined) {
          this.host.jqxDocking('floatingWindowOpacity', arg);
      } else {
          return this.host.jqxDocking('floatingWindowOpacity');
      }
   }

   height(arg?: number | string): number | string {
      if (arg !== undefined) {
          this.host.jqxDocking('height', arg);
      } else {
          return this.host.jqxDocking('height');
      }
   }

   keyboardNavigation(arg?: boolean): boolean {
      if (arg !== undefined) {
          this.host.jqxDocking('keyboardNavigation', arg);
      } else {
          return this.host.jqxDocking('keyboardNavigation');
      }
   }

   mode(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxDocking('mode', arg);
      } else {
          return this.host.jqxDocking('mode');
      }
   }

   orientation(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxDocking('orientation', arg);
      } else {
          return this.host.jqxDocking('orientation');
      }
   }

   rtl(arg?: boolean): boolean {
      if (arg !== undefined) {
          this.host.jqxDocking('rtl', arg);
      } else {
          return this.host.jqxDocking('rtl');
      }
   }

   theme(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxDocking('theme', arg);
      } else {
          return this.host.jqxDocking('theme');
      }
   }

   width(arg?: number | string): number | string {
      if (arg !== undefined) {
          this.host.jqxDocking('width', arg);
      } else {
          return this.host.jqxDocking('width');
      }
   }

   windowsMode(arg?: object): object {
      if (arg !== undefined) {
          this.host.jqxDocking('windowsMode', arg);
      } else {
          return this.host.jqxDocking('windowsMode');
      }
   }

   windowsOffset(arg?: number): number {
      if (arg !== undefined) {
          this.host.jqxDocking('windowsOffset', arg);
      } else {
          return this.host.jqxDocking('windowsOffset');
      }
   }


   // jqxDockingComponent functions
   addWindow(windowId: string, mode: any, panel: number, position: any): void {
      this.host.jqxDocking('addWindow', windowId, mode, panel, position);
   }

   closeWindow(windowId: string): void {
      this.host.jqxDocking('closeWindow', windowId);
   }

   collapseWindow(windowId: string): void {
      this.host.jqxDocking('collapseWindow', windowId);
   }

   destroy(): void {
      this.host.jqxDocking('destroy');
   }

   disableWindowResize(windowId: string): void {
      this.host.jqxDocking('disableWindowResize', windowId);
   }

   disable(): void {
      this.host.jqxDocking('disable');
   }

   exportLayout(): string {
      return this.host.jqxDocking('exportLayout');
   }

   enable(): void {
      this.host.jqxDocking('enable');
   }

   expandWindow(windowId: string): void {
      this.host.jqxDocking('expandWindow', windowId);
   }

   enableWindowResize(windowId: string): void {
      this.host.jqxDocking('enableWindowResize', windowId);
   }

   focus(): void {
      this.host.jqxDocking('focus');
   }

   hideAllCloseButtons(): void {
      this.host.jqxDocking('hideAllCloseButtons');
   }

   hideAllCollapseButtons(): void {
      this.host.jqxDocking('hideAllCollapseButtons');
   }

   hideCollapseButton(windowId: string): void {
      this.host.jqxDocking('hideCollapseButton', windowId);
   }

   hideCloseButton(windowId: string): void {
      this.host.jqxDocking('hideCloseButton', windowId);
   }

   importLayout(Json: string): void {
      this.host.jqxDocking('importLayout', Json);
   }

   move(windowId: string, panel: number, position: number): void {
      this.host.jqxDocking('move', windowId, panel, position);
   }

   pinWindow(windowId: string): void {
      this.host.jqxDocking('pinWindow', windowId);
   }

   setWindowMode(windowId: string, mode: any): void {
      this.host.jqxDocking('setWindowMode', windowId, mode);
   }

   showCloseButton(windowId: string): void {
      this.host.jqxDocking('showCloseButton', windowId);
   }

   showCollapseButton(windowId: string): void {
      this.host.jqxDocking('showCollapseButton', windowId);
   }

   setWindowPosition(windowId: string, top: any, left: number): void {
      this.host.jqxDocking('setWindowPosition', windowId, top, left);
   }

   showAllCloseButtons(): void {
      this.host.jqxDocking('showAllCloseButtons');
   }

   showAllCollapseButtons(): void {
      this.host.jqxDocking('showAllCollapseButtons');
   }

   unpinWindow(windowId: string): void {
      this.host.jqxDocking('unpinWindow', windowId);
   }


   // jqxDockingComponent events
   @Output() onDragStart = new EventEmitter();
   @Output() onDragEnd = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('dragStart', (eventData: any) => { this.onDragStart.emit(eventData); });
      this.host.on('dragEnd', (eventData: any) => { this.onDragEnd.emit(eventData); });
   }

} //jqxDockingComponent

// jqwidgets-react/react_jqxdocking.js
/*
jQWidgets v6.0.4 (2018-July)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxbuttons.js';
import '../jqwidgets/jqxwindow.js';
import '../jqwidgets/jqxdocking.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxDocking extends React.Component {
    componentDidMount() {
        let options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        let properties = ['cookies','cookieOptions','disabled','floatingWindowOpacity','height','keyboardNavigation','mode','orientation','rtl','theme','width','windowsMode','windowsOffset'];
        let options = {};
        for(let item in this.props) {
              if(item === 'settings') {
                  for(let itemTwo in this.props[item]) {
                      options[itemTwo] = this.props[item][itemTwo];
                      }
                } else {
                      if(properties.indexOf(item) !== -1) {
                        options[item] = this.props[item];
                      }
                }
          }
          return options;
      };
    createComponent(options) {
        if(!this.style) {
              for (let style in this.props.style) {
                  JQXLite(this.componentSelector).css(style, this.props.style[style]);
              }
        }
        if(this.props.className !== undefined) {
            let classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
              JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxDocking(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxDocking('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxDocking(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    cookies(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxDocking('cookies', arg)
        } else {
            return JQXLite(this.componentSelector).jqxDocking('cookies');
        }
    };
    cookieOptions(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxDocking('cookieOptions', arg)
        } else {
            return JQXLite(this.componentSelector).jqxDocking('cookieOptions');
        }
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxDocking('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxDocking('disabled');
        }
    };
    floatingWindowOpacity(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxDocking('floatingWindowOpacity', arg)
        } else {
            return JQXLite(this.componentSelector).jqxDocking('floatingWindowOpacity');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxDocking('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxDocking('height');
        }
    };
    keyboardNavigation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxDocking('keyboardNavigation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxDocking('keyboardNavigation');
        }
    };
    mode(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxDocking('mode', arg)
        } else {
            return JQXLite(this.componentSelector).jqxDocking('mode');
        }
    };
    orientation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxDocking('orientation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxDocking('orientation');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxDocking('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxDocking('rtl');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxDocking('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxDocking('theme');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxDocking('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxDocking('width');
        }
    };
    windowsMode(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxDocking('windowsMode', arg)
        } else {
            return JQXLite(this.componentSelector).jqxDocking('windowsMode');
        }
    };
    windowsOffset(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxDocking('windowsOffset', arg)
        } else {
            return JQXLite(this.componentSelector).jqxDocking('windowsOffset');
        }
    };
    addWindow(windowId, mode, panel, position) {
        JQXLite(this.componentSelector).jqxDocking('addWindow', windowId, mode, panel, position);  
    };
    closeWindow(windowId) {
        JQXLite(this.componentSelector).jqxDocking('closeWindow', windowId);  
    };
    collapseWindow(windowId) {
        JQXLite(this.componentSelector).jqxDocking('collapseWindow', windowId);  
    };
    destroy() {
        JQXLite(this.componentSelector).jqxDocking('destroy');  
    };
    disableWindowResize(windowId) {
        JQXLite(this.componentSelector).jqxDocking('disableWindowResize', windowId);  
    };
    disable() {
        JQXLite(this.componentSelector).jqxDocking('disable');  
    };
    exportLayout() {
        return JQXLite(this.componentSelector).jqxDocking('exportLayout');  
    };
    enable() {
        JQXLite(this.componentSelector).jqxDocking('enable');  
    };
    expandWindow(windowId) {
        JQXLite(this.componentSelector).jqxDocking('expandWindow', windowId);  
    };
    enableWindowResize(windowId) {
        JQXLite(this.componentSelector).jqxDocking('enableWindowResize', windowId);  
    };
    focus() {
        JQXLite(this.componentSelector).jqxDocking('focus');  
    };
    hideAllCloseButtons() {
        JQXLite(this.componentSelector).jqxDocking('hideAllCloseButtons');  
    };
    hideAllCollapseButtons() {
        JQXLite(this.componentSelector).jqxDocking('hideAllCollapseButtons');  
    };
    hideCollapseButton(windowId) {
        JQXLite(this.componentSelector).jqxDocking('hideCollapseButton', windowId);  
    };
    hideCloseButton(windowId) {
        JQXLite(this.componentSelector).jqxDocking('hideCloseButton', windowId);  
    };
    importLayout(Json) {
        JQXLite(this.componentSelector).jqxDocking('importLayout', Json);  
    };
    move(windowId, panel, position) {
        JQXLite(this.componentSelector).jqxDocking('move', windowId, panel, position);  
    };
    pinWindow(windowId) {
        JQXLite(this.componentSelector).jqxDocking('pinWindow', windowId);  
    };
    setWindowMode(windowId, mode) {
        JQXLite(this.componentSelector).jqxDocking('setWindowMode', windowId, mode);  
    };
    showCloseButton(windowId) {
        JQXLite(this.componentSelector).jqxDocking('showCloseButton', windowId);  
    };
    showCollapseButton(windowId) {
        JQXLite(this.componentSelector).jqxDocking('showCollapseButton', windowId);  
    };
    setWindowPosition(windowId, top, left) {
        JQXLite(this.componentSelector).jqxDocking('setWindowPosition', windowId, top, left);  
    };
    showAllCloseButtons() {
        JQXLite(this.componentSelector).jqxDocking('showAllCloseButtons');  
    };
    showAllCollapseButtons() {
        JQXLite(this.componentSelector).jqxDocking('showAllCollapseButtons');  
    };
    unpinWindow(windowId) {
        JQXLite(this.componentSelector).jqxDocking('unpinWindow', windowId);  
    };
    render() {
        let id = 'jqxDocking' + JQXLite.generateID();
        this.componentSelector = '#' + id;
        return (
            <div id={id}>{this.props.value}{this.props.children}</div>
        )
    };
};
