// jqwidgets-vue/vue_jqxtoolbar.vue
/*
jQWidgets v7.0.0 (2019-Jan)
Copyright (c) 2011-2019 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxscrollbar.js';
    import '../jqwidgets/jqxlistbox.js';
    import '../jqwidgets/jqxdropdownlist.js';
    import '../jqwidgets/jqxcombobox.js';
    import '../jqwidgets/jqxinput.js';
    import '../jqwidgets/jqxtoolbar.js';

    export default {
        props: {
            disabled: Boolean,
            height: [Number, String],
            initTools: Function,
            minimizeWidth: Number,
            minWidth: Number,
            maxWidth: Number,
            rtl: Boolean,
            tools: String,
            theme: String,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxToolBar' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxToolBar(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxToolBar(usedProps[i]);
                }
                return resultToReturn;
            },
            addTool: function(type, position, separator, menuToolIninitialization) {
                JQXLite(this.componentSelector).jqxToolBar('addTool', type, position, separator, menuToolIninitialization);  
            },
            disableTool: function(index, disable) {
                JQXLite(this.componentSelector).jqxToolBar('disableTool', index, disable);  
            },
            destroy: function() {
                JQXLite(this.componentSelector).jqxToolBar('destroy');  
            },
            destroyTool: function(index) {
                JQXLite(this.componentSelector).jqxToolBar('destroyTool', index);  
            },
            getTools: function() {
                return JQXLite(this.componentSelector).jqxToolBar('getTools');  
            },
            render: function() {
                JQXLite(this.componentSelector).jqxToolBar('render');  
            },
            refresh: function() {
                JQXLite(this.componentSelector).jqxToolBar('refresh');  
            },
            _disabled: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxToolBar('disabled', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxToolBar('disabled');
                }
            },
            _height: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxToolBar('height', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxToolBar('height');
                }
            },
            _initTools: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxToolBar('initTools', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxToolBar('initTools');
                }
            },
            _minimizeWidth: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxToolBar('minimizeWidth', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxToolBar('minimizeWidth');
                }
            },
            _minWidth: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxToolBar('minWidth', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxToolBar('minWidth');
                }
            },
            _maxWidth: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxToolBar('maxWidth', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxToolBar('maxWidth');
                }
            },
            _rtl: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxToolBar('rtl', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxToolBar('rtl');
                }
            },
            _tools: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxToolBar('tools', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxToolBar('tools');
                }
            },
            _theme: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxToolBar('theme', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxToolBar('theme');
                }
            },
            _width: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxToolBar('width', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxToolBar('width');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxToolBar(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['disabled','height','initTools','minimizeWidth','minWidth','maxWidth','rtl','tools','theme','width'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'disabled', {
                    get() {
                        return that._disabled();
                    },
                    set(newValue) {
                        that._disabled(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'height', {
                    get() {
                        return that._height();
                    },
                    set(newValue) {
                        that._height(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'initTools', {
                    get() {
                        return that._initTools();
                    },
                    set(newValue) {
                        that._initTools(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'minimizeWidth', {
                    get() {
                        return that._minimizeWidth();
                    },
                    set(newValue) {
                        that._minimizeWidth(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'minWidth', {
                    get() {
                        return that._minWidth();
                    },
                    set(newValue) {
                        that._minWidth(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'maxWidth', {
                    get() {
                        return that._maxWidth();
                    },
                    set(newValue) {
                        that._maxWidth(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'rtl', {
                    get() {
                        return that._rtl();
                    },
                    set(newValue) {
                        that._rtl(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'tools', {
                    get() {
                        return that._tools();
                    },
                    set(newValue) {
                        that._tools(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'theme', {
                    get() {
                        return that._theme();
                    },
                    set(newValue) {
                        that._theme(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'width', {
                    get() {
                        return that._width();
                    },
                    set(newValue) {
                        that._width(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __wireEvents__: function () {
                const that = this;

                JQXLite(this.componentSelector).on('close', function (event) { that.$emit('close', event); });
                JQXLite(this.componentSelector).on('open', function (event) { that.$emit('open', event); });
            }
        }
    }
</script>

// jqwidgets-react/react_jqxtoolbar.js
/*
jQWidgets v7.0.0 (2019-Jan)
Copyright (c) 2011-2019 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxbuttons.js';
import '../jqwidgets/jqxscrollbar.js';
import '../jqwidgets/jqxlistbox.js';
import '../jqwidgets/jqxdropdownlist.js';
import '../jqwidgets/jqxcombobox.js';
import '../jqwidgets/jqxinput.js';
import '../jqwidgets/jqxtoolbar.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxToolBar extends React.Component {
    constructor(props) {
        super(props);
        const widgetId = 'jqxToolBar' + JQXLite.generateID();
        this.componentSelector = '#' + widgetId;
        this.state = { id: widgetId };
    };
    componentDidMount() {
        const options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        const properties = ['disabled','height','initTools','minimizeWidth','minWidth','maxWidth','rtl','tools','theme','width'];
        let options = {};
        for(let item in this.props) {
            if(item === 'settings') {
                for(let itemTwo in this.props[item]) {
                    options[itemTwo] = this.props[item][itemTwo];
                }
            } else {
                if(properties.indexOf(item) !== -1) {
                      options[item] = this.props[item];
                }
            }
        }
        return options;
    };
    createComponent(options) {
        if(!this.style) {
            for (let style in this.props.style) {
                JQXLite(this.componentSelector).css(style, this.props.style[style]);
            }
        }
        if(this.props.className !== undefined) {
            const classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
            JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxToolBar(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxToolBar('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxToolBar(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxToolBar('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxToolBar('disabled');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxToolBar('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxToolBar('height');
        }
    };
    initTools(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxToolBar('initTools', arg)
        } else {
            return JQXLite(this.componentSelector).jqxToolBar('initTools');
        }
    };
    minimizeWidth(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxToolBar('minimizeWidth', arg)
        } else {
            return JQXLite(this.componentSelector).jqxToolBar('minimizeWidth');
        }
    };
    minWidth(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxToolBar('minWidth', arg)
        } else {
            return JQXLite(this.componentSelector).jqxToolBar('minWidth');
        }
    };
    maxWidth(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxToolBar('maxWidth', arg)
        } else {
            return JQXLite(this.componentSelector).jqxToolBar('maxWidth');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxToolBar('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxToolBar('rtl');
        }
    };
    tools(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxToolBar('tools', arg)
        } else {
            return JQXLite(this.componentSelector).jqxToolBar('tools');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxToolBar('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxToolBar('theme');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxToolBar('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxToolBar('width');
        }
    };
    addTool(type, position, separator, menuToolIninitialization) {
        JQXLite(this.componentSelector).jqxToolBar('addTool', type, position, separator, menuToolIninitialization);  
    };
    disableTool(index, disable) {
        JQXLite(this.componentSelector).jqxToolBar('disableTool', index, disable);  
    };
    destroy() {
        JQXLite(this.componentSelector).jqxToolBar('destroy');  
    };
    destroyTool(index) {
        JQXLite(this.componentSelector).jqxToolBar('destroyTool', index);  
    };
    getTools() {
        return JQXLite(this.componentSelector).jqxToolBar('getTools');  
    };
    performRender() {
        JQXLite(this.componentSelector).jqxToolBar('render');
    };
    refresh() {
        JQXLite(this.componentSelector).jqxToolBar('refresh');  
    };
    render() {
        return (
            <div id={this.state.id}>{this.props.value}{this.props.children}</div>
        )
    };
};
