// jqwidgets-vue3/vue_jqxmaskedinput.vue
<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
	import { onUpdated, onMounted } from 'vue';
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxmaskedinput.js';

    export default {
        props: {
            modelValue: String,
            disabled: {
                default: false,
                type: Boolean
            },
            height: [Number, String],
            mask: String,
            promptChar: String,
            readOnly: {
                default: false,
                type: Boolean
            },
            rtl: {
                default: false,
                type: Boolean
            },
            theme: String,
            textAlign: String,
            value: [String, Number],
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        emits: ["update:modelValue","change","valueChanged"],
        setup(props, context) {
			const id = "jqxMaskedInput" + JQXLite.generateID();
			const componentSelector = '#' + id;
            function createComponent(options) {
                if (!props.autoCreate) __createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            }
            function setOptions (options) {
                JQXLite(componentSelector).jqxMaskedInput(options);
            }
            function getOptions() {
                const usedProps = Object.keys(__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(componentSelector).jqxMaskedInput(usedProps[i]);
                }
                return resultToReturn;
            }
            function clear() {
                JQXLite(componentSelector).jqxMaskedInput('clear');  
            }
            function destroy() {
                JQXLite(componentSelector).jqxMaskedInput('destroy');  
            }
            function focus() {
                JQXLite(componentSelector).jqxMaskedInput('focus');  
            }
            function val(value) {
                if (value !== undefined) {
                    JQXLite(componentSelector).jqxMaskedInput('val',  value)
                } else {
                    return JQXLite(componentSelector).jqxMaskedInput('val');
                }
            }
            function _disabled (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxMaskedInput('disabled', arg)
                } else {
                    return JQXLite(componentSelector).jqxMaskedInput('disabled');
                }
            }
            function _height (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxMaskedInput('height', arg)
                } else {
                    return JQXLite(componentSelector).jqxMaskedInput('height');
                }
            }
            function _mask (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxMaskedInput('mask', arg)
                } else {
                    return JQXLite(componentSelector).jqxMaskedInput('mask');
                }
            }
            function _promptChar (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxMaskedInput('promptChar', arg)
                } else {
                    return JQXLite(componentSelector).jqxMaskedInput('promptChar');
                }
            }
            function _readOnly (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxMaskedInput('readOnly', arg)
                } else {
                    return JQXLite(componentSelector).jqxMaskedInput('readOnly');
                }
            }
            function _rtl (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxMaskedInput('rtl', arg)
                } else {
                    return JQXLite(componentSelector).jqxMaskedInput('rtl');
                }
            }
            function _theme (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxMaskedInput('theme', arg)
                } else {
                    return JQXLite(componentSelector).jqxMaskedInput('theme');
                }
            }
            function _textAlign (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxMaskedInput('textAlign', arg)
                } else {
                    return JQXLite(componentSelector).jqxMaskedInput('textAlign');
                }
            }
            function _value (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxMaskedInput('value', arg)
                } else {
                    return JQXLite(componentSelector).jqxMaskedInput('value');
                }
            }
            function _width (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxMaskedInput('width', arg)
                } else {
                    return JQXLite(componentSelector).jqxMaskedInput('width');
                }
            }
            function __createComponent__ (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = __manageProps__();
                JQXLite(componentSelector).jqxMaskedInput(widgetOptions);
                __wireEvents__();
            }
            function __manageProps__() {
                const widgetProps = ['disabled','height','mask','promptChar','readOnly','rtl','theme','textAlign','value','width'];
                const componentProps = props;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1 && componentProps[prop] !== undefined) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            }
            const options = {
                 get disabled() {
                     return _disabled();
                 },
                 set disabled(newValue) {
                     _disabled(newValue);
                 },
                 get height() {
                     return _height();
                 },
                 set height(newValue) {
                     _height(newValue);
                 },
                 get mask() {
                     return _mask();
                 },
                 set mask(newValue) {
                     _mask(newValue);
                 },
                 get promptChar() {
                     return _promptChar();
                 },
                 set promptChar(newValue) {
                     _promptChar(newValue);
                 },
                 get readOnly() {
                     return _readOnly();
                 },
                 set readOnly(newValue) {
                     _readOnly(newValue);
                 },
                 get rtl() {
                     return _rtl();
                 },
                 set rtl(newValue) {
                     _rtl(newValue);
                 },
                 get theme() {
                     return _theme();
                 },
                 set theme(newValue) {
                     _theme(newValue);
                 },
                 get textAlign() {
                     return _textAlign();
                 },
                 set textAlign(newValue) {
                     _textAlign(newValue);
                 },
                 get value() {
                     return _value();
                 },
                 set value(newValue) {
                     _value(newValue);
                 },
                 get width() {
                     return _width();
                 },
                 set width(newValue) {
                     _width(newValue);
                 },
            }
            function twoWayBinding() {
                const value = JQXLite(componentSelector).jqxMaskedInput('val');
                context.emit('input', value);
                context.emit('update:modelValue', element.value);
            }
            function __wireEvents__() {
                const that = context;

                JQXLite(componentSelector).on('change', function (event) { that.emit('change', event); });
                JQXLite(componentSelector).on('valueChanged', function (event) { that.emit('valueChanged', event); twoWayBinding(); });
            }

			onMounted(() => {
				if (props.autoCreate) __createComponent__();
			})
			onUpdated(() => {
				const widgetOptions = __manageProps__();
				JQXLite(componentSelector).jqxMaskedInput(widgetOptions);
			})
			return {id, componentSelector, clear,destroy,focus,val,twoWayBinding, setOptions, options, getOptions, createComponent};
        },
    }
</script>

// jqwidgets-react/react_jqxmaskedinput.js
import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxmaskedinput.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxMaskedInput extends React.Component {
    constructor(props) {
        super(props);
        const widgetId = 'jqxMaskedInput' + JQXLite.generateID();
        this.componentSelector = '#' + widgetId;
        this.state = { id: widgetId };
    };
    componentDidMount() {
        const options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        const properties = ['disabled','height','mask','promptChar','readOnly','rtl','theme','textAlign','value','width'];
        let options = {};
        for(let item in this.props) {
    	    if(item === 'settings') {
      	      for(let itemTwo in this.props[item]) {
        	        options[itemTwo] = this.props[item][itemTwo];
  			  }
  		  } else {
  			  if(properties.indexOf(item) !== -1) {
      		        options[item] = this.props[item];
  			  }
  		  }
  	  }
  	  return options;
	};
    createComponent(options) {
        if(!this.style) {
    	    for (let style in this.props.style) {
      	      JQXLite(this.componentSelector).css(style, this.props.style[style]);
    	    }
        }
        if(this.props.className !== undefined) {
            const classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
    	    JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxMaskedInput(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxMaskedInput('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxMaskedInput(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxMaskedInput('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxMaskedInput('disabled');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxMaskedInput('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxMaskedInput('height');
        }
    };
    mask(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxMaskedInput('mask', arg)
        } else {
            return JQXLite(this.componentSelector).jqxMaskedInput('mask');
        }
    };
    promptChar(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxMaskedInput('promptChar', arg)
        } else {
            return JQXLite(this.componentSelector).jqxMaskedInput('promptChar');
        }
    };
    readOnly(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxMaskedInput('readOnly', arg)
        } else {
            return JQXLite(this.componentSelector).jqxMaskedInput('readOnly');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxMaskedInput('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxMaskedInput('rtl');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxMaskedInput('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxMaskedInput('theme');
        }
    };
    textAlign(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxMaskedInput('textAlign', arg)
        } else {
            return JQXLite(this.componentSelector).jqxMaskedInput('textAlign');
        }
    };
    value(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxMaskedInput('value', arg)
        } else {
            return JQXLite(this.componentSelector).jqxMaskedInput('value');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxMaskedInput('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxMaskedInput('width');
        }
    };
    clear() {
        JQXLite(this.componentSelector).jqxMaskedInput('clear');  
    };
    destroy() {
        JQXLite(this.componentSelector).jqxMaskedInput('destroy');  
    };
    focus() {
        JQXLite(this.componentSelector).jqxMaskedInput('focus');  
    };
    val(value) {
        if (value !== undefined) {
            JQXLite(this.componentSelector).jqxMaskedInput('val',  value)
        } else {
            return JQXLite(this.componentSelector).jqxMaskedInput('val');
        }
    };

    render() {
        return (
            <div id={this.state.id}>{this.props.value}{this.props.children}</div>
        )
    };
};
