// jqwidgets-vue3/vue_jqxresponsivepanel.vue
<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
	import { onUpdated, onMounted } from 'vue';
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxresponsivepanel.js';

    export default {
        props: {
            animationDirection: String,
            animationHideDelay: [String, Number],
            animationShowDelay: Number,
            animationType: String,
            autoClose: {
                default: true,
                type: Boolean
            },
            collapseBreakpoint: Number,
            collapseWidth: Number,
            height: [Number, String],
            initContent: Function,
            theme: String,
            toggleButton: String,
            toggleButtonSize: Number,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        emits: ["close","collapse","expand","open"],
        setup(props, context) {
			const id = "jqxResponsivePanel" + JQXLite.generateID();
			const componentSelector = '#' + id;
            function createComponent(options) {
                if (!props.autoCreate) __createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            }
            function setOptions (options) {
                JQXLite(componentSelector).jqxResponsivePanel(options);
            }
            function getOptions() {
                const usedProps = Object.keys(__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(componentSelector).jqxResponsivePanel(usedProps[i]);
                }
                return resultToReturn;
            }
            function close() {
                JQXLite(componentSelector).jqxResponsivePanel('close');  
            }
            function destroy() {
                JQXLite(componentSelector).jqxResponsivePanel('destroy');  
            }
            function isCollapsed() {
                return JQXLite(componentSelector).jqxResponsivePanel('isCollapsed');  
            }
            function isOpened() {
                return JQXLite(componentSelector).jqxResponsivePanel('isOpened');  
            }
            function open() {
                JQXLite(componentSelector).jqxResponsivePanel('open');  
            }
            function refresh() {
                JQXLite(componentSelector).jqxResponsivePanel('refresh');  
            }
            function render() {
                JQXLite(componentSelector).jqxResponsivePanel('render');  
            }
            function _animationDirection (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxResponsivePanel('animationDirection', arg)
                } else {
                    return JQXLite(componentSelector).jqxResponsivePanel('animationDirection');
                }
            }
            function _animationHideDelay (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxResponsivePanel('animationHideDelay', arg)
                } else {
                    return JQXLite(componentSelector).jqxResponsivePanel('animationHideDelay');
                }
            }
            function _animationShowDelay (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxResponsivePanel('animationShowDelay', arg)
                } else {
                    return JQXLite(componentSelector).jqxResponsivePanel('animationShowDelay');
                }
            }
            function _animationType (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxResponsivePanel('animationType', arg)
                } else {
                    return JQXLite(componentSelector).jqxResponsivePanel('animationType');
                }
            }
            function _autoClose (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxResponsivePanel('autoClose', arg)
                } else {
                    return JQXLite(componentSelector).jqxResponsivePanel('autoClose');
                }
            }
            function _collapseBreakpoint (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxResponsivePanel('collapseBreakpoint', arg)
                } else {
                    return JQXLite(componentSelector).jqxResponsivePanel('collapseBreakpoint');
                }
            }
            function _collapseWidth (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxResponsivePanel('collapseWidth', arg)
                } else {
                    return JQXLite(componentSelector).jqxResponsivePanel('collapseWidth');
                }
            }
            function _height (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxResponsivePanel('height', arg)
                } else {
                    return JQXLite(componentSelector).jqxResponsivePanel('height');
                }
            }
            function _initContent (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxResponsivePanel('initContent', arg)
                } else {
                    return JQXLite(componentSelector).jqxResponsivePanel('initContent');
                }
            }
            function _theme (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxResponsivePanel('theme', arg)
                } else {
                    return JQXLite(componentSelector).jqxResponsivePanel('theme');
                }
            }
            function _toggleButton (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxResponsivePanel('toggleButton', arg)
                } else {
                    return JQXLite(componentSelector).jqxResponsivePanel('toggleButton');
                }
            }
            function _toggleButtonSize (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxResponsivePanel('toggleButtonSize', arg)
                } else {
                    return JQXLite(componentSelector).jqxResponsivePanel('toggleButtonSize');
                }
            }
            function _width (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxResponsivePanel('width', arg)
                } else {
                    return JQXLite(componentSelector).jqxResponsivePanel('width');
                }
            }
            function __createComponent__ (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = __manageProps__();
                JQXLite(componentSelector).jqxResponsivePanel(widgetOptions);
                __wireEvents__();
            }
            function __manageProps__() {
                const widgetProps = ['animationDirection','animationHideDelay','animationShowDelay','animationType','autoClose','collapseBreakpoint','collapseWidth','height','initContent','theme','toggleButton','toggleButtonSize','width'];
                const componentProps = props;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1 && componentProps[prop] !== undefined) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            }
            const options = {
                 get animationDirection() {
                     return _animationDirection();
                 },
                 set animationDirection(newValue) {
                     _animationDirection(newValue);
                 },
                 get animationHideDelay() {
                     return _animationHideDelay();
                 },
                 set animationHideDelay(newValue) {
                     _animationHideDelay(newValue);
                 },
                 get animationShowDelay() {
                     return _animationShowDelay();
                 },
                 set animationShowDelay(newValue) {
                     _animationShowDelay(newValue);
                 },
                 get animationType() {
                     return _animationType();
                 },
                 set animationType(newValue) {
                     _animationType(newValue);
                 },
                 get autoClose() {
                     return _autoClose();
                 },
                 set autoClose(newValue) {
                     _autoClose(newValue);
                 },
                 get collapseBreakpoint() {
                     return _collapseBreakpoint();
                 },
                 set collapseBreakpoint(newValue) {
                     _collapseBreakpoint(newValue);
                 },
                 get collapseWidth() {
                     return _collapseWidth();
                 },
                 set collapseWidth(newValue) {
                     _collapseWidth(newValue);
                 },
                 get height() {
                     return _height();
                 },
                 set height(newValue) {
                     _height(newValue);
                 },
                 get initContent() {
                     return _initContent();
                 },
                 set initContent(newValue) {
                     _initContent(newValue);
                 },
                 get theme() {
                     return _theme();
                 },
                 set theme(newValue) {
                     _theme(newValue);
                 },
                 get toggleButton() {
                     return _toggleButton();
                 },
                 set toggleButton(newValue) {
                     _toggleButton(newValue);
                 },
                 get toggleButtonSize() {
                     return _toggleButtonSize();
                 },
                 set toggleButtonSize(newValue) {
                     _toggleButtonSize(newValue);
                 },
                 get width() {
                     return _width();
                 },
                 set width(newValue) {
                     _width(newValue);
                 },
            }
            function __wireEvents__() {
                const that = context;

                JQXLite(componentSelector).on('close', function (event) { that.emit('close', event); });
                JQXLite(componentSelector).on('collapse', function (event) { that.emit('collapse', event); });
                JQXLite(componentSelector).on('expand', function (event) { that.emit('expand', event); });
                JQXLite(componentSelector).on('open', function (event) { that.emit('open', event); });
            }

			onMounted(() => {
				if (props.autoCreate) __createComponent__();
			})
			onUpdated(() => {
				const widgetOptions = __manageProps__();
				JQXLite(componentSelector).jqxResponsivePanel(widgetOptions);
			})
			return {id, componentSelector, close,destroy,isCollapsed,isOpened,open,refresh,render, setOptions, options, getOptions, createComponent};
        },
    }
</script>

// jqwidgets-react/react_jqxresponsivepanel.js
/*
jQWidgets v5.3.1 (2017-Sep)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxResponsivePanel extends React.Component {
    componentDidMount() {
        let options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        let properties = ['animationDirection','animationHideDelay','animationShowDelay','animationType','autoClose','collapseBreakpoint','collapseWidth','height','initContent','theme','toggleButton','toggleButtonSize','width'];
        let options = {};
        for(let item in this.props) {
              if(item === 'settings') {
                  for(let itemTwo in this.props[item]) {
                      options[itemTwo] = this.props[item][itemTwo];
                      }
                } else {
                      if(properties.indexOf(item) !== -1) {
                        options[item] = this.props[item];
                      }
                }
          }
          return options;
      };
    createComponent(options) {
        if(!this.style) {
              for (let style in this.props.style) {
                  JQXLite(this.componentSelector).css(style, this.props.style[style]);
              }
        }
        if(this.props.className !== undefined) {
            let classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
              JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxResponsivePanel(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxResponsivePanel('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxResponsivePanel(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    animationDirection(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('animationDirection', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('animationDirection');
        }
    };
    animationHideDelay(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('animationHideDelay', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('animationHideDelay');
        }
    };
    animationShowDelay(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('animationShowDelay', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('animationShowDelay');
        }
    };
    animationType(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('animationType', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('animationType');
        }
    };
    autoClose(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('autoClose', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('autoClose');
        }
    };
    collapseBreakpoint(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('collapseBreakpoint', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('collapseBreakpoint');
        }
    };
    collapseWidth(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('collapseWidth', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('collapseWidth');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('height');
        }
    };
    initContent(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('initContent', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('initContent');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('theme');
        }
    };
    toggleButton(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('toggleButton', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('toggleButton');
        }
    };
    toggleButtonSize(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('toggleButtonSize', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('toggleButtonSize');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxResponsivePanel('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxResponsivePanel('width');
        }
    };
    close() {
        JQXLite(this.componentSelector).jqxResponsivePanel('close');  
    };
    destroy() {
        JQXLite(this.componentSelector).jqxResponsivePanel('destroy');  
    };
    isCollapsed() {
        return JQXLite(this.componentSelector).jqxResponsivePanel('isCollapsed');  
    };
    isOpened() {
        return JQXLite(this.componentSelector).jqxResponsivePanel('isOpened');  
    };
    open() {
        JQXLite(this.componentSelector).jqxResponsivePanel('open');  
    };
    refresh() {
        JQXLite(this.componentSelector).jqxResponsivePanel('refresh');  
    };
    performRender() {
        JQXLite(this.componentSelector).jqxResponsivePanel('render');
    };
    render() {
        let id = 'jqxResponsivePanel' + JQXLite.generateID();
        this.componentSelector = '#' + id;
        return (
            <div id={id}>{this.props.value}{this.props.children}</div>
        )
    };
};
