// jqwidgets-vue/vue_jqxvalidator.vue
/*
jQWidgets v6.1.0 (2018-October)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxvalidator.js';

    export default {
        props: {
            arrow: Boolean,
            animation: String,
            animationDuration: Number,
            closeOnClick: Boolean,
            focus: Boolean,
            hintType: String,
            onError: Function,
            onSuccess: Function,
            position: String,
            rules: Array,
            rtl: Boolean,
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxValidator' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxValidator(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxValidator(usedProps[i]);
                }
                return resultToReturn;
            },
            hideHint: function(id) {
                JQXLite(this.componentSelector).jqxValidator('hideHint', id);  
            },
            hide: function() {
                JQXLite(this.componentSelector).jqxValidator('hide');  
            },
            updatePosition: function() {
                JQXLite(this.componentSelector).jqxValidator('updatePosition');  
            },
            validate: function(htmlElement) {
                JQXLite(this.componentSelector).jqxValidator('validate', htmlElement);  
            },
            validateInput: function(id) {
                JQXLite(this.componentSelector).jqxValidator('validateInput', id);  
            },
            _arrow: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxValidator('arrow', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxValidator('arrow');
                }
            },
            _animation: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxValidator('animation', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxValidator('animation');
                }
            },
            _animationDuration: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxValidator('animationDuration', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxValidator('animationDuration');
                }
            },
            _closeOnClick: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxValidator('closeOnClick', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxValidator('closeOnClick');
                }
            },
            _focus: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxValidator('focus', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxValidator('focus');
                }
            },
            _hintType: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxValidator('hintType', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxValidator('hintType');
                }
            },
            _onError: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxValidator('onError', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxValidator('onError');
                }
            },
            _onSuccess: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxValidator('onSuccess', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxValidator('onSuccess');
                }
            },
            _position: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxValidator('position', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxValidator('position');
                }
            },
            _rules: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxValidator('rules', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxValidator('rules');
                }
            },
            _rtl: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxValidator('rtl', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxValidator('rtl');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxValidator(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['arrow','animation','animationDuration','closeOnClick','focus','hintType','onError','onSuccess','position','rules','rtl'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'arrow', {
                    get() {
                        return that._arrow();
                    },
                    set(newValue) {
                        that._arrow(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'animation', {
                    get() {
                        return that._animation();
                    },
                    set(newValue) {
                        that._animation(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'animationDuration', {
                    get() {
                        return that._animationDuration();
                    },
                    set(newValue) {
                        that._animationDuration(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'closeOnClick', {
                    get() {
                        return that._closeOnClick();
                    },
                    set(newValue) {
                        that._closeOnClick(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'focus', {
                    get() {
                        return that._focus();
                    },
                    set(newValue) {
                        that._focus(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'hintType', {
                    get() {
                        return that._hintType();
                    },
                    set(newValue) {
                        that._hintType(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'onError', {
                    get() {
                        return that._onError();
                    },
                    set(newValue) {
                        that._onError(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'onSuccess', {
                    get() {
                        return that._onSuccess();
                    },
                    set(newValue) {
                        that._onSuccess(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'position', {
                    get() {
                        return that._position();
                    },
                    set(newValue) {
                        that._position(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'rules', {
                    get() {
                        return that._rules();
                    },
                    set(newValue) {
                        that._rules(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'rtl', {
                    get() {
                        return that._rtl();
                    },
                    set(newValue) {
                        that._rtl(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __wireEvents__: function () {
                const that = this;

                JQXLite(this.componentSelector).on('validationError', function (event) { that.$emit('validationError', event); });
                JQXLite(this.componentSelector).on('validationSuccess', function (event) { that.$emit('validationSuccess', event); });
            }
        }
    }
</script>

// jqwidgets-react/react_jqxvalidator.js
/*
jQWidgets v6.1.0 (2018-October)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxvalidator.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxValidator extends React.Component {
    constructor(props) {
        super(props);
        const widgetId = 'jqxValidator' + JQXLite.generateID();
        this.componentSelector = '#' + widgetId;
        this.state = { id: widgetId };
    };
    componentDidMount() {
        const options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        const properties = ['arrow','animation','animationDuration','closeOnClick','focus','hintType','onError','onSuccess','position','rules','rtl'];
        let options = {};
        for(let item in this.props) {
            if(item === 'settings') {
                for(let itemTwo in this.props[item]) {
                    options[itemTwo] = this.props[item][itemTwo];
                }
            } else {
                if(properties.indexOf(item) !== -1) {
                      options[item] = this.props[item];
                }
            }
        }
        return options;
    };
    createComponent(options) {
        if(!this.style) {
            for (let style in this.props.style) {
                JQXLite(this.componentSelector).css(style, this.props.style[style]);
            }
        }
        if(this.props.className !== undefined) {
            const classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
            JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxValidator(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxValidator('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxValidator(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    arrow(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('arrow', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('arrow');
        }
    };
    animation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('animation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('animation');
        }
    };
    animationDuration(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('animationDuration', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('animationDuration');
        }
    };
    closeOnClick(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('closeOnClick', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('closeOnClick');
        }
    };
    focus(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('focus', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('focus');
        }
    };
    hintType(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('hintType', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('hintType');
        }
    };
    onError(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('onError', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('onError');
        }
    };
    onSuccess(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('onSuccess', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('onSuccess');
        }
    };
    position(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('position', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('position');
        }
    };
    rules(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('rules', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('rules');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('rtl');
        }
    };
    hideHint(id) {
        JQXLite(this.componentSelector).jqxValidator('hideHint', id);  
    };
    hide() {
        JQXLite(this.componentSelector).jqxValidator('hide');  
    };
    updatePosition() {
        JQXLite(this.componentSelector).jqxValidator('updatePosition');  
    };
    validate(htmlElement) {
        JQXLite(this.componentSelector).jqxValidator('validate', htmlElement);  
    };
    validateInput(id) {
        JQXLite(this.componentSelector).jqxValidator('validateInput', id);  
    };
    render() {
        return (
            <div id={this.state.id}>{this.props.value}{this.props.children}</div>
        )
    };
};
