// jqwidgets-ts/angular_jqxvalidator.ts
/// <reference path="jqwidgets.d.ts" />
import {Component, Input, Output, EventEmitter, ElementRef, forwardRef} from '@angular/core';
declare let $: any;

@Component({
    selector: 'angularValidator',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxValidatorComponent {
   @Input('width') containerWidth: any;
   @Input('height') containerHeight: any;

   elementRef: ElementRef;
   host;
   widgetObject:  jqwidgets.jqxValidator;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   isHostReady(): boolean {
       return (this.host !== undefined && this.host.length == 1);
   }

   createWidget(options: any): void {
      if (!this.isHostReady()) {

         this.host = $(this.elementRef.nativeElement.firstChild);
         this.__wireEvents__();
         this.widgetObject = jqwidgets.createInstance(this.host, 'jqxValidator', options);
         this.__updateRect__();

      }
   }

   __updateRect__() : void {
      this.host.css({width: this.containerWidth, height: this.containerHeight});
   }

   setOptions(options: any) : void {
      this.host.jqxValidator('setOptions', options);
   }

   // jqxValidatorComponent properties
   arrow(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxValidator('arrow', arg);
      } else {
          return this.host.jqxValidator('arrow');
      }
   }

   animation(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxValidator('animation', arg);
      } else {
          return this.host.jqxValidator('animation');
      }
   }

   animationDuration(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxValidator('animationDuration', arg);
      } else {
          return this.host.jqxValidator('animationDuration');
      }
   }

   closeOnClick(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxValidator('closeOnClick', arg);
      } else {
          return this.host.jqxValidator('closeOnClick');
      }
   }

   focus(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxValidator('focus', arg);
      } else {
          return this.host.jqxValidator('focus');
      }
   }

   hintType(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxValidator('hintType', arg);
      } else {
          return this.host.jqxValidator('hintType');
      }
   }

   onError(arg?: () => void) : any {
      if (arg !== undefined) {
          this.host.jqxValidator('onError', arg);
      } else {
          return this.host.jqxValidator('onError');
      }
   }

   onSuccess(arg?: () => void) : any {
      if (arg !== undefined) {
          this.host.jqxValidator('onSuccess', arg);
      } else {
          return this.host.jqxValidator('onSuccess');
      }
   }

   position(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxValidator('position', arg);
      } else {
          return this.host.jqxValidator('position');
      }
   }

   rules(arg?: Array<jqwidgets.ValidatorRule>) : any {
      if (arg !== undefined) {
          this.host.jqxValidator('rules', arg);
      } else {
          return this.host.jqxValidator('rules');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxValidator('rtl', arg);
      } else {
          return this.host.jqxValidator('rtl');
      }
   }


   // jqxValidatorComponent functions
   hideHint(id: string): void {
      this.host.jqxValidator('hideHint', id);

   }
   hide(): void {
      this.host.jqxValidator('hide');

   }
   updatePosition(): void {
      this.host.jqxValidator('updatePosition');

   }
   validate(htmlElement: any): void {
      this.host.jqxValidator('validate', htmlElement);

   }
   validateInput(id: string): void {
      this.host.jqxValidator('validateInput', id);

   }

   // jqxValidatorComponent events
   @Output() OnValidationError = new EventEmitter();
   @Output() OnValidationSuccess = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('validationError', (eventData) => { this.OnValidationError.emit(eventData); });
      this.host.on('validationSuccess', (eventData) => { this.OnValidationSuccess.emit(eventData); });
   }

} //jqxValidatorComponent

// jqwidgets-react/react_jqxvalidator.js
import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxvalidator.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxValidator extends React.Component {
    constructor(props) {
        super(props);
        const widgetId = 'jqxValidator' + JQXLite.generateID();
        this.componentSelector = '#' + widgetId;
        this.state = { id: widgetId };
    };
    componentDidMount() {
        const options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        const properties = ['arrow','animation','animationDuration','closeOnClick','focus','hintType','onError','onSuccess','position','rules','rtl'];
        let options = {};
        for(let item in this.props) {
    	    if(item === 'settings') {
      	      for(let itemTwo in this.props[item]) {
        	        options[itemTwo] = this.props[item][itemTwo];
  			  }
  		  } else {
  			  if(properties.indexOf(item) !== -1) {
      		        options[item] = this.props[item];
  			  }
  		  }
  	  }
  	  return options;
	};
    createComponent(options) {
        if(!this.style) {
    	    for (let style in this.props.style) {
      	      JQXLite(this.componentSelector).css(style, this.props.style[style]);
    	    }
        }
        if(this.props.className !== undefined) {
            const classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
    	    JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxValidator(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxValidator('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxValidator(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    arrow(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('arrow', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('arrow');
        }
    };
    animation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('animation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('animation');
        }
    };
    animationDuration(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('animationDuration', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('animationDuration');
        }
    };
    closeOnClick(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('closeOnClick', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('closeOnClick');
        }
    };
    focus(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('focus', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('focus');
        }
    };
    hintType(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('hintType', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('hintType');
        }
    };
    onError(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('onError', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('onError');
        }
    };
    onSuccess(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('onSuccess', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('onSuccess');
        }
    };
    position(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('position', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('position');
        }
    };
    rules(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('rules', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('rules');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxValidator('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxValidator('rtl');
        }
    };
    hideHint(id) {
        JQXLite(this.componentSelector).jqxValidator('hideHint', id);  
    };
    hide() {
        JQXLite(this.componentSelector).jqxValidator('hide');  
    };
    updatePosition() {
        JQXLite(this.componentSelector).jqxValidator('updatePosition');  
    };
    validate(htmlElement) {
        JQXLite(this.componentSelector).jqxValidator('validate', htmlElement);  
    };
    validateInput(id) {
        JQXLite(this.componentSelector).jqxValidator('validateInput', id);  
    };
    render() {
        return (
            <div id={this.state.id}>{this.props.value}{this.props.children}</div>
        )
    };
};
