// jqwidgets-ts/angular_jqxrangeselector.ts
/*
jQWidgets v5.5.0 (2017-Dec)
Copyright (c) 2011-2017 jQWidgets.
License: https://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxdata.js';
import '../jqwidgets/jqxtooltip.js';
import '../jqwidgets/jqxrangeselector.js';
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges, ChangeDetectionStrategy } from '@angular/core';
declare let JQXLite: any;

@Component({
    selector: 'jqxRangeSelector',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxRangeSelectorComponent implements OnChanges
{
   @Input('disabled') attrDisabled: boolean;
   @Input('showGroupLabels') attrShowGroupLabels: boolean;
   @Input('labelsOnTicks') attrLabelsOnTicks: boolean;
   @Input('markersFormatFunction') attrMarkersFormatFunction: any;
   @Input('labelsFormat') attrLabelsFormat: any;
   @Input('labelsFormatFunction') attrLabelsFormatFunction: any;
   @Input('labelPrecision') attrLabelPrecision: number;
   @Input('moveOnClick') attrMoveOnClick: boolean;
   @Input('markerRenderer') attrMarkerRenderer: any;
   @Input('markerPrecision') attrMarkerPrecision: number;
   @Input('majorLabelRenderer') attrMajorLabelRenderer: any;
   @Input('markersFormat') attrMarkersFormat: any;
   @Input('majorTicksInterval') attrMajorTicksInterval: string | number;
   @Input('minorTicksInterval') attrMinorTicksInterval: number;
   @Input('max') attrMax: string | number;
   @Input('min') attrMin: string | number;
   @Input('padding') attrPadding: number | string;
   @Input('range') attrRange: jqwidgets.RangeSelectorRange;
   @Input('resizable') attrResizable: boolean;
   @Input('rtl') attrRtl: boolean;
   @Input('showMinorTicks') attrShowMinorTicks: boolean;
   @Input('snapToTicks') attrSnapToTicks: boolean;
   @Input('showMajorLabels') attrShowMajorLabels: boolean;
   @Input('showMarkers') attrShowMarkers: boolean;
   @Input('theme') attrTheme: string;
   @Input('width') attrWidth: string | number;
   @Input('height') attrHeight: string | number;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['disabled','showGroupLabels','labelsOnTicks','markersFormatFunction','height','labelsFormat','labelsFormatFunction','labelPrecision','moveOnClick','markerRenderer','markerPrecision','majorLabelRenderer','markersFormat','majorTicksInterval','minorTicksInterval','max','min','padding','range','resizable','rtl','showMinorTicks','snapToTicks','showMajorLabels','showMarkers','theme','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxRangeSelector;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean = false;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxRangeSelector(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxRangeSelector(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxRangeSelector(this.properties[i])) {
                  this.host.jqxRangeSelector(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void {
      let classes: any = parentEl.classList;
      if (classes.length > 0) {
        childEl.classList.add(...classes);
      }
      parentEl.className = '';
   }

   moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void {
      let style = parentEl.style.cssText;
      childEl.style.cssText = style
      parentEl.style.cssText = '';
   }

   createComponent(options?: any): void {
      if (options) {
         JQXLite.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = JQXLite(this.elementRef.nativeElement.firstChild);

      this.moveClasses(this.elementRef.nativeElement, this.host[0]);
      this.moveStyles(this.elementRef.nativeElement, this.host[0]);

      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxRangeSelector', options);

      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   setOptions(options: any) : void {
      this.host.jqxRangeSelector('setOptions', options);
   }

   // jqxRangeSelectorComponent properties
   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('disabled', arg);
      } else {
          return this.host.jqxRangeSelector('disabled');
      }
   }

   showGroupLabels(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('showGroupLabels', arg);
      } else {
          return this.host.jqxRangeSelector('showGroupLabels');
      }
   }

   labelsOnTicks(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('labelsOnTicks', arg);
      } else {
          return this.host.jqxRangeSelector('labelsOnTicks');
      }
   }

   markersFormatFunction(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('markersFormatFunction', arg);
      } else {
          return this.host.jqxRangeSelector('markersFormatFunction');
      }
   }

   height(arg?: string | number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('height', arg);
      } else {
          return this.host.jqxRangeSelector('height');
      }
   }

   labelsFormat(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('labelsFormat', arg);
      } else {
          return this.host.jqxRangeSelector('labelsFormat');
      }
   }

   labelsFormatFunction(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('labelsFormatFunction', arg);
      } else {
          return this.host.jqxRangeSelector('labelsFormatFunction');
      }
   }

   labelPrecision(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('labelPrecision', arg);
      } else {
          return this.host.jqxRangeSelector('labelPrecision');
      }
   }

   moveOnClick(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('moveOnClick', arg);
      } else {
          return this.host.jqxRangeSelector('moveOnClick');
      }
   }

   markerRenderer(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('markerRenderer', arg);
      } else {
          return this.host.jqxRangeSelector('markerRenderer');
      }
   }

   markerPrecision(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('markerPrecision', arg);
      } else {
          return this.host.jqxRangeSelector('markerPrecision');
      }
   }

   majorLabelRenderer(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('majorLabelRenderer', arg);
      } else {
          return this.host.jqxRangeSelector('majorLabelRenderer');
      }
   }

   markersFormat(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('markersFormat', arg);
      } else {
          return this.host.jqxRangeSelector('markersFormat');
      }
   }

   majorTicksInterval(arg?: string | number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('majorTicksInterval', arg);
      } else {
          return this.host.jqxRangeSelector('majorTicksInterval');
      }
   }

   minorTicksInterval(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('minorTicksInterval', arg);
      } else {
          return this.host.jqxRangeSelector('minorTicksInterval');
      }
   }

   max(arg?: string | number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('max', arg);
      } else {
          return this.host.jqxRangeSelector('max');
      }
   }

   min(arg?: string | number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('min', arg);
      } else {
          return this.host.jqxRangeSelector('min');
      }
   }

   padding(arg?: number | string) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('padding', arg);
      } else {
          return this.host.jqxRangeSelector('padding');
      }
   }

   range(arg?: jqwidgets.RangeSelectorRange) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('range', arg);
      } else {
          return this.host.jqxRangeSelector('range');
      }
   }

   resizable(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('resizable', arg);
      } else {
          return this.host.jqxRangeSelector('resizable');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('rtl', arg);
      } else {
          return this.host.jqxRangeSelector('rtl');
      }
   }

   showMinorTicks(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('showMinorTicks', arg);
      } else {
          return this.host.jqxRangeSelector('showMinorTicks');
      }
   }

   snapToTicks(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('snapToTicks', arg);
      } else {
          return this.host.jqxRangeSelector('snapToTicks');
      }
   }

   showMajorLabels(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('showMajorLabels', arg);
      } else {
          return this.host.jqxRangeSelector('showMajorLabels');
      }
   }

   showMarkers(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('showMarkers', arg);
      } else {
          return this.host.jqxRangeSelector('showMarkers');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('theme', arg);
      } else {
          return this.host.jqxRangeSelector('theme');
      }
   }

   width(arg?: string | number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('width', arg);
      } else {
          return this.host.jqxRangeSelector('width');
      }
   }


   // jqxRangeSelectorComponent functions
   destroy(): void {
      this.host.jqxRangeSelector('destroy');
   }

   getRange(): jqwidgets.RangeSelectorGetRange {
      return this.host.jqxRangeSelector('getRange');
   }

   render(): void {
      this.host.jqxRangeSelector('render');
   }

   refresh(): void {
      this.host.jqxRangeSelector('refresh');
   }

   setRange(from: any, to: any): void {
      this.host.jqxRangeSelector('setRange', from, to);
   }


   // jqxRangeSelectorComponent events
   @Output() onChange = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('change', (eventData: any) => { this.onChange.emit(eventData); });
   }

} //jqxRangeSelectorComponent

// jqwidgets-react/react_jqxrangeselector.js
/*
jQWidgets v6.2.0 (2018-Dec)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxdata.js';
import '../jqwidgets/jqxtooltip.js';
import '../jqwidgets/jqxrangeselector.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxRangeSelector extends React.Component {
    constructor(props) {
        super(props);
        const widgetId = 'jqxRangeSelector' + JQXLite.generateID();
        this.componentSelector = '#' + widgetId;
        this.state = { id: widgetId };
    };
    componentDidMount() {
        const options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        const properties = ['disabled','showGroupLabels','labelsOnTicks','markersFormatFunction','height','labelsFormat','labelsFormatFunction','labelPrecision','moveOnClick','markerRenderer','markerPrecision','majorLabelRenderer','markersFormat','majorTicksInterval','minorTicksInterval','max','min','padding','range','resizable','rtl','showMinorTicks','snapToTicks','showMajorLabels','showMarkers','theme','width'];
        let options = {};
        for(let item in this.props) {
            if(item === 'settings') {
                for(let itemTwo in this.props[item]) {
                    options[itemTwo] = this.props[item][itemTwo];
                }
            } else {
                if(properties.indexOf(item) !== -1) {
                      options[item] = this.props[item];
                }
            }
        }
        return options;
    };
    createComponent(options) {
        if(!this.style) {
            for (let style in this.props.style) {
                JQXLite(this.componentSelector).css(style, this.props.style[style]);
            }
        }
        if(this.props.className !== undefined) {
            const classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
            JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxRangeSelector(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxRangeSelector('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxRangeSelector(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('disabled');
        }
    };
    showGroupLabels(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('showGroupLabels', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('showGroupLabels');
        }
    };
    labelsOnTicks(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('labelsOnTicks', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('labelsOnTicks');
        }
    };
    markersFormatFunction(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('markersFormatFunction', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('markersFormatFunction');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('height');
        }
    };
    labelsFormat(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('labelsFormat', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('labelsFormat');
        }
    };
    labelsFormatFunction(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('labelsFormatFunction', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('labelsFormatFunction');
        }
    };
    labelPrecision(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('labelPrecision', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('labelPrecision');
        }
    };
    moveOnClick(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('moveOnClick', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('moveOnClick');
        }
    };
    markerRenderer(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('markerRenderer', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('markerRenderer');
        }
    };
    markerPrecision(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('markerPrecision', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('markerPrecision');
        }
    };
    majorLabelRenderer(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('majorLabelRenderer', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('majorLabelRenderer');
        }
    };
    markersFormat(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('markersFormat', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('markersFormat');
        }
    };
    majorTicksInterval(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('majorTicksInterval', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('majorTicksInterval');
        }
    };
    minorTicksInterval(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('minorTicksInterval', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('minorTicksInterval');
        }
    };
    max(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('max', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('max');
        }
    };
    min(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('min', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('min');
        }
    };
    padding(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('padding', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('padding');
        }
    };
    range(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('range', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('range');
        }
    };
    resizable(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('resizable', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('resizable');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('rtl');
        }
    };
    showMinorTicks(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('showMinorTicks', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('showMinorTicks');
        }
    };
    snapToTicks(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('snapToTicks', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('snapToTicks');
        }
    };
    showMajorLabels(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('showMajorLabels', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('showMajorLabels');
        }
    };
    showMarkers(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('showMarkers', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('showMarkers');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('theme');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxRangeSelector('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxRangeSelector('width');
        }
    };
    destroy() {
        JQXLite(this.componentSelector).jqxRangeSelector('destroy');  
    };
    getRange() {
        return JQXLite(this.componentSelector).jqxRangeSelector('getRange');  
    };
    performRender() {
        JQXLite(this.componentSelector).jqxRangeSelector('render');
    };
    refresh() {
        JQXLite(this.componentSelector).jqxRangeSelector('refresh');  
    };
    setRange(from, to) {
        JQXLite(this.componentSelector).jqxRangeSelector('setRange', from, to);  
    };
    render() {
        return (
            <div id={this.state.id}>{this.props.value}{this.props.children}</div>
        )
    };
};
