// jqwidgets-vue3/vue_jqxswitchbutton.vue
<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
	import { onUpdated, onMounted } from 'vue';
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxswitchbutton.js';

    export default {
        props: {
            modelValue: String,
            checked: {
                default: false,
                type: Boolean
            },
            disabled: {
                default: false,
                type: Boolean
            },
            height: [Number, String],
            orientation: String,
            onLabel: String,
            offLabel: String,
            thumbSize: String,
            rtl: {
                default: false,
                type: Boolean
            },
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        emits: ["update:modelValue","checked","change","unchecked"],
        setup(props, context) {
			const id = "jqxSwitchButton" + JQXLite.generateID();
			const componentSelector = '#' + id;
            function createComponent(options) {
                if (!props.autoCreate) __createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            }
            function setOptions (options) {
                JQXLite(componentSelector).jqxSwitchButton(options);
            }
            function getOptions() {
                const usedProps = Object.keys(__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(componentSelector).jqxSwitchButton(usedProps[i]);
                }
                return resultToReturn;
            }
            function check() {
                JQXLite(componentSelector).jqxSwitchButton('check');  
            }
            function disable() {
                JQXLite(componentSelector).jqxSwitchButton('disable');  
            }
            function enable() {
                JQXLite(componentSelector).jqxSwitchButton('enable');  
            }
            function toggle() {
                JQXLite(componentSelector).jqxSwitchButton('toggle');  
            }
            function uncheck() {
                JQXLite(componentSelector).jqxSwitchButton('uncheck');  
            }
            function val(value) {
                if (value !== undefined) {
                    JQXLite(componentSelector).jqxSwitchButton('val',  value)
                } else {
                    return JQXLite(componentSelector).jqxSwitchButton('val');
                }
            }
            function _checked (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSwitchButton('checked', arg)
                } else {
                    return JQXLite(componentSelector).jqxSwitchButton('checked');
                }
            }
            function _disabled (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSwitchButton('disabled', arg)
                } else {
                    return JQXLite(componentSelector).jqxSwitchButton('disabled');
                }
            }
            function _height (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSwitchButton('height', arg)
                } else {
                    return JQXLite(componentSelector).jqxSwitchButton('height');
                }
            }
            function _orientation (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSwitchButton('orientation', arg)
                } else {
                    return JQXLite(componentSelector).jqxSwitchButton('orientation');
                }
            }
            function _onLabel (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSwitchButton('onLabel', arg)
                } else {
                    return JQXLite(componentSelector).jqxSwitchButton('onLabel');
                }
            }
            function _offLabel (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSwitchButton('offLabel', arg)
                } else {
                    return JQXLite(componentSelector).jqxSwitchButton('offLabel');
                }
            }
            function _thumbSize (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSwitchButton('thumbSize', arg)
                } else {
                    return JQXLite(componentSelector).jqxSwitchButton('thumbSize');
                }
            }
            function _rtl (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSwitchButton('rtl', arg)
                } else {
                    return JQXLite(componentSelector).jqxSwitchButton('rtl');
                }
            }
            function _width (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSwitchButton('width', arg)
                } else {
                    return JQXLite(componentSelector).jqxSwitchButton('width');
                }
            }
            function __createComponent__ (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = __manageProps__();
                JQXLite(componentSelector).jqxSwitchButton(widgetOptions);
                __wireEvents__();
            }
            function __manageProps__() {
                const widgetProps = ['checked','disabled','height','orientation','onLabel','offLabel','thumbSize','rtl','width'];
                const componentProps = props;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1 && componentProps[prop] !== undefined) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            }
            const options = {
                 get checked() {
                     return _checked();
                 },
                 set checked(newValue) {
                     _checked(newValue);
                 },
                 get disabled() {
                     return _disabled();
                 },
                 set disabled(newValue) {
                     _disabled(newValue);
                 },
                 get height() {
                     return _height();
                 },
                 set height(newValue) {
                     _height(newValue);
                 },
                 get orientation() {
                     return _orientation();
                 },
                 set orientation(newValue) {
                     _orientation(newValue);
                 },
                 get onLabel() {
                     return _onLabel();
                 },
                 set onLabel(newValue) {
                     _onLabel(newValue);
                 },
                 get offLabel() {
                     return _offLabel();
                 },
                 set offLabel(newValue) {
                     _offLabel(newValue);
                 },
                 get thumbSize() {
                     return _thumbSize();
                 },
                 set thumbSize(newValue) {
                     _thumbSize(newValue);
                 },
                 get rtl() {
                     return _rtl();
                 },
                 set rtl(newValue) {
                     _rtl(newValue);
                 },
                 get width() {
                     return _width();
                 },
                 set width(newValue) {
                     _width(newValue);
                 },
            }
            function twoWayBinding() {
                const value = JQXLite(componentSelector).jqxSwitchButton('val');
                context.emit('input', value);
                context.emit('update:modelValue', element.value);
            }
            function __wireEvents__() {
                const that = context;

                JQXLite(componentSelector).on('checked', function (event) { that.emit('checked', event); });
                JQXLite(componentSelector).on('change', function (event) { that.emit('change', event); twoWayBinding(); });
                JQXLite(componentSelector).on('unchecked', function (event) { that.emit('unchecked', event); });
            }

			onMounted(() => {
				if (props.autoCreate) __createComponent__();
			})
			onUpdated(() => {
				const widgetOptions = __manageProps__();
				JQXLite(componentSelector).jqxSwitchButton(widgetOptions);
			})
			return {id, componentSelector, check,disable,enable,toggle,uncheck,val,twoWayBinding, setOptions, options, getOptions, createComponent};
        },
    }
</script>

// jqwidgets-react/react_jqxswitchbutton.js
/*
jQWidgets v6.0.5 (2018-July)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxswitchbutton.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxSwitchButton extends React.Component {
    componentDidMount() {
        let options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        let properties = ['checked','disabled','height','orientation','onLabel','offLabel','thumbSize','rtl','width'];
        let options = {};
        for(let item in this.props) {
              if(item === 'settings') {
                  for(let itemTwo in this.props[item]) {
                      options[itemTwo] = this.props[item][itemTwo];
                      }
                } else {
                      if(properties.indexOf(item) !== -1) {
                        options[item] = this.props[item];
                      }
                }
          }
          return options;
      };
    createComponent(options) {
        if(!this.style) {
              for (let style in this.props.style) {
                  JQXLite(this.componentSelector).css(style, this.props.style[style]);
              }
        }
        if(this.props.className !== undefined) {
            let classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
              JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxSwitchButton(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxSwitchButton('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxSwitchButton(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    checked(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSwitchButton('checked', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSwitchButton('checked');
        }
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSwitchButton('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSwitchButton('disabled');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSwitchButton('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSwitchButton('height');
        }
    };
    orientation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSwitchButton('orientation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSwitchButton('orientation');
        }
    };
    onLabel(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSwitchButton('onLabel', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSwitchButton('onLabel');
        }
    };
    offLabel(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSwitchButton('offLabel', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSwitchButton('offLabel');
        }
    };
    thumbSize(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSwitchButton('thumbSize', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSwitchButton('thumbSize');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSwitchButton('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSwitchButton('rtl');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSwitchButton('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSwitchButton('width');
        }
    };
    check() {
        JQXLite(this.componentSelector).jqxSwitchButton('check');  
    };
    disable() {
        JQXLite(this.componentSelector).jqxSwitchButton('disable');  
    };
    enable() {
        JQXLite(this.componentSelector).jqxSwitchButton('enable');  
    };
    toggle() {
        JQXLite(this.componentSelector).jqxSwitchButton('toggle');  
    };
    uncheck() {
        JQXLite(this.componentSelector).jqxSwitchButton('uncheck');  
    };
    val(value) {
        if (value !== undefined) {
            JQXLite(this.componentSelector).jqxSwitchButton('val',  value)
        } else {
            return JQXLite(this.componentSelector).jqxSwitchButton('val');
        }
    };

    render() {
        let id = 'jqxSwitchButton' + JQXLite.generateID();
        this.componentSelector = '#' + id;
        return (
            <div id={id}>{this.props.value}{this.props.children}</div>
        )
    };
};
