// jqwidgets-vue/vue_jqxeditor.vue
/*
jQWidgets v6.1.0 (2018-October)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxdata.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxscrollbar.js';
    import '../jqwidgets/jqxlistbox.js';
    import '../jqwidgets/jqxdropdownlist.js';
    import '../jqwidgets/jqxdropdownbutton.js';
    import '../jqwidgets/jqxwindow.js';
    import '../jqwidgets/jqxeditor.js';
    import '../jqwidgets/jqxcheckbox.js';
    import '../jqwidgets/jqxtooltip.js';
    import '../jqwidgets/jqxcolorpicker.js';

    export default {
        props: {
            createCommand: Function,
            disabled: Boolean,
            editable: Boolean,
            height: [Number, String],
            lineBreak: String,
            localization: Object,
            pasteMode: String,
            rtl: Boolean,
            stylesheets: Array,
            theme: String,
            toolbarPosition: String,
            tools: String,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxEditor' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxEditor(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxEditor(usedProps[i]);
                }
                return resultToReturn;
            },
            destroy: function() {
                JQXLite(this.componentSelector).jqxEditor('destroy');  
            },
            focus: function() {
                JQXLite(this.componentSelector).jqxEditor('focus');  
            },
            print: function() {
                JQXLite(this.componentSelector).jqxEditor('print');  
            },
            setMode: function(mode) {
                JQXLite(this.componentSelector).jqxEditor('setMode', mode);  
            },
            val: function(value) {
                if (value !== undefined) {
                    JQXLite(this.componentSelector).jqxEditor('val',  value)
                } else {
                    return JQXLite(this.componentSelector).jqxEditor('val');
                }
            },
            _createCommand: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxEditor('createCommand', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxEditor('createCommand');
                }
            },
            _disabled: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxEditor('disabled', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxEditor('disabled');
                }
            },
            _editable: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxEditor('editable', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxEditor('editable');
                }
            },
            _height: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxEditor('height', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxEditor('height');
                }
            },
            _lineBreak: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxEditor('lineBreak', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxEditor('lineBreak');
                }
            },
            _localization: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxEditor('localization', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxEditor('localization');
                }
            },
            _pasteMode: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxEditor('pasteMode', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxEditor('pasteMode');
                }
            },
            _rtl: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxEditor('rtl', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxEditor('rtl');
                }
            },
            _stylesheets: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxEditor('stylesheets', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxEditor('stylesheets');
                }
            },
            _theme: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxEditor('theme', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxEditor('theme');
                }
            },
            _toolbarPosition: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxEditor('toolbarPosition', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxEditor('toolbarPosition');
                }
            },
            _tools: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxEditor('tools', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxEditor('tools');
                }
            },
            _width: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxEditor('width', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxEditor('width');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxEditor(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['createCommand','disabled','editable','height','lineBreak','localization','pasteMode','rtl','stylesheets','theme','toolbarPosition','tools','width'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'createCommand', {
                    get() {
                        return that._createCommand();
                    },
                    set(newValue) {
                        that._createCommand(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'disabled', {
                    get() {
                        return that._disabled();
                    },
                    set(newValue) {
                        that._disabled(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'editable', {
                    get() {
                        return that._editable();
                    },
                    set(newValue) {
                        that._editable(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'height', {
                    get() {
                        return that._height();
                    },
                    set(newValue) {
                        that._height(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'lineBreak', {
                    get() {
                        return that._lineBreak();
                    },
                    set(newValue) {
                        that._lineBreak(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'localization', {
                    get() {
                        return that._localization();
                    },
                    set(newValue) {
                        that._localization(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'pasteMode', {
                    get() {
                        return that._pasteMode();
                    },
                    set(newValue) {
                        that._pasteMode(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'rtl', {
                    get() {
                        return that._rtl();
                    },
                    set(newValue) {
                        that._rtl(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'stylesheets', {
                    get() {
                        return that._stylesheets();
                    },
                    set(newValue) {
                        that._stylesheets(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'theme', {
                    get() {
                        return that._theme();
                    },
                    set(newValue) {
                        that._theme(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'toolbarPosition', {
                    get() {
                        return that._toolbarPosition();
                    },
                    set(newValue) {
                        that._toolbarPosition(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'tools', {
                    get() {
                        return that._tools();
                    },
                    set(newValue) {
                        that._tools(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'width', {
                    get() {
                        return that._width();
                    },
                    set(newValue) {
                        that._width(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __wireEvents__: function () {
                const that = this;

                JQXLite(this.componentSelector).on('change', function (event) { that.$emit('change', event); });
            }
        }
    }
</script>

// jqwidgets-react/react_jqxeditor.js
/*
jQWidgets v6.0.5 (2018-July)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxdata.js';
import '../jqwidgets/jqxbuttons.js';
import '../jqwidgets/jqxscrollbar.js';
import '../jqwidgets/jqxlistbox.js';
import '../jqwidgets/jqxdropdownlist.js';
import '../jqwidgets/jqxdropdownbutton.js';
import '../jqwidgets/jqxwindow.js';
import '../jqwidgets/jqxeditor.js';
import '../jqwidgets/jqxcheckbox.js';
import '../jqwidgets/jqxtooltip.js';
import '../jqwidgets/jqxcolorpicker.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxEditor extends React.Component {
    componentDidMount() {
        let options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        let properties = ['createCommand','disabled','editable','height','lineBreak','localization','pasteMode','rtl','stylesheets','theme','toolbarPosition','tools','width'];
        let options = {};
        for(let item in this.props) {
              if(item === 'settings') {
                  for(let itemTwo in this.props[item]) {
                      options[itemTwo] = this.props[item][itemTwo];
                      }
                } else {
                      if(properties.indexOf(item) !== -1) {
                        options[item] = this.props[item];
                      }
                }
          }
          return options;
      };
    createComponent(options) {
        if(!this.style) {
              for (let style in this.props.style) {
                  JQXLite(this.componentSelector).css(style, this.props.style[style]);
              }
        }
        if(this.props.className !== undefined) {
            let classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
              JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxEditor(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxEditor('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxEditor(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    createCommand(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxEditor('createCommand', arg)
        } else {
            return JQXLite(this.componentSelector).jqxEditor('createCommand');
        }
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxEditor('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxEditor('disabled');
        }
    };
    editable(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxEditor('editable', arg)
        } else {
            return JQXLite(this.componentSelector).jqxEditor('editable');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxEditor('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxEditor('height');
        }
    };
    lineBreak(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxEditor('lineBreak', arg)
        } else {
            return JQXLite(this.componentSelector).jqxEditor('lineBreak');
        }
    };
    localization(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxEditor('localization', arg)
        } else {
            return JQXLite(this.componentSelector).jqxEditor('localization');
        }
    };
    pasteMode(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxEditor('pasteMode', arg)
        } else {
            return JQXLite(this.componentSelector).jqxEditor('pasteMode');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxEditor('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxEditor('rtl');
        }
    };
    stylesheets(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxEditor('stylesheets', arg)
        } else {
            return JQXLite(this.componentSelector).jqxEditor('stylesheets');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxEditor('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxEditor('theme');
        }
    };
    toolbarPosition(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxEditor('toolbarPosition', arg)
        } else {
            return JQXLite(this.componentSelector).jqxEditor('toolbarPosition');
        }
    };
    tools(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxEditor('tools', arg)
        } else {
            return JQXLite(this.componentSelector).jqxEditor('tools');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxEditor('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxEditor('width');
        }
    };
    destroy() {
        JQXLite(this.componentSelector).jqxEditor('destroy');  
    };
    focus() {
        JQXLite(this.componentSelector).jqxEditor('focus');  
    };
    print() {
        JQXLite(this.componentSelector).jqxEditor('print');  
    };
    setMode(mode) {
        JQXLite(this.componentSelector).jqxEditor('setMode', mode);  
    };
    val(value) {
        if (value !== undefined) {
            JQXLite(this.componentSelector).jqxEditor('val',  value)
        } else {
            return JQXLite(this.componentSelector).jqxEditor('val');
        }
    };

    render() {
        let id = 'jqxEditor' + JQXLite.generateID();
        this.componentSelector = '#' + id;
        return (
            <div id={id}>{this.props.value}{this.props.children}</div>
        )
    };
};
