// jqwidgets-vue3/vue_jqxbulletchart.vue
<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
	import { onUpdated, onMounted } from 'vue';
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxdata.js';
    import '../jqwidgets/jqxtooltip.js';
    import '../jqwidgets/jqxbulletchart.js';

    export default {
        props: {
            animationDuration: Number,
            barSize: [String, Number],
            description: String,
            disabled: {
                default: false,
                type: Boolean
            },
            height: [Number, String],
            labelsFormat: String,
            labelsFormatFunction: Function,
            orientation: String,
            pointer: Object,
            rtl: {
                default: false,
                type: Boolean
            },
            ranges: Array,
            showTooltip: {
                default: true,
                type: Boolean
            },
            target: Object,
            ticks: Object,
            title: String,
            tooltipFormatFunction: Function,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        emits: ["change"],
        setup(props, context) {
			const id = "jqxBulletChart" + JQXLite.generateID();
			const componentSelector = '#' + id;
            function createComponent(options) {
                if (!props.autoCreate) __createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            }
            function setOptions (options) {
                JQXLite(componentSelector).jqxBulletChart(options);
            }
            function getOptions() {
                const usedProps = Object.keys(__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(componentSelector).jqxBulletChart(usedProps[i]);
                }
                return resultToReturn;
            }
            function destroy() {
                JQXLite(componentSelector).jqxBulletChart('destroy');  
            }
            function render() {
                JQXLite(componentSelector).jqxBulletChart('render');  
            }
            function refresh() {
                JQXLite(componentSelector).jqxBulletChart('refresh');  
            }
            function val(value) {
                if (value !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('val',  value)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('val');
                }
            }
            function _animationDuration (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('animationDuration', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('animationDuration');
                }
            }
            function _barSize (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('barSize', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('barSize');
                }
            }
            function _description (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('description', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('description');
                }
            }
            function _disabled (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('disabled', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('disabled');
                }
            }
            function _height (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('height', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('height');
                }
            }
            function _labelsFormat (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('labelsFormat', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('labelsFormat');
                }
            }
            function _labelsFormatFunction (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('labelsFormatFunction', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('labelsFormatFunction');
                }
            }
            function _orientation (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('orientation', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('orientation');
                }
            }
            function _pointer (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('pointer', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('pointer');
                }
            }
            function _rtl (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('rtl', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('rtl');
                }
            }
            function _ranges (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('ranges', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('ranges');
                }
            }
            function _showTooltip (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('showTooltip', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('showTooltip');
                }
            }
            function _target (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('target', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('target');
                }
            }
            function _ticks (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('ticks', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('ticks');
                }
            }
            function _title (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('title', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('title');
                }
            }
            function _tooltipFormatFunction (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('tooltipFormatFunction', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('tooltipFormatFunction');
                }
            }
            function _width (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxBulletChart('width', arg)
                } else {
                    return JQXLite(componentSelector).jqxBulletChart('width');
                }
            }
            function __createComponent__ (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = __manageProps__();
                JQXLite(componentSelector).jqxBulletChart(widgetOptions);
                __wireEvents__();
            }
            function __manageProps__() {
                const widgetProps = ['animationDuration','barSize','description','disabled','height','labelsFormat','labelsFormatFunction','orientation','pointer','rtl','ranges','showTooltip','target','ticks','title','tooltipFormatFunction','width'];
                const componentProps = props;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1 && componentProps[prop] !== undefined) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            }
            const options = {
                 get animationDuration() {
                     return _animationDuration();
                 },
                 set animationDuration(newValue) {
                     _animationDuration(newValue);
                 },
                 get barSize() {
                     return _barSize();
                 },
                 set barSize(newValue) {
                     _barSize(newValue);
                 },
                 get description() {
                     return _description();
                 },
                 set description(newValue) {
                     _description(newValue);
                 },
                 get disabled() {
                     return _disabled();
                 },
                 set disabled(newValue) {
                     _disabled(newValue);
                 },
                 get height() {
                     return _height();
                 },
                 set height(newValue) {
                     _height(newValue);
                 },
                 get labelsFormat() {
                     return _labelsFormat();
                 },
                 set labelsFormat(newValue) {
                     _labelsFormat(newValue);
                 },
                 get labelsFormatFunction() {
                     return _labelsFormatFunction();
                 },
                 set labelsFormatFunction(newValue) {
                     _labelsFormatFunction(newValue);
                 },
                 get orientation() {
                     return _orientation();
                 },
                 set orientation(newValue) {
                     _orientation(newValue);
                 },
                 get pointer() {
                     return _pointer();
                 },
                 set pointer(newValue) {
                     _pointer(newValue);
                 },
                 get rtl() {
                     return _rtl();
                 },
                 set rtl(newValue) {
                     _rtl(newValue);
                 },
                 get ranges() {
                     return _ranges();
                 },
                 set ranges(newValue) {
                     _ranges(newValue);
                 },
                 get showTooltip() {
                     return _showTooltip();
                 },
                 set showTooltip(newValue) {
                     _showTooltip(newValue);
                 },
                 get target() {
                     return _target();
                 },
                 set target(newValue) {
                     _target(newValue);
                 },
                 get ticks() {
                     return _ticks();
                 },
                 set ticks(newValue) {
                     _ticks(newValue);
                 },
                 get title() {
                     return _title();
                 },
                 set title(newValue) {
                     _title(newValue);
                 },
                 get tooltipFormatFunction() {
                     return _tooltipFormatFunction();
                 },
                 set tooltipFormatFunction(newValue) {
                     _tooltipFormatFunction(newValue);
                 },
                 get width() {
                     return _width();
                 },
                 set width(newValue) {
                     _width(newValue);
                 },
            }
            function __wireEvents__() {
                const that = context;

                JQXLite(componentSelector).on('change', function (event) { that.emit('change', event); });
            }

			onMounted(() => {
				if (props.autoCreate) __createComponent__();
			})
			onUpdated(() => {
				const widgetOptions = __manageProps__();
				JQXLite(componentSelector).jqxBulletChart(widgetOptions);
			})
			return {id, componentSelector, destroy,render,refresh,val, setOptions, options, getOptions, createComponent};
        },
    }
</script>

// jqwidgets-ng/esm2015/jqxbulletchart/angular_jqxbulletchart.js
import '../jqwidgets/jqxcore';
import '../jqwidgets/jqxdata';
import '../jqwidgets/jqxtooltip';
import '../jqwidgets/jqxbulletchart';
/// <reference path="../../jqwidgets.d.ts" />
import * as tslib_1 from "tslib";
import { Component, Input, Output, EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
let jqxBulletChartComponent = class jqxBulletChartComponent {
    constructor(containerElement) {
        this.autoCreate = true;
        this.properties = ['animationDuration', 'barSize', 'description', 'disabled', 'height', 'labelsFormat', 'labelsFormatFunction', 'orientation', 'pointer', 'rtl', 'ranges', 'showTooltip', 'target', 'ticks', 'title', 'tooltipFormatFunction', 'width'];
        // jqxBulletChartComponent events
        this.onChange = new EventEmitter();
        this.elementRef = containerElement;
    }
    ngOnInit() {
        if (this.autoCreate) {
            this.createComponent();
        }
    }
    ;
    ngOnChanges(changes) {
        if (this.host) {
            for (let i = 0; i < this.properties.length; i++) {
                let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
                let areEqual = false;
                if (this[attrName] !== undefined) {
                    if (typeof this[attrName] === 'object') {
                        if (this[attrName] instanceof Array) {
                            areEqual = this.arraysEqual(this[attrName], this.host.jqxBulletChart(this.properties[i]));
                        }
                        if (areEqual) {
                            return false;
                        }
                        this.host.jqxBulletChart(this.properties[i], this[attrName]);
                        continue;
                    }
                    if (this[attrName] !== this.host.jqxBulletChart(this.properties[i])) {
                        this.host.jqxBulletChart(this.properties[i], this[attrName]);
                    }
                }
            }
        }
    }
    arraysEqual(attrValue, hostValue) {
        if ((attrValue && !hostValue) || (!attrValue && hostValue)) {
            return false;
        }
        if (attrValue.length != hostValue.length) {
            return false;
        }
        for (let i = 0; i < attrValue.length; i++) {
            if (attrValue[i] !== hostValue[i]) {
                return false;
            }
        }
        return true;
    }
    manageAttributes() {
        let options = {};
        for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            if (this[attrName] !== undefined) {
                options[this.properties[i]] = this[attrName];
            }
        }
        return options;
    }
    moveClasses(parentEl, childEl) {
        let classes = parentEl.classList;
        if (classes.length > 0) {
            childEl.classList.add(...classes);
        }
        parentEl.className = '';
    }
    moveStyles(parentEl, childEl) {
        let style = parentEl.style.cssText;
        childEl.style.cssText = style;
        parentEl.style.cssText = '';
    }
    createComponent(options) {
        if (this.host) {
            return;
        }
        if (options) {
            JQXLite.extend(options, this.manageAttributes());
        }
        else {
            options = this.manageAttributes();
        }
        this.host = JQXLite(this.elementRef.nativeElement.firstChild);
        this.moveClasses(this.elementRef.nativeElement, this.host[0]);
        this.moveStyles(this.elementRef.nativeElement, this.host[0]);
        this.__wireEvents__();
        this.widgetObject = jqwidgets.createInstance(this.host, 'jqxBulletChart', options);
    }
    createWidget(options) {
        this.createComponent(options);
    }
    __updateRect__() {
        if (this.host)
            this.host.css({ width: this.attrWidth, height: this.attrHeight });
    }
    setOptions(options) {
        this.host.jqxBulletChart('setOptions', options);
    }
    // jqxBulletChartComponent properties
    animationDuration(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('animationDuration', arg);
        }
        else {
            return this.host.jqxBulletChart('animationDuration');
        }
    }
    barSize(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('barSize', arg);
        }
        else {
            return this.host.jqxBulletChart('barSize');
        }
    }
    description(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('description', arg);
        }
        else {
            return this.host.jqxBulletChart('description');
        }
    }
    disabled(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('disabled', arg);
        }
        else {
            return this.host.jqxBulletChart('disabled');
        }
    }
    height(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('height', arg);
        }
        else {
            return this.host.jqxBulletChart('height');
        }
    }
    labelsFormat(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('labelsFormat', arg);
        }
        else {
            return this.host.jqxBulletChart('labelsFormat');
        }
    }
    labelsFormatFunction(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('labelsFormatFunction', arg);
        }
        else {
            return this.host.jqxBulletChart('labelsFormatFunction');
        }
    }
    orientation(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('orientation', arg);
        }
        else {
            return this.host.jqxBulletChart('orientation');
        }
    }
    pointer(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('pointer', arg);
        }
        else {
            return this.host.jqxBulletChart('pointer');
        }
    }
    rtl(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('rtl', arg);
        }
        else {
            return this.host.jqxBulletChart('rtl');
        }
    }
    ranges(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('ranges', arg);
        }
        else {
            return this.host.jqxBulletChart('ranges');
        }
    }
    showTooltip(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('showTooltip', arg);
        }
        else {
            return this.host.jqxBulletChart('showTooltip');
        }
    }
    target(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('target', arg);
        }
        else {
            return this.host.jqxBulletChart('target');
        }
    }
    ticks(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('ticks', arg);
        }
        else {
            return this.host.jqxBulletChart('ticks');
        }
    }
    title(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('title', arg);
        }
        else {
            return this.host.jqxBulletChart('title');
        }
    }
    tooltipFormatFunction(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('tooltipFormatFunction', arg);
        }
        else {
            return this.host.jqxBulletChart('tooltipFormatFunction');
        }
    }
    width(arg) {
        if (arg !== undefined) {
            this.host.jqxBulletChart('width', arg);
        }
        else {
            return this.host.jqxBulletChart('width');
        }
    }
    // jqxBulletChartComponent functions
    destroy() {
        this.host.jqxBulletChart('destroy');
    }
    render() {
        this.host.jqxBulletChart('render');
    }
    refresh() {
        this.host.jqxBulletChart('refresh');
    }
    val(value) {
        if (value !== undefined) {
            return this.host.jqxBulletChart('val', value);
        }
        else {
            return this.host.jqxBulletChart('val');
        }
    }
    ;
    __wireEvents__() {
        this.host.on('change', (eventData) => { this.onChange.emit(eventData); });
    }
}; //jqxBulletChartComponent
jqxBulletChartComponent.ctorParameters = () => [
    { type: ElementRef }
];
tslib_1.__decorate([
    Input('animationDuration'),
    tslib_1.__metadata("design:type", Number)
], jqxBulletChartComponent.prototype, "attrAnimationDuration", void 0);
tslib_1.__decorate([
    Input('barSize'),
    tslib_1.__metadata("design:type", Object)
], jqxBulletChartComponent.prototype, "attrBarSize", void 0);
tslib_1.__decorate([
    Input('description'),
    tslib_1.__metadata("design:type", String)
], jqxBulletChartComponent.prototype, "attrDescription", void 0);
tslib_1.__decorate([
    Input('disabled'),
    tslib_1.__metadata("design:type", Boolean)
], jqxBulletChartComponent.prototype, "attrDisabled", void 0);
tslib_1.__decorate([
    Input('labelsFormat'),
    tslib_1.__metadata("design:type", String)
], jqxBulletChartComponent.prototype, "attrLabelsFormat", void 0);
tslib_1.__decorate([
    Input('labelsFormatFunction'),
    tslib_1.__metadata("design:type", Function)
], jqxBulletChartComponent.prototype, "attrLabelsFormatFunction", void 0);
tslib_1.__decorate([
    Input('orientation'),
    tslib_1.__metadata("design:type", String)
], jqxBulletChartComponent.prototype, "attrOrientation", void 0);
tslib_1.__decorate([
    Input('pointer'),
    tslib_1.__metadata("design:type", Object)
], jqxBulletChartComponent.prototype, "attrPointer", void 0);
tslib_1.__decorate([
    Input('rtl'),
    tslib_1.__metadata("design:type", Boolean)
], jqxBulletChartComponent.prototype, "attrRtl", void 0);
tslib_1.__decorate([
    Input('ranges'),
    tslib_1.__metadata("design:type", Array)
], jqxBulletChartComponent.prototype, "attrRanges", void 0);
tslib_1.__decorate([
    Input('showTooltip'),
    tslib_1.__metadata("design:type", Boolean)
], jqxBulletChartComponent.prototype, "attrShowTooltip", void 0);
tslib_1.__decorate([
    Input('target'),
    tslib_1.__metadata("design:type", Object)
], jqxBulletChartComponent.prototype, "attrTarget", void 0);
tslib_1.__decorate([
    Input('ticks'),
    tslib_1.__metadata("design:type", Object)
], jqxBulletChartComponent.prototype, "attrTicks", void 0);
tslib_1.__decorate([
    Input('title'),
    tslib_1.__metadata("design:type", String)
], jqxBulletChartComponent.prototype, "attrTitle", void 0);
tslib_1.__decorate([
    Input('tooltipFormatFunction'),
    tslib_1.__metadata("design:type", Function)
], jqxBulletChartComponent.prototype, "attrTooltipFormatFunction", void 0);
tslib_1.__decorate([
    Input('width'),
    tslib_1.__metadata("design:type", Object)
], jqxBulletChartComponent.prototype, "attrWidth", void 0);
tslib_1.__decorate([
    Input('height'),
    tslib_1.__metadata("design:type", Object)
], jqxBulletChartComponent.prototype, "attrHeight", void 0);
tslib_1.__decorate([
    Input('auto-create'),
    tslib_1.__metadata("design:type", Boolean)
], jqxBulletChartComponent.prototype, "autoCreate", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxBulletChartComponent.prototype, "onChange", void 0);
jqxBulletChartComponent = tslib_1.__decorate([
    Component({
        selector: 'jqxBulletChart',
        template: '<div><ng-content></ng-content></div>'
    }),
    tslib_1.__metadata("design:paramtypes", [ElementRef])
], jqxBulletChartComponent);
export { jqxBulletChartComponent };
