// jqwidgets-ng/esm2015/jqxslider/angular_jqxslider.js
import '../jqwidgets/jqxcore';
import '../jqwidgets/jqxbuttons';
import '../jqwidgets/jqxslider';
/// <reference path="../../jqwidgets.d.ts" />
import * as tslib_1 from "tslib";
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges, ChangeDetectionStrategy } from '@angular/core';
import { NG_VALUE_ACCESSOR } from '@angular/forms';
const noop = () => { };
const ɵ0 = noop;
const CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => jqxSliderComponent),
    multi: true
};
let jqxSliderComponent = class jqxSliderComponent {
    constructor(containerElement) {
        this.autoCreate = true;
        this.properties = ['buttonsPosition', 'disabled', 'height', 'layout', 'mode', 'minorTicksFrequency', 'minorTickSize', 'max', 'min', 'orientation', 'rangeSlider', 'rtl', 'step', 'showTicks', 'showMinorTicks', 'showTickLabels', 'showButtons', 'showRange', 'template', 'theme', 'ticksPosition', 'ticksFrequency', 'tickSize', 'tickLabelFormatFunction', 'tooltip', 'tooltipHideDelay', 'tooltipPosition', 'tooltipFormatFunction', 'value', 'values', 'width'];
        this.onTouchedCallback = noop;
        this.onChangeCallback = noop;
        // jqxSliderComponent events
        this.onChange = new EventEmitter();
        this.onSlide = new EventEmitter();
        this.onSlideStart = new EventEmitter();
        this.onSlideEnd = new EventEmitter();
        this.elementRef = containerElement;
    }
    ngOnInit() {
        if (this.autoCreate) {
            this.createComponent();
        }
    }
    ;
    ngOnChanges(changes) {
        if (this.host) {
            for (let i = 0; i < this.properties.length; i++) {
                let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
                let areEqual = false;
                if (this[attrName] !== undefined) {
                    if (typeof this[attrName] === 'object') {
                        if (this[attrName] instanceof Array) {
                            areEqual = this.arraysEqual(this[attrName], this.host.jqxSlider(this.properties[i]));
                        }
                        if (areEqual) {
                            return false;
                        }
                        this.host.jqxSlider(this.properties[i], this[attrName]);
                        continue;
                    }
                    if (this[attrName] !== this.host.jqxSlider(this.properties[i])) {
                        this.host.jqxSlider(this.properties[i], this[attrName]);
                    }
                }
            }
        }
    }
    arraysEqual(attrValue, hostValue) {
        if ((attrValue && !hostValue) || (!attrValue && hostValue)) {
            return false;
        }
        if (attrValue.length != hostValue.length) {
            return false;
        }
        for (let i = 0; i < attrValue.length; i++) {
            if (attrValue[i] !== hostValue[i]) {
                return false;
            }
        }
        return true;
    }
    manageAttributes() {
        let options = {};
        for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            if (this[attrName] !== undefined) {
                options[this.properties[i]] = this[attrName];
            }
        }
        return options;
    }
    moveClasses(parentEl, childEl) {
        let classes = parentEl.classList;
        if (classes.length > 0) {
            childEl.classList.add(...classes);
        }
        parentEl.className = '';
    }
    moveStyles(parentEl, childEl) {
        let style = parentEl.style.cssText;
        childEl.style.cssText = style;
        parentEl.style.cssText = '';
    }
    createComponent(options) {
        if (this.host) {
            return;
        }
        if (options) {
            JQXLite.extend(options, this.manageAttributes());
        }
        else {
            options = this.manageAttributes();
        }
        this.host = JQXLite(this.elementRef.nativeElement.firstChild);
        this.moveClasses(this.elementRef.nativeElement, this.host[0]);
        this.moveStyles(this.elementRef.nativeElement, this.host[0]);
        this.__wireEvents__();
        this.widgetObject = jqwidgets.createInstance(this.host, 'jqxSlider', options);
    }
    createWidget(options) {
        this.createComponent(options);
    }
    __updateRect__() {
        if (this.host)
            this.host.css({ width: this.attrWidth, height: this.attrHeight });
    }
    get ngValue() {
        if (this.widgetObject) {
            const value = this.host.val();
            return value;
        }
        return '';
    }
    set ngValue(value) {
        if (this.widgetObject) {
            this.onChangeCallback(value);
        }
    }
    writeValue(value) {
        if (this.widgetObject) {
            this.onChangeCallback(this.host.val());
        }
    }
    registerOnChange(fn) {
        this.onChangeCallback = fn;
    }
    registerOnTouched(fn) {
        this.onTouchedCallback = fn;
    }
    setOptions(options) {
        this.host.jqxSlider('setOptions', options);
    }
    // jqxSliderComponent properties
    buttonsPosition(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('buttonsPosition', arg);
        }
        else {
            return this.host.jqxSlider('buttonsPosition');
        }
    }
    disabled(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('disabled', arg);
        }
        else {
            return this.host.jqxSlider('disabled');
        }
    }
    height(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('height', arg);
        }
        else {
            return this.host.jqxSlider('height');
        }
    }
    layout(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('layout', arg);
        }
        else {
            return this.host.jqxSlider('layout');
        }
    }
    mode(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('mode', arg);
        }
        else {
            return this.host.jqxSlider('mode');
        }
    }
    minorTicksFrequency(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('minorTicksFrequency', arg);
        }
        else {
            return this.host.jqxSlider('minorTicksFrequency');
        }
    }
    minorTickSize(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('minorTickSize', arg);
        }
        else {
            return this.host.jqxSlider('minorTickSize');
        }
    }
    max(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('max', arg);
        }
        else {
            return this.host.jqxSlider('max');
        }
    }
    min(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('min', arg);
        }
        else {
            return this.host.jqxSlider('min');
        }
    }
    orientation(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('orientation', arg);
        }
        else {
            return this.host.jqxSlider('orientation');
        }
    }
    rangeSlider(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('rangeSlider', arg);
        }
        else {
            return this.host.jqxSlider('rangeSlider');
        }
    }
    rtl(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('rtl', arg);
        }
        else {
            return this.host.jqxSlider('rtl');
        }
    }
    step(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('step', arg);
        }
        else {
            return this.host.jqxSlider('step');
        }
    }
    showTicks(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('showTicks', arg);
        }
        else {
            return this.host.jqxSlider('showTicks');
        }
    }
    showMinorTicks(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('showMinorTicks', arg);
        }
        else {
            return this.host.jqxSlider('showMinorTicks');
        }
    }
    showTickLabels(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('showTickLabels', arg);
        }
        else {
            return this.host.jqxSlider('showTickLabels');
        }
    }
    showButtons(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('showButtons', arg);
        }
        else {
            return this.host.jqxSlider('showButtons');
        }
    }
    showRange(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('showRange', arg);
        }
        else {
            return this.host.jqxSlider('showRange');
        }
    }
    template(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('template', arg);
        }
        else {
            return this.host.jqxSlider('template');
        }
    }
    theme(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('theme', arg);
        }
        else {
            return this.host.jqxSlider('theme');
        }
    }
    ticksPosition(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('ticksPosition', arg);
        }
        else {
            return this.host.jqxSlider('ticksPosition');
        }
    }
    ticksFrequency(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('ticksFrequency', arg);
        }
        else {
            return this.host.jqxSlider('ticksFrequency');
        }
    }
    tickSize(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('tickSize', arg);
        }
        else {
            return this.host.jqxSlider('tickSize');
        }
    }
    tickLabelFormatFunction(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('tickLabelFormatFunction', arg);
        }
        else {
            return this.host.jqxSlider('tickLabelFormatFunction');
        }
    }
    tooltip(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('tooltip', arg);
        }
        else {
            return this.host.jqxSlider('tooltip');
        }
    }
    tooltipHideDelay(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('tooltipHideDelay', arg);
        }
        else {
            return this.host.jqxSlider('tooltipHideDelay');
        }
    }
    tooltipPosition(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('tooltipPosition', arg);
        }
        else {
            return this.host.jqxSlider('tooltipPosition');
        }
    }
    tooltipFormatFunction(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('tooltipFormatFunction', arg);
        }
        else {
            return this.host.jqxSlider('tooltipFormatFunction');
        }
    }
    value(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('value', arg);
        }
        else {
            return this.host.jqxSlider('value');
        }
    }
    values(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('values', arg);
        }
        else {
            return this.host.jqxSlider('values');
        }
    }
    width(arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('width', arg);
        }
        else {
            return this.host.jqxSlider('width');
        }
    }
    // jqxSliderComponent functions
    destroy() {
        this.host.jqxSlider('destroy');
    }
    decrementValue() {
        this.host.jqxSlider('decrementValue');
    }
    disable() {
        this.host.jqxSlider('disable');
    }
    enable() {
        this.host.jqxSlider('enable');
    }
    focus() {
        this.host.jqxSlider('focus');
    }
    getValue() {
        return this.host.jqxSlider('getValue');
    }
    incrementValue() {
        this.host.jqxSlider('incrementValue');
    }
    setValue(index) {
        this.host.jqxSlider('setValue', index);
    }
    val(value) {
        if (value !== undefined) {
            return this.host.jqxSlider('val', value);
        }
        else {
            return this.host.jqxSlider('val');
        }
    }
    ;
    __wireEvents__() {
        this.host.on('change', (eventData) => { this.onChange.emit(eventData); this.onChangeCallback(this.host.val()); });
        this.host.on('slide', (eventData) => { this.onSlide.emit(eventData); });
        this.host.on('slideStart', (eventData) => { this.onSlideStart.emit(eventData); });
        this.host.on('slideEnd', (eventData) => { this.onSlideEnd.emit(eventData); });
    }
}; //jqxSliderComponent
jqxSliderComponent.ctorParameters = () => [
    { type: ElementRef }
];
tslib_1.__decorate([
    Input('buttonsPosition'),
    tslib_1.__metadata("design:type", String)
], jqxSliderComponent.prototype, "attrButtonsPosition", void 0);
tslib_1.__decorate([
    Input('disabled'),
    tslib_1.__metadata("design:type", Boolean)
], jqxSliderComponent.prototype, "attrDisabled", void 0);
tslib_1.__decorate([
    Input('layout'),
    tslib_1.__metadata("design:type", String)
], jqxSliderComponent.prototype, "attrLayout", void 0);
tslib_1.__decorate([
    Input('mode'),
    tslib_1.__metadata("design:type", String)
], jqxSliderComponent.prototype, "attrMode", void 0);
tslib_1.__decorate([
    Input('minorTicksFrequency'),
    tslib_1.__metadata("design:type", Number)
], jqxSliderComponent.prototype, "attrMinorTicksFrequency", void 0);
tslib_1.__decorate([
    Input('minorTickSize'),
    tslib_1.__metadata("design:type", Number)
], jqxSliderComponent.prototype, "attrMinorTickSize", void 0);
tslib_1.__decorate([
    Input('max'),
    tslib_1.__metadata("design:type", Number)
], jqxSliderComponent.prototype, "attrMax", void 0);
tslib_1.__decorate([
    Input('min'),
    tslib_1.__metadata("design:type", Number)
], jqxSliderComponent.prototype, "attrMin", void 0);
tslib_1.__decorate([
    Input('orientation'),
    tslib_1.__metadata("design:type", String)
], jqxSliderComponent.prototype, "attrOrientation", void 0);
tslib_1.__decorate([
    Input('rangeSlider'),
    tslib_1.__metadata("design:type", Boolean)
], jqxSliderComponent.prototype, "attrRangeSlider", void 0);
tslib_1.__decorate([
    Input('rtl'),
    tslib_1.__metadata("design:type", Boolean)
], jqxSliderComponent.prototype, "attrRtl", void 0);
tslib_1.__decorate([
    Input('step'),
    tslib_1.__metadata("design:type", Number)
], jqxSliderComponent.prototype, "attrStep", void 0);
tslib_1.__decorate([
    Input('showTicks'),
    tslib_1.__metadata("design:type", Boolean)
], jqxSliderComponent.prototype, "attrShowTicks", void 0);
tslib_1.__decorate([
    Input('showMinorTicks'),
    tslib_1.__metadata("design:type", Boolean)
], jqxSliderComponent.prototype, "attrShowMinorTicks", void 0);
tslib_1.__decorate([
    Input('showTickLabels'),
    tslib_1.__metadata("design:type", Boolean)
], jqxSliderComponent.prototype, "attrShowTickLabels", void 0);
tslib_1.__decorate([
    Input('showButtons'),
    tslib_1.__metadata("design:type", Boolean)
], jqxSliderComponent.prototype, "attrShowButtons", void 0);
tslib_1.__decorate([
    Input('showRange'),
    tslib_1.__metadata("design:type", Boolean)
], jqxSliderComponent.prototype, "attrShowRange", void 0);
tslib_1.__decorate([
    Input('template'),
    tslib_1.__metadata("design:type", String)
], jqxSliderComponent.prototype, "attrTemplate", void 0);
tslib_1.__decorate([
    Input('theme'),
    tslib_1.__metadata("design:type", String)
], jqxSliderComponent.prototype, "attrTheme", void 0);
tslib_1.__decorate([
    Input('ticksPosition'),
    tslib_1.__metadata("design:type", String)
], jqxSliderComponent.prototype, "attrTicksPosition", void 0);
tslib_1.__decorate([
    Input('ticksFrequency'),
    tslib_1.__metadata("design:type", Number)
], jqxSliderComponent.prototype, "attrTicksFrequency", void 0);
tslib_1.__decorate([
    Input('tickSize'),
    tslib_1.__metadata("design:type", Number)
], jqxSliderComponent.prototype, "attrTickSize", void 0);
tslib_1.__decorate([
    Input('tickLabelFormatFunction'),
    tslib_1.__metadata("design:type", Function)
], jqxSliderComponent.prototype, "attrTickLabelFormatFunction", void 0);
tslib_1.__decorate([
    Input('tooltip'),
    tslib_1.__metadata("design:type", Boolean)
], jqxSliderComponent.prototype, "attrTooltip", void 0);
tslib_1.__decorate([
    Input('tooltipHideDelay'),
    tslib_1.__metadata("design:type", Number)
], jqxSliderComponent.prototype, "attrTooltipHideDelay", void 0);
tslib_1.__decorate([
    Input('tooltipPosition'),
    tslib_1.__metadata("design:type", String)
], jqxSliderComponent.prototype, "attrTooltipPosition", void 0);
tslib_1.__decorate([
    Input('tooltipFormatFunction'),
    tslib_1.__metadata("design:type", Function)
], jqxSliderComponent.prototype, "attrTooltipFormatFunction", void 0);
tslib_1.__decorate([
    Input('value'),
    tslib_1.__metadata("design:type", Object)
], jqxSliderComponent.prototype, "attrValue", void 0);
tslib_1.__decorate([
    Input('values'),
    tslib_1.__metadata("design:type", Array)
], jqxSliderComponent.prototype, "attrValues", void 0);
tslib_1.__decorate([
    Input('width'),
    tslib_1.__metadata("design:type", Object)
], jqxSliderComponent.prototype, "attrWidth", void 0);
tslib_1.__decorate([
    Input('height'),
    tslib_1.__metadata("design:type", Object)
], jqxSliderComponent.prototype, "attrHeight", void 0);
tslib_1.__decorate([
    Input('auto-create'),
    tslib_1.__metadata("design:type", Boolean)
], jqxSliderComponent.prototype, "autoCreate", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxSliderComponent.prototype, "onChange", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxSliderComponent.prototype, "onSlide", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxSliderComponent.prototype, "onSlideStart", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxSliderComponent.prototype, "onSlideEnd", void 0);
jqxSliderComponent = tslib_1.__decorate([
    Component({
        selector: 'jqxSlider',
        template: '<div><ng-content></ng-content></div>',
        providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR],
        changeDetection: ChangeDetectionStrategy.OnPush
    }),
    tslib_1.__metadata("design:paramtypes", [ElementRef])
], jqxSliderComponent);
export { jqxSliderComponent };
export { ɵ0 };

// jqwidgets-vue3/vue_jqxslider.vue
<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
	import { onUpdated, onMounted } from 'vue';
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxslider.js';

    export default {
        props: {
            modelValue: String,
            buttonsPosition: String,
            disabled: {
                default: false,
                type: Boolean
            },
            height: [Number, String],
            layout: String,
            mode: String,
            minorTicksFrequency: Number,
            minorTickSize: Number,
            max: Number,
            min: Number,
            orientation: String,
            rangeSlider: {
                default: false,
                type: Boolean
            },
            rtl: {
                default: false,
                type: Boolean
            },
            step: Number,
            showTicks: {
                default: true,
                type: Boolean
            },
            showMinorTicks: {
                default: false,
                type: Boolean
            },
            showTickLabels: {
                default: false,
                type: Boolean
            },
            showButtons: {
                default: true,
                type: Boolean
            },
            showRange: {
                default: true,
                type: Boolean
            },
            template: String,
            theme: String,
            ticksPosition: String,
            ticksFrequency: Number,
            tickSize: Number,
            tickLabelFormatFunction: Function,
            tooltip: {
                default: false,
                type: Boolean
            },
            tooltipHideDelay: Number,
            tooltipPosition: String,
            tooltipFormatFunction: Function,
            value: Number,
            values: Array,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        emits: ["update:modelValue","change","slide","slideStart","slideEnd"],
        setup(props, context) {
			const id = "jqxSlider" + JQXLite.generateID();
			const componentSelector = '#' + id;
            function createComponent(options) {
                if (!props.autoCreate) __createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            }
            function setOptions (options) {
                JQXLite(componentSelector).jqxSlider(options);
            }
            function getOptions() {
                const usedProps = Object.keys(__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(componentSelector).jqxSlider(usedProps[i]);
                }
                return resultToReturn;
            }
            function destroy() {
                JQXLite(componentSelector).jqxSlider('destroy');  
            }
            function decrementValue() {
                JQXLite(componentSelector).jqxSlider('decrementValue');  
            }
            function disable() {
                JQXLite(componentSelector).jqxSlider('disable');  
            }
            function enable() {
                JQXLite(componentSelector).jqxSlider('enable');  
            }
            function focus() {
                JQXLite(componentSelector).jqxSlider('focus');  
            }
            function getValue() {
                return JQXLite(componentSelector).jqxSlider('getValue');  
            }
            function incrementValue() {
                JQXLite(componentSelector).jqxSlider('incrementValue');  
            }
            function setValue(index) {
                JQXLite(componentSelector).jqxSlider('setValue', index);  
            }
            function val(value) {
                if (value !== undefined) {
                    JQXLite(componentSelector).jqxSlider('val',  value)
                } else {
                    return JQXLite(componentSelector).jqxSlider('val');
                }
            }
            function _buttonsPosition (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('buttonsPosition', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('buttonsPosition');
                }
            }
            function _disabled (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('disabled', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('disabled');
                }
            }
            function _height (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('height', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('height');
                }
            }
            function _layout (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('layout', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('layout');
                }
            }
            function _mode (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('mode', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('mode');
                }
            }
            function _minorTicksFrequency (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('minorTicksFrequency', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('minorTicksFrequency');
                }
            }
            function _minorTickSize (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('minorTickSize', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('minorTickSize');
                }
            }
            function _max (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('max', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('max');
                }
            }
            function _min (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('min', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('min');
                }
            }
            function _orientation (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('orientation', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('orientation');
                }
            }
            function _rangeSlider (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('rangeSlider', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('rangeSlider');
                }
            }
            function _rtl (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('rtl', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('rtl');
                }
            }
            function _step (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('step', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('step');
                }
            }
            function _showTicks (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('showTicks', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('showTicks');
                }
            }
            function _showMinorTicks (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('showMinorTicks', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('showMinorTicks');
                }
            }
            function _showTickLabels (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('showTickLabels', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('showTickLabels');
                }
            }
            function _showButtons (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('showButtons', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('showButtons');
                }
            }
            function _showRange (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('showRange', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('showRange');
                }
            }
            function _template (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('template', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('template');
                }
            }
            function _theme (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('theme', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('theme');
                }
            }
            function _ticksPosition (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('ticksPosition', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('ticksPosition');
                }
            }
            function _ticksFrequency (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('ticksFrequency', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('ticksFrequency');
                }
            }
            function _tickSize (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('tickSize', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('tickSize');
                }
            }
            function _tickLabelFormatFunction (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('tickLabelFormatFunction', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('tickLabelFormatFunction');
                }
            }
            function _tooltip (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('tooltip', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('tooltip');
                }
            }
            function _tooltipHideDelay (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('tooltipHideDelay', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('tooltipHideDelay');
                }
            }
            function _tooltipPosition (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('tooltipPosition', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('tooltipPosition');
                }
            }
            function _tooltipFormatFunction (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('tooltipFormatFunction', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('tooltipFormatFunction');
                }
            }
            function _value (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('value', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('value');
                }
            }
            function _values (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('values', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('values');
                }
            }
            function _width (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSlider('width', arg)
                } else {
                    return JQXLite(componentSelector).jqxSlider('width');
                }
            }
            function __createComponent__ (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = __manageProps__();
                JQXLite(componentSelector).jqxSlider(widgetOptions);
                __wireEvents__();
            }
            function __manageProps__() {
                const widgetProps = ['buttonsPosition','disabled','height','layout','mode','minorTicksFrequency','minorTickSize','max','min','orientation','rangeSlider','rtl','step','showTicks','showMinorTicks','showTickLabels','showButtons','showRange','template','theme','ticksPosition','ticksFrequency','tickSize','tickLabelFormatFunction','tooltip','tooltipHideDelay','tooltipPosition','tooltipFormatFunction','value','values','width'];
                const componentProps = props;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1 && componentProps[prop] !== undefined) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            }
            const options = {
                 get buttonsPosition() {
                     return _buttonsPosition();
                 },
                 set buttonsPosition(newValue) {
                     _buttonsPosition(newValue);
                 },
                 get disabled() {
                     return _disabled();
                 },
                 set disabled(newValue) {
                     _disabled(newValue);
                 },
                 get height() {
                     return _height();
                 },
                 set height(newValue) {
                     _height(newValue);
                 },
                 get layout() {
                     return _layout();
                 },
                 set layout(newValue) {
                     _layout(newValue);
                 },
                 get mode() {
                     return _mode();
                 },
                 set mode(newValue) {
                     _mode(newValue);
                 },
                 get minorTicksFrequency() {
                     return _minorTicksFrequency();
                 },
                 set minorTicksFrequency(newValue) {
                     _minorTicksFrequency(newValue);
                 },
                 get minorTickSize() {
                     return _minorTickSize();
                 },
                 set minorTickSize(newValue) {
                     _minorTickSize(newValue);
                 },
                 get max() {
                     return _max();
                 },
                 set max(newValue) {
                     _max(newValue);
                 },
                 get min() {
                     return _min();
                 },
                 set min(newValue) {
                     _min(newValue);
                 },
                 get orientation() {
                     return _orientation();
                 },
                 set orientation(newValue) {
                     _orientation(newValue);
                 },
                 get rangeSlider() {
                     return _rangeSlider();
                 },
                 set rangeSlider(newValue) {
                     _rangeSlider(newValue);
                 },
                 get rtl() {
                     return _rtl();
                 },
                 set rtl(newValue) {
                     _rtl(newValue);
                 },
                 get step() {
                     return _step();
                 },
                 set step(newValue) {
                     _step(newValue);
                 },
                 get showTicks() {
                     return _showTicks();
                 },
                 set showTicks(newValue) {
                     _showTicks(newValue);
                 },
                 get showMinorTicks() {
                     return _showMinorTicks();
                 },
                 set showMinorTicks(newValue) {
                     _showMinorTicks(newValue);
                 },
                 get showTickLabels() {
                     return _showTickLabels();
                 },
                 set showTickLabels(newValue) {
                     _showTickLabels(newValue);
                 },
                 get showButtons() {
                     return _showButtons();
                 },
                 set showButtons(newValue) {
                     _showButtons(newValue);
                 },
                 get showRange() {
                     return _showRange();
                 },
                 set showRange(newValue) {
                     _showRange(newValue);
                 },
                 get template() {
                     return _template();
                 },
                 set template(newValue) {
                     _template(newValue);
                 },
                 get theme() {
                     return _theme();
                 },
                 set theme(newValue) {
                     _theme(newValue);
                 },
                 get ticksPosition() {
                     return _ticksPosition();
                 },
                 set ticksPosition(newValue) {
                     _ticksPosition(newValue);
                 },
                 get ticksFrequency() {
                     return _ticksFrequency();
                 },
                 set ticksFrequency(newValue) {
                     _ticksFrequency(newValue);
                 },
                 get tickSize() {
                     return _tickSize();
                 },
                 set tickSize(newValue) {
                     _tickSize(newValue);
                 },
                 get tickLabelFormatFunction() {
                     return _tickLabelFormatFunction();
                 },
                 set tickLabelFormatFunction(newValue) {
                     _tickLabelFormatFunction(newValue);
                 },
                 get tooltip() {
                     return _tooltip();
                 },
                 set tooltip(newValue) {
                     _tooltip(newValue);
                 },
                 get tooltipHideDelay() {
                     return _tooltipHideDelay();
                 },
                 set tooltipHideDelay(newValue) {
                     _tooltipHideDelay(newValue);
                 },
                 get tooltipPosition() {
                     return _tooltipPosition();
                 },
                 set tooltipPosition(newValue) {
                     _tooltipPosition(newValue);
                 },
                 get tooltipFormatFunction() {
                     return _tooltipFormatFunction();
                 },
                 set tooltipFormatFunction(newValue) {
                     _tooltipFormatFunction(newValue);
                 },
                 get value() {
                     return _value();
                 },
                 set value(newValue) {
                     _value(newValue);
                 },
                 get values() {
                     return _values();
                 },
                 set values(newValue) {
                     _values(newValue);
                 },
                 get width() {
                     return _width();
                 },
                 set width(newValue) {
                     _width(newValue);
                 },
            }
            function twoWayBinding() {
				const element = JQXLite(componentSelector).jqxSlider('element');
                const value = JQXLite(componentSelector).jqxSlider('val');
                context.emit('input', value);
                context.emit('update:modelValue', element.value);
            }
            function __wireEvents__() {
                const that = context;

                JQXLite(componentSelector).on('change', function (event) { that.emit('change', event); twoWayBinding(); });
                JQXLite(componentSelector).on('slide', function (event) { that.emit('slide', event); });
                JQXLite(componentSelector).on('slideStart', function (event) { that.emit('slideStart', event); });
                JQXLite(componentSelector).on('slideEnd', function (event) { that.emit('slideEnd', event); });
            }

			onMounted(() => {
				if (props.autoCreate) __createComponent__();
			})
			onUpdated(() => {
				const widgetOptions = __manageProps__();
				JQXLite(componentSelector).jqxSlider(widgetOptions);
			})
			return {id, componentSelector, destroy,decrementValue,disable,enable,focus,getValue,incrementValue,setValue,val,twoWayBinding, setOptions, options, getOptions, createComponent};
        },
    }
</script>
