// jqwidgets-react/react_jqxknob.js
/*
jQWidgets v7.1.0 (2019-Feb)
Copyright (c) 2011-2019 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxdraw.js';
import '../jqwidgets/jqxknob.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxKnob extends React.Component {
    constructor(props) {
        super(props);
        const widgetId = 'jqxKnob' + JQXLite.generateID();
        this.componentSelector = '#' + widgetId;
        this.state = { id: widgetId };
    };
    componentDidMount() {
        const options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        const properties = ['allowValueChangeOnClick','allowValueChangeOnDrag','allowValueChangeOnMouseWheel','changing','dragEndAngle','dragStartAngle','disabled','dial','endAngle','height','labels','marks','min','max','progressBar','pointer','pointerGrabAction','rotation','startAngle','spinner','style','step','snapToStep','value','width'];
        let options = {};
        for(let item in this.props) {
            if(item === 'settings') {
                for(let itemTwo in this.props[item]) {
                    options[itemTwo] = this.props[item][itemTwo];
                }
            } else {
                if(properties.indexOf(item) !== -1) {
                      options[item] = this.props[item];
                }
            }
        }
        return options;
    };
    createComponent(options) {
        if(!this.style) {
            for (let style in this.props.style) {
                JQXLite(this.componentSelector).css(style, this.props.style[style]);
            }
        }
        if(this.props.className !== undefined) {
            const classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
            JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxKnob(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxKnob('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxKnob(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    allowValueChangeOnClick(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('allowValueChangeOnClick', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('allowValueChangeOnClick');
        }
    };
    allowValueChangeOnDrag(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('allowValueChangeOnDrag', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('allowValueChangeOnDrag');
        }
    };
    allowValueChangeOnMouseWheel(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('allowValueChangeOnMouseWheel', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('allowValueChangeOnMouseWheel');
        }
    };
    changing(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('changing', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('changing');
        }
    };
    dragEndAngle(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('dragEndAngle', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('dragEndAngle');
        }
    };
    dragStartAngle(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('dragStartAngle', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('dragStartAngle');
        }
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('disabled');
        }
    };
    dial(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('dial', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('dial');
        }
    };
    endAngle(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('endAngle', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('endAngle');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('height');
        }
    };
    labels(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('labels', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('labels');
        }
    };
    marks(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('marks', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('marks');
        }
    };
    min(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('min', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('min');
        }
    };
    max(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('max', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('max');
        }
    };
    progressBar(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('progressBar', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('progressBar');
        }
    };
    pointer(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('pointer', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('pointer');
        }
    };
    pointerGrabAction(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('pointerGrabAction', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('pointerGrabAction');
        }
    };
    rotation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('rotation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('rotation');
        }
    };
    startAngle(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('startAngle', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('startAngle');
        }
    };
    spinner(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('spinner', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('spinner');
        }
    };
    style(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('style', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('style');
        }
    };
    step(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('step', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('step');
        }
    };
    snapToStep(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('snapToStep', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('snapToStep');
        }
    };
    value(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('value', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('value');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('width');
        }
    };
    destroy() {
        JQXLite(this.componentSelector).jqxKnob('destroy');  
    };
    val(value) {
        if (value !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('val',  value)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('val');
        }
    };

    render() {
        return (
            <div id={this.state.id}>{this.props.value}{this.props.children}</div>
        )
    };
};

// jqwidgets-vue3/vue_jqxknob.vue
<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
	import { onUpdated, onMounted } from 'vue';
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxdraw.js';
    import '../jqwidgets/jqxknob.js';

    export default {
        props: {
            allowValueChangeOnClick: {
                default: true,
                type: Boolean
            },
            allowValueChangeOnDrag: {
                default: true,
                type: Boolean
            },
            allowValueChangeOnMouseWheel: {
                default: true,
                type: Boolean
            },
            changing: Function,
            dragEndAngle: Number,
            dragStartAngle: Number,
            disabled: {
                default: false,
                type: Boolean
            },
            dial: Object,
            endAngle: Number,
            height: [Number, String],
            labels: Object,
            marks: Object,
            min: Number,
            max: Number,
            progressBar: Object,
            pointer: [Array, Object],
            pointerGrabAction: String,
            rotation: String,
            startAngle: Number,
            spinner: Object,
            styles: Object,
            step: [Number, String],
            snapToStep: {
                default: true,
                type: Boolean
            },
            value: [Number, Array],
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        emits: ["change"],
        setup(props, context) {
			const id = "jqxKnob" + JQXLite.generateID();
			const componentSelector = '#' + id;
            function createComponent(options) {
                if (!props.autoCreate) __createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            }
            function setOptions (options) {
                JQXLite(componentSelector).jqxKnob(options);
            }
            function getOptions() {
                const usedProps = Object.keys(__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(componentSelector).jqxKnob(usedProps[i]);
                }
                return resultToReturn;
            }
            function destroy() {
                JQXLite(componentSelector).jqxKnob('destroy');  
            }
            function val(value) {
                if (value !== undefined) {
                    JQXLite(componentSelector).jqxKnob('val',  value)
                } else {
                    return JQXLite(componentSelector).jqxKnob('val');
                }
            }
            function _allowValueChangeOnClick (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('allowValueChangeOnClick', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('allowValueChangeOnClick');
                }
            }
            function _allowValueChangeOnDrag (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('allowValueChangeOnDrag', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('allowValueChangeOnDrag');
                }
            }
            function _allowValueChangeOnMouseWheel (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('allowValueChangeOnMouseWheel', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('allowValueChangeOnMouseWheel');
                }
            }
            function _changing (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('changing', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('changing');
                }
            }
            function _dragEndAngle (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('dragEndAngle', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('dragEndAngle');
                }
            }
            function _dragStartAngle (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('dragStartAngle', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('dragStartAngle');
                }
            }
            function _disabled (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('disabled', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('disabled');
                }
            }
            function _dial (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('dial', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('dial');
                }
            }
            function _endAngle (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('endAngle', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('endAngle');
                }
            }
            function _height (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('height', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('height');
                }
            }
            function _labels (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('labels', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('labels');
                }
            }
            function _marks (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('marks', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('marks');
                }
            }
            function _min (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('min', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('min');
                }
            }
            function _max (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('max', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('max');
                }
            }
            function _progressBar (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('progressBar', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('progressBar');
                }
            }
            function _pointer (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('pointer', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('pointer');
                }
            }
            function _pointerGrabAction (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('pointerGrabAction', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('pointerGrabAction');
                }
            }
            function _rotation (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('rotation', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('rotation');
                }
            }
            function _startAngle (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('startAngle', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('startAngle');
                }
            }
            function _spinner (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('spinner', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('spinner');
                }
            }
            function _styles (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('styles', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('styles');
                }
            }
            function _step (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('step', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('step');
                }
            }
            function _snapToStep (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('snapToStep', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('snapToStep');
                }
            }
            function _value (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('value', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('value');
                }
            }
            function _width (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKnob('width', arg)
                } else {
                    return JQXLite(componentSelector).jqxKnob('width');
                }
            }
            function __createComponent__ (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = __manageProps__();
                JQXLite(componentSelector).jqxKnob(widgetOptions);
                __wireEvents__();
            }
            function __manageProps__() {
                const widgetProps = ['allowValueChangeOnClick','allowValueChangeOnDrag','allowValueChangeOnMouseWheel','changing','dragEndAngle','dragStartAngle','disabled','dial','endAngle','height','labels','marks','min','max','progressBar','pointer','pointerGrabAction','rotation','startAngle','spinner','styles','step','snapToStep','value','width'];
                const componentProps = props;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1 && componentProps[prop] !== undefined) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            }
            const options = {
                 get allowValueChangeOnClick() {
                     return _allowValueChangeOnClick();
                 },
                 set allowValueChangeOnClick(newValue) {
                     _allowValueChangeOnClick(newValue);
                 },
                 get allowValueChangeOnDrag() {
                     return _allowValueChangeOnDrag();
                 },
                 set allowValueChangeOnDrag(newValue) {
                     _allowValueChangeOnDrag(newValue);
                 },
                 get allowValueChangeOnMouseWheel() {
                     return _allowValueChangeOnMouseWheel();
                 },
                 set allowValueChangeOnMouseWheel(newValue) {
                     _allowValueChangeOnMouseWheel(newValue);
                 },
                 get changing() {
                     return _changing();
                 },
                 set changing(newValue) {
                     _changing(newValue);
                 },
                 get dragEndAngle() {
                     return _dragEndAngle();
                 },
                 set dragEndAngle(newValue) {
                     _dragEndAngle(newValue);
                 },
                 get dragStartAngle() {
                     return _dragStartAngle();
                 },
                 set dragStartAngle(newValue) {
                     _dragStartAngle(newValue);
                 },
                 get disabled() {
                     return _disabled();
                 },
                 set disabled(newValue) {
                     _disabled(newValue);
                 },
                 get dial() {
                     return _dial();
                 },
                 set dial(newValue) {
                     _dial(newValue);
                 },
                 get endAngle() {
                     return _endAngle();
                 },
                 set endAngle(newValue) {
                     _endAngle(newValue);
                 },
                 get height() {
                     return _height();
                 },
                 set height(newValue) {
                     _height(newValue);
                 },
                 get labels() {
                     return _labels();
                 },
                 set labels(newValue) {
                     _labels(newValue);
                 },
                 get marks() {
                     return _marks();
                 },
                 set marks(newValue) {
                     _marks(newValue);
                 },
                 get min() {
                     return _min();
                 },
                 set min(newValue) {
                     _min(newValue);
                 },
                 get max() {
                     return _max();
                 },
                 set max(newValue) {
                     _max(newValue);
                 },
                 get progressBar() {
                     return _progressBar();
                 },
                 set progressBar(newValue) {
                     _progressBar(newValue);
                 },
                 get pointer() {
                     return _pointer();
                 },
                 set pointer(newValue) {
                     _pointer(newValue);
                 },
                 get pointerGrabAction() {
                     return _pointerGrabAction();
                 },
                 set pointerGrabAction(newValue) {
                     _pointerGrabAction(newValue);
                 },
                 get rotation() {
                     return _rotation();
                 },
                 set rotation(newValue) {
                     _rotation(newValue);
                 },
                 get startAngle() {
                     return _startAngle();
                 },
                 set startAngle(newValue) {
                     _startAngle(newValue);
                 },
                 get spinner() {
                     return _spinner();
                 },
                 set spinner(newValue) {
                     _spinner(newValue);
                 },
                 get styles() {
                     return _styles();
                 },
                 set styles(newValue) {
                     _styles(newValue);
                 },
                 get step() {
                     return _step();
                 },
                 set step(newValue) {
                     _step(newValue);
                 },
                 get snapToStep() {
                     return _snapToStep();
                 },
                 set snapToStep(newValue) {
                     _snapToStep(newValue);
                 },
                 get value() {
                     return _value();
                 },
                 set value(newValue) {
                     _value(newValue);
                 },
                 get width() {
                     return _width();
                 },
                 set width(newValue) {
                     _width(newValue);
                 },
            }
            function __wireEvents__() {
                const that = context;

                JQXLite(componentSelector).on('change', function (event) { that.emit('change', event); });
            }

			onMounted(() => {
				if (props.autoCreate) __createComponent__();
			})
			onUpdated(() => {
				const widgetOptions = __manageProps__();
				JQXLite(componentSelector).jqxKnob(widgetOptions);
			})
			return {id, componentSelector, destroy,val, setOptions, options, getOptions, createComponent};
        },
    }
</script>
