// jqwidgets-ng/esm2015/jqxdocking/angular_jqxdocking.js
import '../jqwidgets/jqxcore';
import '../jqwidgets/jqxbuttons';
import '../jqwidgets/jqxwindow';
import '../jqwidgets/jqxdocking';
/// <reference path="../../jqwidgets.d.ts" />
import * as tslib_1 from "tslib";
import { Component, Input, Output, EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
let jqxDockingComponent = class jqxDockingComponent {
    constructor(containerElement) {
        this.autoCreate = true;
        this.properties = ['cookies', 'cookieOptions', 'disabled', 'floatingWindowOpacity', 'height', 'keyboardNavigation', 'mode', 'orientation', 'rtl', 'theme', 'width', 'windowsMode', 'windowsOffset'];
        // jqxDockingComponent events
        this.onDragStart = new EventEmitter();
        this.onDragEnd = new EventEmitter();
        this.elementRef = containerElement;
    }
    ngOnInit() {
        if (this.autoCreate) {
            this.createComponent();
        }
    }
    ;
    ngOnChanges(changes) {
        if (this.host) {
            for (let i = 0; i < this.properties.length; i++) {
                let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
                let areEqual = false;
                if (this[attrName] !== undefined) {
                    if (typeof this[attrName] === 'object') {
                        if (this[attrName] instanceof Array) {
                            areEqual = this.arraysEqual(this[attrName], this.host.jqxDocking(this.properties[i]));
                        }
                        if (areEqual) {
                            return false;
                        }
                        this.host.jqxDocking(this.properties[i], this[attrName]);
                        continue;
                    }
                    if (this[attrName] !== this.host.jqxDocking(this.properties[i])) {
                        this.host.jqxDocking(this.properties[i], this[attrName]);
                    }
                }
            }
        }
    }
    arraysEqual(attrValue, hostValue) {
        if ((attrValue && !hostValue) || (!attrValue && hostValue)) {
            return false;
        }
        if (attrValue.length != hostValue.length) {
            return false;
        }
        for (let i = 0; i < attrValue.length; i++) {
            if (attrValue[i] !== hostValue[i]) {
                return false;
            }
        }
        return true;
    }
    manageAttributes() {
        let options = {};
        for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            if (this[attrName] !== undefined) {
                options[this.properties[i]] = this[attrName];
            }
        }
        return options;
    }
    moveClasses(parentEl, childEl) {
        let classes = parentEl.classList;
        if (classes.length > 0) {
            childEl.classList.add(...classes);
        }
        parentEl.className = '';
    }
    moveStyles(parentEl, childEl) {
        let style = parentEl.style.cssText;
        childEl.style.cssText = style;
        parentEl.style.cssText = '';
    }
    createComponent(options) {
        if (this.host) {
            return;
        }
        if (options) {
            JQXLite.extend(options, this.manageAttributes());
        }
        else {
            options = this.manageAttributes();
        }
        this.host = JQXLite(this.elementRef.nativeElement.firstChild);
        this.moveClasses(this.elementRef.nativeElement, this.host[0]);
        this.moveStyles(this.elementRef.nativeElement, this.host[0]);
        this.__wireEvents__();
        this.widgetObject = jqwidgets.createInstance(this.host, 'jqxDocking', options);
    }
    createWidget(options) {
        this.createComponent(options);
    }
    __updateRect__() {
        if (this.host)
            this.host.css({ width: this.attrWidth, height: this.attrHeight });
    }
    setOptions(options) {
        this.host.jqxDocking('setOptions', options);
    }
    // jqxDockingComponent properties
    cookies(arg) {
        if (arg !== undefined) {
            this.host.jqxDocking('cookies', arg);
        }
        else {
            return this.host.jqxDocking('cookies');
        }
    }
    cookieOptions(arg) {
        if (arg !== undefined) {
            this.host.jqxDocking('cookieOptions', arg);
        }
        else {
            return this.host.jqxDocking('cookieOptions');
        }
    }
    disabled(arg) {
        if (arg !== undefined) {
            this.host.jqxDocking('disabled', arg);
        }
        else {
            return this.host.jqxDocking('disabled');
        }
    }
    floatingWindowOpacity(arg) {
        if (arg !== undefined) {
            this.host.jqxDocking('floatingWindowOpacity', arg);
        }
        else {
            return this.host.jqxDocking('floatingWindowOpacity');
        }
    }
    height(arg) {
        if (arg !== undefined) {
            this.host.jqxDocking('height', arg);
        }
        else {
            return this.host.jqxDocking('height');
        }
    }
    keyboardNavigation(arg) {
        if (arg !== undefined) {
            this.host.jqxDocking('keyboardNavigation', arg);
        }
        else {
            return this.host.jqxDocking('keyboardNavigation');
        }
    }
    mode(arg) {
        if (arg !== undefined) {
            this.host.jqxDocking('mode', arg);
        }
        else {
            return this.host.jqxDocking('mode');
        }
    }
    orientation(arg) {
        if (arg !== undefined) {
            this.host.jqxDocking('orientation', arg);
        }
        else {
            return this.host.jqxDocking('orientation');
        }
    }
    rtl(arg) {
        if (arg !== undefined) {
            this.host.jqxDocking('rtl', arg);
        }
        else {
            return this.host.jqxDocking('rtl');
        }
    }
    theme(arg) {
        if (arg !== undefined) {
            this.host.jqxDocking('theme', arg);
        }
        else {
            return this.host.jqxDocking('theme');
        }
    }
    width(arg) {
        if (arg !== undefined) {
            this.host.jqxDocking('width', arg);
        }
        else {
            return this.host.jqxDocking('width');
        }
    }
    windowsMode(arg) {
        if (arg !== undefined) {
            this.host.jqxDocking('windowsMode', arg);
        }
        else {
            return this.host.jqxDocking('windowsMode');
        }
    }
    windowsOffset(arg) {
        if (arg !== undefined) {
            this.host.jqxDocking('windowsOffset', arg);
        }
        else {
            return this.host.jqxDocking('windowsOffset');
        }
    }
    // jqxDockingComponent functions
    addWindow(windowId, mode, panel, position) {
        this.host.jqxDocking('addWindow', windowId, mode, panel, position);
    }
    closeWindow(windowId) {
        this.host.jqxDocking('closeWindow', windowId);
    }
    collapseWindow(windowId) {
        this.host.jqxDocking('collapseWindow', windowId);
    }
    destroy() {
        this.host.jqxDocking('destroy');
    }
    disableWindowResize(windowId) {
        this.host.jqxDocking('disableWindowResize', windowId);
    }
    disable() {
        this.host.jqxDocking('disable');
    }
    exportLayout() {
        return this.host.jqxDocking('exportLayout');
    }
    enable() {
        this.host.jqxDocking('enable');
    }
    expandWindow(windowId) {
        this.host.jqxDocking('expandWindow', windowId);
    }
    enableWindowResize(windowId) {
        this.host.jqxDocking('enableWindowResize', windowId);
    }
    focus() {
        this.host.jqxDocking('focus');
    }
    hideAllCloseButtons() {
        this.host.jqxDocking('hideAllCloseButtons');
    }
    hideAllCollapseButtons() {
        this.host.jqxDocking('hideAllCollapseButtons');
    }
    hideCollapseButton(windowId) {
        this.host.jqxDocking('hideCollapseButton', windowId);
    }
    hideCloseButton(windowId) {
        this.host.jqxDocking('hideCloseButton', windowId);
    }
    importLayout(Json) {
        this.host.jqxDocking('importLayout', Json);
    }
    move(windowId, panel, position) {
        this.host.jqxDocking('move', windowId, panel, position);
    }
    pinWindow(windowId) {
        this.host.jqxDocking('pinWindow', windowId);
    }
    setWindowMode(windowId, mode) {
        this.host.jqxDocking('setWindowMode', windowId, mode);
    }
    showCloseButton(windowId) {
        this.host.jqxDocking('showCloseButton', windowId);
    }
    showCollapseButton(windowId) {
        this.host.jqxDocking('showCollapseButton', windowId);
    }
    setWindowPosition(windowId, top, left) {
        this.host.jqxDocking('setWindowPosition', windowId, top, left);
    }
    showAllCloseButtons() {
        this.host.jqxDocking('showAllCloseButtons');
    }
    showAllCollapseButtons() {
        this.host.jqxDocking('showAllCollapseButtons');
    }
    unpinWindow(windowId) {
        this.host.jqxDocking('unpinWindow', windowId);
    }
    __wireEvents__() {
        this.host.on('dragStart', (eventData) => { this.onDragStart.emit(eventData); });
        this.host.on('dragEnd', (eventData) => { this.onDragEnd.emit(eventData); });
    }
}; //jqxDockingComponent
jqxDockingComponent.ctorParameters = () => [
    { type: ElementRef }
];
tslib_1.__decorate([
    Input('cookies'),
    tslib_1.__metadata("design:type", Boolean)
], jqxDockingComponent.prototype, "attrCookies", void 0);
tslib_1.__decorate([
    Input('cookieOptions'),
    tslib_1.__metadata("design:type", Object)
], jqxDockingComponent.prototype, "attrCookieOptions", void 0);
tslib_1.__decorate([
    Input('disabled'),
    tslib_1.__metadata("design:type", Boolean)
], jqxDockingComponent.prototype, "attrDisabled", void 0);
tslib_1.__decorate([
    Input('floatingWindowOpacity'),
    tslib_1.__metadata("design:type", Number)
], jqxDockingComponent.prototype, "attrFloatingWindowOpacity", void 0);
tslib_1.__decorate([
    Input('keyboardNavigation'),
    tslib_1.__metadata("design:type", Boolean)
], jqxDockingComponent.prototype, "attrKeyboardNavigation", void 0);
tslib_1.__decorate([
    Input('mode'),
    tslib_1.__metadata("design:type", String)
], jqxDockingComponent.prototype, "attrMode", void 0);
tslib_1.__decorate([
    Input('orientation'),
    tslib_1.__metadata("design:type", String)
], jqxDockingComponent.prototype, "attrOrientation", void 0);
tslib_1.__decorate([
    Input('rtl'),
    tslib_1.__metadata("design:type", Boolean)
], jqxDockingComponent.prototype, "attrRtl", void 0);
tslib_1.__decorate([
    Input('theme'),
    tslib_1.__metadata("design:type", String)
], jqxDockingComponent.prototype, "attrTheme", void 0);
tslib_1.__decorate([
    Input('windowsMode'),
    tslib_1.__metadata("design:type", Object)
], jqxDockingComponent.prototype, "attrWindowsMode", void 0);
tslib_1.__decorate([
    Input('windowsOffset'),
    tslib_1.__metadata("design:type", Number)
], jqxDockingComponent.prototype, "attrWindowsOffset", void 0);
tslib_1.__decorate([
    Input('width'),
    tslib_1.__metadata("design:type", Object)
], jqxDockingComponent.prototype, "attrWidth", void 0);
tslib_1.__decorate([
    Input('height'),
    tslib_1.__metadata("design:type", Object)
], jqxDockingComponent.prototype, "attrHeight", void 0);
tslib_1.__decorate([
    Input('auto-create'),
    tslib_1.__metadata("design:type", Boolean)
], jqxDockingComponent.prototype, "autoCreate", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxDockingComponent.prototype, "onDragStart", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxDockingComponent.prototype, "onDragEnd", void 0);
jqxDockingComponent = tslib_1.__decorate([
    Component({
        selector: 'jqxDocking',
        template: '<div><ng-content></ng-content></div>'
    }),
    tslib_1.__metadata("design:paramtypes", [ElementRef])
], jqxDockingComponent);
export { jqxDockingComponent };

// jqwidgets-vue3/vue_jqxdocking.vue
<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
	import { onUpdated, onMounted } from 'vue';
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxwindow.js';
    import '../jqwidgets/jqxdocking.js';

    export default {
        props: {
            cookies: {
                default: false,
                type: Boolean
            },
            cookieOptions: Object,
            disabled: {
                default: false,
                type: Boolean
            },
            floatingWindowOpacity: Number,
            height: [Number, String],
            keyboardNavigation: {
                default: false,
                type: Boolean
            },
            mode: String,
            orientation: String,
            rtl: {
                default: false,
                type: Boolean
            },
            theme: String,
            width: [Number, String],
            windowsMode: Object,
            windowsOffset: Number,
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        emits: ["dragStart","dragEnd"],
        setup(props, context) {
			const id = "jqxDocking" + JQXLite.generateID();
			const componentSelector = '#' + id;
            function createComponent(options) {
                if (!props.autoCreate) __createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            }
            function setOptions (options) {
                JQXLite(componentSelector).jqxDocking(options);
            }
            function getOptions() {
                const usedProps = Object.keys(__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(componentSelector).jqxDocking(usedProps[i]);
                }
                return resultToReturn;
            }
            function addWindow(windowId, mode, panel, position) {
                JQXLite(componentSelector).jqxDocking('addWindow', windowId, mode, panel, position);  
            }
            function closeWindow(windowId) {
                JQXLite(componentSelector).jqxDocking('closeWindow', windowId);  
            }
            function collapseWindow(windowId) {
                JQXLite(componentSelector).jqxDocking('collapseWindow', windowId);  
            }
            function destroy() {
                JQXLite(componentSelector).jqxDocking('destroy');  
            }
            function disableWindowResize(windowId) {
                JQXLite(componentSelector).jqxDocking('disableWindowResize', windowId);  
            }
            function disable() {
                JQXLite(componentSelector).jqxDocking('disable');  
            }
            function exportLayout() {
                return JQXLite(componentSelector).jqxDocking('exportLayout');  
            }
            function enable() {
                JQXLite(componentSelector).jqxDocking('enable');  
            }
            function expandWindow(windowId) {
                JQXLite(componentSelector).jqxDocking('expandWindow', windowId);  
            }
            function enableWindowResize(windowId) {
                JQXLite(componentSelector).jqxDocking('enableWindowResize', windowId);  
            }
            function focus() {
                JQXLite(componentSelector).jqxDocking('focus');  
            }
            function hideAllCloseButtons() {
                JQXLite(componentSelector).jqxDocking('hideAllCloseButtons');  
            }
            function hideAllCollapseButtons() {
                JQXLite(componentSelector).jqxDocking('hideAllCollapseButtons');  
            }
            function hideCollapseButton(windowId) {
                JQXLite(componentSelector).jqxDocking('hideCollapseButton', windowId);  
            }
            function hideCloseButton(windowId) {
                JQXLite(componentSelector).jqxDocking('hideCloseButton', windowId);  
            }
            function importLayout(Json) {
                JQXLite(componentSelector).jqxDocking('importLayout', Json);  
            }
            function move(windowId, panel, position) {
                JQXLite(componentSelector).jqxDocking('move', windowId, panel, position);  
            }
            function pinWindow(windowId) {
                JQXLite(componentSelector).jqxDocking('pinWindow', windowId);  
            }
            function setWindowMode(windowId, mode) {
                JQXLite(componentSelector).jqxDocking('setWindowMode', windowId, mode);  
            }
            function showCloseButton(windowId) {
                JQXLite(componentSelector).jqxDocking('showCloseButton', windowId);  
            }
            function showCollapseButton(windowId) {
                JQXLite(componentSelector).jqxDocking('showCollapseButton', windowId);  
            }
            function setWindowPosition(windowId, top, left) {
                JQXLite(componentSelector).jqxDocking('setWindowPosition', windowId, top, left);  
            }
            function showAllCloseButtons() {
                JQXLite(componentSelector).jqxDocking('showAllCloseButtons');  
            }
            function showAllCollapseButtons() {
                JQXLite(componentSelector).jqxDocking('showAllCollapseButtons');  
            }
            function unpinWindow(windowId) {
                JQXLite(componentSelector).jqxDocking('unpinWindow', windowId);  
            }
            function _cookies (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxDocking('cookies', arg)
                } else {
                    return JQXLite(componentSelector).jqxDocking('cookies');
                }
            }
            function _cookieOptions (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxDocking('cookieOptions', arg)
                } else {
                    return JQXLite(componentSelector).jqxDocking('cookieOptions');
                }
            }
            function _disabled (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxDocking('disabled', arg)
                } else {
                    return JQXLite(componentSelector).jqxDocking('disabled');
                }
            }
            function _floatingWindowOpacity (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxDocking('floatingWindowOpacity', arg)
                } else {
                    return JQXLite(componentSelector).jqxDocking('floatingWindowOpacity');
                }
            }
            function _height (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxDocking('height', arg)
                } else {
                    return JQXLite(componentSelector).jqxDocking('height');
                }
            }
            function _keyboardNavigation (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxDocking('keyboardNavigation', arg)
                } else {
                    return JQXLite(componentSelector).jqxDocking('keyboardNavigation');
                }
            }
            function _mode (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxDocking('mode', arg)
                } else {
                    return JQXLite(componentSelector).jqxDocking('mode');
                }
            }
            function _orientation (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxDocking('orientation', arg)
                } else {
                    return JQXLite(componentSelector).jqxDocking('orientation');
                }
            }
            function _rtl (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxDocking('rtl', arg)
                } else {
                    return JQXLite(componentSelector).jqxDocking('rtl');
                }
            }
            function _theme (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxDocking('theme', arg)
                } else {
                    return JQXLite(componentSelector).jqxDocking('theme');
                }
            }
            function _width (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxDocking('width', arg)
                } else {
                    return JQXLite(componentSelector).jqxDocking('width');
                }
            }
            function _windowsMode (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxDocking('windowsMode', arg)
                } else {
                    return JQXLite(componentSelector).jqxDocking('windowsMode');
                }
            }
            function _windowsOffset (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxDocking('windowsOffset', arg)
                } else {
                    return JQXLite(componentSelector).jqxDocking('windowsOffset');
                }
            }
            function __createComponent__ (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = __manageProps__();
                JQXLite(componentSelector).jqxDocking(widgetOptions);
                __wireEvents__();
            }
            function __manageProps__() {
                const widgetProps = ['cookies','cookieOptions','disabled','floatingWindowOpacity','height','keyboardNavigation','mode','orientation','rtl','theme','width','windowsMode','windowsOffset'];
                const componentProps = props;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1 && componentProps[prop] !== undefined) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            }
            const options = {
                 get cookies() {
                     return _cookies();
                 },
                 set cookies(newValue) {
                     _cookies(newValue);
                 },
                 get cookieOptions() {
                     return _cookieOptions();
                 },
                 set cookieOptions(newValue) {
                     _cookieOptions(newValue);
                 },
                 get disabled() {
                     return _disabled();
                 },
                 set disabled(newValue) {
                     _disabled(newValue);
                 },
                 get floatingWindowOpacity() {
                     return _floatingWindowOpacity();
                 },
                 set floatingWindowOpacity(newValue) {
                     _floatingWindowOpacity(newValue);
                 },
                 get height() {
                     return _height();
                 },
                 set height(newValue) {
                     _height(newValue);
                 },
                 get keyboardNavigation() {
                     return _keyboardNavigation();
                 },
                 set keyboardNavigation(newValue) {
                     _keyboardNavigation(newValue);
                 },
                 get mode() {
                     return _mode();
                 },
                 set mode(newValue) {
                     _mode(newValue);
                 },
                 get orientation() {
                     return _orientation();
                 },
                 set orientation(newValue) {
                     _orientation(newValue);
                 },
                 get rtl() {
                     return _rtl();
                 },
                 set rtl(newValue) {
                     _rtl(newValue);
                 },
                 get theme() {
                     return _theme();
                 },
                 set theme(newValue) {
                     _theme(newValue);
                 },
                 get width() {
                     return _width();
                 },
                 set width(newValue) {
                     _width(newValue);
                 },
                 get windowsMode() {
                     return _windowsMode();
                 },
                 set windowsMode(newValue) {
                     _windowsMode(newValue);
                 },
                 get windowsOffset() {
                     return _windowsOffset();
                 },
                 set windowsOffset(newValue) {
                     _windowsOffset(newValue);
                 },
            }
            function __wireEvents__() {
                const that = context;

                JQXLite(componentSelector).on('dragStart', function (event) { that.emit('dragStart', event); });
                JQXLite(componentSelector).on('dragEnd', function (event) { that.emit('dragEnd', event); });
            }

			onMounted(() => {
				if (props.autoCreate) __createComponent__();
			})
			onUpdated(() => {
				const widgetOptions = __manageProps__();
				JQXLite(componentSelector).jqxDocking(widgetOptions);
			})
			return {id, componentSelector, addWindow,closeWindow,collapseWindow,destroy,disableWindowResize,disable,exportLayout,enable,expandWindow,enableWindowResize,focus,hideAllCloseButtons,hideAllCollapseButtons,hideCollapseButton,hideCloseButton,importLayout,move,pinWindow,setWindowMode,showCloseButton,showCollapseButton,setWindowPosition,showAllCloseButtons,showAllCollapseButtons,unpinWindow, setOptions, options, getOptions, createComponent};
        },
    }
</script>
