// jqwidgets-ng/esm2015/jqxpivotgrid/angular_jqxpivotgrid.js
import '../jqwidgets/jqxcore';
import '../jqwidgets/jqxdata';
import '../jqwidgets/jqxbuttons';
import '../jqwidgets/jqxscrollbar';
import '../jqwidgets/jqxmenu';
import '../jqwidgets/jqxwindow';
import '../jqwidgets/jqxdragdrop';
import '../jqwidgets/jqxcheckbox';
import '../jqwidgets/jqxinput';
import '../jqwidgets/jqxlistbox';
import '../jqwidgets/jqxdropdownlist';
import '../jqwidgets/jqxpivot';
import '../jqwidgets/jqxpivotgrid';
import '../jqwidgets/jqxpivotdesigner';
/// <reference path="../../jqwidgets.d.ts" />
import * as tslib_1 from "tslib";
import { Component, Input, Output, EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
let jqxPivotGridComponent = class jqxPivotGridComponent {
    constructor(containerElement) {
        this.autoCreate = true;
        this.properties = ['source', 'localization', 'scrollBarsEnabled', 'selectionEnabled', 'multipleSelectionEnabled', 'treeStyleRows', 'autoResize', 'itemsRenderer', 'cellsRenderer'];
        // jqxPivotGridComponent events
        this.onPivotitemexpanding = new EventEmitter();
        this.onPivotitemexpanded = new EventEmitter();
        this.onPivotitemcollapsing = new EventEmitter();
        this.onPivotitemcollapsed = new EventEmitter();
        this.onSortchanging = new EventEmitter();
        this.onSortchanged = new EventEmitter();
        this.onSortremoving = new EventEmitter();
        this.onSortremoved = new EventEmitter();
        this.onPivotitemselectionchanged = new EventEmitter();
        this.onPivotcellmousedown = new EventEmitter();
        this.onPivotcellmouseup = new EventEmitter();
        this.onPivotcellclick = new EventEmitter();
        this.onPivotcelldblclick = new EventEmitter();
        this.onPivotitemmousedown = new EventEmitter();
        this.onPivotitemmouseup = new EventEmitter();
        this.onPivotitemclick = new EventEmitter();
        this.onPivotitemdblclick = new EventEmitter();
        this.elementRef = containerElement;
        JQXLite(window).resize(() => {
            this.__updateRect__();
        });
    }
    ngOnInit() {
        if (this.autoCreate) {
            this.createComponent();
        }
    }
    ;
    ngOnChanges(changes) {
        if (this.host) {
            for (let i = 0; i < this.properties.length; i++) {
                let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
                let areEqual = false;
                if (this[attrName] !== undefined) {
                    if (typeof this[attrName] === 'object') {
                        if (this[attrName] instanceof Array) {
                            areEqual = this.arraysEqual(this[attrName], this.host.jqxPivotGrid(this.properties[i]));
                        }
                        if (areEqual) {
                            return false;
                        }
                        this.host.jqxPivotGrid(this.properties[i], this[attrName]);
                        continue;
                    }
                    if (this[attrName] !== this.host.jqxPivotGrid(this.properties[i])) {
                        this.host.jqxPivotGrid(this.properties[i], this[attrName]);
                    }
                }
            }
        }
    }
    arraysEqual(attrValue, hostValue) {
        if ((attrValue && !hostValue) || (!attrValue && hostValue)) {
            return false;
        }
        if (attrValue.length != hostValue.length) {
            return false;
        }
        for (let i = 0; i < attrValue.length; i++) {
            if (attrValue[i] !== hostValue[i]) {
                return false;
            }
        }
        return true;
    }
    manageAttributes() {
        let options = {};
        for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            if (this[attrName] !== undefined) {
                options[this.properties[i]] = this[attrName];
            }
        }
        return options;
    }
    moveClasses(parentEl, childEl) {
        let classes = parentEl.classList;
        if (classes.length > 0) {
            childEl.classList.add(...classes);
        }
        parentEl.className = '';
    }
    moveStyles(parentEl, childEl) {
        let style = parentEl.style.cssText;
        childEl.style.cssText = style;
        parentEl.style.cssText = '';
    }
    createComponent(options) {
        if (this.host) {
            return;
        }
        if (options) {
            JQXLite.extend(options, this.manageAttributes());
        }
        else {
            options = this.manageAttributes();
        }
        this.host = JQXLite(this.elementRef.nativeElement.firstChild);
        this.moveClasses(this.elementRef.nativeElement, this.host[0]);
        this.moveStyles(this.elementRef.nativeElement, this.host[0]);
        this.__wireEvents__();
        this.widgetObject = jqwidgets.createInstance(this.host, 'jqxPivotGrid', options);
        this.__updateRect__();
    }
    createWidget(options) {
        this.createComponent(options);
    }
    __updateRect__() {
        if (this.host)
            this.host.css({ width: this.attrWidth, height: this.attrHeight });
        this.refresh();
    }
    setOptions(options) {
        this.host.jqxPivotGrid('setOptions', options);
    }
    // jqxPivotGridComponent properties
    source(arg) {
        if (arg !== undefined) {
            this.host.jqxPivotGrid('source', arg);
        }
        else {
            return this.host.jqxPivotGrid('source');
        }
    }
    localization(arg) {
        if (arg !== undefined) {
            this.host.jqxPivotGrid('localization', arg);
        }
        else {
            return this.host.jqxPivotGrid('localization');
        }
    }
    scrollBarsEnabled(arg) {
        if (arg !== undefined) {
            this.host.jqxPivotGrid('scrollBarsEnabled', arg);
        }
        else {
            return this.host.jqxPivotGrid('scrollBarsEnabled');
        }
    }
    selectionEnabled(arg) {
        if (arg !== undefined) {
            this.host.jqxPivotGrid('selectionEnabled', arg);
        }
        else {
            return this.host.jqxPivotGrid('selectionEnabled');
        }
    }
    multipleSelectionEnabled(arg) {
        if (arg !== undefined) {
            this.host.jqxPivotGrid('multipleSelectionEnabled', arg);
        }
        else {
            return this.host.jqxPivotGrid('multipleSelectionEnabled');
        }
    }
    treeStyleRows(arg) {
        if (arg !== undefined) {
            this.host.jqxPivotGrid('treeStyleRows', arg);
        }
        else {
            return this.host.jqxPivotGrid('treeStyleRows');
        }
    }
    autoResize(arg) {
        if (arg !== undefined) {
            this.host.jqxPivotGrid('autoResize', arg);
        }
        else {
            return this.host.jqxPivotGrid('autoResize');
        }
    }
    itemsRenderer(arg) {
        if (arg !== undefined) {
            this.host.jqxPivotGrid('itemsRenderer', arg);
        }
        else {
            return this.host.jqxPivotGrid('itemsRenderer');
        }
    }
    cellsRenderer(arg) {
        if (arg !== undefined) {
            this.host.jqxPivotGrid('cellsRenderer', arg);
        }
        else {
            return this.host.jqxPivotGrid('cellsRenderer');
        }
    }
    // jqxPivotGridComponent functions
    getInstance() {
        return this.host.jqxPivotGrid('getInstance');
    }
    refresh() {
        this.host.jqxPivotGrid('refresh');
    }
    getPivotRows() {
        return this.host.jqxPivotGrid('getPivotRows');
    }
    getPivotColumns() {
        return this.host.jqxPivotGrid('getPivotColumns');
    }
    getPivotCells() {
        return this.host.jqxPivotGrid('getPivotCells');
    }
    __wireEvents__() {
        this.host.on('pivotitemexpanding', (eventData) => { this.onPivotitemexpanding.emit(eventData); });
        this.host.on('pivotitemexpanded', (eventData) => { this.onPivotitemexpanded.emit(eventData); });
        this.host.on('pivotitemcollapsing', (eventData) => { this.onPivotitemcollapsing.emit(eventData); });
        this.host.on('pivotitemcollapsed', (eventData) => { this.onPivotitemcollapsed.emit(eventData); });
        this.host.on('sortchanging', (eventData) => { this.onSortchanging.emit(eventData); });
        this.host.on('sortchanged', (eventData) => { this.onSortchanged.emit(eventData); });
        this.host.on('sortremoving', (eventData) => { this.onSortremoving.emit(eventData); });
        this.host.on('sortremoved', (eventData) => { this.onSortremoved.emit(eventData); });
        this.host.on('pivotitemselectionchanged', (eventData) => { this.onPivotitemselectionchanged.emit(eventData); });
        this.host.on('pivotcellmousedown', (eventData) => { this.onPivotcellmousedown.emit(eventData); });
        this.host.on('pivotcellmouseup', (eventData) => { this.onPivotcellmouseup.emit(eventData); });
        this.host.on('pivotcellclick', (eventData) => { this.onPivotcellclick.emit(eventData); });
        this.host.on('pivotcelldblclick', (eventData) => { this.onPivotcelldblclick.emit(eventData); });
        this.host.on('pivotitemmousedown', (eventData) => { this.onPivotitemmousedown.emit(eventData); });
        this.host.on('pivotitemmouseup', (eventData) => { this.onPivotitemmouseup.emit(eventData); });
        this.host.on('pivotitemclick', (eventData) => { this.onPivotitemclick.emit(eventData); });
        this.host.on('pivotitemdblclick', (eventData) => { this.onPivotitemdblclick.emit(eventData); });
    }
}; //jqxPivotGridComponent
jqxPivotGridComponent.ctorParameters = () => [
    { type: ElementRef }
];
tslib_1.__decorate([
    Input('source'),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "attrSource", void 0);
tslib_1.__decorate([
    Input('localization'),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "attrLocalization", void 0);
tslib_1.__decorate([
    Input('scrollBarsEnabled'),
    tslib_1.__metadata("design:type", Boolean)
], jqxPivotGridComponent.prototype, "attrScrollBarsEnabled", void 0);
tslib_1.__decorate([
    Input('selectionEnabled'),
    tslib_1.__metadata("design:type", Boolean)
], jqxPivotGridComponent.prototype, "attrSelectionEnabled", void 0);
tslib_1.__decorate([
    Input('multipleSelectionEnabled'),
    tslib_1.__metadata("design:type", Boolean)
], jqxPivotGridComponent.prototype, "attrMultipleSelectionEnabled", void 0);
tslib_1.__decorate([
    Input('treeStyleRows'),
    tslib_1.__metadata("design:type", Boolean)
], jqxPivotGridComponent.prototype, "attrTreeStyleRows", void 0);
tslib_1.__decorate([
    Input('autoResize'),
    tslib_1.__metadata("design:type", Boolean)
], jqxPivotGridComponent.prototype, "attrAutoResize", void 0);
tslib_1.__decorate([
    Input('itemsRenderer'),
    tslib_1.__metadata("design:type", Function)
], jqxPivotGridComponent.prototype, "attrItemsRenderer", void 0);
tslib_1.__decorate([
    Input('cellsRenderer'),
    tslib_1.__metadata("design:type", Function)
], jqxPivotGridComponent.prototype, "attrCellsRenderer", void 0);
tslib_1.__decorate([
    Input('width'),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "attrWidth", void 0);
tslib_1.__decorate([
    Input('height'),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "attrHeight", void 0);
tslib_1.__decorate([
    Input('auto-create'),
    tslib_1.__metadata("design:type", Boolean)
], jqxPivotGridComponent.prototype, "autoCreate", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onPivotitemexpanding", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onPivotitemexpanded", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onPivotitemcollapsing", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onPivotitemcollapsed", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onSortchanging", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onSortchanged", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onSortremoving", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onSortremoved", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onPivotitemselectionchanged", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onPivotcellmousedown", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onPivotcellmouseup", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onPivotcellclick", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onPivotcelldblclick", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onPivotitemmousedown", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onPivotitemmouseup", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onPivotitemclick", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxPivotGridComponent.prototype, "onPivotitemdblclick", void 0);
jqxPivotGridComponent = tslib_1.__decorate([
    Component({
        selector: 'jqxPivotGrid',
        template: '<div><ng-content></ng-content></div>'
    }),
    tslib_1.__metadata("design:paramtypes", [ElementRef])
], jqxPivotGridComponent);
export { jqxPivotGridComponent };

// jqwidgets-vue3/vue_jqxpivotgrid.vue
<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
	import { onUpdated, onMounted } from 'vue';
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxdata.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxscrollbar.js';
    import '../jqwidgets/jqxmenu.js';
    import '../jqwidgets/jqxwindow.js';
    import '../jqwidgets/jqxdragdrop.js';
    import '../jqwidgets/jqxcheckbox.js';
    import '../jqwidgets/jqxinput.js';
    import '../jqwidgets/jqxlistbox.js';
    import '../jqwidgets/jqxdropdownlist.js';
    import '../jqwidgets/jqxpivot.js';
    import '../jqwidgets/jqxpivotgrid.js';
    import '../jqwidgets/jqxpivotdesigner.js';

    export default {
        props: {
            source: Object,
            localization: Object,
            scrollBarsEnabled: {
                default: true,
                type: Boolean
            },
            selectionEnabled: {
                default: true,
                type: Boolean
            },
            multipleSelectionEnabled: {
                default: true,
                type: Boolean
            },
            treeStyleRows: {
                default: true,
                type: Boolean
            },
            autoResize: {
                default: false,
                type: Boolean
            },
            itemsRenderer: Function,
            cellsRenderer: Function,
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        emits: ["pivotitemexpanding","pivotitemexpanded","pivotitemcollapsing","pivotitemcollapsed","sortchanging","sortchanged","sortremoving","sortremoved","pivotitemselectionchanged","pivotcellmousedown","pivotcellmouseup","pivotcellclick","pivotcelldblclick","pivotitemmousedown","pivotitemmouseup","pivotitemclick","pivotitemdblclick"],
        setup(props, context) {
			const id = "jqxPivotGrid" + JQXLite.generateID();
			const componentSelector = '#' + id;
            function createComponent(options) {
                if (!props.autoCreate) __createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            }
            function setOptions (options) {
                JQXLite(componentSelector).jqxPivotGrid(options);
            }
            function getOptions() {
                const usedProps = Object.keys(__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(componentSelector).jqxPivotGrid(usedProps[i]);
                }
                return resultToReturn;
            }
            function getInstance() {
                return JQXLite(componentSelector).jqxPivotGrid('getInstance');  
            }
            function refresh() {
                return JQXLite(componentSelector).jqxPivotGrid('refresh');  
            }
            function getPivotRows() {
                return JQXLite(componentSelector).jqxPivotGrid('getPivotRows');  
            }
            function getPivotColumns() {
                return JQXLite(componentSelector).jqxPivotGrid('getPivotColumns');  
            }
            function getPivotCells() {
                return JQXLite(componentSelector).jqxPivotGrid('getPivotCells');  
            }
            function _source (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxPivotGrid('source', arg)
                } else {
                    return JQXLite(componentSelector).jqxPivotGrid('source');
                }
            }
            function _localization (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxPivotGrid('localization', arg)
                } else {
                    return JQXLite(componentSelector).jqxPivotGrid('localization');
                }
            }
            function _scrollBarsEnabled (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxPivotGrid('scrollBarsEnabled', arg)
                } else {
                    return JQXLite(componentSelector).jqxPivotGrid('scrollBarsEnabled');
                }
            }
            function _selectionEnabled (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxPivotGrid('selectionEnabled', arg)
                } else {
                    return JQXLite(componentSelector).jqxPivotGrid('selectionEnabled');
                }
            }
            function _multipleSelectionEnabled (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxPivotGrid('multipleSelectionEnabled', arg)
                } else {
                    return JQXLite(componentSelector).jqxPivotGrid('multipleSelectionEnabled');
                }
            }
            function _treeStyleRows (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxPivotGrid('treeStyleRows', arg)
                } else {
                    return JQXLite(componentSelector).jqxPivotGrid('treeStyleRows');
                }
            }
            function _autoResize (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxPivotGrid('autoResize', arg)
                } else {
                    return JQXLite(componentSelector).jqxPivotGrid('autoResize');
                }
            }
            function _itemsRenderer (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxPivotGrid('itemsRenderer', arg)
                } else {
                    return JQXLite(componentSelector).jqxPivotGrid('itemsRenderer');
                }
            }
            function _cellsRenderer (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxPivotGrid('cellsRenderer', arg)
                } else {
                    return JQXLite(componentSelector).jqxPivotGrid('cellsRenderer');
                }
            }
            function __createComponent__ (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = __manageProps__();
                JQXLite(componentSelector).jqxPivotGrid(widgetOptions);
                __wireEvents__();
            }
            function __manageProps__() {
                const widgetProps = ['source','localization','scrollBarsEnabled','selectionEnabled','multipleSelectionEnabled','treeStyleRows','autoResize','itemsRenderer','cellsRenderer'];
                const componentProps = props;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1 && componentProps[prop] !== undefined) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            }
            const options = {
                 get source() {
                     return _source();
                 },
                 set source(newValue) {
                     _source(newValue);
                 },
                 get localization() {
                     return _localization();
                 },
                 set localization(newValue) {
                     _localization(newValue);
                 },
                 get scrollBarsEnabled() {
                     return _scrollBarsEnabled();
                 },
                 set scrollBarsEnabled(newValue) {
                     _scrollBarsEnabled(newValue);
                 },
                 get selectionEnabled() {
                     return _selectionEnabled();
                 },
                 set selectionEnabled(newValue) {
                     _selectionEnabled(newValue);
                 },
                 get multipleSelectionEnabled() {
                     return _multipleSelectionEnabled();
                 },
                 set multipleSelectionEnabled(newValue) {
                     _multipleSelectionEnabled(newValue);
                 },
                 get treeStyleRows() {
                     return _treeStyleRows();
                 },
                 set treeStyleRows(newValue) {
                     _treeStyleRows(newValue);
                 },
                 get autoResize() {
                     return _autoResize();
                 },
                 set autoResize(newValue) {
                     _autoResize(newValue);
                 },
                 get itemsRenderer() {
                     return _itemsRenderer();
                 },
                 set itemsRenderer(newValue) {
                     _itemsRenderer(newValue);
                 },
                 get cellsRenderer() {
                     return _cellsRenderer();
                 },
                 set cellsRenderer(newValue) {
                     _cellsRenderer(newValue);
                 },
            }
            function __wireEvents__() {
                const that = context;

                JQXLite(componentSelector).on('pivotitemexpanding', function (event) { that.emit('pivotitemexpanding', event); });
                JQXLite(componentSelector).on('pivotitemexpanded', function (event) { that.emit('pivotitemexpanded', event); });
                JQXLite(componentSelector).on('pivotitemcollapsing', function (event) { that.emit('pivotitemcollapsing', event); });
                JQXLite(componentSelector).on('pivotitemcollapsed', function (event) { that.emit('pivotitemcollapsed', event); });
                JQXLite(componentSelector).on('sortchanging', function (event) { that.emit('sortchanging', event); });
                JQXLite(componentSelector).on('sortchanged', function (event) { that.emit('sortchanged', event); });
                JQXLite(componentSelector).on('sortremoving', function (event) { that.emit('sortremoving', event); });
                JQXLite(componentSelector).on('sortremoved', function (event) { that.emit('sortremoved', event); });
                JQXLite(componentSelector).on('pivotitemselectionchanged', function (event) { that.emit('pivotitemselectionchanged', event); });
                JQXLite(componentSelector).on('pivotcellmousedown', function (event) { that.emit('pivotcellmousedown', event); });
                JQXLite(componentSelector).on('pivotcellmouseup', function (event) { that.emit('pivotcellmouseup', event); });
                JQXLite(componentSelector).on('pivotcellclick', function (event) { that.emit('pivotcellclick', event); });
                JQXLite(componentSelector).on('pivotcelldblclick', function (event) { that.emit('pivotcelldblclick', event); });
                JQXLite(componentSelector).on('pivotitemmousedown', function (event) { that.emit('pivotitemmousedown', event); });
                JQXLite(componentSelector).on('pivotitemmouseup', function (event) { that.emit('pivotitemmouseup', event); });
                JQXLite(componentSelector).on('pivotitemclick', function (event) { that.emit('pivotitemclick', event); });
                JQXLite(componentSelector).on('pivotitemdblclick', function (event) { that.emit('pivotitemdblclick', event); });
            }

			onMounted(() => {
				if (props.autoCreate) __createComponent__();
			})
			onUpdated(() => {
				const widgetOptions = __manageProps__();
				JQXLite(componentSelector).jqxPivotGrid(widgetOptions);
			})
			return {id, componentSelector, getInstance,refresh,getPivotRows,getPivotColumns,getPivotCells, setOptions, options, getOptions, createComponent};
        },
    }
</script>
