// jqwidgets-ng/esm2015/jqxkanban/angular_jqxkanban.js
import '../jqwidgets/jqxcore';
import '../jqwidgets/jqxsortable';
import '../jqwidgets/jqxsplitter';
import '../jqwidgets/jqxdata';
import '../jqwidgets/jqxkanban';
/// <reference path="../../jqwidgets.d.ts" />
import * as tslib_1 from "tslib";
import { Component, Input, Output, EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
let jqxKanbanComponent = class jqxKanbanComponent {
    constructor(containerElement) {
        this.autoCreate = true;
        this.properties = ['columnRenderer', 'columns', 'connectWith', 'headerHeight', 'headerWidth', 'height', 'itemRenderer', 'ready', 'rtl', 'source', 'resources', 'template', 'templateContent', 'theme', 'width'];
        // jqxKanbanComponent events
        this.onColumnAttrClicked = new EventEmitter();
        this.onColumnCollapsed = new EventEmitter();
        this.onColumnExpanded = new EventEmitter();
        this.onItemAttrClicked = new EventEmitter();
        this.onItemMoved = new EventEmitter();
        this.elementRef = containerElement;
    }
    ngOnInit() {
        if (this.autoCreate) {
            this.createComponent();
        }
    }
    ;
    ngOnChanges(changes) {
        if (this.host) {
            for (let i = 0; i < this.properties.length; i++) {
                let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
                let areEqual = false;
                if (this[attrName] !== undefined) {
                    if (typeof this[attrName] === 'object') {
                        if (this[attrName] instanceof Array) {
                            areEqual = this.arraysEqual(this[attrName], this.host.jqxKanban(this.properties[i]));
                        }
                        if (areEqual) {
                            return false;
                        }
                        this.host.jqxKanban(this.properties[i], this[attrName]);
                        continue;
                    }
                    if (this[attrName] !== this.host.jqxKanban(this.properties[i])) {
                        this.host.jqxKanban(this.properties[i], this[attrName]);
                    }
                }
            }
        }
    }
    arraysEqual(attrValue, hostValue) {
        if ((attrValue && !hostValue) || (!attrValue && hostValue)) {
            return false;
        }
        if (attrValue.length != hostValue.length) {
            return false;
        }
        for (let i = 0; i < attrValue.length; i++) {
            if (attrValue[i] !== hostValue[i]) {
                return false;
            }
        }
        return true;
    }
    manageAttributes() {
        let options = {};
        for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            if (this[attrName] !== undefined) {
                options[this.properties[i]] = this[attrName];
            }
        }
        return options;
    }
    moveClasses(parentEl, childEl) {
        let classes = parentEl.classList;
        if (classes.length > 0) {
            childEl.classList.add(...classes);
        }
        parentEl.className = '';
    }
    moveStyles(parentEl, childEl) {
        let style = parentEl.style.cssText;
        childEl.style.cssText = style;
        parentEl.style.cssText = '';
    }
    createComponent(options) {
        if (this.host) {
            return;
        }
        if (options) {
            JQXLite.extend(options, this.manageAttributes());
        }
        else {
            options = this.manageAttributes();
        }
        this.host = JQXLite(this.elementRef.nativeElement.firstChild);
        this.moveClasses(this.elementRef.nativeElement, this.host[0]);
        this.moveStyles(this.elementRef.nativeElement, this.host[0]);
        this.__wireEvents__();
        this.widgetObject = jqwidgets.createInstance(this.host, 'jqxKanban', options);
    }
    createWidget(options) {
        this.createComponent(options);
    }
    __updateRect__() {
        if (this.host)
            this.host.css({ width: this.attrWidth, height: this.attrHeight });
    }
    setOptions(options) {
        this.host.jqxKanban('setOptions', options);
    }
    // jqxKanbanComponent properties
    columnRenderer(arg) {
        if (arg !== undefined) {
            this.host.jqxKanban('columnRenderer', arg);
        }
        else {
            return this.host.jqxKanban('columnRenderer');
        }
    }
    columns(arg) {
        if (arg !== undefined) {
            this.host.jqxKanban('columns', arg);
        }
        else {
            return this.host.jqxKanban('columns');
        }
    }
    connectWith(arg) {
        if (arg !== undefined) {
            this.host.jqxKanban('connectWith', arg);
        }
        else {
            return this.host.jqxKanban('connectWith');
        }
    }
    headerHeight(arg) {
        if (arg !== undefined) {
            this.host.jqxKanban('headerHeight', arg);
        }
        else {
            return this.host.jqxKanban('headerHeight');
        }
    }
    headerWidth(arg) {
        if (arg !== undefined) {
            this.host.jqxKanban('headerWidth', arg);
        }
        else {
            return this.host.jqxKanban('headerWidth');
        }
    }
    height(arg) {
        if (arg !== undefined) {
            this.host.jqxKanban('height', arg);
        }
        else {
            return this.host.jqxKanban('height');
        }
    }
    itemRenderer(arg) {
        if (arg !== undefined) {
            this.host.jqxKanban('itemRenderer', arg);
        }
        else {
            return this.host.jqxKanban('itemRenderer');
        }
    }
    ready(arg) {
        if (arg !== undefined) {
            this.host.jqxKanban('ready', arg);
        }
        else {
            return this.host.jqxKanban('ready');
        }
    }
    rtl(arg) {
        if (arg !== undefined) {
            this.host.jqxKanban('rtl', arg);
        }
        else {
            return this.host.jqxKanban('rtl');
        }
    }
    source(arg) {
        if (arg !== undefined) {
            this.host.jqxKanban('source', arg);
        }
        else {
            return this.host.jqxKanban('source');
        }
    }
    resources(arg) {
        if (arg !== undefined) {
            this.host.jqxKanban('resources', arg);
        }
        else {
            return this.host.jqxKanban('resources');
        }
    }
    template(arg) {
        if (arg !== undefined) {
            this.host.jqxKanban('template', arg);
        }
        else {
            return this.host.jqxKanban('template');
        }
    }
    templateContent(arg) {
        if (arg !== undefined) {
            this.host.jqxKanban('templateContent', arg);
        }
        else {
            return this.host.jqxKanban('templateContent');
        }
    }
    theme(arg) {
        if (arg !== undefined) {
            this.host.jqxKanban('theme', arg);
        }
        else {
            return this.host.jqxKanban('theme');
        }
    }
    width(arg) {
        if (arg !== undefined) {
            this.host.jqxKanban('width', arg);
        }
        else {
            return this.host.jqxKanban('width');
        }
    }
    // jqxKanbanComponent functions
    addItem(newItem) {
        this.host.jqxKanban('addItem', newItem);
    }
    destroy() {
        this.host.jqxKanban('destroy');
    }
    getColumn(dataField) {
        return this.host.jqxKanban('getColumn', dataField);
    }
    getColumnItems(dataField) {
        return this.host.jqxKanban('getColumnItems', dataField);
    }
    getItems() {
        return this.host.jqxKanban('getItems');
    }
    removeItem(itemId) {
        this.host.jqxKanban('removeItem', itemId);
    }
    updateItem(itemId, newContent) {
        this.host.jqxKanban('updateItem', itemId, newContent);
    }
    __wireEvents__() {
        this.host.on('columnAttrClicked', (eventData) => { this.onColumnAttrClicked.emit(eventData); });
        this.host.on('columnCollapsed', (eventData) => { this.onColumnCollapsed.emit(eventData); });
        this.host.on('columnExpanded', (eventData) => { this.onColumnExpanded.emit(eventData); });
        this.host.on('itemAttrClicked', (eventData) => { this.onItemAttrClicked.emit(eventData); });
        this.host.on('itemMoved', (eventData) => { this.onItemMoved.emit(eventData); });
    }
}; //jqxKanbanComponent
jqxKanbanComponent.ctorParameters = () => [
    { type: ElementRef }
];
tslib_1.__decorate([
    Input('columnRenderer'),
    tslib_1.__metadata("design:type", Function)
], jqxKanbanComponent.prototype, "attrColumnRenderer", void 0);
tslib_1.__decorate([
    Input('columns'),
    tslib_1.__metadata("design:type", Array)
], jqxKanbanComponent.prototype, "attrColumns", void 0);
tslib_1.__decorate([
    Input('connectWith'),
    tslib_1.__metadata("design:type", String)
], jqxKanbanComponent.prototype, "attrConnectWith", void 0);
tslib_1.__decorate([
    Input('headerHeight'),
    tslib_1.__metadata("design:type", Object)
], jqxKanbanComponent.prototype, "attrHeaderHeight", void 0);
tslib_1.__decorate([
    Input('headerWidth'),
    tslib_1.__metadata("design:type", Number)
], jqxKanbanComponent.prototype, "attrHeaderWidth", void 0);
tslib_1.__decorate([
    Input('itemRenderer'),
    tslib_1.__metadata("design:type", Function)
], jqxKanbanComponent.prototype, "attrItemRenderer", void 0);
tslib_1.__decorate([
    Input('ready'),
    tslib_1.__metadata("design:type", Function)
], jqxKanbanComponent.prototype, "attrReady", void 0);
tslib_1.__decorate([
    Input('rtl'),
    tslib_1.__metadata("design:type", Boolean)
], jqxKanbanComponent.prototype, "attrRtl", void 0);
tslib_1.__decorate([
    Input('source'),
    tslib_1.__metadata("design:type", Object)
], jqxKanbanComponent.prototype, "attrSource", void 0);
tslib_1.__decorate([
    Input('resources'),
    tslib_1.__metadata("design:type", Object)
], jqxKanbanComponent.prototype, "attrResources", void 0);
tslib_1.__decorate([
    Input('template'),
    tslib_1.__metadata("design:type", String)
], jqxKanbanComponent.prototype, "attrTemplate", void 0);
tslib_1.__decorate([
    Input('templateContent'),
    tslib_1.__metadata("design:type", Object)
], jqxKanbanComponent.prototype, "attrTemplateContent", void 0);
tslib_1.__decorate([
    Input('theme'),
    tslib_1.__metadata("design:type", String)
], jqxKanbanComponent.prototype, "attrTheme", void 0);
tslib_1.__decorate([
    Input('width'),
    tslib_1.__metadata("design:type", Object)
], jqxKanbanComponent.prototype, "attrWidth", void 0);
tslib_1.__decorate([
    Input('height'),
    tslib_1.__metadata("design:type", Object)
], jqxKanbanComponent.prototype, "attrHeight", void 0);
tslib_1.__decorate([
    Input('auto-create'),
    tslib_1.__metadata("design:type", Boolean)
], jqxKanbanComponent.prototype, "autoCreate", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxKanbanComponent.prototype, "onColumnAttrClicked", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxKanbanComponent.prototype, "onColumnCollapsed", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxKanbanComponent.prototype, "onColumnExpanded", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxKanbanComponent.prototype, "onItemAttrClicked", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxKanbanComponent.prototype, "onItemMoved", void 0);
jqxKanbanComponent = tslib_1.__decorate([
    Component({
        selector: 'jqxKanban',
        template: '<div><ng-content></ng-content></div>'
    }),
    tslib_1.__metadata("design:paramtypes", [ElementRef])
], jqxKanbanComponent);
export { jqxKanbanComponent };

// jqwidgets-vue3/vue_jqxkanban.vue
<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
	import { onUpdated, onMounted } from 'vue';
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxsortable.js';
    import '../jqwidgets/jqxsplitter.js';
    import '../jqwidgets/jqxdata.js';
    import '../jqwidgets/jqxkanban.js';

    export default {
        props: {
            columnRenderer: Function,
            columns: Array,
            connectWith: String,
            headerHeight: Number,
            headerWidth: Number,
            height: [String, Number],
            itemRenderer: Function,
            ready: Function,
            rtl: {
                default: false,
                type: Boolean
            },
            source: [Array, Object],
            resources: [Array, Object],
            template: String,
            templateContent: Object,
            theme: String,
            width: [String, Number],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        emits: ["columnAttrClicked","columnCollapsed","columnExpanded","itemAttrClicked","itemMoved"],
        setup(props, context) {
			const id = "jqxKanban" + JQXLite.generateID();
			const componentSelector = '#' + id;
            function createComponent(options) {
                if (!props.autoCreate) __createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            }
            function setOptions (options) {
                JQXLite(componentSelector).jqxKanban(options);
            }
            function getOptions() {
                const usedProps = Object.keys(__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(componentSelector).jqxKanban(usedProps[i]);
                }
                return resultToReturn;
            }
            function addItem(newItem) {
                JQXLite(componentSelector).jqxKanban('addItem', newItem);  
            }
            function destroy() {
                JQXLite(componentSelector).jqxKanban('destroy');  
            }
            function getColumn(dataField) {
                return JQXLite(componentSelector).jqxKanban('getColumn', dataField);  
            }
            function getColumnItems(dataField) {
                return JQXLite(componentSelector).jqxKanban('getColumnItems', dataField);  
            }
            function getItems() {
                return JQXLite(componentSelector).jqxKanban('getItems');  
            }
            function removeItem(itemId) {
                JQXLite(componentSelector).jqxKanban('removeItem', itemId);  
            }
            function updateItem(itemId, newContent) {
                JQXLite(componentSelector).jqxKanban('updateItem', itemId, newContent);  
            }
            function _columnRenderer (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKanban('columnRenderer', arg)
                } else {
                    return JQXLite(componentSelector).jqxKanban('columnRenderer');
                }
            }
            function _columns (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKanban('columns', arg)
                } else {
                    return JQXLite(componentSelector).jqxKanban('columns');
                }
            }
            function _connectWith (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKanban('connectWith', arg)
                } else {
                    return JQXLite(componentSelector).jqxKanban('connectWith');
                }
            }
            function _headerHeight (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKanban('headerHeight', arg)
                } else {
                    return JQXLite(componentSelector).jqxKanban('headerHeight');
                }
            }
            function _headerWidth (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKanban('headerWidth', arg)
                } else {
                    return JQXLite(componentSelector).jqxKanban('headerWidth');
                }
            }
            function _height (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKanban('height', arg)
                } else {
                    return JQXLite(componentSelector).jqxKanban('height');
                }
            }
            function _itemRenderer (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKanban('itemRenderer', arg)
                } else {
                    return JQXLite(componentSelector).jqxKanban('itemRenderer');
                }
            }
            function _ready (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKanban('ready', arg)
                } else {
                    return JQXLite(componentSelector).jqxKanban('ready');
                }
            }
            function _rtl (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKanban('rtl', arg)
                } else {
                    return JQXLite(componentSelector).jqxKanban('rtl');
                }
            }
            function _source (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKanban('source', arg)
                } else {
                    return JQXLite(componentSelector).jqxKanban('source');
                }
            }
            function _resources (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKanban('resources', arg)
                } else {
                    return JQXLite(componentSelector).jqxKanban('resources');
                }
            }
            function _template (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKanban('template', arg)
                } else {
                    return JQXLite(componentSelector).jqxKanban('template');
                }
            }
            function _templateContent (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKanban('templateContent', arg)
                } else {
                    return JQXLite(componentSelector).jqxKanban('templateContent');
                }
            }
            function _theme (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKanban('theme', arg)
                } else {
                    return JQXLite(componentSelector).jqxKanban('theme');
                }
            }
            function _width (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxKanban('width', arg)
                } else {
                    return JQXLite(componentSelector).jqxKanban('width');
                }
            }
            function __createComponent__ (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = __manageProps__();
                JQXLite(componentSelector).jqxKanban(widgetOptions);
                __wireEvents__();
            }
            function __manageProps__() {
                const widgetProps = ['columnRenderer','columns','connectWith','headerHeight','headerWidth','height','itemRenderer','ready','rtl','source','resources','template','templateContent','theme','width'];
                const componentProps = props;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1 && componentProps[prop] !== undefined) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            }
            const options = {
                 get columnRenderer() {
                     return _columnRenderer();
                 },
                 set columnRenderer(newValue) {
                     _columnRenderer(newValue);
                 },
                 get columns() {
                     return _columns();
                 },
                 set columns(newValue) {
                     _columns(newValue);
                 },
                 get connectWith() {
                     return _connectWith();
                 },
                 set connectWith(newValue) {
                     _connectWith(newValue);
                 },
                 get headerHeight() {
                     return _headerHeight();
                 },
                 set headerHeight(newValue) {
                     _headerHeight(newValue);
                 },
                 get headerWidth() {
                     return _headerWidth();
                 },
                 set headerWidth(newValue) {
                     _headerWidth(newValue);
                 },
                 get height() {
                     return _height();
                 },
                 set height(newValue) {
                     _height(newValue);
                 },
                 get itemRenderer() {
                     return _itemRenderer();
                 },
                 set itemRenderer(newValue) {
                     _itemRenderer(newValue);
                 },
                 get ready() {
                     return _ready();
                 },
                 set ready(newValue) {
                     _ready(newValue);
                 },
                 get rtl() {
                     return _rtl();
                 },
                 set rtl(newValue) {
                     _rtl(newValue);
                 },
                 get source() {
                     return _source();
                 },
                 set source(newValue) {
                     _source(newValue);
                 },
                 get resources() {
                     return _resources();
                 },
                 set resources(newValue) {
                     _resources(newValue);
                 },
                 get template() {
                     return _template();
                 },
                 set template(newValue) {
                     _template(newValue);
                 },
                 get templateContent() {
                     return _templateContent();
                 },
                 set templateContent(newValue) {
                     _templateContent(newValue);
                 },
                 get theme() {
                     return _theme();
                 },
                 set theme(newValue) {
                     _theme(newValue);
                 },
                 get width() {
                     return _width();
                 },
                 set width(newValue) {
                     _width(newValue);
                 },
            }
            function __wireEvents__() {
                const that = context;

                JQXLite(componentSelector).on('columnAttrClicked', function (event) { that.emit('columnAttrClicked', event); });
                JQXLite(componentSelector).on('columnCollapsed', function (event) { that.emit('columnCollapsed', event); });
                JQXLite(componentSelector).on('columnExpanded', function (event) { that.emit('columnExpanded', event); });
                JQXLite(componentSelector).on('itemAttrClicked', function (event) { that.emit('itemAttrClicked', event); });
                JQXLite(componentSelector).on('itemMoved', function (event) { that.emit('itemMoved', event); });
            }

			onMounted(() => {
				if (props.autoCreate) __createComponent__();
			})
			onUpdated(() => {
				const widgetOptions = __manageProps__();
				JQXLite(componentSelector).jqxKanban(widgetOptions);
			})
			return {id, componentSelector, addItem,destroy,getColumn,getColumnItems,getItems,removeItem,updateItem, setOptions, options, getOptions, createComponent};
        },
    }
</script>
