// jqwidgets-react/react_jqxsplitter.js
import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxbuttons.js';
import '../jqwidgets/jqxsplitter.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxSplitter extends React.Component {
    constructor(props) {
        super(props);
        const widgetId = 'jqxSplitter' + JQXLite.generateID();
        this.componentSelector = '#' + widgetId;
        this.state = { id: widgetId };
    };
    componentDidMount() {
        const options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        const properties = ['disabled','height','orientation','panels','resizable','splitBarSize','showSplitBar','theme','width'];
        let options = {};
        for(let item in this.props) {
    	    if(item === 'settings') {
      	      for(let itemTwo in this.props[item]) {
        	        options[itemTwo] = this.props[item][itemTwo];
  			  }
  		  } else {
  			  if(properties.indexOf(item) !== -1) {
      		        options[item] = this.props[item];
  			  }
  		  }
  	  }
  	  return options;
	};
    createComponent(options) {
        if(!this.style) {
    	    for (let style in this.props.style) {
      	      JQXLite(this.componentSelector).css(style, this.props.style[style]);
    	    }
        }
        if(this.props.className !== undefined) {
            const classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
    	    JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxSplitter(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxSplitter('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxSplitter(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSplitter('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSplitter('disabled');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSplitter('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSplitter('height');
        }
    };
    orientation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSplitter('orientation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSplitter('orientation');
        }
    };
    panels(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSplitter('panels', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSplitter('panels');
        }
    };
    resizable(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSplitter('resizable', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSplitter('resizable');
        }
    };
    splitBarSize(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSplitter('splitBarSize', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSplitter('splitBarSize');
        }
    };
    showSplitBar(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSplitter('showSplitBar', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSplitter('showSplitBar');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSplitter('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSplitter('theme');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxSplitter('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxSplitter('width');
        }
    };
    collapse() {
        JQXLite(this.componentSelector).jqxSplitter('collapse');  
    };
    destroy() {
        JQXLite(this.componentSelector).jqxSplitter('destroy');  
    };
    disable() {
        JQXLite(this.componentSelector).jqxSplitter('disable');  
    };
    enable() {
        JQXLite(this.componentSelector).jqxSplitter('enable');  
    };
    expand() {
        JQXLite(this.componentSelector).jqxSplitter('expand');  
    };
    performRender() {
        JQXLite(this.componentSelector).jqxSplitter('render');
    };
    refresh() {
        JQXLite(this.componentSelector).jqxSplitter('refresh');  
    };
    render() {
        return (
            <div id={this.state.id}>{this.props.value}{this.props.children}</div>
        )
    };
};

// jqwidgets-vue3/vue_jqxsplitter.vue
<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
	import { onUpdated, onMounted } from 'vue';
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxsplitter.js';

    export default {
        props: {
            disabled: {
                default: false,
                type: Boolean
            },
            height: [Number, String],
            orientation: String,
            panels: Array,
            resizable: {
                default: true,
                type: Boolean
            },
            splitBarSize: Number,
            showSplitBar: {
                default: true,
                type: Boolean
            },
            theme: String,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        emits: ["collapsed","expanded","resize","resizeStart"],
        setup(props, context) {
			const id = "jqxSplitter" + JQXLite.generateID();
			const componentSelector = '#' + id;
            function createComponent(options) {
                if (!props.autoCreate) __createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            }
            function setOptions (options) {
                JQXLite(componentSelector).jqxSplitter(options);
            }
            function getOptions() {
                const usedProps = Object.keys(__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(componentSelector).jqxSplitter(usedProps[i]);
                }
                return resultToReturn;
            }
            function collapse() {
                JQXLite(componentSelector).jqxSplitter('collapse');  
            }
            function destroy() {
                JQXLite(componentSelector).jqxSplitter('destroy');  
            }
            function disable() {
                JQXLite(componentSelector).jqxSplitter('disable');  
            }
            function enable() {
                JQXLite(componentSelector).jqxSplitter('enable');  
            }
            function expand() {
                JQXLite(componentSelector).jqxSplitter('expand');  
            }
            function render() {
                JQXLite(componentSelector).jqxSplitter('render');  
            }
            function refresh() {
                JQXLite(componentSelector).jqxSplitter('refresh');  
            }
            function _disabled (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSplitter('disabled', arg)
                } else {
                    return JQXLite(componentSelector).jqxSplitter('disabled');
                }
            }
            function _height (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSplitter('height', arg)
                } else {
                    return JQXLite(componentSelector).jqxSplitter('height');
                }
            }
            function _orientation (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSplitter('orientation', arg)
                } else {
                    return JQXLite(componentSelector).jqxSplitter('orientation');
                }
            }
            function _panels (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSplitter('panels', arg)
                } else {
                    return JQXLite(componentSelector).jqxSplitter('panels');
                }
            }
            function _resizable (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSplitter('resizable', arg)
                } else {
                    return JQXLite(componentSelector).jqxSplitter('resizable');
                }
            }
            function _splitBarSize (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSplitter('splitBarSize', arg)
                } else {
                    return JQXLite(componentSelector).jqxSplitter('splitBarSize');
                }
            }
            function _showSplitBar (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSplitter('showSplitBar', arg)
                } else {
                    return JQXLite(componentSelector).jqxSplitter('showSplitBar');
                }
            }
            function _theme (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSplitter('theme', arg)
                } else {
                    return JQXLite(componentSelector).jqxSplitter('theme');
                }
            }
            function _width (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxSplitter('width', arg)
                } else {
                    return JQXLite(componentSelector).jqxSplitter('width');
                }
            }
            function __createComponent__ (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = __manageProps__();
                JQXLite(componentSelector).jqxSplitter(widgetOptions);
                __wireEvents__();
            }
            function __manageProps__() {
                const widgetProps = ['disabled','height','orientation','panels','resizable','splitBarSize','showSplitBar','theme','width'];
                const componentProps = props;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1 && componentProps[prop] !== undefined) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            }
            const options = {
                 get disabled() {
                     return _disabled();
                 },
                 set disabled(newValue) {
                     _disabled(newValue);
                 },
                 get height() {
                     return _height();
                 },
                 set height(newValue) {
                     _height(newValue);
                 },
                 get orientation() {
                     return _orientation();
                 },
                 set orientation(newValue) {
                     _orientation(newValue);
                 },
                 get panels() {
                     return _panels();
                 },
                 set panels(newValue) {
                     _panels(newValue);
                 },
                 get resizable() {
                     return _resizable();
                 },
                 set resizable(newValue) {
                     _resizable(newValue);
                 },
                 get splitBarSize() {
                     return _splitBarSize();
                 },
                 set splitBarSize(newValue) {
                     _splitBarSize(newValue);
                 },
                 get showSplitBar() {
                     return _showSplitBar();
                 },
                 set showSplitBar(newValue) {
                     _showSplitBar(newValue);
                 },
                 get theme() {
                     return _theme();
                 },
                 set theme(newValue) {
                     _theme(newValue);
                 },
                 get width() {
                     return _width();
                 },
                 set width(newValue) {
                     _width(newValue);
                 },
            }
            function __wireEvents__() {
                const that = context;

                JQXLite(componentSelector).on('collapsed', function (event) { that.emit('collapsed', event); });
                JQXLite(componentSelector).on('expanded', function (event) { that.emit('expanded', event); });
                JQXLite(componentSelector).on('resize', function (event) { that.emit('resize', event); });
                JQXLite(componentSelector).on('resizeStart', function (event) { that.emit('resizeStart', event); });
            }

			onMounted(() => {
				if (props.autoCreate) __createComponent__();
			})
			onUpdated(() => {
				const widgetOptions = __manageProps__();
				JQXLite(componentSelector).jqxSplitter(widgetOptions);
			})
			return {id, componentSelector, collapse,destroy,disable,enable,expand,render,refresh, setOptions, options, getOptions, createComponent};
        },
    }
</script>
