// jqwidgets-vue3/vue_jqxnavigationbar.vue
<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
	import { onUpdated, onMounted } from 'vue';
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxnavigationbar.js';

    export default {
        props: {
            animationType: String,
            arrowPosition: String,
            collapseAnimationDuration: Number,
            disabled: {
                default: false,
                type: Boolean
            },
            expandAnimationDuration: Number,
            expandMode: String,
            expandedIndexes: Array,
            height: [Number, String],
            initContent: Function,
            rtl: {
                default: false,
                type: Boolean
            },
            showArrow: {
                default: true,
                type: Boolean
            },
            theme: String,
            toggleMode: String,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        emits: ["collapsingItem","collapsedItem","expandingItem","expandedItem"],
        setup(props, context) {
			const id = "jqxNavigationBar" + JQXLite.generateID();
			const componentSelector = '#' + id;
            function createComponent(options) {
                if (!props.autoCreate) __createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            }
            function setOptions (options) {
                JQXLite(componentSelector).jqxNavigationBar(options);
            }
            function getOptions() {
                const usedProps = Object.keys(__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(componentSelector).jqxNavigationBar(usedProps[i]);
                }
                return resultToReturn;
            }
            function add(header, content) {
                JQXLite(componentSelector).jqxNavigationBar('add', header, content);  
            }
            function collapseAt(index) {
                JQXLite(componentSelector).jqxNavigationBar('collapseAt', index);  
            }
            function disableAt(index) {
                JQXLite(componentSelector).jqxNavigationBar('disableAt', index);  
            }
            function disable() {
                JQXLite(componentSelector).jqxNavigationBar('disable');  
            }
            function destroy() {
                JQXLite(componentSelector).jqxNavigationBar('destroy');  
            }
            function expandAt(index) {
                JQXLite(componentSelector).jqxNavigationBar('expandAt', index);  
            }
            function enableAt(index) {
                JQXLite(componentSelector).jqxNavigationBar('enableAt', index);  
            }
            function enable() {
                JQXLite(componentSelector).jqxNavigationBar('enable');  
            }
            function focus() {
                JQXLite(componentSelector).jqxNavigationBar('focus');  
            }
            function getHeaderContentAt(index) {
                return JQXLite(componentSelector).jqxNavigationBar('getHeaderContentAt', index);  
            }
            function getContentAt(index) {
                return JQXLite(componentSelector).jqxNavigationBar('getContentAt', index);  
            }
            function hideArrowAt(index) {
                JQXLite(componentSelector).jqxNavigationBar('hideArrowAt', index);  
            }
            function invalidate() {
                JQXLite(componentSelector).jqxNavigationBar('invalidate');  
            }
            function insert(Index, header, content) {
                JQXLite(componentSelector).jqxNavigationBar('insert', Index, header, content);  
            }
            function refresh() {
                JQXLite(componentSelector).jqxNavigationBar('refresh');  
            }
            function render() {
                JQXLite(componentSelector).jqxNavigationBar('render');  
            }
            function remove(index) {
                JQXLite(componentSelector).jqxNavigationBar('remove', index);  
            }
            function setContentAt(index, item) {
                JQXLite(componentSelector).jqxNavigationBar('setContentAt', index, item);  
            }
            function setHeaderContentAt(index, item) {
                JQXLite(componentSelector).jqxNavigationBar('setHeaderContentAt', index, item);  
            }
            function showArrowAt(index) {
                JQXLite(componentSelector).jqxNavigationBar('showArrowAt', index);  
            }
            function update(index, header, content) {
                JQXLite(componentSelector).jqxNavigationBar('update', index, header, content);  
            }
            function val(value) {
                if (value !== undefined) {
                    JQXLite(componentSelector).jqxNavigationBar('val',  value)
                } else {
                    return JQXLite(componentSelector).jqxNavigationBar('val');
                }
            }
            function _animationType (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxNavigationBar('animationType', arg)
                } else {
                    return JQXLite(componentSelector).jqxNavigationBar('animationType');
                }
            }
            function _arrowPosition (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxNavigationBar('arrowPosition', arg)
                } else {
                    return JQXLite(componentSelector).jqxNavigationBar('arrowPosition');
                }
            }
            function _collapseAnimationDuration (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxNavigationBar('collapseAnimationDuration', arg)
                } else {
                    return JQXLite(componentSelector).jqxNavigationBar('collapseAnimationDuration');
                }
            }
            function _disabled (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxNavigationBar('disabled', arg)
                } else {
                    return JQXLite(componentSelector).jqxNavigationBar('disabled');
                }
            }
            function _expandAnimationDuration (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxNavigationBar('expandAnimationDuration', arg)
                } else {
                    return JQXLite(componentSelector).jqxNavigationBar('expandAnimationDuration');
                }
            }
            function _expandMode (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxNavigationBar('expandMode', arg)
                } else {
                    return JQXLite(componentSelector).jqxNavigationBar('expandMode');
                }
            }
            function _expandedIndexes (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxNavigationBar('expandedIndexes', arg)
                } else {
                    return JQXLite(componentSelector).jqxNavigationBar('expandedIndexes');
                }
            }
            function _height (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxNavigationBar('height', arg)
                } else {
                    return JQXLite(componentSelector).jqxNavigationBar('height');
                }
            }
            function _initContent (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxNavigationBar('initContent', arg)
                } else {
                    return JQXLite(componentSelector).jqxNavigationBar('initContent');
                }
            }
            function _rtl (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxNavigationBar('rtl', arg)
                } else {
                    return JQXLite(componentSelector).jqxNavigationBar('rtl');
                }
            }
            function _showArrow (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxNavigationBar('showArrow', arg)
                } else {
                    return JQXLite(componentSelector).jqxNavigationBar('showArrow');
                }
            }
            function _theme (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxNavigationBar('theme', arg)
                } else {
                    return JQXLite(componentSelector).jqxNavigationBar('theme');
                }
            }
            function _toggleMode (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxNavigationBar('toggleMode', arg)
                } else {
                    return JQXLite(componentSelector).jqxNavigationBar('toggleMode');
                }
            }
            function _width (arg) {
                if (arg !== undefined) {
                    JQXLite(componentSelector).jqxNavigationBar('width', arg)
                } else {
                    return JQXLite(componentSelector).jqxNavigationBar('width');
                }
            }
            function __createComponent__ (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = __manageProps__();
                JQXLite(componentSelector).jqxNavigationBar(widgetOptions);
                __wireEvents__();
            }
            function __manageProps__() {
                const widgetProps = ['animationType','arrowPosition','collapseAnimationDuration','disabled','expandAnimationDuration','expandMode','expandedIndexes','height','initContent','rtl','showArrow','theme','toggleMode','width'];
                const componentProps = props;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1 && componentProps[prop] !== undefined) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            }
            const options = {
                 get animationType() {
                     return _animationType();
                 },
                 set animationType(newValue) {
                     _animationType(newValue);
                 },
                 get arrowPosition() {
                     return _arrowPosition();
                 },
                 set arrowPosition(newValue) {
                     _arrowPosition(newValue);
                 },
                 get collapseAnimationDuration() {
                     return _collapseAnimationDuration();
                 },
                 set collapseAnimationDuration(newValue) {
                     _collapseAnimationDuration(newValue);
                 },
                 get disabled() {
                     return _disabled();
                 },
                 set disabled(newValue) {
                     _disabled(newValue);
                 },
                 get expandAnimationDuration() {
                     return _expandAnimationDuration();
                 },
                 set expandAnimationDuration(newValue) {
                     _expandAnimationDuration(newValue);
                 },
                 get expandMode() {
                     return _expandMode();
                 },
                 set expandMode(newValue) {
                     _expandMode(newValue);
                 },
                 get expandedIndexes() {
                     return _expandedIndexes();
                 },
                 set expandedIndexes(newValue) {
                     _expandedIndexes(newValue);
                 },
                 get height() {
                     return _height();
                 },
                 set height(newValue) {
                     _height(newValue);
                 },
                 get initContent() {
                     return _initContent();
                 },
                 set initContent(newValue) {
                     _initContent(newValue);
                 },
                 get rtl() {
                     return _rtl();
                 },
                 set rtl(newValue) {
                     _rtl(newValue);
                 },
                 get showArrow() {
                     return _showArrow();
                 },
                 set showArrow(newValue) {
                     _showArrow(newValue);
                 },
                 get theme() {
                     return _theme();
                 },
                 set theme(newValue) {
                     _theme(newValue);
                 },
                 get toggleMode() {
                     return _toggleMode();
                 },
                 set toggleMode(newValue) {
                     _toggleMode(newValue);
                 },
                 get width() {
                     return _width();
                 },
                 set width(newValue) {
                     _width(newValue);
                 },
            }
            function __wireEvents__() {
                const that = context;

                JQXLite(componentSelector).on('collapsingItem', function (event) { that.emit('collapsingItem', event); });
                JQXLite(componentSelector).on('collapsedItem', function (event) { that.emit('collapsedItem', event); });
                JQXLite(componentSelector).on('expandingItem', function (event) { that.emit('expandingItem', event); });
                JQXLite(componentSelector).on('expandedItem', function (event) { that.emit('expandedItem', event); });
            }

			onMounted(() => {
				if (props.autoCreate) __createComponent__();
			})
			onUpdated(() => {
				const widgetOptions = __manageProps__();
				JQXLite(componentSelector).jqxNavigationBar(widgetOptions);
			})
			return {id, componentSelector, add,collapseAt,disableAt,disable,destroy,expandAt,enableAt,enable,focus,getHeaderContentAt,getContentAt,hideArrowAt,invalidate,insert,refresh,render,remove,setContentAt,setHeaderContentAt,showArrowAt,update,val, setOptions, options, getOptions, createComponent};
        },
    }
</script>

// jqwidgets-ng/esm2015/jqxnavigationbar/angular_jqxnavigationbar.js
import '../jqwidgets/jqxcore';
import '../jqwidgets/jqxnavigationbar';
/// <reference path="../../jqwidgets.d.ts" />
import * as tslib_1 from "tslib";
import { Component, Input, Output, EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
let jqxNavigationBarComponent = class jqxNavigationBarComponent {
    constructor(containerElement) {
        this.autoCreate = true;
        this.properties = ['animationType', 'arrowPosition', 'collapseAnimationDuration', 'disabled', 'expandAnimationDuration', 'expandMode', 'expandedIndexes', 'height', 'initContent', 'rtl', 'showArrow', 'theme', 'toggleMode', 'width'];
        // jqxNavigationBarComponent events
        this.onCollapsingItem = new EventEmitter();
        this.onCollapsedItem = new EventEmitter();
        this.onExpandingItem = new EventEmitter();
        this.onExpandedItem = new EventEmitter();
        this.elementRef = containerElement;
    }
    ngOnInit() {
        if (this.autoCreate) {
            this.createComponent();
        }
    }
    ;
    ngOnChanges(changes) {
        if (this.host) {
            for (let i = 0; i < this.properties.length; i++) {
                let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
                let areEqual = false;
                if (this[attrName] !== undefined) {
                    if (typeof this[attrName] === 'object') {
                        if (this[attrName] instanceof Array) {
                            areEqual = this.arraysEqual(this[attrName], this.host.jqxNavigationBar(this.properties[i]));
                        }
                        if (areEqual) {
                            return false;
                        }
                        this.host.jqxNavigationBar(this.properties[i], this[attrName]);
                        continue;
                    }
                    if (this[attrName] !== this.host.jqxNavigationBar(this.properties[i])) {
                        this.host.jqxNavigationBar(this.properties[i], this[attrName]);
                    }
                }
            }
        }
    }
    arraysEqual(attrValue, hostValue) {
        if ((attrValue && !hostValue) || (!attrValue && hostValue)) {
            return false;
        }
        if (attrValue.length != hostValue.length) {
            return false;
        }
        for (let i = 0; i < attrValue.length; i++) {
            if (attrValue[i] !== hostValue[i]) {
                return false;
            }
        }
        return true;
    }
    manageAttributes() {
        let options = {};
        for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            if (this[attrName] !== undefined) {
                options[this.properties[i]] = this[attrName];
            }
        }
        return options;
    }
    moveClasses(parentEl, childEl) {
        let classes = parentEl.classList;
        if (classes.length > 0) {
            childEl.classList.add(...classes);
        }
        parentEl.className = '';
    }
    moveStyles(parentEl, childEl) {
        let style = parentEl.style.cssText;
        childEl.style.cssText = style;
        parentEl.style.cssText = '';
    }
    createComponent(options) {
        if (this.host) {
            return;
        }
        if (options) {
            JQXLite.extend(options, this.manageAttributes());
        }
        else {
            options = this.manageAttributes();
        }
        this.host = JQXLite(this.elementRef.nativeElement.firstChild);
        this.moveClasses(this.elementRef.nativeElement, this.host[0]);
        this.moveStyles(this.elementRef.nativeElement, this.host[0]);
        this.__wireEvents__();
        this.widgetObject = jqwidgets.createInstance(this.host, 'jqxNavigationBar', options);
    }
    createWidget(options) {
        this.createComponent(options);
    }
    __updateRect__() {
        if (this.host)
            this.host.css({ width: this.attrWidth, height: this.attrHeight });
    }
    setOptions(options) {
        this.host.jqxNavigationBar('setOptions', options);
    }
    // jqxNavigationBarComponent properties
    animationType(arg) {
        if (arg !== undefined) {
            this.host.jqxNavigationBar('animationType', arg);
        }
        else {
            return this.host.jqxNavigationBar('animationType');
        }
    }
    arrowPosition(arg) {
        if (arg !== undefined) {
            this.host.jqxNavigationBar('arrowPosition', arg);
        }
        else {
            return this.host.jqxNavigationBar('arrowPosition');
        }
    }
    collapseAnimationDuration(arg) {
        if (arg !== undefined) {
            this.host.jqxNavigationBar('collapseAnimationDuration', arg);
        }
        else {
            return this.host.jqxNavigationBar('collapseAnimationDuration');
        }
    }
    disabled(arg) {
        if (arg !== undefined) {
            this.host.jqxNavigationBar('disabled', arg);
        }
        else {
            return this.host.jqxNavigationBar('disabled');
        }
    }
    expandAnimationDuration(arg) {
        if (arg !== undefined) {
            this.host.jqxNavigationBar('expandAnimationDuration', arg);
        }
        else {
            return this.host.jqxNavigationBar('expandAnimationDuration');
        }
    }
    expandMode(arg) {
        if (arg !== undefined) {
            this.host.jqxNavigationBar('expandMode', arg);
        }
        else {
            return this.host.jqxNavigationBar('expandMode');
        }
    }
    expandedIndexes(arg) {
        if (arg !== undefined) {
            this.host.jqxNavigationBar('expandedIndexes', arg);
        }
        else {
            return this.host.jqxNavigationBar('expandedIndexes');
        }
    }
    height(arg) {
        if (arg !== undefined) {
            this.host.jqxNavigationBar('height', arg);
        }
        else {
            return this.host.jqxNavigationBar('height');
        }
    }
    initContent(arg) {
        if (arg !== undefined) {
            this.host.jqxNavigationBar('initContent', arg);
        }
        else {
            return this.host.jqxNavigationBar('initContent');
        }
    }
    rtl(arg) {
        if (arg !== undefined) {
            this.host.jqxNavigationBar('rtl', arg);
        }
        else {
            return this.host.jqxNavigationBar('rtl');
        }
    }
    showArrow(arg) {
        if (arg !== undefined) {
            this.host.jqxNavigationBar('showArrow', arg);
        }
        else {
            return this.host.jqxNavigationBar('showArrow');
        }
    }
    theme(arg) {
        if (arg !== undefined) {
            this.host.jqxNavigationBar('theme', arg);
        }
        else {
            return this.host.jqxNavigationBar('theme');
        }
    }
    toggleMode(arg) {
        if (arg !== undefined) {
            this.host.jqxNavigationBar('toggleMode', arg);
        }
        else {
            return this.host.jqxNavigationBar('toggleMode');
        }
    }
    width(arg) {
        if (arg !== undefined) {
            this.host.jqxNavigationBar('width', arg);
        }
        else {
            return this.host.jqxNavigationBar('width');
        }
    }
    // jqxNavigationBarComponent functions
    add(header, content) {
        this.host.jqxNavigationBar('add', header, content);
    }
    collapseAt(index) {
        this.host.jqxNavigationBar('collapseAt', index);
    }
    disableAt(index) {
        this.host.jqxNavigationBar('disableAt', index);
    }
    disable() {
        this.host.jqxNavigationBar('disable');
    }
    destroy() {
        this.host.jqxNavigationBar('destroy');
    }
    expandAt(index) {
        this.host.jqxNavigationBar('expandAt', index);
    }
    enableAt(index) {
        this.host.jqxNavigationBar('enableAt', index);
    }
    enable() {
        this.host.jqxNavigationBar('enable');
    }
    focus() {
        this.host.jqxNavigationBar('focus');
    }
    getHeaderContentAt(index) {
        return this.host.jqxNavigationBar('getHeaderContentAt', index);
    }
    getContentAt(index) {
        return this.host.jqxNavigationBar('getContentAt', index);
    }
    hideArrowAt(index) {
        this.host.jqxNavigationBar('hideArrowAt', index);
    }
    invalidate() {
        this.host.jqxNavigationBar('invalidate');
    }
    insert(Index, header, content) {
        this.host.jqxNavigationBar('insert', Index, header, content);
    }
    refresh() {
        this.host.jqxNavigationBar('refresh');
    }
    render() {
        this.host.jqxNavigationBar('render');
    }
    remove(index) {
        this.host.jqxNavigationBar('remove', index);
    }
    setContentAt(index, item) {
        this.host.jqxNavigationBar('setContentAt', index, item);
    }
    setHeaderContentAt(index, item) {
        this.host.jqxNavigationBar('setHeaderContentAt', index, item);
    }
    showArrowAt(index) {
        this.host.jqxNavigationBar('showArrowAt', index);
    }
    update(index, header, content) {
        this.host.jqxNavigationBar('update', index, header, content);
    }
    val(value) {
        if (value !== undefined) {
            return this.host.jqxNavigationBar('val', value);
        }
        else {
            return this.host.jqxNavigationBar('val');
        }
    }
    ;
    __wireEvents__() {
        this.host.on('collapsingItem', (eventData) => { this.onCollapsingItem.emit(eventData); });
        this.host.on('collapsedItem', (eventData) => { this.onCollapsedItem.emit(eventData); });
        this.host.on('expandingItem', (eventData) => { this.onExpandingItem.emit(eventData); });
        this.host.on('expandedItem', (eventData) => { this.onExpandedItem.emit(eventData); });
    }
}; //jqxNavigationBarComponent
jqxNavigationBarComponent.ctorParameters = () => [
    { type: ElementRef }
];
tslib_1.__decorate([
    Input('animationType'),
    tslib_1.__metadata("design:type", String)
], jqxNavigationBarComponent.prototype, "attrAnimationType", void 0);
tslib_1.__decorate([
    Input('arrowPosition'),
    tslib_1.__metadata("design:type", String)
], jqxNavigationBarComponent.prototype, "attrArrowPosition", void 0);
tslib_1.__decorate([
    Input('collapseAnimationDuration'),
    tslib_1.__metadata("design:type", Number)
], jqxNavigationBarComponent.prototype, "attrCollapseAnimationDuration", void 0);
tslib_1.__decorate([
    Input('disabled'),
    tslib_1.__metadata("design:type", Boolean)
], jqxNavigationBarComponent.prototype, "attrDisabled", void 0);
tslib_1.__decorate([
    Input('expandAnimationDuration'),
    tslib_1.__metadata("design:type", Number)
], jqxNavigationBarComponent.prototype, "attrExpandAnimationDuration", void 0);
tslib_1.__decorate([
    Input('expandMode'),
    tslib_1.__metadata("design:type", String)
], jqxNavigationBarComponent.prototype, "attrExpandMode", void 0);
tslib_1.__decorate([
    Input('expandedIndexes'),
    tslib_1.__metadata("design:type", Array)
], jqxNavigationBarComponent.prototype, "attrExpandedIndexes", void 0);
tslib_1.__decorate([
    Input('initContent'),
    tslib_1.__metadata("design:type", Function)
], jqxNavigationBarComponent.prototype, "attrInitContent", void 0);
tslib_1.__decorate([
    Input('rtl'),
    tslib_1.__metadata("design:type", Boolean)
], jqxNavigationBarComponent.prototype, "attrRtl", void 0);
tslib_1.__decorate([
    Input('showArrow'),
    tslib_1.__metadata("design:type", Boolean)
], jqxNavigationBarComponent.prototype, "attrShowArrow", void 0);
tslib_1.__decorate([
    Input('theme'),
    tslib_1.__metadata("design:type", String)
], jqxNavigationBarComponent.prototype, "attrTheme", void 0);
tslib_1.__decorate([
    Input('toggleMode'),
    tslib_1.__metadata("design:type", String)
], jqxNavigationBarComponent.prototype, "attrToggleMode", void 0);
tslib_1.__decorate([
    Input('width'),
    tslib_1.__metadata("design:type", Object)
], jqxNavigationBarComponent.prototype, "attrWidth", void 0);
tslib_1.__decorate([
    Input('height'),
    tslib_1.__metadata("design:type", Object)
], jqxNavigationBarComponent.prototype, "attrHeight", void 0);
tslib_1.__decorate([
    Input('auto-create'),
    tslib_1.__metadata("design:type", Boolean)
], jqxNavigationBarComponent.prototype, "autoCreate", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxNavigationBarComponent.prototype, "onCollapsingItem", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxNavigationBarComponent.prototype, "onCollapsedItem", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxNavigationBarComponent.prototype, "onExpandingItem", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxNavigationBarComponent.prototype, "onExpandedItem", void 0);
jqxNavigationBarComponent = tslib_1.__decorate([
    Component({
        selector: 'jqxNavigationBar',
        template: '<div><ng-content></ng-content></div>'
    }),
    tslib_1.__metadata("design:paramtypes", [ElementRef])
], jqxNavigationBarComponent);
export { jqxNavigationBarComponent };
