// jqwidgets-vue/vue_jqxslider.vue
/*
jQWidgets v8.1.4 (2019-July)
Copyright (c) 2011-2019 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxslider.js';

    export default {
        props: {
            buttonsPosition: String,
            disabled: Boolean,
            height: [Number, String],
            layout: String,
            mode: String,
            minorTicksFrequency: Number,
            minorTickSize: Number,
            max: Number,
            min: Number,
            orientation: String,
            rangeSlider: Boolean,
            rtl: Boolean,
            step: Number,
            showTicks: Boolean,
            showMinorTicks: Boolean,
            showTickLabels: Boolean,
            showButtons: Boolean,
            showRange: Boolean,
            template: String,
            theme: String,
            ticksPosition: String,
            ticksFrequency: Number,
            tickSize: Number,
            tickLabelFormatFunction: Function,
            tooltip: Boolean,
            tooltipHideDelay: Number,
            tooltipPosition: String,
            tooltipFormatFunction: Function,
            value: Number,
            values: Array,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxSlider' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxSlider(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxSlider(usedProps[i]);
                }
                return resultToReturn;
            },
            destroy: function() {
                JQXLite(this.componentSelector).jqxSlider('destroy');  
            },
            decrementValue: function() {
                JQXLite(this.componentSelector).jqxSlider('decrementValue');  
            },
            disable: function() {
                JQXLite(this.componentSelector).jqxSlider('disable');  
            },
            enable: function() {
                JQXLite(this.componentSelector).jqxSlider('enable');  
            },
            focus: function() {
                JQXLite(this.componentSelector).jqxSlider('focus');  
            },
            getValue: function() {
                return JQXLite(this.componentSelector).jqxSlider('getValue');  
            },
            incrementValue: function() {
                JQXLite(this.componentSelector).jqxSlider('incrementValue');  
            },
            setValue: function(index) {
                JQXLite(this.componentSelector).jqxSlider('setValue', index);  
            },
            val: function(value) {
                if (value !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('val',  value)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('val');
                }
            },
            _buttonsPosition: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('buttonsPosition', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('buttonsPosition');
                }
            },
            _disabled: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('disabled', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('disabled');
                }
            },
            _height: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('height', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('height');
                }
            },
            _layout: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('layout', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('layout');
                }
            },
            _mode: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('mode', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('mode');
                }
            },
            _minorTicksFrequency: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('minorTicksFrequency', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('minorTicksFrequency');
                }
            },
            _minorTickSize: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('minorTickSize', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('minorTickSize');
                }
            },
            _max: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('max', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('max');
                }
            },
            _min: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('min', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('min');
                }
            },
            _orientation: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('orientation', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('orientation');
                }
            },
            _rangeSlider: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('rangeSlider', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('rangeSlider');
                }
            },
            _rtl: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('rtl', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('rtl');
                }
            },
            _step: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('step', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('step');
                }
            },
            _showTicks: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('showTicks', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('showTicks');
                }
            },
            _showMinorTicks: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('showMinorTicks', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('showMinorTicks');
                }
            },
            _showTickLabels: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('showTickLabels', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('showTickLabels');
                }
            },
            _showButtons: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('showButtons', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('showButtons');
                }
            },
            _showRange: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('showRange', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('showRange');
                }
            },
            _template: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('template', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('template');
                }
            },
            _theme: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('theme', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('theme');
                }
            },
            _ticksPosition: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('ticksPosition', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('ticksPosition');
                }
            },
            _ticksFrequency: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('ticksFrequency', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('ticksFrequency');
                }
            },
            _tickSize: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('tickSize', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('tickSize');
                }
            },
            _tickLabelFormatFunction: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('tickLabelFormatFunction', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('tickLabelFormatFunction');
                }
            },
            _tooltip: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('tooltip', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('tooltip');
                }
            },
            _tooltipHideDelay: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('tooltipHideDelay', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('tooltipHideDelay');
                }
            },
            _tooltipPosition: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('tooltipPosition', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('tooltipPosition');
                }
            },
            _tooltipFormatFunction: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('tooltipFormatFunction', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('tooltipFormatFunction');
                }
            },
            _value: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('value', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('value');
                }
            },
            _values: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('values', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('values');
                }
            },
            _width: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSlider('width', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSlider('width');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxSlider(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['buttonsPosition','disabled','height','layout','mode','minorTicksFrequency','minorTickSize','max','min','orientation','rangeSlider','rtl','step','showTicks','showMinorTicks','showTickLabels','showButtons','showRange','template','theme','ticksPosition','ticksFrequency','tickSize','tickLabelFormatFunction','tooltip','tooltipHideDelay','tooltipPosition','tooltipFormatFunction','value','values','width'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'buttonsPosition', {
                    get: function() {
                        return that._buttonsPosition();
                    },
                    set: function(newValue) {
                        that._buttonsPosition(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'disabled', {
                    get: function() {
                        return that._disabled();
                    },
                    set: function(newValue) {
                        that._disabled(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'height', {
                    get: function() {
                        return that._height();
                    },
                    set: function(newValue) {
                        that._height(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'layout', {
                    get: function() {
                        return that._layout();
                    },
                    set: function(newValue) {
                        that._layout(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'mode', {
                    get: function() {
                        return that._mode();
                    },
                    set: function(newValue) {
                        that._mode(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'minorTicksFrequency', {
                    get: function() {
                        return that._minorTicksFrequency();
                    },
                    set: function(newValue) {
                        that._minorTicksFrequency(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'minorTickSize', {
                    get: function() {
                        return that._minorTickSize();
                    },
                    set: function(newValue) {
                        that._minorTickSize(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'max', {
                    get: function() {
                        return that._max();
                    },
                    set: function(newValue) {
                        that._max(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'min', {
                    get: function() {
                        return that._min();
                    },
                    set: function(newValue) {
                        that._min(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'orientation', {
                    get: function() {
                        return that._orientation();
                    },
                    set: function(newValue) {
                        that._orientation(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'rangeSlider', {
                    get: function() {
                        return that._rangeSlider();
                    },
                    set: function(newValue) {
                        that._rangeSlider(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'rtl', {
                    get: function() {
                        return that._rtl();
                    },
                    set: function(newValue) {
                        that._rtl(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'step', {
                    get: function() {
                        return that._step();
                    },
                    set: function(newValue) {
                        that._step(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'showTicks', {
                    get: function() {
                        return that._showTicks();
                    },
                    set: function(newValue) {
                        that._showTicks(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'showMinorTicks', {
                    get: function() {
                        return that._showMinorTicks();
                    },
                    set: function(newValue) {
                        that._showMinorTicks(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'showTickLabels', {
                    get: function() {
                        return that._showTickLabels();
                    },
                    set: function(newValue) {
                        that._showTickLabels(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'showButtons', {
                    get: function() {
                        return that._showButtons();
                    },
                    set: function(newValue) {
                        that._showButtons(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'showRange', {
                    get: function() {
                        return that._showRange();
                    },
                    set: function(newValue) {
                        that._showRange(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'template', {
                    get: function() {
                        return that._template();
                    },
                    set: function(newValue) {
                        that._template(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'theme', {
                    get: function() {
                        return that._theme();
                    },
                    set: function(newValue) {
                        that._theme(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'ticksPosition', {
                    get: function() {
                        return that._ticksPosition();
                    },
                    set: function(newValue) {
                        that._ticksPosition(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'ticksFrequency', {
                    get: function() {
                        return that._ticksFrequency();
                    },
                    set: function(newValue) {
                        that._ticksFrequency(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'tickSize', {
                    get: function() {
                        return that._tickSize();
                    },
                    set: function(newValue) {
                        that._tickSize(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'tickLabelFormatFunction', {
                    get: function() {
                        return that._tickLabelFormatFunction();
                    },
                    set: function(newValue) {
                        that._tickLabelFormatFunction(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'tooltip', {
                    get: function() {
                        return that._tooltip();
                    },
                    set: function(newValue) {
                        that._tooltip(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'tooltipHideDelay', {
                    get: function() {
                        return that._tooltipHideDelay();
                    },
                    set: function(newValue) {
                        that._tooltipHideDelay(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'tooltipPosition', {
                    get: function() {
                        return that._tooltipPosition();
                    },
                    set: function(newValue) {
                        that._tooltipPosition(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'tooltipFormatFunction', {
                    get: function() {
                        return that._tooltipFormatFunction();
                    },
                    set: function(newValue) {
                        that._tooltipFormatFunction(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'value', {
                    get: function() {
                        return that._value();
                    },
                    set: function(newValue) {
                        that._value(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'values', {
                    get: function() {
                        return that._values();
                    },
                    set: function(newValue) {
                        that._values(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'width', {
                    get: function() {
                        return that._width();
                    },
                    set: function(newValue) {
                        that._width(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __twoWayDataBinding__: function () {
                const value = JQXLite(this.componentSelector).jqxSlider('val');
                this.$emit('input', value);
            },
            __wireEvents__: function () {
                const that = this;

                JQXLite(this.componentSelector).on('change', function (event) { that.$emit('change', event); that.__twoWayDataBinding__(); });
                JQXLite(this.componentSelector).on('slide', function (event) { that.$emit('slide', event); });
                JQXLite(this.componentSelector).on('slideStart', function (event) { that.$emit('slideStart', event); });
                JQXLite(this.componentSelector).on('slideEnd', function (event) { that.$emit('slideEnd', event); });
            }
        }
    }
</script>

// jqwidgets-ng/esm5/jqxslider/angular_jqxslider.js
import '../jqwidgets/jqxcore';
import '../jqwidgets/jqxbuttons';
import '../jqwidgets/jqxslider';
/// <reference path="../../jqwidgets.d.ts" />
import * as tslib_1 from "tslib";
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges, ChangeDetectionStrategy } from '@angular/core';
import { NG_VALUE_ACCESSOR } from '@angular/forms';
var noop = function () { };
var ɵ0 = noop;
var CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(function () { return jqxSliderComponent; }),
    multi: true
};
var jqxSliderComponent = /** @class */ (function () {
    function jqxSliderComponent(containerElement) {
        this.autoCreate = true;
        this.properties = ['buttonsPosition', 'disabled', 'height', 'layout', 'mode', 'minorTicksFrequency', 'minorTickSize', 'max', 'min', 'orientation', 'rangeSlider', 'rtl', 'step', 'showTicks', 'showMinorTicks', 'showTickLabels', 'showButtons', 'showRange', 'template', 'theme', 'ticksPosition', 'ticksFrequency', 'tickSize', 'tickLabelFormatFunction', 'tooltip', 'tooltipHideDelay', 'tooltipPosition', 'tooltipFormatFunction', 'value', 'values', 'width'];
        this.onTouchedCallback = noop;
        this.onChangeCallback = noop;
        // jqxSliderComponent events
        this.onChange = new EventEmitter();
        this.onSlide = new EventEmitter();
        this.onSlideStart = new EventEmitter();
        this.onSlideEnd = new EventEmitter();
        this.elementRef = containerElement;
    }
    jqxSliderComponent.prototype.ngOnInit = function () {
        if (this.autoCreate) {
            this.createComponent();
        }
    };
    ;
    jqxSliderComponent.prototype.ngOnChanges = function (changes) {
        if (this.host) {
            for (var i = 0; i < this.properties.length; i++) {
                var attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
                var areEqual = false;
                if (this[attrName] !== undefined) {
                    if (typeof this[attrName] === 'object') {
                        if (this[attrName] instanceof Array) {
                            areEqual = this.arraysEqual(this[attrName], this.host.jqxSlider(this.properties[i]));
                        }
                        if (areEqual) {
                            return false;
                        }
                        this.host.jqxSlider(this.properties[i], this[attrName]);
                        continue;
                    }
                    if (this[attrName] !== this.host.jqxSlider(this.properties[i])) {
                        this.host.jqxSlider(this.properties[i], this[attrName]);
                    }
                }
            }
        }
    };
    jqxSliderComponent.prototype.arraysEqual = function (attrValue, hostValue) {
        if ((attrValue && !hostValue) || (!attrValue && hostValue)) {
            return false;
        }
        if (attrValue.length != hostValue.length) {
            return false;
        }
        for (var i = 0; i < attrValue.length; i++) {
            if (attrValue[i] !== hostValue[i]) {
                return false;
            }
        }
        return true;
    };
    jqxSliderComponent.prototype.manageAttributes = function () {
        var options = {};
        for (var i = 0; i < this.properties.length; i++) {
            var attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            if (this[attrName] !== undefined) {
                options[this.properties[i]] = this[attrName];
            }
        }
        return options;
    };
    jqxSliderComponent.prototype.moveClasses = function (parentEl, childEl) {
        var _a;
        var classes = parentEl.classList;
        if (classes.length > 0) {
            (_a = childEl.classList).add.apply(_a, tslib_1.__spread(classes));
        }
        parentEl.className = '';
    };
    jqxSliderComponent.prototype.moveStyles = function (parentEl, childEl) {
        var style = parentEl.style.cssText;
        childEl.style.cssText = style;
        parentEl.style.cssText = '';
    };
    jqxSliderComponent.prototype.createComponent = function (options) {
        if (this.host) {
            return;
        }
        if (options) {
            JQXLite.extend(options, this.manageAttributes());
        }
        else {
            options = this.manageAttributes();
        }
        this.host = JQXLite(this.elementRef.nativeElement.firstChild);
        this.moveClasses(this.elementRef.nativeElement, this.host[0]);
        this.moveStyles(this.elementRef.nativeElement, this.host[0]);
        this.__wireEvents__();
        this.widgetObject = jqwidgets.createInstance(this.host, 'jqxSlider', options);
    };
    jqxSliderComponent.prototype.createWidget = function (options) {
        this.createComponent(options);
    };
    jqxSliderComponent.prototype.__updateRect__ = function () {
        if (this.host)
            this.host.css({ width: this.attrWidth, height: this.attrHeight });
    };
    Object.defineProperty(jqxSliderComponent.prototype, "ngValue", {
        get: function () {
            if (this.widgetObject) {
                var value = this.host.val();
                return value;
            }
            return '';
        },
        set: function (value) {
            if (this.widgetObject) {
                this.onChangeCallback(value);
            }
        },
        enumerable: true,
        configurable: true
    });
    jqxSliderComponent.prototype.writeValue = function (value) {
        if (this.widgetObject) {
            this.onChangeCallback(this.host.val());
        }
    };
    jqxSliderComponent.prototype.registerOnChange = function (fn) {
        this.onChangeCallback = fn;
    };
    jqxSliderComponent.prototype.registerOnTouched = function (fn) {
        this.onTouchedCallback = fn;
    };
    jqxSliderComponent.prototype.setOptions = function (options) {
        this.host.jqxSlider('setOptions', options);
    };
    // jqxSliderComponent properties
    jqxSliderComponent.prototype.buttonsPosition = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('buttonsPosition', arg);
        }
        else {
            return this.host.jqxSlider('buttonsPosition');
        }
    };
    jqxSliderComponent.prototype.disabled = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('disabled', arg);
        }
        else {
            return this.host.jqxSlider('disabled');
        }
    };
    jqxSliderComponent.prototype.height = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('height', arg);
        }
        else {
            return this.host.jqxSlider('height');
        }
    };
    jqxSliderComponent.prototype.layout = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('layout', arg);
        }
        else {
            return this.host.jqxSlider('layout');
        }
    };
    jqxSliderComponent.prototype.mode = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('mode', arg);
        }
        else {
            return this.host.jqxSlider('mode');
        }
    };
    jqxSliderComponent.prototype.minorTicksFrequency = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('minorTicksFrequency', arg);
        }
        else {
            return this.host.jqxSlider('minorTicksFrequency');
        }
    };
    jqxSliderComponent.prototype.minorTickSize = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('minorTickSize', arg);
        }
        else {
            return this.host.jqxSlider('minorTickSize');
        }
    };
    jqxSliderComponent.prototype.max = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('max', arg);
        }
        else {
            return this.host.jqxSlider('max');
        }
    };
    jqxSliderComponent.prototype.min = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('min', arg);
        }
        else {
            return this.host.jqxSlider('min');
        }
    };
    jqxSliderComponent.prototype.orientation = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('orientation', arg);
        }
        else {
            return this.host.jqxSlider('orientation');
        }
    };
    jqxSliderComponent.prototype.rangeSlider = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('rangeSlider', arg);
        }
        else {
            return this.host.jqxSlider('rangeSlider');
        }
    };
    jqxSliderComponent.prototype.rtl = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('rtl', arg);
        }
        else {
            return this.host.jqxSlider('rtl');
        }
    };
    jqxSliderComponent.prototype.step = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('step', arg);
        }
        else {
            return this.host.jqxSlider('step');
        }
    };
    jqxSliderComponent.prototype.showTicks = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('showTicks', arg);
        }
        else {
            return this.host.jqxSlider('showTicks');
        }
    };
    jqxSliderComponent.prototype.showMinorTicks = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('showMinorTicks', arg);
        }
        else {
            return this.host.jqxSlider('showMinorTicks');
        }
    };
    jqxSliderComponent.prototype.showTickLabels = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('showTickLabels', arg);
        }
        else {
            return this.host.jqxSlider('showTickLabels');
        }
    };
    jqxSliderComponent.prototype.showButtons = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('showButtons', arg);
        }
        else {
            return this.host.jqxSlider('showButtons');
        }
    };
    jqxSliderComponent.prototype.showRange = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('showRange', arg);
        }
        else {
            return this.host.jqxSlider('showRange');
        }
    };
    jqxSliderComponent.prototype.template = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('template', arg);
        }
        else {
            return this.host.jqxSlider('template');
        }
    };
    jqxSliderComponent.prototype.theme = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('theme', arg);
        }
        else {
            return this.host.jqxSlider('theme');
        }
    };
    jqxSliderComponent.prototype.ticksPosition = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('ticksPosition', arg);
        }
        else {
            return this.host.jqxSlider('ticksPosition');
        }
    };
    jqxSliderComponent.prototype.ticksFrequency = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('ticksFrequency', arg);
        }
        else {
            return this.host.jqxSlider('ticksFrequency');
        }
    };
    jqxSliderComponent.prototype.tickSize = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('tickSize', arg);
        }
        else {
            return this.host.jqxSlider('tickSize');
        }
    };
    jqxSliderComponent.prototype.tickLabelFormatFunction = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('tickLabelFormatFunction', arg);
        }
        else {
            return this.host.jqxSlider('tickLabelFormatFunction');
        }
    };
    jqxSliderComponent.prototype.tooltip = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('tooltip', arg);
        }
        else {
            return this.host.jqxSlider('tooltip');
        }
    };
    jqxSliderComponent.prototype.tooltipHideDelay = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('tooltipHideDelay', arg);
        }
        else {
            return this.host.jqxSlider('tooltipHideDelay');
        }
    };
    jqxSliderComponent.prototype.tooltipPosition = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('tooltipPosition', arg);
        }
        else {
            return this.host.jqxSlider('tooltipPosition');
        }
    };
    jqxSliderComponent.prototype.tooltipFormatFunction = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('tooltipFormatFunction', arg);
        }
        else {
            return this.host.jqxSlider('tooltipFormatFunction');
        }
    };
    jqxSliderComponent.prototype.value = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('value', arg);
        }
        else {
            return this.host.jqxSlider('value');
        }
    };
    jqxSliderComponent.prototype.values = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('values', arg);
        }
        else {
            return this.host.jqxSlider('values');
        }
    };
    jqxSliderComponent.prototype.width = function (arg) {
        if (arg !== undefined) {
            this.host.jqxSlider('width', arg);
        }
        else {
            return this.host.jqxSlider('width');
        }
    };
    // jqxSliderComponent functions
    jqxSliderComponent.prototype.destroy = function () {
        this.host.jqxSlider('destroy');
    };
    jqxSliderComponent.prototype.decrementValue = function () {
        this.host.jqxSlider('decrementValue');
    };
    jqxSliderComponent.prototype.disable = function () {
        this.host.jqxSlider('disable');
    };
    jqxSliderComponent.prototype.enable = function () {
        this.host.jqxSlider('enable');
    };
    jqxSliderComponent.prototype.focus = function () {
        this.host.jqxSlider('focus');
    };
    jqxSliderComponent.prototype.getValue = function () {
        return this.host.jqxSlider('getValue');
    };
    jqxSliderComponent.prototype.incrementValue = function () {
        this.host.jqxSlider('incrementValue');
    };
    jqxSliderComponent.prototype.setValue = function (index) {
        this.host.jqxSlider('setValue', index);
    };
    jqxSliderComponent.prototype.val = function (value) {
        if (value !== undefined) {
            return this.host.jqxSlider('val', value);
        }
        else {
            return this.host.jqxSlider('val');
        }
    };
    ;
    jqxSliderComponent.prototype.__wireEvents__ = function () {
        var _this = this;
        this.host.on('change', function (eventData) { _this.onChange.emit(eventData); _this.onChangeCallback(_this.host.val()); });
        this.host.on('slide', function (eventData) { _this.onSlide.emit(eventData); });
        this.host.on('slideStart', function (eventData) { _this.onSlideStart.emit(eventData); });
        this.host.on('slideEnd', function (eventData) { _this.onSlideEnd.emit(eventData); });
    };
    jqxSliderComponent.ctorParameters = function () { return [
        { type: ElementRef }
    ]; };
    tslib_1.__decorate([
        Input('buttonsPosition'),
        tslib_1.__metadata("design:type", String)
    ], jqxSliderComponent.prototype, "attrButtonsPosition", void 0);
    tslib_1.__decorate([
        Input('disabled'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxSliderComponent.prototype, "attrDisabled", void 0);
    tslib_1.__decorate([
        Input('layout'),
        tslib_1.__metadata("design:type", String)
    ], jqxSliderComponent.prototype, "attrLayout", void 0);
    tslib_1.__decorate([
        Input('mode'),
        tslib_1.__metadata("design:type", String)
    ], jqxSliderComponent.prototype, "attrMode", void 0);
    tslib_1.__decorate([
        Input('minorTicksFrequency'),
        tslib_1.__metadata("design:type", Number)
    ], jqxSliderComponent.prototype, "attrMinorTicksFrequency", void 0);
    tslib_1.__decorate([
        Input('minorTickSize'),
        tslib_1.__metadata("design:type", Number)
    ], jqxSliderComponent.prototype, "attrMinorTickSize", void 0);
    tslib_1.__decorate([
        Input('max'),
        tslib_1.__metadata("design:type", Number)
    ], jqxSliderComponent.prototype, "attrMax", void 0);
    tslib_1.__decorate([
        Input('min'),
        tslib_1.__metadata("design:type", Number)
    ], jqxSliderComponent.prototype, "attrMin", void 0);
    tslib_1.__decorate([
        Input('orientation'),
        tslib_1.__metadata("design:type", String)
    ], jqxSliderComponent.prototype, "attrOrientation", void 0);
    tslib_1.__decorate([
        Input('rangeSlider'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxSliderComponent.prototype, "attrRangeSlider", void 0);
    tslib_1.__decorate([
        Input('rtl'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxSliderComponent.prototype, "attrRtl", void 0);
    tslib_1.__decorate([
        Input('step'),
        tslib_1.__metadata("design:type", Number)
    ], jqxSliderComponent.prototype, "attrStep", void 0);
    tslib_1.__decorate([
        Input('showTicks'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxSliderComponent.prototype, "attrShowTicks", void 0);
    tslib_1.__decorate([
        Input('showMinorTicks'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxSliderComponent.prototype, "attrShowMinorTicks", void 0);
    tslib_1.__decorate([
        Input('showTickLabels'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxSliderComponent.prototype, "attrShowTickLabels", void 0);
    tslib_1.__decorate([
        Input('showButtons'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxSliderComponent.prototype, "attrShowButtons", void 0);
    tslib_1.__decorate([
        Input('showRange'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxSliderComponent.prototype, "attrShowRange", void 0);
    tslib_1.__decorate([
        Input('template'),
        tslib_1.__metadata("design:type", String)
    ], jqxSliderComponent.prototype, "attrTemplate", void 0);
    tslib_1.__decorate([
        Input('theme'),
        tslib_1.__metadata("design:type", String)
    ], jqxSliderComponent.prototype, "attrTheme", void 0);
    tslib_1.__decorate([
        Input('ticksPosition'),
        tslib_1.__metadata("design:type", String)
    ], jqxSliderComponent.prototype, "attrTicksPosition", void 0);
    tslib_1.__decorate([
        Input('ticksFrequency'),
        tslib_1.__metadata("design:type", Number)
    ], jqxSliderComponent.prototype, "attrTicksFrequency", void 0);
    tslib_1.__decorate([
        Input('tickSize'),
        tslib_1.__metadata("design:type", Number)
    ], jqxSliderComponent.prototype, "attrTickSize", void 0);
    tslib_1.__decorate([
        Input('tickLabelFormatFunction'),
        tslib_1.__metadata("design:type", Function)
    ], jqxSliderComponent.prototype, "attrTickLabelFormatFunction", void 0);
    tslib_1.__decorate([
        Input('tooltip'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxSliderComponent.prototype, "attrTooltip", void 0);
    tslib_1.__decorate([
        Input('tooltipHideDelay'),
        tslib_1.__metadata("design:type", Number)
    ], jqxSliderComponent.prototype, "attrTooltipHideDelay", void 0);
    tslib_1.__decorate([
        Input('tooltipPosition'),
        tslib_1.__metadata("design:type", String)
    ], jqxSliderComponent.prototype, "attrTooltipPosition", void 0);
    tslib_1.__decorate([
        Input('tooltipFormatFunction'),
        tslib_1.__metadata("design:type", Function)
    ], jqxSliderComponent.prototype, "attrTooltipFormatFunction", void 0);
    tslib_1.__decorate([
        Input('value'),
        tslib_1.__metadata("design:type", Object)
    ], jqxSliderComponent.prototype, "attrValue", void 0);
    tslib_1.__decorate([
        Input('values'),
        tslib_1.__metadata("design:type", Array)
    ], jqxSliderComponent.prototype, "attrValues", void 0);
    tslib_1.__decorate([
        Input('width'),
        tslib_1.__metadata("design:type", Object)
    ], jqxSliderComponent.prototype, "attrWidth", void 0);
    tslib_1.__decorate([
        Input('height'),
        tslib_1.__metadata("design:type", Object)
    ], jqxSliderComponent.prototype, "attrHeight", void 0);
    tslib_1.__decorate([
        Input('auto-create'),
        tslib_1.__metadata("design:type", Boolean)
    ], jqxSliderComponent.prototype, "autoCreate", void 0);
    tslib_1.__decorate([
        Output(),
        tslib_1.__metadata("design:type", Object)
    ], jqxSliderComponent.prototype, "onChange", void 0);
    tslib_1.__decorate([
        Output(),
        tslib_1.__metadata("design:type", Object)
    ], jqxSliderComponent.prototype, "onSlide", void 0);
    tslib_1.__decorate([
        Output(),
        tslib_1.__metadata("design:type", Object)
    ], jqxSliderComponent.prototype, "onSlideStart", void 0);
    tslib_1.__decorate([
        Output(),
        tslib_1.__metadata("design:type", Object)
    ], jqxSliderComponent.prototype, "onSlideEnd", void 0);
    jqxSliderComponent = tslib_1.__decorate([
        Component({
            selector: 'jqxSlider',
            template: '<div><ng-content></ng-content></div>',
            providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR],
            changeDetection: ChangeDetectionStrategy.OnPush
        }),
        tslib_1.__metadata("design:paramtypes", [ElementRef])
    ], jqxSliderComponent);
    return jqxSliderComponent;
}()); //jqxSliderComponent
export { jqxSliderComponent };
export { ɵ0 };
