// jqwidgets-react/react_jqxcalendar.js
/*
jQWidgets v6.0.4 (2018-July)
Copyright (c) 2011-2018 jQWidgets.
License: https://jqwidgets.com/license/
*/

import '../jqwidgets/styles/jqx.base.css';
import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxbuttons.js';
import '../jqwidgets/jqxtooltip.js';
import '../jqwidgets/globalization/globalize.js';
import '../jqwidgets/jqxdatetimeinput.js';
import '../jqwidgets/jqxcalendar.js';

import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxCalendar extends React.Component {
    componentDidMount() {
        let options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        let properties = ['backText','columnHeaderHeight','clearString','culture','dayNameFormat','disabled','enableWeekend','enableViews','enableOtherMonthDays','enableFastNavigation','enableHover','enableAutoNavigation','enableTooltips','forwardText','firstDayOfWeek','height','min','max','navigationDelay','rowHeaderWidth','readOnly','restrictedDates','rtl','stepMonths','showWeekNumbers','showDayNames','showOtherMonthDays','showFooter','selectionMode','specialDates','theme','titleHeight','titleFormat','todayString','value','width'];
        let options = {};
        for(let item in this.props) {
              if(item === 'settings') {
                  for(let itemTwo in this.props[item]) {
                      options[itemTwo] = this.props[item][itemTwo];
                      }
                } else {
                      if(properties.indexOf(item) !== -1) {
                        options[item] = this.props[item];
                      }
                }
          }
          return options;
      };
    createComponent(options) {
        if(!this.style) {
              for (let style in this.props.style) {
                  JQXLite(this.componentSelector).css(style, this.props.style[style]);
              }
        }
        if(this.props.className !== undefined) {
            let classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
              JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxCalendar(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxCalendar('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxCalendar(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    backText(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('backText', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('backText');
        }
    };
    columnHeaderHeight(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('columnHeaderHeight', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('columnHeaderHeight');
        }
    };
    clearString(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('clearString', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('clearString');
        }
    };
    culture(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('culture', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('culture');
        }
    };
    dayNameFormat(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('dayNameFormat', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('dayNameFormat');
        }
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('disabled');
        }
    };
    enableWeekend(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('enableWeekend', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('enableWeekend');
        }
    };
    enableViews(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('enableViews', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('enableViews');
        }
    };
    enableOtherMonthDays(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('enableOtherMonthDays', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('enableOtherMonthDays');
        }
    };
    enableFastNavigation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('enableFastNavigation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('enableFastNavigation');
        }
    };
    enableHover(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('enableHover', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('enableHover');
        }
    };
    enableAutoNavigation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('enableAutoNavigation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('enableAutoNavigation');
        }
    };
    enableTooltips(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('enableTooltips', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('enableTooltips');
        }
    };
    forwardText(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('forwardText', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('forwardText');
        }
    };
    firstDayOfWeek(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('firstDayOfWeek', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('firstDayOfWeek');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('height');
        }
    };
    min(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('min', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('min');
        }
    };
    max(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('max', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('max');
        }
    };
    navigationDelay(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('navigationDelay', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('navigationDelay');
        }
    };
    rowHeaderWidth(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('rowHeaderWidth', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('rowHeaderWidth');
        }
    };
    readOnly(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('readOnly', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('readOnly');
        }
    };
    restrictedDates(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('restrictedDates', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('restrictedDates');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('rtl');
        }
    };
    stepMonths(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('stepMonths', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('stepMonths');
        }
    };
    showWeekNumbers(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('showWeekNumbers', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('showWeekNumbers');
        }
    };
    showDayNames(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('showDayNames', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('showDayNames');
        }
    };
    showOtherMonthDays(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('showOtherMonthDays', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('showOtherMonthDays');
        }
    };
    showFooter(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('showFooter', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('showFooter');
        }
    };
    selectionMode(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('selectionMode', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('selectionMode');
        }
    };
    specialDates(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('specialDates', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('specialDates');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('theme');
        }
    };
    titleHeight(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('titleHeight', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('titleHeight');
        }
    };
    titleFormat(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('titleFormat', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('titleFormat');
        }
    };
    todayString(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('todayString', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('todayString');
        }
    };
    value(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('value', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('value');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('width');
        }
    };
    clear() {
        JQXLite(this.componentSelector).jqxCalendar('clear');  
    };
    destroy() {
        JQXLite(this.componentSelector).jqxCalendar('destroy');  
    };
    focus() {
        JQXLite(this.componentSelector).jqxCalendar('focus');  
    };
    addSpecialDate(date, tooltip, text) {
        JQXLite(this.componentSelector).jqxCalendar('addSpecialDate', date, tooltip, text);  
    };
    getMinDate() {
        return JQXLite(this.componentSelector).jqxCalendar('getMinDate');  
    };
    getMaxDate() {
        return JQXLite(this.componentSelector).jqxCalendar('getMaxDate');  
    };
    getDate() {
        return JQXLite(this.componentSelector).jqxCalendar('getDate');  
    };
    getRange() {
        return JQXLite(this.componentSelector).jqxCalendar('getRange');  
    };
    navigateForward(months) {
        JQXLite(this.componentSelector).jqxCalendar('navigateForward', months);  
    };
    navigateBackward(months) {
        JQXLite(this.componentSelector).jqxCalendar('navigateBackward', months);  
    };
    performRender() {
        JQXLite(this.componentSelector).jqxCalendar('render');
    };
    refresh() {
        JQXLite(this.componentSelector).jqxCalendar('refresh');  
    };
    setMinDate(date) {
        JQXLite(this.componentSelector).jqxCalendar('setMinDate', date);  
    };
    setMaxDate(date) {
        JQXLite(this.componentSelector).jqxCalendar('setMaxDate', date);  
    };
    setDate(date) {
        JQXLite(this.componentSelector).jqxCalendar('setDate', date);  
    };
    setRange(date, date2) {
        JQXLite(this.componentSelector).jqxCalendar('setRange', date, date2);  
    };
    today() {
        JQXLite(this.componentSelector).jqxCalendar('today');  
    };
    val(value, value2) {
        if (value !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('val',  value, value2)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('val');
        }
    };

    render() {
        let id = 'jqxCalendar' + JQXLite.generateID();
        this.componentSelector = '#' + id;
        return (
            <div id={id}>{this.props.value}{this.props.children}</div>
        )
    };
};

// jqwidgets-ng/esm2015/jqxcalendar/angular_jqxcalendar.js
import '../jqwidgets/jqxcore';
import '../jqwidgets/globalization/globalize';
import '../jqwidgets/jqxbuttons';
import '../jqwidgets/jqxtooltip';
import '../jqwidgets/jqxdatetimeinput';
import '../jqwidgets/jqxcalendar';
/// <reference path="../../jqwidgets.d.ts" />
import * as tslib_1 from "tslib";
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges, ChangeDetectionStrategy } from '@angular/core';
import { NG_VALUE_ACCESSOR } from '@angular/forms';
const noop = () => { };
const ɵ0 = noop;
const CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => jqxCalendarComponent),
    multi: true
};
let jqxCalendarComponent = class jqxCalendarComponent {
    constructor(containerElement) {
        this.autoCreate = true;
        this.properties = ['backText', 'columnHeaderHeight', 'clearString', 'culture', 'dayNameFormat', 'disabled', 'enableWeekend', 'enableViews', 'enableOtherMonthDays', 'enableFastNavigation', 'enableHover', 'enableAutoNavigation', 'enableTooltips', 'forwardText', 'firstDayOfWeek', 'height', 'min', 'max', 'navigationDelay', 'rowHeaderWidth', 'readOnly', 'restrictedDates', 'rtl', 'stepMonths', 'showWeekNumbers', 'showDayNames', 'showOtherMonthDays', 'showFooter', 'selectionMode', 'specialDates', 'theme', 'titleHeight', 'titleFormat', 'todayString', 'value', 'width'];
        this.onTouchedCallback = noop;
        this.onChangeCallback = noop;
        // jqxCalendarComponent events
        this.onBackButtonClick = new EventEmitter();
        this.onChange = new EventEmitter();
        this.onNextButtonClick = new EventEmitter();
        this.onViewChange = new EventEmitter();
        this.elementRef = containerElement;
    }
    ngOnInit() {
        if (this.autoCreate) {
            this.createComponent();
        }
    }
    ;
    ngOnChanges(changes) {
        if (this.host) {
            for (let i = 0; i < this.properties.length; i++) {
                let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
                let areEqual = false;
                if (this[attrName] !== undefined) {
                    if (typeof this[attrName] === 'object') {
                        if (this[attrName] instanceof Array) {
                            areEqual = this.arraysEqual(this[attrName], this.host.jqxCalendar(this.properties[i]));
                        }
                        if (areEqual) {
                            return false;
                        }
                        this.host.jqxCalendar(this.properties[i], this[attrName]);
                        continue;
                    }
                    if (this[attrName] !== this.host.jqxCalendar(this.properties[i])) {
                        this.host.jqxCalendar(this.properties[i], this[attrName]);
                    }
                }
            }
        }
    }
    arraysEqual(attrValue, hostValue) {
        if ((attrValue && !hostValue) || (!attrValue && hostValue)) {
            return false;
        }
        if (attrValue.length != hostValue.length) {
            return false;
        }
        for (let i = 0; i < attrValue.length; i++) {
            if (attrValue[i] !== hostValue[i]) {
                return false;
            }
        }
        return true;
    }
    manageAttributes() {
        let options = {};
        for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            if (this[attrName] !== undefined) {
                options[this.properties[i]] = this[attrName];
            }
        }
        return options;
    }
    moveClasses(parentEl, childEl) {
        let classes = parentEl.classList;
        if (classes.length > 0) {
            childEl.classList.add(...classes);
        }
        parentEl.className = '';
    }
    moveStyles(parentEl, childEl) {
        let style = parentEl.style.cssText;
        childEl.style.cssText = style;
        parentEl.style.cssText = '';
    }
    createComponent(options) {
        if (this.host) {
            return;
        }
        if (options) {
            JQXLite.extend(options, this.manageAttributes());
        }
        else {
            options = this.manageAttributes();
        }
        this.host = JQXLite(this.elementRef.nativeElement.firstChild);
        this.moveClasses(this.elementRef.nativeElement, this.host[0]);
        this.moveStyles(this.elementRef.nativeElement, this.host[0]);
        this.__wireEvents__();
        this.widgetObject = jqwidgets.createInstance(this.host, 'jqxCalendar', options);
    }
    createWidget(options) {
        this.createComponent(options);
    }
    __updateRect__() {
        if (this.host)
            this.host.css({ width: this.attrWidth, height: this.attrHeight });
    }
    writeValue(value) {
        if (this.widgetObject) {
            this.onChangeCallback(this.host.val());
        }
    }
    registerOnChange(fn) {
        this.onChangeCallback = fn;
    }
    registerOnTouched(fn) {
        this.onTouchedCallback = fn;
    }
    setOptions(options) {
        this.host.jqxCalendar('setOptions', options);
    }
    // jqxCalendarComponent properties
    backText(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('backText', arg);
        }
        else {
            return this.host.jqxCalendar('backText');
        }
    }
    columnHeaderHeight(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('columnHeaderHeight', arg);
        }
        else {
            return this.host.jqxCalendar('columnHeaderHeight');
        }
    }
    clearString(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('clearString', arg);
        }
        else {
            return this.host.jqxCalendar('clearString');
        }
    }
    culture(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('culture', arg);
        }
        else {
            return this.host.jqxCalendar('culture');
        }
    }
    dayNameFormat(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('dayNameFormat', arg);
        }
        else {
            return this.host.jqxCalendar('dayNameFormat');
        }
    }
    disabled(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('disabled', arg);
        }
        else {
            return this.host.jqxCalendar('disabled');
        }
    }
    enableWeekend(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('enableWeekend', arg);
        }
        else {
            return this.host.jqxCalendar('enableWeekend');
        }
    }
    enableViews(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('enableViews', arg);
        }
        else {
            return this.host.jqxCalendar('enableViews');
        }
    }
    enableOtherMonthDays(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('enableOtherMonthDays', arg);
        }
        else {
            return this.host.jqxCalendar('enableOtherMonthDays');
        }
    }
    enableFastNavigation(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('enableFastNavigation', arg);
        }
        else {
            return this.host.jqxCalendar('enableFastNavigation');
        }
    }
    enableHover(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('enableHover', arg);
        }
        else {
            return this.host.jqxCalendar('enableHover');
        }
    }
    enableAutoNavigation(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('enableAutoNavigation', arg);
        }
        else {
            return this.host.jqxCalendar('enableAutoNavigation');
        }
    }
    enableTooltips(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('enableTooltips', arg);
        }
        else {
            return this.host.jqxCalendar('enableTooltips');
        }
    }
    forwardText(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('forwardText', arg);
        }
        else {
            return this.host.jqxCalendar('forwardText');
        }
    }
    firstDayOfWeek(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('firstDayOfWeek', arg);
        }
        else {
            return this.host.jqxCalendar('firstDayOfWeek');
        }
    }
    height(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('height', arg);
        }
        else {
            return this.host.jqxCalendar('height');
        }
    }
    min(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('min', arg);
        }
        else {
            return this.host.jqxCalendar('min');
        }
    }
    max(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('max', arg);
        }
        else {
            return this.host.jqxCalendar('max');
        }
    }
    navigationDelay(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('navigationDelay', arg);
        }
        else {
            return this.host.jqxCalendar('navigationDelay');
        }
    }
    rowHeaderWidth(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('rowHeaderWidth', arg);
        }
        else {
            return this.host.jqxCalendar('rowHeaderWidth');
        }
    }
    readOnly(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('readOnly', arg);
        }
        else {
            return this.host.jqxCalendar('readOnly');
        }
    }
    restrictedDates(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('restrictedDates', arg);
        }
        else {
            return this.host.jqxCalendar('restrictedDates');
        }
    }
    rtl(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('rtl', arg);
        }
        else {
            return this.host.jqxCalendar('rtl');
        }
    }
    stepMonths(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('stepMonths', arg);
        }
        else {
            return this.host.jqxCalendar('stepMonths');
        }
    }
    showWeekNumbers(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('showWeekNumbers', arg);
        }
        else {
            return this.host.jqxCalendar('showWeekNumbers');
        }
    }
    showDayNames(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('showDayNames', arg);
        }
        else {
            return this.host.jqxCalendar('showDayNames');
        }
    }
    showOtherMonthDays(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('showOtherMonthDays', arg);
        }
        else {
            return this.host.jqxCalendar('showOtherMonthDays');
        }
    }
    showFooter(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('showFooter', arg);
        }
        else {
            return this.host.jqxCalendar('showFooter');
        }
    }
    selectionMode(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('selectionMode', arg);
        }
        else {
            return this.host.jqxCalendar('selectionMode');
        }
    }
    specialDates(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('specialDates', arg);
        }
        else {
            return this.host.jqxCalendar('specialDates');
        }
    }
    theme(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('theme', arg);
        }
        else {
            return this.host.jqxCalendar('theme');
        }
    }
    titleHeight(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('titleHeight', arg);
        }
        else {
            return this.host.jqxCalendar('titleHeight');
        }
    }
    titleFormat(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('titleFormat', arg);
        }
        else {
            return this.host.jqxCalendar('titleFormat');
        }
    }
    todayString(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('todayString', arg);
        }
        else {
            return this.host.jqxCalendar('todayString');
        }
    }
    value(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('value', arg);
        }
        else {
            return this.host.jqxCalendar('value');
        }
    }
    width(arg) {
        if (arg !== undefined) {
            this.host.jqxCalendar('width', arg);
        }
        else {
            return this.host.jqxCalendar('width');
        }
    }
    // jqxCalendarComponent functions
    clear() {
        this.host.jqxCalendar('clear');
    }
    destroy() {
        this.host.jqxCalendar('destroy');
    }
    focus() {
        this.host.jqxCalendar('focus');
    }
    addSpecialDate(date, specialDateClass, text) {
        this.host.jqxCalendar('addSpecialDate', date, specialDateClass, text);
    }
    getMinDate() {
        return this.host.jqxCalendar('getMinDate');
    }
    getMaxDate() {
        return this.host.jqxCalendar('getMaxDate');
    }
    getDate() {
        return this.host.jqxCalendar('getDate');
    }
    getRange() {
        return this.host.jqxCalendar('getRange');
    }
    navigateForward(months) {
        this.host.jqxCalendar('navigateForward', months);
    }
    navigateBackward(months) {
        this.host.jqxCalendar('navigateBackward', months);
    }
    render() {
        this.host.jqxCalendar('render');
    }
    refresh() {
        this.host.jqxCalendar('refresh');
    }
    setMinDate(date) {
        this.host.jqxCalendar('setMinDate', date);
    }
    setMaxDate(date) {
        this.host.jqxCalendar('setMaxDate', date);
    }
    setDate(date) {
        this.host.jqxCalendar('setDate', date);
    }
    setRange(date, date2) {
        this.host.jqxCalendar('setRange', date, date2);
    }
    today() {
        this.host.jqxCalendar('today');
    }
    val(value, value2) {
        if (value !== undefined) {
            return this.host.jqxCalendar('val', value, value2);
        }
        else {
            return this.host.jqxCalendar('val');
        }
    }
    ;
    __wireEvents__() {
        this.host.on('backButtonClick', (eventData) => { this.onBackButtonClick.emit(eventData); });
        this.host.on('change', (eventData) => { this.onChange.emit(eventData); this.onChangeCallback(this.host.val()); });
        this.host.on('nextButtonClick', (eventData) => { this.onNextButtonClick.emit(eventData); });
        this.host.on('viewChange', (eventData) => { this.onViewChange.emit(eventData); });
    }
}; //jqxCalendarComponent
jqxCalendarComponent.ctorParameters = () => [
    { type: ElementRef }
];
tslib_1.__decorate([
    Input('backText'),
    tslib_1.__metadata("design:type", String)
], jqxCalendarComponent.prototype, "attrBackText", void 0);
tslib_1.__decorate([
    Input('columnHeaderHeight'),
    tslib_1.__metadata("design:type", Number)
], jqxCalendarComponent.prototype, "attrColumnHeaderHeight", void 0);
tslib_1.__decorate([
    Input('clearString'),
    tslib_1.__metadata("design:type", String)
], jqxCalendarComponent.prototype, "attrClearString", void 0);
tslib_1.__decorate([
    Input('culture'),
    tslib_1.__metadata("design:type", String)
], jqxCalendarComponent.prototype, "attrCulture", void 0);
tslib_1.__decorate([
    Input('dayNameFormat'),
    tslib_1.__metadata("design:type", String)
], jqxCalendarComponent.prototype, "attrDayNameFormat", void 0);
tslib_1.__decorate([
    Input('disabled'),
    tslib_1.__metadata("design:type", Boolean)
], jqxCalendarComponent.prototype, "attrDisabled", void 0);
tslib_1.__decorate([
    Input('enableWeekend'),
    tslib_1.__metadata("design:type", Boolean)
], jqxCalendarComponent.prototype, "attrEnableWeekend", void 0);
tslib_1.__decorate([
    Input('enableViews'),
    tslib_1.__metadata("design:type", Boolean)
], jqxCalendarComponent.prototype, "attrEnableViews", void 0);
tslib_1.__decorate([
    Input('enableOtherMonthDays'),
    tslib_1.__metadata("design:type", Boolean)
], jqxCalendarComponent.prototype, "attrEnableOtherMonthDays", void 0);
tslib_1.__decorate([
    Input('enableFastNavigation'),
    tslib_1.__metadata("design:type", Boolean)
], jqxCalendarComponent.prototype, "attrEnableFastNavigation", void 0);
tslib_1.__decorate([
    Input('enableHover'),
    tslib_1.__metadata("design:type", Boolean)
], jqxCalendarComponent.prototype, "attrEnableHover", void 0);
tslib_1.__decorate([
    Input('enableAutoNavigation'),
    tslib_1.__metadata("design:type", Boolean)
], jqxCalendarComponent.prototype, "attrEnableAutoNavigation", void 0);
tslib_1.__decorate([
    Input('enableTooltips'),
    tslib_1.__metadata("design:type", Boolean)
], jqxCalendarComponent.prototype, "attrEnableTooltips", void 0);
tslib_1.__decorate([
    Input('forwardText'),
    tslib_1.__metadata("design:type", String)
], jqxCalendarComponent.prototype, "attrForwardText", void 0);
tslib_1.__decorate([
    Input('firstDayOfWeek'),
    tslib_1.__metadata("design:type", Number)
], jqxCalendarComponent.prototype, "attrFirstDayOfWeek", void 0);
tslib_1.__decorate([
    Input('min'),
    tslib_1.__metadata("design:type", Object)
], jqxCalendarComponent.prototype, "attrMin", void 0);
tslib_1.__decorate([
    Input('max'),
    tslib_1.__metadata("design:type", Object)
], jqxCalendarComponent.prototype, "attrMax", void 0);
tslib_1.__decorate([
    Input('navigationDelay'),
    tslib_1.__metadata("design:type", Number)
], jqxCalendarComponent.prototype, "attrNavigationDelay", void 0);
tslib_1.__decorate([
    Input('rowHeaderWidth'),
    tslib_1.__metadata("design:type", Object)
], jqxCalendarComponent.prototype, "attrRowHeaderWidth", void 0);
tslib_1.__decorate([
    Input('readOnly'),
    tslib_1.__metadata("design:type", Boolean)
], jqxCalendarComponent.prototype, "attrReadOnly", void 0);
tslib_1.__decorate([
    Input('restrictedDates'),
    tslib_1.__metadata("design:type", Array)
], jqxCalendarComponent.prototype, "attrRestrictedDates", void 0);
tslib_1.__decorate([
    Input('rtl'),
    tslib_1.__metadata("design:type", Boolean)
], jqxCalendarComponent.prototype, "attrRtl", void 0);
tslib_1.__decorate([
    Input('stepMonths'),
    tslib_1.__metadata("design:type", Number)
], jqxCalendarComponent.prototype, "attrStepMonths", void 0);
tslib_1.__decorate([
    Input('showWeekNumbers'),
    tslib_1.__metadata("design:type", Boolean)
], jqxCalendarComponent.prototype, "attrShowWeekNumbers", void 0);
tslib_1.__decorate([
    Input('showDayNames'),
    tslib_1.__metadata("design:type", Boolean)
], jqxCalendarComponent.prototype, "attrShowDayNames", void 0);
tslib_1.__decorate([
    Input('showOtherMonthDays'),
    tslib_1.__metadata("design:type", Boolean)
], jqxCalendarComponent.prototype, "attrShowOtherMonthDays", void 0);
tslib_1.__decorate([
    Input('showFooter'),
    tslib_1.__metadata("design:type", Boolean)
], jqxCalendarComponent.prototype, "attrShowFooter", void 0);
tslib_1.__decorate([
    Input('selectionMode'),
    tslib_1.__metadata("design:type", String)
], jqxCalendarComponent.prototype, "attrSelectionMode", void 0);
tslib_1.__decorate([
    Input('specialDates'),
    tslib_1.__metadata("design:type", Array)
], jqxCalendarComponent.prototype, "attrSpecialDates", void 0);
tslib_1.__decorate([
    Input('theme'),
    tslib_1.__metadata("design:type", String)
], jqxCalendarComponent.prototype, "attrTheme", void 0);
tslib_1.__decorate([
    Input('titleHeight'),
    tslib_1.__metadata("design:type", Number)
], jqxCalendarComponent.prototype, "attrTitleHeight", void 0);
tslib_1.__decorate([
    Input('titleFormat'),
    tslib_1.__metadata("design:type", String)
], jqxCalendarComponent.prototype, "attrTitleFormat", void 0);
tslib_1.__decorate([
    Input('todayString'),
    tslib_1.__metadata("design:type", String)
], jqxCalendarComponent.prototype, "attrTodayString", void 0);
tslib_1.__decorate([
    Input('value'),
    tslib_1.__metadata("design:type", Date)
], jqxCalendarComponent.prototype, "attrValue", void 0);
tslib_1.__decorate([
    Input('width'),
    tslib_1.__metadata("design:type", Object)
], jqxCalendarComponent.prototype, "attrWidth", void 0);
tslib_1.__decorate([
    Input('height'),
    tslib_1.__metadata("design:type", Object)
], jqxCalendarComponent.prototype, "attrHeight", void 0);
tslib_1.__decorate([
    Input('auto-create'),
    tslib_1.__metadata("design:type", Boolean)
], jqxCalendarComponent.prototype, "autoCreate", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxCalendarComponent.prototype, "onBackButtonClick", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxCalendarComponent.prototype, "onChange", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxCalendarComponent.prototype, "onNextButtonClick", void 0);
tslib_1.__decorate([
    Output(),
    tslib_1.__metadata("design:type", Object)
], jqxCalendarComponent.prototype, "onViewChange", void 0);
jqxCalendarComponent = tslib_1.__decorate([
    Component({
        selector: 'jqxCalendar',
        template: '<div><ng-content></ng-content></div>',
        providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR],
        changeDetection: ChangeDetectionStrategy.OnPush
    }),
    tslib_1.__metadata("design:paramtypes", [ElementRef])
], jqxCalendarComponent);
export { jqxCalendarComponent };
export { ɵ0 };
